### PR TITLE
API: Fix FileRange validation to reject negative offset/length

### LINKED ISSUE #15922: API: Fix FileRange validation order to reject negative offset/length
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

`FileRange` currently validates `length()` and `offset()` before assigning constructor parameters to fields. Because those getters return default field values at that point, negative constructor inputs can bypass validation.

This allows malformed ranges to propagate into vectored reads and trigger runtime failures.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [x] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by barry3406**
## Summary

- `FileRange` constructor validates `length()` and `offset()` (getters) before assigning fields, so negative inputs bypass validation silently since field defaults are 0
- Changed to validate constructor parameters directly instead of getters
- Added `TestFileRange.java` with test cases for negative offset, negative length, null byteBuffer, and valid construction

## Root Cause

```java
// BEFORE — length() returns 0 (field default), not the parameter value
Preconditions.checkArgument(
    length() >= 0, "Invalid length: %s in range (must be >= 0)", length);

// AFTER — validates the actual parameter
Preconditions.checkArgument(
    length >= 0, "Invalid length: %s in range (must be >= 0)", length);
```

## Test Plan

- [x] Added `TestFileRange.java` covering negative offset, negative length, null byteBuffer, and valid range
- [ ] Existing CI tests should pass

Fixes #15922

### CODE REVIEW

**Review by huaxingao — APPROVED** [review]
LGTM

**Comment by barry3406** [comment]
Thanks for the review @huaxingao! Let me know if there's anything else needed on my end before merge — happy to address it.

**Review by singhpk234 — APPROVED** [review]

File: api/src/main/java/org/apache/iceberg/io/FileRange.java [hunk 1]
```diff
@@ -31,10 +31,8 @@ public class FileRange {
   public FileRange(CompletableFuture<ByteBuffer> byteBuffer, long offset, int length)
       throws EOFException {
```
Comment (anoopj) [inline api/src/main/java/org/apache/iceberg/io/FileRange.java]: This is existing code, but I don't see any place in the constructor that can throw `EOFException`.

**Review by anoopj — APPROVED** [review]

File: api/src/test/java/org/apache/iceberg/io/TestFileRange.java [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+    assertThat(range.length()).isEqualTo(100);
+    assertThat(range.byteBuffer()).isSameAs(future);
+  }
+
+  @Test
+  public void negativeLength() {
+    CompletableFuture<ByteBuffer> future = new CompletableFuture<>();
+    assertThatThrownBy(() -> new FileRange(future, 0L, -1))
+        .isInstanceOf(IllegalArgumentException.class)
+        .hasMessageContaining("Invalid length");
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/io/TestFileRange.java]: the tests should all check for the exact error msg by using `hasMessage(...)`

Comment (barry3406) [reply api/src/test/java/org/apache/iceberg/io/TestFileRange.java]: done, switched to hasMessage with the exact strings

File: api/src/main/java/org/apache/iceberg/io/FileRange.java (hunk 1 above)
Comment (barry3406) [reply api/src/main/java/org/apache/iceberg/io/FileRange.java]: yep, nothing in the body throws it. `ParquetIO.convertRanges` catches `EOFException` around `new FileRange(...)` though, so the two are coupled — got added together in #13997. figured I'd leave that cleanup outside this one.

**Review by mukund-thakur — APPROVED** [review]

File: api/src/main/java/org/apache/iceberg/io/FileRange.java (hunk 1 above)
Comment (mukund-thakur) [reply api/src/main/java/org/apache/iceberg/io/FileRange.java]: created a pr to remove this https://github.com/apache/iceberg/pull/15973. Please take a look. Thanks.

**Comment by huaxingao** [comment]
Thanks @barry3406 for the PR! Thanks everyone for the review!
