### PR TITLE
Flink 1.14:  Add EqualityFieldKeySelector.

### LINKED ISSUE #2918: Flink: get duplicate rows when sync CDC data by FlinkSQL
### Duplicate Rows Problem

Recently, I trying use FlinkSQL to synchronize MySQL to iceberg. Saving MySQL/PostgreSQL to iceberg is very common case in the construction of data warehouses.  But I got duplicat rows which have same primary key in iceberg table but not in mysql table. I will illustrate the reason of this problem as follow.

Assume we have a sample MySQL table which just has one record:

id | data
---|---
1| aaa

And we define an ETL job by FlinkSQL as follow:
```
CREATE TABLE `mysql_table` (
    `id` INT, 
    `data` STRING
)
WITH (
    'connector' = 'mysql-cdc', 
    'database-name' = 'xxx', 
    ...
)

CREATE TABLE `iceberg_table` (
    `id` INT, 
    `data` STRING
    PRIMARY KEY(id) NOT ENFORCED
)
WITH (
    'connector' = 'iceberg', 
    'catalog-type' = 'hive', 
    'catalog-name' = 'iceberg', 
    'catalog-database' = 'xxx', 
    'format.version' = '2'
    ...
)

INSERT INTO `iceberg_table``
SELECT `id`, `data` FROM `mysql_table`
```

If we don't setting the default parallelism of job, we will get the job graph like this:
```
FlinkCDCSource ---forward---> Filter ---forward---> IcebergStreamWriter ---forward---> IcebergFilesCommitter
```
That will be work fine and not duplicat rows. because all opr parallelism is 1, and all cdc data will be distributed to one IcebergStreamWriter.

But once we setting the default parallelism of job by `SET table.exec.resource.default-parallelism=3`, we will get another job graph as follow:
```
                              +---> Filter ---forward---> IcebergStreamWriter-1 ---+
FlinkCDCSource ---rebalance---+---> Filter ---forward---> IcebergStreamWriter-2 ---+---rebalance---> IcebergFilesCommitter
                              +---> Filter ---forward---> IcebergStreamWriter-3 ---+
```
Notice the `Filter` opr parallelism is follow the job default parallelism and increase to 3.  For iceberg `FlinkSink`, due to the `writeParallelism` is not be set so the `IcebergStreamWriter` parallelism will follow the `rowDataInput`(`Filter`) parallelism as 3.
The `FlinkCDCSource` parallelism will be alway 1, because binlog data need to be send by serial.  Consider Flink use `rebalance` as default shuffle strategy. Now we can see the CDC data will be rebalance to three different `Filter` and then emit different `IcebergStreamWriter`. 

At this time, If we insert one row and update it as follow, we will get an duplicate row.
```
INSERT INTO `mysql_table`(id, data) VALUES(2, 'bbb');
UPDATE `mysql_table` SET data = 'xxx' WHERE id = '2';
```
MySQL:

id | data
---|---
1| aaa
2| xxx

Iceberg:

id | data
---|---
1| aaa
2| bbb
2| xxx

We got the duplicate row of `<2, 'bbb'>` because the change log data wil be rebalance to different `IcebergStreamWriter`. 
For the first `INSERT` SQL, we will got a +I record, and that will be send to the `IcebergStreamWriter-1`.
For the second `UPDATE` SQL, we will got a -U record and a +U record. The -U record will be send to the `IcebergStreamWriter-2` and +U record wil be rebalance to the `IcebergStreamWriter-3` 
Due to `IcebergStreamWriter-2` have not any data `INSERT` before, it's insertedRowMap is empty, and then the pos-delete(-U) will be ignore and will not write to delete file. 
Finally we got an duplicate row `<2, 'bbb'>`.

### Disorder Problem
The reason for duplicat rows is as mentioned above, but when I try to fix that by add keyBy before `IcebergStreamWriter`, I encounter another problem.
For FlinkSQL, flink will append a `Filter` opr before call `IcebergTableSink.getSinkRuntimeProvider` to prevenet send null data to downstream.  So, when we get the `rowDataInput` from flink in `FlinkSink`, `rowDataInput` definitely contain a `Filter` opr which parallelism is follow the job default parallelism as above. 

In our case, if we just keyBy `equalityFields` before add `IcebergStreamWriter`, we will get the job graph as follow: 
```
                              +---> Filter ---+      +---> IcebergStreamWriter-1 ---+
FlinkCDCSource ---rebalance---+---> Filter ---+-hash-+---> IcebergStreamWriter-2 ---+---rebalance---> IcebergFilesCommitter
                              +---> Filter ---+      +---> IcebergStreamWriter-3 ---+
```
Notice the CDC data come from `FlinkCDCSource` will be rebalance to `Filter` immediately.  Even if all CDC data which have same key will be emit to same `IcebergStreamWriter`, but that will make disorder between CDC data(e.g. same IcebergStreamWriter will receive +U before -U). And finally we will get a lot of strange result. 

### Goal
In summary, I think iceberg should ensure that data with the same primary key will be updated and not duplicat rows when we sink CDC/UPSERT data to iceberg. 
I trying to fix this problem by chaining the `Source` and `Filter` opr and add keyBy before `IcebergStreamWriter` when use FlinkSQL. Finally I want to got a correct job graph like this:
```
                                             +---> IcebergStreamWriter-1 ---+
FlinkCDCSource ---forward---> Filter ---hash-+---> IcebergStreamWriter-2 ---+---rebalance---> IcebergFilesCommitter
                                             +---> IcebergStreamWriter-3 ---+
```

### LINKED ISSUE #3551: Flink: Get KryoException when starting a flink job.
Currently I encounter a `KryoException` when I submit a flink job to flink 1.12.x. 
```
2021-11-12 18:07:03,976 WARN  org.apache.flink.runtime.taskmanager.Task                    dw_rt_ods.ods_mysql_cdc_hive_exec_job-IcebergStreamWriter (1/1)#0 [] - database.table-IcebergStreamWriter (1/1)#0 (2377289ed0fedccf9d510099ec769e24) switched from RUNNING to FAILED.
java.lang.RuntimeException: Exception occurred while setting the current key context.
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.setCurrentKey(StreamOperatorStateHandler.java:322) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setCurrentKey(AbstractStreamOperator.java:532) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setKeyContextElement(AbstractStreamOperator.java:527) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setKeyContextElement1(AbstractStreamOperator.java:514) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:190) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:204) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:174) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:396) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:191) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:617) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:581) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755) [flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570) [flink-dist_2.12-1.12.1.jar:1.12.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
getters (org.apache.iceberg.flink.RowDataWrapper)
struct (org.apache.iceberg.util.StructProjection)
struct (org.apache.iceberg.util.StructLikeWrapper)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:82) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:316) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.serializeKeyGroupAndKey(RocksDBSerializedCompositeKeyBuilder.java:157) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.setKeyAndKeyGroup(RocksDBSerializedCompositeKeyBuilder.java:93) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBKeyedStateBackend.setCurrentKey(RocksDBKeyedStateBackend.java:386) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.setCurrentKey(StreamOperatorStateHandler.java:320) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	... 14 more
Caused by: java.lang.NullPointerException
	at com.esotericsoftware.kryo.Kryo.getSerializer(Kryo.java:476) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:345) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.write(DefaultArraySerializers.java:289) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.api.java.typeutils.runtime.kryo.KryoSerializer.serialize(KryoSerializer.java:316) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.serializeKeyGroupAndKey(RocksDBSerializedCompositeKeyBuilder.java:157) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBSerializedCompositeKeyBuilder.setKeyAndKeyGroup(RocksDBSerializedCompositeKeyBuilder.java:93) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.contrib.streaming.state.RocksDBKeyedStateBackend.setCurrentKey(RocksDBKeyedStateBackend.java:386) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.setCurrentKey(StreamOperatorStateHandler.java:320) ~[flink-dist_2.12-1.12.1.jar:1.12.1]
	... 14 more
```

### PR DESCRIPTION
**Pull request by Reo-LEI**
For CDC data, usually we will simply synchronize the data to iceberg.  And we can use FlinkSQL to do this.

Consider we use FlinkSQL define a sourc of cdc-connector and a sink of iceberg-connector, and simply INSERT INTO cdc data from src to snk. Finally we will get a job graph like this:
```
FlinkCDCSource ---forward---> Filter ---forward---> IcebergStreamWriter ---forward---> IcebergFilesCommitter
```
That will be work fine, because all opr parallelism is 1, all cdc data will be distributed to one `IcebergStreamWriter`.

But once we setting the default parallelism of job, example 3 parrallelism, we will get another job graph as follow:
```
                              +---> Filter ---forward---> IcebergStreamWriter ---+
FlinkCDCSource ---rebalance---+---> Filter ---forward---> IcebergStreamWriter ---+---rebalance---> IcebergFilesCommitter
                              +---> Filter ---forward---> IcebergStreamWriter ---+
```
Now the CDC data will be distributed to three different `IcebergStreamWriter`, because we have not keyBy the primary key. If we insert one row and update it as follow, we will get an duplicate row.
```
// first field is id(primary key), second field is value
INSERT <1, aaa>
UPDATE <1, bbb>
```
Because the change log wil be rebalance to different `IcebergStreamWriter`, first writer will get +I record, second writer will get -U record and last writer will get +U record. Due to second writer's `insertedRowMap` is empty and the pos-delete(-U) will be ignore. Finally we got an duplicate row.

I try to fix that by add keyBy before `IcebergStreamWriter` and chaining the `Source` and `Filter` opr if use FlinkSQL.

Fixes #2918 
Fixes #3551

### CODE REVIEW

**Comment by coolderli** [comment]
I think this may be avoided by setting `write.distribution-mode` to `hash`.
https://github.com/apache/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java#L322

**Comment by Reo-LEI** [comment]
> I think this may be avoided by setting `write.distribution-mode` to `hash`.
> https://github.com/apache/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java#L322

Actually set `write.distribution-mode = hash` can not resolve this. Because CDC data shoule be distributed to primary key but not partition fields. For example, an iceberg table has equalityFields (dt, hour, id) and partition fields (dt, hour). If set `write.distribution-mode = hash`, the CDC data will be keyBy (dt, hour), and we can not ensure same id CDC data will send to same `IcebergStreamWriter`. 

And the second reason is , for FlinkSQL, `rowDataInput` contain a `FlinkCDCSource ` opr and a `Filter` opr. The `FlinkCDCSource ` opr parallelism is 1 and the `Filter` opr parallelism use job default parallelism. If we only keyBy `rowDataInput` output data to `IcebergStreamWriter`, we will get a job graph as follow: 
```
                              +---> Filter ---+      +---> IcebergStreamWriter ---+
FlinkCDCSource ---rebalance---+---> Filter ---+-hash-+---> IcebergStreamWriter ---+---rebalance---> IcebergFilesCommitter
                              +---> Filter ---+      +---> IcebergStreamWriter ---+
```
As result, the CDC data will be rebalance to `Filter`. That will make CDC data disorder(e.g. same `IcebergStreamWriter` will receive +U before -U), and we will get some strange result. So we need to keep the `Filter` have same parallelism to it's input opr.

**Comment by Reo-LEI** [comment]
Could you take look of this? @openinx

File: flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java [hunk 1]
```diff
@@ -83,29 +83,39 @@
...
+        new Object[] {"parquet", 4, true, TableProperties.WRITE_DISTRIBUTION_MODE_NONE},
+        new Object[] {"parquet", 4, false, TableProperties.WRITE_DISTRIBUTION_MODE_NONE},
+        new Object[] {"avro", 1, true, TableProperties.WRITE_DISTRIBUTION_MODE_HASH},
+        new Object[] {"avro", 1, false, TableProperties.WRITE_DISTRIBUTION_MODE_HASH},
+        new Object[] {"avro", 4, true, TableProperties.WRITE_DISTRIBUTION_MODE_HASH},
+        new Object[] {"avro", 4, false, TableProperties.WRITE_DISTRIBUTION_MODE_HASH},
+        new Object[] {"parquet", 1, true, TableProperties.WRITE_DISTRIBUTION_MODE_HASH},
+        new Object[] {"parquet", 1, false, TableProperties.WRITE_DISTRIBUTION_MODE_HASH},
+        new Object[] {"parquet", 4, true, TableProperties.WRITE_DISTRIBUTION_MODE_HASH},
+        new Object[] {"parquet", 4, false, TableProperties.WRITE_DISTRIBUTION_MODE_HASH}
```
Comment (kbendick) [inline flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:109]: Are there any tests that set any other values for `write.distribution-mode` than `hash`?

Given that Flink CDC is a pretty common use case for Iceberg, It would be great to add tests here for `none` and `ordered` since this has been added to the tests as well, if possible.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 2]
```diff
@@ -313,13 +320,21 @@ public Builder uidPrefix(String newPrefix) {
...
-            return input;
-          } else {
+          if (!partitionSpec.isUnpartitioned() && !equalityFieldIds.isEmpty()) {
+            return input.keyBy(new HybridKeySelector(partitionSpec, equalityFieldIds, iSchema, flinkRowType));
+          } else if (!partitionSpec.isUnpartitioned() && equalityFieldIds.isEmpty()) {
             return input.keyBy(new PartitionKeySelector(partitionSpec, iSchema, flinkRowType));
+          } else if (partitionSpec.isUnpartitioned() && !equalityFieldIds.isEmpty()) {
+            return input.keyBy(new EqualityFieldKeySelector(equalityFieldIds, table.schema(), flinkRowType));
+          } else {
+            return input;
```
Comment (kbendick) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:337]: It seems like we've gotten into a lot of `if` nesting. Would it make sense to either add a utility function, or add some method that returns more reader-friendly value from the equalityFieldIds? For me, its not as clear to see `isEmpty()` vs for example seeing `isUnpartitioned()`.

Can we add a utility or a method with some name that helps developers more easily understand the different cases, especially given we have so much `if else` nesting?

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java [hunk 3]
```diff
@@ -59,12 +60,22 @@ public SinkRuntimeProvider getSinkRuntimeProvider(Context context) {
...
-        .equalityFieldColumns(equalityColumns)
-        .overwrite(overwrite)
-        .build();
+    return (DataStreamSinkProvider) dataStream ->  {
+      // For CDC case in FlinkSQL, change log will be rebalanced(default partition strategy) distributed to Filter opr
+      // when set job default parallelism greater than 1. That will make change log data disorder and produce a wrong
+      // result for iceberg(e.g. +U comes before -U). Here try to specific the Filter opr parallelism same as it's
+      // input to keep Filter chaining it's input and avoid rebalance.
+      Transformation<?> forwardOpr = dataStream.getTransformation();
+      if (forwardOpr.getName().equals("Filter") && forwardOpr.getInputs().size() == 1) {
```
Comment (kbendick) [inline flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java:69]: Correct me if I'm wrong, but can't users set the name of the operators themselves?

Is there a way (possibly in the Flink SDK) that we can determine if we're in CDC mode (or more generally, if we have a retract stream) that is more specific than this? I'm worried we might catch more cases here than we mean to and unnecessarily force parallelism on jobs that don't require it.

File: flink/src/main/java/org/apache/iceberg/flink/sink/HybridKeySelector.java [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+package org.apache.iceberg.flink.sink;
+
+import java.util.List;
+import org.apache.flink.api.java.functions.KeySelector;
+import org.apache.flink.table.data.RowData;
+import org.apache.flink.table.types.logical.RowType;
+import org.apache.iceberg.PartitionSpec;
+import org.apache.iceberg.Schema;
+
+public class HybridKeySelector implements KeySelector<RowData, String> {
```
Comment (kbendick) [inline flink/src/main/java/org/apache/iceberg/flink/sink/HybridKeySelector.java:24]: Nit but also an important question to help me understand better =)

The name `HybridKeySelector` is admittedly somewhat confusing to me initially. Once I see the class definition, it's more understandable, but I do have to look through the source to see what `Hybrid` means.

Which leads me to my question:
In the case of current `HybridKeySelector`, we're using the PartitionKey and the `EqualityFieldKey`. This seems to work for `hash` distribution (at least per the updated tests), but what about `range` and `none`? Which key selectors would they use?

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 5]
```diff
@@ -260,18 +263,21 @@ public Builder uidPrefix(String newPrefix) {
...
-      this.writeParallelism = writeParallelism == null ? rowDataInput.getParallelism() : writeParallelism;
-
       SingleOutputStreamOperator<WriteResult> writerStream = rowDataInput
-          .transform(ICEBERG_STREAM_WRITER_NAME, TypeInformation.of(WriteResult.class), streamWriter)
-          .setParallelism(writeParallelism);
+          .transform(ICEBERG_STREAM_WRITER_NAME, TypeInformation.of(WriteResult.class), streamWriter);
+
+      if (this.writeParallelism != null) {
+        writerStream.setParallelism(writeParallelism);
+      }
```
Comment (kbendick) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:279]: Is it possible for this to be `null`? I notice the null check is new.

Also, in cases where you'd added `setParallelism` calls, what happens if this `writeParallelism` is also set? Is that a situation that could be encountered?

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java [hunk 6]
```diff
@@ -59,12 +60,22 @@ public SinkRuntimeProvider getSinkRuntimeProvider(Context context) {
...
+        forwardOpr.setParallelism(forwardOpr.getInputs().get(0).getParallelism());
```
Comment (kbendick) [inline flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java:70]: How does setting the parallelism here interplay with the parallelism of the writer?

I notice there's one other place where we set the parallelism based on some feature of the input, but we also have write parallelism that I've commented on below. Is it possible for `writeParallelism` in the below section to be different than what users have, say in the case of the CDC stream? For example, could you draw the DAG if a users input `Filter` has p=2, and then `writeParallelism` is set to `p=3`. Or is that not a possible case?

**Review by kbendick — COMMENTED** [review]
Hi @Reo-LEI, I want to say first that I see your concern, so thank you for this PR. That said, I've been doing much more SparkSQL lately than Flink SQL and so I have some questions to help me better understand the situation, if you don't mind.

You've drawn a lot of graphs that have helped illustrate your point, but at least as I've read, I don't think I've seen one that shows what the output DAG in your example case would be. Could you possibly add one that illustrates the parallelism of N=3?

Additionally, I am wondering if there is possibly a need for different key selectors in the case of `range` partitioning. If one has an UPSERT stream of adds and deletes in general, will they be affected by this issue as well?

Lastly, have you observed an example of this in the wild (in a running job)? I know that it's not going to be easy to set up a test case for this in a real environment, as this is an edge case, but I'd love to know if you feel you've personally seen this, or if this is more of a usability concern you have (which is still valid, but as I haven't used Flink in recent months, I'm relying on you and others to help me better understand the issue).

Again, I really appreciate the time you've taken to help with diagrams to illustrate your point.

**Comment by kbendick** [comment]
Also, as my Flink is a little rusty compared to my Spark knowledge, can you please open an issue (or link it to your commit)? I can help tag some relevant people there if we don't hear from openinx after a bit here =)

**Comment by Reo-LEI** [comment]
Thanks for your review and give me a lot of advice @kbendick . I open an issue #2918 to illustrate this problem more detailly, I hope that can help you to understand this.

**Comment by Reo-LEI** [comment]
> Additionally, I am wondering if there is possibly a need for different key selectors in the case of `range` partitioning. If one has an UPSERT stream of adds and deletes in general, will they be affected by this issue as well?
I think we don't need a key selector for `range` partitioning, because iceberg-flink don't support `range` partitioning yet. And I think `range` partitioning is not easy to impl in streaming system, and we can't ignore this case now.

**Comment by Reo-LEI** [comment]
> EDIT - Finally, we've talked a lot about the CDC case that it map side only (though with a potential rebalance or hash inside of it), but can users still get themselves into an unhappy case if they have a retract stream that they re-key or something themselves (say they do some ETL on a CDC stream)?

Could you give me some examples for this case? For upsert and retract stream, I think these streams should keyBy `equalityFields`(primary key) to keep update the same row with same pk.

File: flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java (hunk 1 above)
Comment (Reo-LEI) [reply flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:109]: Actually, the line 94 to 101 is use  `none` as `write.distribution-mode`.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 2 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:337]: That is make sense, I will add an utility method to do this.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 5 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:279]: That would be null if use not set, if `writeParallelism` is null, the `writerStream` would use flink job default parallelism, or else use `writeParallelism` specific value. This `writeParallelism` setting only effect to `IcebergStreamingWriter` parallelism, I think that would not bring other side effect.

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java (hunk 6 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java:70]: `Filter` parallelism different than `IcebergStreamingWriter` is possible and common. Here setting `Filter` parallelism as it's input is want to let `Filter` chain to it's Input, and keep input stream data original order. `writeParallelism` will setting the `IcebergStreaming` parallelism, that will only effect on write performance. 

If `equalityFieldColumns` has been setting, that is mean data stream will be `keyBy` by `equalityFieldColumns` between `Filter` and `IcebergStreamingWriter`. If `equalityFieldColumns` is null, that will be `rebalance` between `Filter` and `IcebergStreamingWriter`.

**Comment by coolderli** [comment]
> Actually set `write.distribution-mode = hash` can not resolve this. Because CDC data shoule be distributed to primary key but not partition fields. For example, an iceberg table has equalityFields (dt, hour, id) and partition fields (dt, hour). If set `write.distribution-mode = hash`, the CDC data will be keyBy (dt, hour), and we can not ensure same id CDC data will send to same `IcebergStreamWriter`.

I'm a litter confused. Assume that the upstream data is orderly, if the CDC data are key by (dt, hour), the same id should be send to the same `IcebergStreamWriter`.

`dt=2021-08-03, hour=10, id=1` and `dt=2021-08-03, hour=10, id=2` should be the same `IcebergStreamWriter`. I think a partition is just a subset of the primary key. If anything is wrong, please let me know. Thanks!

**Comment by Reo-LEI** [comment]
> > Actually set `write.distribution-mode = hash` can not resolve this. Because CDC data shoule be distributed to primary key but not partition fields. For example, an iceberg table has equalityFields (dt, hour, id) and partition fields (dt, hour). If set `write.distribution-mode = hash`, the CDC data will be keyBy (dt, hour), and we can not ensure same id CDC data will send to same `IcebergStreamWriter`.
> 
> I'm a litter confused. Assume that the upstream data is orderly, if the CDC data are key by (dt, hour), the same id should be send to the same `IcebergStreamWriter`.
> 
> `dt=2021-08-03, hour=10, id=1` and `dt=2021-08-03, hour=10, id=2` should be the same `IcebergStreamWriter`. I think a partition is just a subset of the primary key. If anything is wrong, please let me know. Thanks!

I think my example is inappropriate for CDC case which upstream of `IcebergStreamingWriter` is orderly. Because CDC data have -U record, that partition values can let record route to correct writer and delet the old record. 

I think  set `write.distribution-mode = hash` will work only on iceberg table have partition fields and inpurt stream is CDC case. Onec inpurt stream is upsert stream or iceberg table is an unpartitioned table which don't have any partition fields,  set `write.distribution-mode = hash` will fail.

The reason I don't agree with use `write.distribution-mode = hash` to avoid this problem is `write.distribution-mode` is use to reduce the number of small file but not to resolve row-level delete. We should not bind distribution-mode to row-level delete.

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java (hunk 3 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java:69]: The `Filter` opr is appended by flink to prevenet send null data to downstream. So the `Fliter` opr will alway exists when we use FlinkSQL to construct our job, and I think the opr name can not be change by user(so far I'm not found relevant api to rename an opr by sql).

And I think we can simply set the `Filter` opr parallelism as its input and keep `Filter` chain its input opr in all case and without worrying some side-effect. Because `Filter` will not effect the input stream.

Here only change the forward opr parallelism when forward opr is `Filter`, I think that is generally enough and safe condition to keep `Filter` chain its input

File: flink/src/main/java/org/apache/iceberg/flink/sink/HybridKeySelector.java (hunk 4 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/HybridKeySelector.java:24]: I agree `HybridKeySelector` is not easy to understand. So I will rename it to `CombinedKeySelector`.

I think distribution mode and key selector is not one-to-one correspondence, different distribution mode will use 
`EqualityFieldKeySelector` or `PartitionKeySelector` or `CombinedKeySelector`. And `range` mode will not be consider here, cuz flink not support `range` mode yet.

**Comment by Reo-LEI** [comment]
ping @kbendick @openinx 
cc @rdblue @aokolnychyi @stevenzwu

File: flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java (hunk 1 above)
Comment (kbendick) [reply flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:109]: Ah my bad. My eyes deceive me =)

**Comment by kbendick** [comment]
This PR should link to this issue: https://github.com/apache/iceberg/issues/2918

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java (hunk 3 above)
Comment (kbendick) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java:69]: So I'm still not comfortable with relying on this `Filter` operation being appended. This assumes that Flink won't change that behavior, or that we'll catch it in between releases.

Is there another way to detect the CDC case without relying on the `Filter` operation?

Also, I think we'll potentially catch more cases than just CDC by relying on `Filter` (as that's a pretty generic operation name).

Is there no way to detect that the source is a change data capture? Or that we more generally have a `RetractStream` (unless I'm mistaken, The +U / -U should be in play because this is a `RetractStream`).

Comment (kbendick) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java:69]: I guess this could also be an `UpsertStream`.

Would it make more sense to check if the stream is either an `UpsertStream` or a `RetractStream`? Checking for `Filter` seems brittle to me and as though it likely casts a very wide net.

**Comment by stevenzwu** [comment]
@Reo-LEI I left a comment in the issue #2918. Let's continue the problem discussion there. 

You probably want to rebase the PR properly. right now, it shows 1,000+ files modified.

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java (hunk 3 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java]: I found that we can capture the inputstream changelog mode when A is called, and then determine whether `Filter` is needed to chain its input by checking inputstream changelog mode.

**Comment by Reo-LEI** [comment]
> @Reo-LEI I left a comment in the issue #2918. Let's continue the problem discussion there.
> 
> You probably want to rebase the PR properly. right now, it shows 1,000+ files modified.

My mistake, I have been fix that. @stevenzwu

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 7]
```diff
@@ -369,6 +373,27 @@ private String operatorName(String suffix) {
...
+      return input;
+    }
+
+    private KeySelector<RowData, String> getKeySelector(List<Integer> equalityFieldIds, PartitionSpec partitionSpec,
+        Schema schema, RowType rowType) {
+      boolean hasPrimaryKey = equalityFieldIds != null && !equalityFieldIds.isEmpty();
+      boolean hasPartitionKey = partitionSpec != null && !partitionSpec.isUnpartitioned();
+
+      if (hasPrimaryKey && hasPartitionKey) {
+        return new CombinedKeySelector(partitionSpec, equalityFieldIds, schema, rowType);
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:389]: this defeats the purpose of hash distribution, which is make sure one writer task processed data from one partition. This `CombinedKeySelector` will nullify the goal. It seems to me that hash shuffle and equality key shuffle shouldn't be enabled at the same time.

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java (hunk 6 above)
Comment (stevenzwu) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java:71]: This is what worries me a little. this might make sense for the filter operator for the CDC stream. but is it always a good thing for other scenarios for the Flink Iceberg sink to change the parallelism of an upstream operator (which doesn't below to the Iceberg sink)?

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 8]
```diff
@@ -140,13 +141,14 @@ private Builder forRowData(DataStream<RowData> newRowDataInput) {
                                             MapFunction<T, RowData> mapper,
                                             TypeInformation<RowData> outputType) {
       this.inputCreator = newUidPrefix -> {
+        // Input stream order is crucial for some situation(e.g. in cdc case), So we need to set the map opr
+        // parallelism as it's input to keep map opr chain to input, and ensure input stream will not be rebalanced.
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:145]: I agree with this change. Since map operator is part of the Flink sink, it is ok to set the parallelism.

File: flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java [hunk 9]
```diff
@@ -148,10 +159,6 @@ private void testChangeLogs(List<String> equalityFieldColumns,
                               List<List<Record>> expectedRecordsPerCheckpoint) throws Exception {
     DataStream<Row> dataStream = env.addSource(new BoundedTestSource<>(elementsPerCheckpoint), ROW_TYPE_INFO);
 
-    // Shuffle by the equality key, so that different operations of the same key could be wrote in order when
```
Comment (stevenzwu) [inline flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:151]: maybe this unit test demonstrates the original intention that FlinkSink assumes certainly ordering of input stream and it is not the responsibility of the FlinkSink to correct any ordering problem.

File: flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java [hunk 10]
```diff
@@ -83,29 +83,39 @@
...
-        new Object[] {"avro", 1, false},
-        new Object[] {"avro", 2, true},
-        new Object[] {"avro", 2, false},
-        new Object[] {"parquet", 1, true},
-        new Object[] {"parquet", 1, false},
-        new Object[] {"parquet", 2, true},
-        new Object[] {"parquet", 2, false}
+        new Object[] {"avro", 1, true, TableProperties.WRITE_DISTRIBUTION_MODE_NONE},
+        new Object[] {"avro", 1, false, TableProperties.WRITE_DISTRIBUTION_MODE_NONE},
+        new Object[] {"avro", 4, true, TableProperties.WRITE_DISTRIBUTION_MODE_NONE},
```
Comment (stevenzwu) [inline flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:96]: nit: curious why the change of 2->4?

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 7 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:389]: As far as I know, between equality key and partition key are two independent fields, there is no restriction between them. So I add `CombinedKeySelector` to maintain the independence between them. But that will defeats the purpose of hash distribution as you say. 

restrict enable hash distribution mode when `equalityFieldIds` is not null is one way to reslove this problem, but I think should we restrict partition key must be a subset of equality key to reslove this? Actualy, I have little confuse between equality key and partition key. 

I think partition key should be a subset of equality key, because when user define the equality key in partitioned table that is mean one row should be unique in each partition. Such as we got a table partitioned by <day, hour>, we should ensure equality key contain partition key like <day, hour, id>, but not like <id>. I think the later is confusing and make no sense.
Just like a MySQL table which primary key is <userId>, and sharding data by <day, hour> to different table, and still require keep <userId> is unique in global.

Once we can ensure partition key is a subset of equality key, we can remove the `CombinedKeySelector` and use equality key sheffle data.

File: flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java (hunk 10 above)
Comment (Reo-LEI) [reply flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:96]: Because parallelism 2 could not cover this problem situation.  
Suppose we have change log as follow:
```
+I<1, "aaa">
-U<1, "aaa">
+U<1, "bbb"> 
```





So I increase that to 4

File: flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java (hunk 9 above)
Comment (Reo-LEI) [reply flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:151]: Unfortunately, we could not assumes FlinkSink will got ordering input stream. Such as when using FlinkSQL, we could not easily to control network shuffle between two opr, and that will require user to have a good understanding of how FlinkSink even FlinkSQL works.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 7 above)
Comment (stevenzwu) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:389]: regardless the answer to the question on "partition key is a subset of equality key", we probably don't need `CombinedKeySelector `
* yes. then equality key shuffle is equivalent to the combined key
* no. we only need the equality key shuffle to maintain the order. combing equality key and partition key shuffle won't bring any benefit of reducing the number of data files (that hash distribution on partition key brings)

**Comment by openinx** [comment]
@Reo-LEI Thanks for the contribution, sounds like I'm late for the reviewing.  Would you like to resolve the conflicts , I think I will get this reviewing tomorrow, thanks.

**Comment by Reo-LEI** [comment]
> @Reo-LEI Thanks for the contribution, sounds like I'm late for the reviewing. Would you like to resolve the conflicts , I think I will get this reviewing tomorrow, thanks.

@openinx Thanks for your reply. Since I discuss this PR with @kbendick  @stevenzwu, I think the implementation of setting `Filter` opr parallelism and use `CombinedKeySelector` to key by equality key and partition key maybe not a good way to reslove this problem. I'm plan to refactor this, and maybe you could review this PR after that. :)

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java (hunk 3 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java]: Resolve for https://github.com/apache/iceberg/issues/2918#issuecomment-926804817

File: flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java (hunk 6 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java]: Resolve for https://github.com/apache/iceberg/issues/2918#issuecomment-926804817

**Comment by Reo-LEI** [comment]
After the above discussion, I think we can resolve the duplicate rows by add equality/partition shuffle between `inputStream` and `IcebergStreamWriter`. And for FlinkStreaming, we can resolve disorder problem by keep `map` operator parallelism same as `inputStream`. For FlinkSQL, we can resolve disorder problem by upgrade flink to 1.13 as I mentioned on https://github.com/apache/iceberg/issues/2918#issuecomment-926804817.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 11]
```diff
@@ -412,10 +417,16 @@ private String operatorName(String suffix) {
...
+          if (!equalityFieldIds.isEmpty()) {
+            return input.keyBy(new EqualityFieldKeySelector(equalityFieldIds, iSchema, flinkRowType));
+          }
           return input;
 
         case HASH:
           if (partitionSpec.isUnpartitioned()) {
+            if (!equalityFieldIds.isEmpty()) {
+              return input.keyBy(new EqualityFieldKeySelector(equalityFieldIds, iSchema, flinkRowType));
+            }
```
Comment (Reo-LEI) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:429]: For line 420 to 429 is trying to resolve the duplicate rows problem. If equality fields are already specified, in default, that will shuffle records by `equalityFieldIds` for unpartitioned and partitioned table. 

The all cases about `Distribution Mode` discussion as follow: 

Case | Stremaing Type | Distribution Mode | Primary Key | Partition Key | Shuffle by
-- | -- | -- | -- | -- | --
1 | retract | NONE | userId |   | userId
2 | retract | NONE | userId | day, hour | userId
3 | retract | HASH | userId |   | userId
4 | retract | HASH | userId | day, hour | day, hour
5 | upsert | NONE | userId |   | userId
6 | upsert | NONE | day, hour, userId | day, hour | day, hour, userId
7 | upsert | HASH | userId |   | userId
8 | upsert | HASH | day, hour, userId | day, hour | day, hour


According to the solution of https://github.com/apache/iceberg/pull/2898#issuecomment-926830884, we will get the job graph as follow for all cases.
```
ChangelogStream-1 ---forward---> Filter/Map-1 ---+      +---> IcebergStreamWriter-1 ---+
          ...                          ...       +-hash-+             ...              +-rebalance---> IcebergFilesCommitter
ChangelogStream-m ---forward---> Filter/Map-m ---+      +---> IcebergStreamWriter-n ---+
```
Now, we can ensure all cdc/upsert record will send to correct `IcebergStreamWriter` and no -U message will be ignored.

**Comment by Reo-LEI** [comment]
I have completed the refactoring of this PR, Could you help review this PR again? @kbendick @stevenzwu @openinx

**Comment by openinx** [comment]
Thanks @Reo-LEI for the work,  I think I will take a look today or tomarrow !   Looks like it's a PR to read & understand the whole context !

**Comment by Reo-LEI** [comment]
> Thanks @Reo-LEI for the work, I think I will take a look today or tomarrow ! Looks like it's a PR to read & understand the whole context !

@openinx I think you could catch up the context through this issue https://github.com/apache/iceberg/issues/2918. :)

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 12]
```diff
@@ -0,0 +1,65 @@
...
+
+/**
+ * Create a {@link KeySelector} to shuffle by equality fields, to ensure same equality fields record will be emitted to
+ * same writer. That can prevent create duplicate record when insert and delete one row which have same equality field
+ * values on different writer in one transaction, and guarantee pos-delete will take effect.
+ */
+class EqualityFieldKeySelector extends BaseKeySelector<RowData, String> {
+
+  private static final String SEPARATOR = "-";
+  private final Integer keySize;
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:40]: nit: use primitive type?

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 13]
```diff
@@ -0,0 +1,65 @@
...
+      Accessor<StructLike> accessor = schema.accessorForField(equalityFieldIds.get(i));
+      Preconditions.checkArgument(accessor != null,
+          "Cannot build accessor for field: " + schema.findField(equalityFieldIds.get(i)));
+      accessors[i] = accessor;
+    }
+  }
+
+  @Override
+  public String getKey(RowData row) {
+    String[] values = new String[keySize];
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:59]: can we cache and reuse the array?

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 14]
```diff
@@ -0,0 +1,65 @@
...
+    for (int i = 0; i < keySize; i++) {
+      values[i] = accessors[i].get(lazyRowDataWrapper().wrap(row)).toString();
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:61]: Can `accessors[i].get(lazyRowDataWrapper().wrap(row))` return null?

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 12 above)
Comment (openinx) [reply flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:40]: I don't think we need to maintain this `keySize` to be a local variable.  The `accessors.length` is good enough to get the length in the following `getKey` method.

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 15]
```diff
@@ -0,0 +1,65 @@
...
+    for (int i = 0; i < keySize; i++) {
+      Accessor<StructLike> accessor = schema.accessorForField(equalityFieldIds.get(i));
+      Preconditions.checkArgument(accessor != null,
+          "Cannot build accessor for field: " + schema.findField(equalityFieldIds.get(i)));
+      accessors[i] = accessor;
+    }
+  }
+
+  @Override
+  public String getKey(RowData row) {
```
Comment (openinx) [inline flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:58]: Should we convert all those rows into a `String` ?  I think that will introduce much serialize cost, right ? How about using the `StructLikeWrapper` if the flink backend won't reference the generated keys.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 16]
```diff
@@ -144,13 +144,14 @@ private Builder forRowData(DataStream<RowData> newRowDataInput) {
                                             MapFunction<T, RowData> mapper,
                                             TypeInformation<RowData> outputType) {
       this.inputCreator = newUidPrefix -> {
+        // Input stream order is crucial for some situation(e.g. in cdc case). Therefore, we need to set the parallelism
+        // of map operator same as it's input to keep map operator chaining it's input, and avoid rebalanced by default.
```
Comment (openinx) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:148]: NIt: `it's` -> `its` ?

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 17]
```diff
@@ -144,13 +144,14 @@ private Builder forRowData(DataStream<RowData> newRowDataInput) {
...
+        SingleOutputStreamOperator<RowData> inputStream = input.map(mapper, outputType)
+            .setParallelism(input.getParallelism());
```
Comment (openinx) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:150]: Sounds good to me ,  do we have any unit tests to address the regression issue ?

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 18]
```diff
@@ -412,10 +417,16 @@ private String operatorName(String suffix) {
 
       switch (writeMode) {
         case NONE:
+          if (!equalityFieldIds.isEmpty()) {
+            return input.keyBy(new EqualityFieldKeySelector(equalityFieldIds, iSchema, flinkRowType));
```
Comment (openinx) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:421]: As the `RANGE` distribution mode will also fallback to use `NONE` mode,  shouldn't we also use the same shuffle strategy for it ?

Comment (openinx) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:421]: See: https://github.com/apache/iceberg/pull/2898/files#diff-a26cb8b3f0f5b0e6a9f110bb0b3fdd0ed625bfc9faf27e248f6446818cad4d69R436

Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:421]: Yes! `RANGE` distribution mode should use the same shuffle strategy,  I miss this case, thanks for your remind！

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 17 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:150]: I will add am unit test to cover this.

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 12 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:40]: LGTM

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 15 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:58]: I like this idea! I will trying to use `StructLikeWrapper` as shuffle key.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 17 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:150]: I think we set different job parallelism in 'TestFlinkIcebergSinkV2' can already cover this, right?

https://github.com/apache/iceberg/pull/2898/files#diff-13e2e5b52d0effe51e1b470df77cb08b5ec8cc4f3a7f0fd4e51ee212fc83f76aL130

**Comment by Reo-LEI** [comment]
Thanks to @openinx and @stevenzwu for review! I have been refactor the `EqualityFieldKeySelector` by `StructLikeWrapper` and resolve some comment. Maybe you can take another look for this. :)

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 19]
```diff
@@ -0,0 +1,58 @@
...
+    this.schema = schema;
+    this.deleteSchema = TypeUtil.select(schema, Sets.newHashSet(equalityFieldIds));
+  }
+
+  @Override
+  public StructLikeWrapper getKey(RowData row) {
+    // lazily construct because projection and wrapper are not serializable.
+    projection = projection == null ? StructProjection.create(schema, deleteSchema) : projection;
+    wrapper = wrapper == null ? StructLikeWrapper.forType(deleteSchema.asStruct()) : wrapper;
+    return wrapper.set(projection.wrap(lazyRowDataWrapper().wrap(row)));
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:56]: why does the return type need to be `StructLikeWrapper`? Can we directly return `projection.wrap(lazyRowDataWrapper().wrap(row))`?

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+  EqualityFieldKeySelector(List<Integer> equalityFieldIds, Schema schema, RowType flinkSchema) {
+    super(schema, flinkSchema);
+    this.schema = schema;
+    this.deleteSchema = TypeUtil.select(schema, Sets.newHashSet(equalityFieldIds));
+  }
+
+  @Override
+  public StructLikeWrapper getKey(RowData row) {
+    // lazily construct because projection and wrapper are not serializable.
+    projection = projection == null ? StructProjection.create(schema, deleteSchema) : projection;
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:54]: nit: maybe introduce `lazyStructProjection()` (similar to the ` lazyRowDataWrapper ` in base class)?

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 21]
```diff
@@ -283,15 +284,27 @@ public Builder uidPrefix(String newPrefix) {
         }
       }
 
+      // Find out the equality field id list based on the user-provided equality field column names.
+      List<Integer> equalityFieldIds = Lists.newArrayList();
+      if (equalityFieldColumns != null && equalityFieldColumns.size() > 0) {
+        for (String column : equalityFieldColumns) {
+          org.apache.iceberg.types.Types.NestedField field = table.schema().findField(column);
+          Preconditions.checkNotNull(field, "Missing required equality field column '%s' in table schema %s",
```
Comment (stevenzwu) [inline flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:292]: nit: do we need to include table schema in the error msg?

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 19 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:56]: Because `StructProjection` don't have `hashCode` method, we need to depend on `StructLikeWrapper` to offer `hashCode` method used by `KeySelector`.

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 20 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:54]: I think only `EqualityFieldKeySelector` need to project table schema to delete schema by `equalityFieldIds`, but not all `KeySelector`. Such as `PartitionKeySelector` generate key by `PartitionSpec`, but not `equalityFieldIds`.

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 21 above)
Comment (Reo-LEI) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:292]: I think this is needed, that is helpful for user to find out the problem.

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 20 above)
Comment (stevenzwu) [reply flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:54]: sorry, I meant `lazyStructProjection()` in this `EqualityFieldKeySelector ` class, not the base class

File: flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 19 above)
Comment (stevenzwu) [reply flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:56]: got it. thx for explaining. there are so many wrap/wrapper in this line of code. maybe rename `wrapper` to `structLikeWrapper`?

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 21 above)
Comment (stevenzwu) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:292]: table schema can be very long and make the log difficult to read. user can always inspect table schema using tools like Spark, Trino, Flink etc. You can keep it unless more people think it is not necessary

File: flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 18 above)
Comment (stevenzwu) [reply flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:421]: I am wondering if we can have explicit `DistributionMode` to shuffle by equality columns. Current `HASH` mode is more like `HASH-BY-PARTITION-COLUMNS`. We can have a `HASH-BY-EQUALITY-COLUMNS`. We can discuss the names, but you should get my idea.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 22]
```diff
@@ -0,0 +1,67 @@
...
+  public String getKey(RowData row) throws Exception {
+    StringBuilder builder = new StringBuilder("Key(");
+    for (int i = 0; i < accessors.length; i++) {
+      if (i != 0) {
+        builder.append(",");
+      }
+      builder.append(accessors[i].get(lazyRowDataWrapper().wrap(row)));
+    }
+    builder.append(")");
+    return builder.toString();
```
Comment (Reo-LEI) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:65]: retrun string but not `StructLikeWrapper` as key to prevent the kryo serialization issue as I mention on this [comment](https://github.com/apache/iceberg/issues/3551#issuecomment-1005360552).

**Comment by Reo-LEI** [comment]
I fix the kryo serialization problem of #3551, dose anybody can take an other look of this PR? If there are no other concerns about this PR, I think we can merge this. @rdblue @openinx @jackye1995 @stevenzwu @kbendick

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 23]
```diff
@@ -0,0 +1,67 @@
...
+  }
+
+  @Override
+  public String getKey(RowData row) throws Exception {
+    StringBuilder builder = new StringBuilder("Key(");
+    for (int i = 0; i < accessors.length; i++) {
+      if (i != 0) {
+        builder.append(",");
+      }
+      builder.append(accessors[i].get(lazyRowDataWrapper().wrap(row)));
```
Comment (stevenzwu) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:62]: nit: we can `wrap(row)` once outside the for loop

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 24]
```diff
@@ -0,0 +1,67 @@
...
+      Accessor<StructLike> accessor = schema.accessorForField(equalityFieldIds.get(i));
+      Preconditions.checkArgument(accessor != null,
+          "Cannot build accessor for field: " + schema.findField(equalityFieldIds.get(i)));
+      accessors[i] = accessor;
+    }
+  }
+
+  @Override
+  public String getKey(RowData row) throws Exception {
+    StringBuilder builder = new StringBuilder("Key(");
```
Comment (stevenzwu) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:57]: nit: do we need the `key(...)` wrap in the string?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 25]
```diff
@@ -424,6 +435,9 @@ private String operatorName(String suffix) {
         case RANGE:
           LOG.warn("Fallback to use 'none' distribution mode, because {}={} is not supported in flink now",
```
Comment (stevenzwu) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:436]: we need to move this log line into an else block

Comment (stevenzwu) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:436]: this also reminds me that it might be good to add some info level logs to mention the distribution applied.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 23 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: Good catch! I will move this out of the loop.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 24 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: I remove `Key(...)` format and use `[...]` to keep it same as `PartitionKey`.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 25 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: OK, this warn has been move to else block and I add different info log to mention different distribution mode will distribute rows by which fields.

**Review by stevenzwu — APPROVED** [review]

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 26]
```diff
@@ -412,18 +417,38 @@ private String operatorName(String suffix) {
 
       switch (writeMode) {
         case NONE:
+          if (!equalityFieldIds.isEmpty()) {
```
Comment (stevenzwu) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:420]: nit: personally I like the if-else style. but don't need to change until someone else also thinks the same way.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 27]
```diff
@@ -0,0 +1,68 @@
...
+
+  @Override
+  public String getKey(RowData row) throws Exception {
+    StructLike record = lazyRowDataWrapper().wrap(row);
+    StringBuilder builder = new StringBuilder("[");
+    for (int i = 0; i < accessors.length; i++) {
+      if (i != 0) {
+        builder.append(",");
+      }
+      builder.append(accessors[i].get(record));
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:63]: I don't think it is safe to convert to String implicitly because some values don't implement toString for a string representation. I think that you'll get byte[] or ByteBuffer and that would cause you to get different keys for equal fixed or binary values.

Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:63]: That is make sense, I will serialize the key as ByteBuffer. And I want to know are we allow use NestedType(List/Map/Struct) as equality field? If we allow this, I need a little more effort to support this.

Comment (rdblue) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: No, we don't have nested types in equality fields.

File: flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java [hunk 28]
```diff
@@ -84,36 +84,63 @@
...
+        new Object[] {"avro", 4, true, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"avro", 4, false, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"orc", 1, true, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"orc", 1, false, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"orc", 4, true, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"orc", 4, false, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"parquet", 1, true, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"parquet", 1, false, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"parquet", 4, true, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE},
+        new Object[] {"parquet", 4, false, TableProperties.WRITE_DISTRIBUTION_MODE_RANGE}
```
Comment (rdblue) [inline flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:132]: The number of tests doesn't need to be increased by 3x. Instead, can you keep the same test cases and add distribution modes that make sense? For example, have Avro use NONE, Parquet use HASH, and ORC use RANGE.

Comment (Reo-LEI) [reply flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:108]: I think that is ok, becasue distribution modes are only related to parallelism and partition. I have remove the unnecessary test cases.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 27 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: Great! So I can keep to use `Conversions` to serialize the key as ByteBuffer.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 29]
```diff
@@ -0,0 +1,75 @@
...
+      Accessor<StructLike> accessor = schema.accessorForField(equalityFieldIds.get(i));
+      Preconditions.checkArgument(accessor != null,
+          "Cannot build accessor for field: {}", schema.findField(equalityFieldIds.get(i)));
+
+      accessors[i] = accessor;
+    }
+  }
+
+  @Override
+  public ByteBuffer getKey(RowData row) throws Exception {
```
Comment (stevenzwu) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:62]: this is used in the hot code path of per-record processing. small concern on the number of ByteBuffer creation/wrap, concatenation. but not sure how to make it better and maybe we don't pre-maturely optimize it until is proved to be a problem.

Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:62]: Agree!

**Comment by Reo-LEI** [comment]
@rdblue Any other concerns about this PR?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 30]
```diff
@@ -283,15 +284,27 @@ public Builder uidPrefix(String newPrefix) {
         }
       }
 
+      // Find out the equality field id list based on the user-provided equality field column names.
+      List<Integer> equalityFieldIds = Lists.newArrayList();
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:288]: If the equality field columns are null, then what about using the equality fields from the schema by default?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 31]
```diff
@@ -412,18 +417,38 @@ private String operatorName(String suffix) {
 
       switch (writeMode) {
         case NONE:
+          if (!equalityFieldIds.isEmpty()) {
+            LOG.info("Distribute rows by equality fields in '{}' distribution mode", DistributionMode.NONE.modeName());
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:421]: Are so many info statements needed?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 32]
```diff
@@ -412,18 +417,38 @@ private String operatorName(String suffix) {
...
         case HASH:
           if (partitionSpec.isUnpartitioned()) {
+            if (!equalityFieldIds.isEmpty()) {
+              LOG.info("Distribute rows by equality fields in '{}' distribution mode, because table is unpartitioned",
+                  DistributionMode.HASH.modeName());
+              return input.keyBy(new EqualityFieldKeySelector(equalityFieldIds, iSchema, flinkRowType));
+            }
+
+            LOG.warn("Fallback to use '{}' distribution mode, because table is unpartitioned",
+                DistributionMode.NONE.modeName());
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:436]: This is happening because the table is unpartitioned _and_ there are no equality fields set.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 33]
```diff
@@ -412,18 +417,38 @@ private String operatorName(String suffix) {
...
             return input;
           } else {
+            LOG.info("Distribute rows by partition fields in '{}' distribution mode", DistributionMode.HASH.modeName());
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: Why not use both partition and equality field? Why is it okay to ignore equality fields for this case?

Comment (stevenzwu) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: hash distribution was trying to bring all rows for the same partition value to a single writer. if we include equality field, that would defeat the purpose. On the other hand, if we don't include equality field, we would still suffer the issue that this PR is trying to address. Maybe with equality field, we shouldn't use `HASH` distribution?

Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: I discuss the [approach ](https://github.com/apache/iceberg/pull/2898#discussion_r693618065) of combined key with steven before. And I list all cases of distribution in [here](https://github.com/apache/iceberg/pull/2898#discussion_r715845154). 

For this case(table is partitioned and have equality fields and enabled `HASH` distribution), I think we should demand the partition key must be a part of equality key, and we could distribute rows by equality key. Otherwise, we should raise an error and not allow use `HASH` distribution with equality fields.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 31 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:421]: Yes, I agree with steven on this [discussion ](https://github.com/apache/iceberg/pull/2898#discussion_r779281367) that we should indicate we distribute rows by what key in what distribution mode.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 32 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:436]: If the equality fields are not set, that is mean this table maybe don't have equality fields at all. I think we should not mention equality fields to remind user to setting the equality fields, right?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 30 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:288]: Currently, the `equalityFieldIds` value come from the `equalityFieldColumns`, and the `equalityFieldColumns` setting by user or parse from primary key of SQL. 

Usually, the `equalityFieldColumns` should equal to the `identifierFieldIds` of schema, and we don't need the default value of `equalityFieldIds`. But when user remove the setting of `equalityFieldColumns` or remove parimary key from SQL, and the `identifierFieldIds` is not null. If we use `identifierFieldIds` as default value of `equalityFieldIds`, I can't imagine what's going to happen, maybe it's not what the user wants.

Comment (rdblue) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:288]: I think that Flink should default to the defined identifier field IDs for upsert behavior. If the user sets the columns explicitly, then we should check and warn if they don't match.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 33 above)
Comment (rdblue) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: For HASH, we have two cases. First, the hash distribution by partition key may satisfy the required equality distribution. For example, distributing by bucket(16, id) for the equality field id satisfies the requirement because all id values are sent to the same task.

If the partition distribution satisfies the equality distribution, then this should use the partition distribution. Otherwise, it should use the equality distribution to guarantee correctness. It's up to @stevenzwu and you whether you think the latter case should fail and throw an exception ("The required distribution, hash by partition key, does not correctly group the upsert key") or should warn and use the equality distribuiton.

Comment (stevenzwu) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: When users set HASH distribution, the intention is to cluster data by partition columns. if the hash distribution by partition key doesn't satisfy the required equality distribution, personally I prefer fail with an exception (instead of silently converting the behavior to equality distribution). In this case, I would say it is an incorrect config. We shouldn't set HASH distribution config at all.

**Comment by liubo1022126** [comment]
@Reo-LEI @rdblue hi，boys，We are currently using the flink upsert function. In which version is this PR planned to be released?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 33 above)
Comment (kbendick) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: Strongly agree on loudly, strongly failing (hopefully with a helpful exception) vs silently misbehaving.

**Comment by Reo-LEI** [comment]
> @Reo-LEI @rdblue hi，boys，We are currently using the flink upsert function. In which version is this PR planned to be released?

I will adressing comments in this weeken. Thank you for your attention! @liubo1022126

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 31 above)
Comment (kbendick) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:421]: There are quite a number of info logs that seem to repeat similar statements. Can these at least be merged somehow?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 33 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: It seems like a safer way to forbid using HASH distribution with equality fields. I will fix this later.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 32 above)
Comment (kbendick) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:436]: > his is happening because the table is unpartitioned and there are no equality fields set. 

I think what Ryan means is that if we’re logging the reason some change is occuring, we should log the full reason. An unpartitioned table with equality field ids set wouldn’t fall back to NONE but the log message tells the user only part of the reasoning so they have incomplete information on changing the behavior.

And the users set writeMode, so likely some of them want to determine how to get the desired distribution mode in their job. So people will potentially think they _have_ to partition their table when they could just set equality fields and avoid having to change their data layout.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 33 above)
Comment (rdblue) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:439]: @Reo-LEI, I don't think that's accurate. The requirement is to detect whether the equality distribution is satisfied by the hash distribution. If it is, then you can use the hash distribution. If not, then fail.

I think that check should be whether there are any partition fields that use a source column that is not part of the identifier fields. For example, a table with `type`, `id`, and `data` and a simple key `id` requires any partition transform that uses `id`, like `bucket(256, id)` or `truncate(id, 10)`. But if there is an additional field like `data` then we can't guarantee that all `id` values go to the same data partition.

Another case that does work is when the table identifier is made from both `type` and `id`. In that case, partitioning by either `type` or `id` individually works. Same with partitioning by `type` and `id`. But again, partitioning by data ruins the distribution.

So the logic should be: make sure that the partition spec includes at least one identifier field column and that all of the partition source fields are identifier fields.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 26 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: done

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 30 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:289]: done

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 31 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: I deleted some unnecessary logs and rewritten the statements. Now the statements of the logs will not be repeated. Please take a look again.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 32 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: I rephrased the log and added the full reason. Please take a look again.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java (hunk 33 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: Thanks @rdblue for the detailed explanation, and @kbendick and @stevenzwu for the advice!

I reorganized the code of distribute. And for this case (table is partitioned and have equality fields and enabled HASH distribution) I added a check to requiring all of the partition source fields are identifier fields. Please take a look again.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseKeySelector.java [hunk 34]
```diff
@@ -0,0 +1,49 @@
...
+ */
+
+package org.apache.iceberg.flink.sink;
+
+import org.apache.flink.api.java.functions.KeySelector;
+import org.apache.flink.table.types.logical.RowType;
+import org.apache.iceberg.Schema;
+import org.apache.iceberg.flink.RowDataWrapper;
+
+
```
Comment (openinx) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseKeySelector.java:27]: Nit: we usually left only one blank line here, right ?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 29 above)
Comment (openinx) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:62]: We don't need to construct a totally new `ByteBuffer` for generating the shuffling key.  Actually we can only construct a lightweight `StructLikeWrapper` which will calculate its hashCode for shuffling purpose.   Because in the root path,  the `KeyGroupRangeAssignment` only need the key's `hashCode`. see https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/flink/runtime/state/KeyGroupRangeAssignment.java#L65 . 

As this is a hot code path as @stevenzwu said, I will strongly suggest to use the shadow clone approach rather then the deep clone one.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseKeySelector.java (hunk 34 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseKeySelector.java]: Fixed.

Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseKeySelector.java]: Fixed.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 29 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: Nice catch! I have rolled back the implementation of `EqualityFieldKeySelector` to use `StructLikeWrapper` and return the `hashCode` of `Struct Like Wrapper`. Please read it again!

**Review by openinx — CHANGES_REQUESTED** [review]
Thanks @Reo-LEI's contribution, I left several comments that I think we need to address.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 35]
```diff
@@ -0,0 +1,75 @@
...
+  protected StructLikeWrapper lazyStructLikeWrapper() {
+    if (structLikeWrapper == null) {
+      structLikeWrapper = StructLikeWrapper.forType(deleteSchema.asStruct());
+    }
+    return structLikeWrapper;
+  }
+
+  @Override
+  public Integer getKey(RowData row) {
+    return lazyStructLikeWrapper().set(lazyStructProjection().wrap(lazyRowDataWrapper().wrap(row))).hashCode();
```
[the remark this answers is not in the document]
Comment (stevenzwu) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:73]: +1. 

I also have a a little concern here. For the keyBy, we are essentially doing two layers of hashCode:  equalityKeys.hashCode().hashCode(). wondering if it can cause any skewed distribution. Don't know if it is a problem or not.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 36]
```diff
@@ -0,0 +1,75 @@
...
+
+  private final Schema schema;
+  private final Schema deleteSchema;
+
+  private transient StructProjection structProjection;
+  private transient StructLikeWrapper structLikeWrapper;
+
+  EqualityFieldKeySelector(List<Integer> equalityFieldIds, Schema schema, RowType flinkSchema) {
+    super(schema, flinkSchema);
+    this.schema = schema;
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:48]: OK，I will remove the `BaseKeySelector` until we got more other key selector and we need this.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 37]
```diff
@@ -0,0 +1,75 @@
...
+import org.apache.flink.table.types.logical.RowType;
+import org.apache.iceberg.Schema;
+import org.apache.iceberg.relocated.com.google.common.collect.Sets;
+import org.apache.iceberg.types.TypeUtil;
+import org.apache.iceberg.util.StructLikeWrapper;
+import org.apache.iceberg.util.StructProjection;
+
+/**
+ * Create a {@link KeySelector} to shuffle by equality fields, to ensure same equality fields record will be emitted to
+ * same writer. That can prevent create duplicate record when insert and delete one row which have same equality field
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: done

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 35 above)
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: > Nit: It more clear for me to understand the unfolded code like the following

Done. 

> For the keyBy, we are essentially doing two layers of hashCode: equalityKeys.hashCode().hashCode(). wondering if it can cause any skewed distribution.

I think we shoult not worry about the second `hashCode()`, because Interger's `hashCode` is the value itself.

However, `keyBy` with equailty fields does have skewed data in some cases, but I think we can avoid the skewed data by setting the equailty fields, using the equailty fields as a partition, and then turning on the `HASH` distribution mode (as Ryan said, make sure that all of the partition source fields are identifier fields, we can distribute data by partition key).

For example, if the equailty fields of a table is `id` and `type`, we can partition the `id`, such as `bucket(id, 16)`, and then turn on the `HASH distribution mode`, and the data will be distributed by the partition key  `bucket(id, 16)`. And we avoid the skewed data.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 38]
```diff
@@ -146,13 +148,14 @@ private Builder forRowData(DataStream<RowData> newRowDataInput) {
                                             MapFunction<T, RowData> mapper,
                                             TypeInformation<RowData> outputType) {
       this.inputCreator = newUidPrefix -> {
+        // Input stream order is crucial for some situation(e.g. in cdc case). Therefore, we need to set the parallelism
+        // of map operator same as its input to keep map operator chaining its input, and avoid rebalanced by default.
+        SingleOutputStreamOperator<RowData> inputStream = input.map(mapper, outputType)
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:153]: Currently, many test cases of `TestFlinkIcebergSinkV2` are depend on this config. If we remove this, these test case would be faild. I think these test cases has cover this change.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 39]
```diff
@@ -295,15 +298,34 @@ public Builder setSnapshotProperty(String property, String value) {
...
+        Set<Integer> equalityFieldSet = Sets.newHashSetWithExpectedSize(equalityFieldColumns.size());
+        for (String column : equalityFieldColumns) {
+          org.apache.iceberg.types.Types.NestedField field = table.schema().findField(column);
+          Preconditions.checkNotNull(field, "Missing required equality field column '%s' in table schema %s",
+              column, table.schema());
+          equalityFieldSet.add(field.fieldId());
+        }
+
+        if (!equalityFieldSet.equals(table.schema().identifierFieldIds())) {
+          LOG.warn("The configured equality field columns are not match with the identifier fields of schema, " +
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: done

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 40]
```diff
@@ -295,15 +298,34 @@ public Builder setSnapshotProperty(String property, String value) {
...
+              "use job specified equality field columns as the equality fields by default.");
+        }
+        equalityFieldIds = Lists.newArrayList(equalityFieldSet);
+      }
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: done

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 41]
```diff
@@ -422,21 +436,50 @@ private String operatorName(String suffix) {
...
+            }
           }
 
         case RANGE:
-          LOG.warn("Fallback to use 'none' distribution mode, because {}={} is not supported in flink now",
-              WRITE_DISTRIBUTION_MODE, DistributionMode.RANGE.modeName());
-          return input;
+          if (equalityFieldIds.isEmpty()) {
+            LOG.warn("Fallback to use 'none' distribution mode, because there are no equality fields set " +
+                "and write.distribution-mode=range is not supported yet in flink");
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: done

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 42]
```diff
@@ -422,21 +436,50 @@ private String operatorName(String suffix) {
...
+            return input;
+          } else {
+            LOG.info("Distribute rows by equality fields, because there are equality fields set " +
+                "and write.distribution-mode=range is not supported yet in flink");
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java]: done

File: flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java [hunk 43]
```diff
@@ -84,36 +84,39 @@
   private final FileFormat format;
   private final int parallelism;
   private final boolean partitioned;
+  private final String distributionMode;
 
   private StreamExecutionEnvironment env;
   private TestTableLoader tableLoader;
 
-  @Parameterized.Parameters(name = "FileFormat = {0}, Parallelism = {1}, Partitioned={2}")
+  @Parameterized.Parameters(name = "FileFormat = {0}, Parallelism = {1}, Partitioned={2}, Distribution={3}")
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java]: done

File: flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java [hunk 44]
```diff
@@ -155,10 +159,6 @@ private void testChangeLogs(List<String> equalityFieldColumns,
                               List<List<Record>> expectedRecordsPerCheckpoint) throws Exception {
     DataStream<Row> dataStream = env.addSource(new BoundedTestSource<>(elementsPerCheckpoint), ROW_TYPE_INFO);
 
-    // Shuffle by the equality key, so that different operations of the same key could be wrote in order when
-    // executing tasks in parallel.
-    dataStream = dataStream.keyBy(keySelector);
```
[the remark this answers is not in the document]
Comment (Reo-LEI) [reply flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java:160]: Yes, because we ensure the input will not be disorder in `FlinkSink.forMapperOutputType` and data will be correctly  distributed by equaily fields or partition fields in different distribution mode. So we can remove this in unittest

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseKeySelector.java [hunk 45]
```diff
@@ -0,0 +1,48 @@
...
+ */
+
+package org.apache.iceberg.flink.sink;
+
+import org.apache.flink.api.java.functions.KeySelector;
+import org.apache.flink.table.types.logical.RowType;
+import org.apache.iceberg.Schema;
+import org.apache.iceberg.flink.RowDataWrapper;
+
+abstract class BaseKeySelector<I, K> implements KeySelector<I, K> {
```
Comment (openinx) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseKeySelector.java:27]: So this class can be removed now ?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java [hunk 46]
```diff
@@ -338,6 +345,27 @@ private String operatorName(String suffix) {
...
+      if (equalityFieldColumns != null && equalityFieldColumns.size() > 0) {
+        Set<Integer> equalityFieldSet = Sets.newHashSetWithExpectedSize(equalityFieldColumns.size());
+        for (String column : equalityFieldColumns) {
+          org.apache.iceberg.types.Types.NestedField field = table.schema().findField(column);
+          Preconditions.checkNotNull(field, "Missing required equality field column '%s' in table schema %s",
+              column, table.schema());
+          equalityFieldSet.add(field.fieldId());
+        }
+
+        if (!equalityFieldSet.equals(table.schema().identifierFieldIds())) {
```
Comment (openinx) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:359]: The `identifierFieldsIds` will be a `ImmutableHashSet`, while the `equalityFieldSet` will be a `HashSet`,  the the `.equals` will always be false, right ? 
I think it's better to change to check set size & elements for two sets.

Comment (openinx) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:359]: The `identifierFieldsIds` will be a `ImmutableHashSet`, while the `equalityFieldSet` will be a `HashSet`,  the the `.equals` will always be false, right ? 
I think it's better to change to check set size & elements for two sets.

Comment (openinx) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java:361]: Okay, I checked the HashSet's equal method, it does not check the concrete class type. this should be fine.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java [hunk 47]
```diff
@@ -0,0 +1,91 @@
...
+
+  private final Schema schema;
+  private final RowType flinkSchema;
+  private final Schema deleteSchema;
+
+  private transient RowDataWrapper rowDataWrapper;
+  private transient StructProjection structProjection;
+  private transient StructLikeWrapper structLikeWrapper;
+
+  EqualityFieldKeySelector(List<Integer> equalityFieldIds, Schema schema, RowType flinkSchema) {
```
Comment (openinx) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java:47]: Nit: Could we shift the `equalityFieldIds`  to be to 3rd argument ? That makes argument definition order strickly match the following assignment order.  It's a minor thing but make the code more clear.

**Review by openinx — APPROVED** [review]
I left a minor comment, but I think it's okay to get this merged now.  Thanks @Reo-LEI for the contribution, and thanks @stevenzwu @kbendick @rdblue for the reviewing.  This should also be applied to other flink 1.12 and flink 1.13.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java (hunk 47 above)
Comment (Reo-LEI) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/EqualityFieldKeySelector.java]: Done, and thanks for reviewing!

**Comment by Reo-LEI** [comment]
Thanks @openinx  @stevenzwu @kbendick @rdblue for the reviewing! I will port this patch to flink 1.12 and 1.13 after this merged.
