### PR TITLE
Only warn if OAuth2 server URI is not set

### LINKED ISSUE #13732: Misleading warning when configuring OAuth 2 URI
### Apache Iceberg version

1.9.2 (latest release)

### Query engine

None

### Please describe the bug 🐞

1. Configure the Iceberg REST client to use a custom OAuth2 endpoint via the `oauth2-server-uri` property with the same host as the catalog.
2. Receive this warning asking you to configure the `oauth2-server-uri` property:
  ```
  WARN OAuth2Manager: Iceberg REST client is missing the OAuth2 server URI configuration and defaults ... 
This warning will disappear if the OAuth2 endpoint is explicitly configured. See https://github.com/apache/iceberg/issues/10537
  ```

The underlying cause is [the check](https://github.com/apache/iceberg/blob/c23b341ea4398c2513fe2495a44fc6f23e4d72ef/core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java#L297-L299) in `OAuth2Manager` that determines whether:

1. The `oauth2-server-uri` property is set, and  
2. The configured OAuth2 endpoint has the catalog URI as its prefix or is a relative path URI.

Since we want to remove the default tokens endpoint (`/v1/oauth/tokens`) as part of [#10537](https://github.com/apache/iceberg/issues/10537), the intention behind the warning is presumably to alert users who rely on the catalog’s built-in tokens endpoint. 
However, the current check incorrectly flags scenarios in which users have explicitly configured the OAuth2 server URI to a path that resembles the catalog server uri.

#### Proposed Fix

- Allow users to set `oauth2-server-uri` to any desired URL.  
  - Eliminate the assumption that if a custom OAuth2 endpoint is under the same domain or path prefix as the catalog endpoint, it must be using `<catalog-uri>/v1/oauth/tokens`.  
- (if we want to) Only trigger the warning if `oauth2-server-uri` is truly unset or if it is a relative path (`/v1/oauth/tokens`).  

This reflects the principle that the client should not attempt to override user intentions regarding where the OAuth2 server lives when it's explicitly set. 
This also does not interfere with the plan to remove the endpoint or alter the default behavior.

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by 1raghavmahajan**
Closes #13732 

```
WARN OAuth2Manager: Iceberg REST client is missing the OAuth2 server URI configuration and defaults ... 
This warning will disappear if the OAuth2 endpoint is explicitly configured. See https://github.com/apache/iceberg/issues/10537
```
Above warning was shown for 2 scenarios. Updated behavior:
- Warn if OAuth2Properties.OAUTH2_SERVER_URI is not set.
- ~Also warn if OAuth2Properties.OAUTH2_SERVER_URI is set but ends with [v1/oauth/tokens](https://github.com/apache/iceberg/blob/4ae61621c1b5e7f245961b3de48d6d8a3856d012/core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java#L57-L59)~

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java [hunk 1]
```diff
@@ -273,33 +273,32 @@ protected OAuth2Util.AuthSession newSessionFromTokenResponse(
...
-  }
-
-  private static boolean usesDeprecatedTokenEndpoint(Map<String, String> properties) {
-    if (properties.containsKey(OAuth2Properties.OAUTH2_SERVER_URI)) {
+    } else {
       String oauth2ServerUri = properties.get(OAuth2Properties.OAUTH2_SERVER_URI);
-      boolean relativePath = !oauth2ServerUri.startsWith("http");
-      boolean sameHost = oauth2ServerUri.startsWith(properties.get(CatalogProperties.URI));
-      return relativePath || sameHost;
+      if (!oauth2ServerUri.startsWith("http") && oauth2ServerUri.endsWith(ResourcePaths.tokens())) {
```
Comment (1raghavmahajan) [inline core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: I have retained this part, keeping in mind @adutra's intention of warning users if they're still using the tokens endpoint. I stand by allowing users to specify any `oauth2-server-uri`, but if we have to draw a line, the relative path seems less explicit and more likely to indicate that they simply copied the default value to get rid of the old warning.

**Comment by 1raghavmahajan** [comment]
cc @adutra @nastra @danielcweeks

**Comment by 1raghavmahajan** [comment]
cc @rdblue

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java (hunk 1 above)
Comment (kevinjqliu) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: nit: 

is `oauth2ServerUri.endsWith(ResourcePaths.tokens())` the same as `oauth2ServerUri.startsWith(properties.get(CatalogProperties.URI))`? 

also should this is OR instead of AND?

**Review by kevinjqliu — COMMENTED** [review]
LGTM, i have a question about checking if `OAuth2Properties.OAUTH2_SERVER_URI` is set to use the deprecated /tokens endpoint. The logic seems different than before

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java (hunk 1 above)
Comment (1raghavmahajan) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: The earlier validation checked if it was the same host. Now, the logic is different (see https://github.com/apache/iceberg/issues/13732). We now check if the path is relative and indicates the deprecated token endpoint; only then do we warn the user.

Comment (kevinjqliu) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: make sense, do we still need to check if its starts with `http`? seems redundant

Comment (1raghavmahajan) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: We only want the warning for relative paths, not absolute ones. The idea being if I've explicitly set the uri to be under the catalog URI, then I should be able to do so without getting warned. Going back [to](https://github.com/apache/iceberg/pull/13741#discussion_r2254357385) 
>   but if we have to draw a line, the relative path seems less explicit and more likely to indicate that they simply copied the default value to get rid of the old warning.

I could simplify the check by just doing below but then we don't catch prefixes like `/`; and I felt doing URI normalization might a bit overkill. 
```suggestion
      if (oauth2ServerUri.equals(ResourcePaths.tokens())) {
```

Comment (kevinjqliu) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: > We only want the warning for relative paths, not absolute ones.

gotcha makes sense.

> I felt doing URI normalization might a bit overkill.

i like `oauth2ServerUri.endsWith(ResourcePaths.tokens()))`, lets leave it.

Comment (danielcweeks) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: I don't think we should include this check.  This implys that having an endpoint with `v1/oauth/tokens` is incorrect, which is not the case.  We're removing the endpoint from the spec definition, but it's still a fully valid endpoint and relative should be fine as well.  Requiring the explicit URI is good because it's clear and explicit what is being used for auth, but beyond that we don't need to be opinionated.

Comment (1raghavmahajan) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: That was the initial draft of my changes but I wanted to keep it as its akin to warning a user when they're using a deprecated method. If people agree, I'm okay with nuking this extra check.
cc @adutra

Comment (danielcweeks) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: Including the endpoint in the spec is deprecated, but the endpoint is not.  We should only be checking that the user is explicitly setting the server URI (we should not prohibit what they point that to).

Comment (dimas-b) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: I agree that if the token URI is configured explicitly, any value should be permitted. Existing servers should not be required to change token endpoint URIs, even though the API spec lists it as deprecated. Effectively, the deprecation of the token endpoint in the spec requires it to be configured explicitly (in my reading).

**Comment by danielcweeks** [comment]
There seems to be a little confusion over what we're deprecating here and it's bleeding into the warning.  We want to deprecate/remove the `v1/oauth/tokens` from the REST spec as we don't want to define the security/auth required when implementing the spec.

However, this does not mean that we should be warning about a particular path being used (e.g. `v1/oauth/tokens`).  That's a perfectly valid endpoint to use. 

I'm ok with disallowing relative paths if we want to go that direction, but we shouldn't be warning about the `v1/oauth/tokens` path specifically if we do allow relative paths.  Once a user has set the server URI explicitly, it's the same as any other path.

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java (hunk 1 above)
Comment (1raghavmahajan) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: I've removed the special check and now we just warn the user if the endpoint is not explicitly configured.

**Comment by 1raghavmahajan** [comment]
That makes sense. I've updated the PR. This reverts the behavior back to what it was before AuthManager.
- Warn if OAuth2Properties.OAUTH2_SERVER_URI is not set.
- ~Also warn if OAuth2Properties.OAUTH2_SERVER_URI is set but ends with [v1/oauth/tokens](https://github.com/apache/iceberg/blob/4ae61621c1b5e7f245961b3de48d6d8a3856d012/core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java#L57-L59)~

**Comment by 1raghavmahajan** [comment]
@danielcweeks @kevinjqliu If the changes look good, can we merge this?

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java [hunk 2]
```diff
@@ -273,15 +273,15 @@ protected OAuth2Util.AuthSession newSessionFromTokenResponse(
...
+    if (!properties.containsKey(OAuth2Properties.OAUTH2_SERVER_URI)) {
       String credential = properties.get(OAuth2Properties.CREDENTIAL);
       String initToken = properties.get(OAuth2Properties.TOKEN);
       boolean hasCredential = credential != null && !credential.isEmpty();
       boolean hasInitToken = initToken != null;
       if (hasInitToken || hasCredential) {
         LOG.warn(
             "Iceberg REST client is missing the OAuth2 server URI configuration and defaults to {}/{}. "
-                + "This automatic fallback will be removed in a future Iceberg release."
+                + "This automatic fallback will be removed in a future Iceberg release. "
```
Comment (kevinjqliu) [inline core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java:284]: nit: is this extra space required? 
```suggestion
                + "This automatic fallback will be removed in a future Iceberg release."
```

**Review by kevinjqliu — APPROVED** [review]
LGTM! Thanks for the PR

Could you fix the title and description to match the new behavior?

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java (hunk 2 above)
Comment (adutra) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java:284]: I think so? As it's concatenated to the next sentence below.

**Review by dimas-b — APPROVED** [review]

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java [hunk 3]
```diff
@@ -273,15 +273,15 @@ protected OAuth2Util.AuthSession newSessionFromTokenResponse(
   }
 
   private static void warnIfDeprecatedTokenEndpointUsed(Map<String, String> properties) {
```
Comment (kevinjqliu) [inline core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: nit: we can change the name to match the current behavior, which is to warn is `oauth2-server-uri` is not set

Comment (1raghavmahajan) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java]: Pushed. https://github.com/apache/iceberg/pull/13741/commits/b532d9da7b1740f98e9b667ad1979daa5d06dd49

**Review by danielcweeks — APPROVED** [review]

**Comment by kevinjqliu** [comment]
Thanks for the PR @1raghavmahajan and thanks everyone for the review!
