### PR TITLE
Filtering dictionary encoded FIX_LEN_BYTE_ARRAY

### LINKED ISSUE #2546: Dictionary filter for Parquet does not handle FIXED_LEN_BYTE_ARRAY
If a Parquet file contains dictionary encoded `FIXED_LEN_BYTE_ARRAY` values (e.g. `DECIMAL`s) the related filtering throws an `IllegalArgumentException: Cannot decode dictionary of type: FIXED_LEN_BYTE_ARRAY`. I guess the library is not prepared for dictionary encoded `FIXED_LEN_BYTE_ARRAY` values because parquet-mr does not write such encoding for these values (for V1 at least) but it is not a specified behavior so other implementations (like Impala) may write them.

### PR DESCRIPTION
**Pull request by gszadovszky**
Fixes #2546

### CODE REVIEW

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java [hunk 1]
```diff
@@ -406,6 +406,8 @@ public Boolean or(Boolean leftResult, Boolean rightResult) {
 
       for (int i = 0; i <= dict.getMaxId(); i++) {
         switch (col.getPrimitiveType().getPrimitiveTypeName()) {
+          case FIXED_LEN_BYTE_ARRAY: dictSet.add((T) conversion.apply(dict.decodeToBinary(i)));
+            break;
```
Comment (gszadovszky) [inline parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java:410]: I wanted to write the following but Checkstyle failed on it because of indention. I guess, it is/was a [Checkstyle bug](https://github.com/checkstyle/checkstyle/issues/341). I don't have experience on gradle so I am not sure how to fix this in Iceberg configuration. Probably, we need to upgrade Checkstyle somehow.

Anyway, both the current and this other one is correct but I would prefer the latter.
```suggestion
          case FIXED_LEN_BYTE_ARRAY:  // Same as BINARY
```

File: parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java [hunk 2]
```diff
@@ -140,6 +152,7 @@ public void createInputFile() throws IOException {
     OutputFile outFile = Files.localOutput(parquetFile);
     try (FileAppender<Record> appender = Parquet.write(outFile)
         .schema(FILE_SCHEMA)
+        .withWriterVersion(WriterVersion.PARQUET_2_0) // V2 is needed to force dictionary encoding for FIXED type
```
Comment (rdblue) [inline parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java:155]: Why is this?

Comment (gszadovszky) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java:155]: I don't know why we do not use dictionary encoding for V1 but this is the current case. See [DefaultV1ValuesWriterFactory](https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/values/factory/DefaultV1ValuesWriterFactory.java#L78-L80). Meanwhile this behavior is not specified anywhere so other implementations may write it and Impala certainly does.

Comment (pvary) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java:155]: @rdblue: Does Iceberg specification defines which writer version we should use?

@gszadovszky: What happens when a V2 writer is used and an old parquet client tries to read the file.

Thanks,
Peter

Comment (gszadovszky) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java:155]: @pvary: V1 and V2 are quite tricky references because it is not always clear what it covers. From parquet-mr point of view the most basic differences are the page headers (v1 or v2) and the used encodings. Since parquet-mr has support for v2 since a while it is mostly not about the old parquet readers but the other implementations of parquet readers. For example Impala does not support v2 page headers nor the encodings used by parquet-mr in case of v2 is set.
BUT, using dictionary encoding for fixed data types are not against parquet specification for v1. And Impala does it. (It is only parquet-mr that does not do dictionary encoding for fixed types in case of v1 but it can read it and the filtering also works just fine.)

I've been hesitating to switch the whole unit test to V2 (or implement a separate test for fixed+dictionary) but this seemed easier and simpler. Also, V1 or V2 seems irrelevant to this test (excluding the fact that we cannot test fixed+dictionary with V1).

**Comment by gszadovszky** [comment]
I think, it is fine to extend the API with package-private methods for testing purposes. It makes the testing simpler and easier to implement. Meanwhile, I am open to invest on writing the test without the need of this extension if you think it is required.
@rdblue, what do you think?

File: parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java (hunk 2 above)
Comment (rdblue) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java:155]: @pvary, I'm assuming that people mostly don't use Parquet v2 because it was never finalized (to my knowledge). I think there's an ongoing effort in the Parquet community to clean up some of the docs, but I've not seen a vote to adopt any of the v2 encodings as official.

**Comment by rdblue** [comment]
@gszadovszky, I think the package-private method is fine. But we need to make sure that this doesn't stop testing v1 since that's what people primarily use. Could you add v1/v2 as a test parameter so all the tests run on both?

**Comment by gszadovszky** [comment]
Thanks @rdblue. I've thought v1/v2 is irrelevant for this test but I agree it is better to be on the safe side and it's a good idea to add writer version as a test parameter. I'll make this change soon.

File: parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java [hunk 3]
```diff
@@ -911,20 +928,31 @@ public void testTypePromotion() {
...
-    boolean shouldRead = new ParquetDictionaryRowGroupFilter(SCHEMA,
-        greaterThanOrEqual("decimal_fixed", BigDecimal.ZERO)).shouldRead(parquetSchema, rowGroupMetadata,
-            dictionaryStore);
-    Assert.assertTrue("Should read: Half of the decimal_fixed values are greater than 0", shouldRead);
-
-    shouldRead = new ParquetDictionaryRowGroupFilter(SCHEMA, lessThan("decimal_fixed", DECIMAL_MIN_VALUE))
-        .shouldRead(parquetSchema, rowGroupMetadata, dictionaryStore);
-    Assert.assertFalse("Should not read: No decimal_fixed values less than -1234567890.0987654321", shouldRead);
+    switch (writerVersion) {
+      case PARQUET_1_0:
```
Comment (rdblue) [inline parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java:936]: Normally, we would use `Assume` to simply skip this test for Parquet v1. Would you mind doing that here? I don't think we need to validate that Parquet doesn't dictionary encode.

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks, @gszadovszky!
