### PR TITLE
API:add try catch on ExpressionUtils.sanitizeString

### LINKED ISSUE #6911: BaseTableScan(SnapshotScan)::planFiles throws ParseException from logInfo
### Apache Iceberg version

1.1.0

### Query engine

None

### Please describe the bug 🐞

We started getting this exception in some of our UTs after upgrading to 1.1.0. Basically in the test we use a string field in the partition spec, and provide some string partition values like it's converted by a datetime("2020-20-20") write was fine, but read will throw exceptions like this:
    java.time.format.DateTimeParseException: Text '2021-20-20' could not be parsed: Invalid value for MonthOfYear (valid values 1 - 12): 20
        at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:1920)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1855)
        at java.time.LocalDate.parse(LocalDate.java:400)
        at org.apache.iceberg.expressions.Literals$StringLiteral.to(Literals.java:495)
        at org.apache.iceberg.expressions.ExpressionUtil.sanitizeString(ExpressionUtil.java:380)
        at org.apache.iceberg.expressions.ExpressionUtil.sanitize(ExpressionUtil.java:320)
        at org.apache.iceberg.expressions.ExpressionUtil.access$300(ExpressionUtil.java:38)
        at org.apache.iceberg.expressions.ExpressionUtil$StringSanitizer.predicate(ExpressionUtil.java:269)
        at org.apache.iceberg.expressions.ExpressionUtil$StringSanitizer.predicate(ExpressionUtil.java:197)
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:347)
        at org.apache.iceberg.expressions.ExpressionVisitors.visit(ExpressionVisitors.java:366)
        at org.apache.iceberg.expressions.ExpressionUtil.toSanitizedString(ExpressionUtil.java:82)
        at org.apache.iceberg.BaseTableScan.planFiles(BaseTableScan.java:142)
        at org.apache.iceberg.DataTableScan.planFiles(DataTableScan.java:27)

The reason is in [planFiles](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotScan.java#:~:text=ExpressionUtil.toSanitizedString(filter()))), logInfo uses sanitizedString to log the filter. But when user defines the field as string type, Iceberg shouldn't assume it to follow any pattern right? Even if it's an invalid date/month/year, it should still work. And it doesn't feel right to throw in logInfo.

In the latest master both SnapshotScan and BaseAllMetadataTableScan have this check in the log, we can probably change it to use ExpressionParser.ToJson instead.

### PR DESCRIPTION
**Pull request by agnes-xinyi-lu**
Don't throw in sanitizeString because it will fail planFiles when reading with a string filter that matches any of the specific types like Date/Timestamp with parsing failure.
Closes #6911

### CODE REVIEW

**Comment by agnes-xinyi-lu** [comment]
@nastra

**Review by nastra — COMMENTED** [review]
could you also please add some tests to `TestExpressionUtil` for the different types with their invalid string representation?

**Comment by agnes-xinyi-lu** [comment]
> could you also please add some tests to `TestExpressionUtil` for the different types with their invalid string representation?

Done!

File: api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java [hunk 1]
```diff
@@ -596,6 +597,22 @@ public void testSanitizeDateNextWeek() {
...
+  public void testSanitizeStringFallback() {
+    Pattern filterPattern = Pattern.compile("^test = \\(hash-[0-9a-fA-F]{8}\\)$");
+    for (String filter :
+        Lists.newArrayList(
+            "2022-20-29",
+            "2022-04-29T40:49:51.123456",
+            "2022-04-29T23:70:51-07:00",
+            "2022-04-29T23:49:51.123456+100:00")) {
+      String sanitizedFilter = ExpressionUtil.toSanitizedString(Expressions.equal("test", filter));
+      Assert.assertTrue(
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java:610]: rather than using `assertTrue` I think `Assertions.assertThat(filterPattern.matcher(sanitizedFilter)).matches();` would be better, because it will provide additional details when that assertion ever fails: `Expecting java.util.regex.Matcher[pattern=^test = \(hash-[0-9a-fA-F]{8}\)$ region=0,22 lastmatch=] to match.`

Comment (agnes-xinyi-lu) [reply api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java]: I see.

**Review by nastra — APPROVED** [review]
LGTM, thanks for fixing. @Fokko could you please review as well and also trigger CI?

**Review by Fokko — APPROVED** [review]

**Comment by agnes-xinyi-lu** [comment]
Thanks for your code reviews! @Fokko  can you please help merge?

**Comment by Fokko** [comment]
Sure @agnes-xinyi-lu, just wanted to give other a bit of time to also look at this PR.
