### PR TITLE
Core, Spark: Fix equality deletes non-deterministic schema ordering (#13873)

### LINKED ISSUE #13873: Undetermined behavior when fetching from iceberg table
### Apache Iceberg version

1.6.1

### Query engine

Spark

### Please describe the bug 🐞

1. Run `mkdir warehouse/default` to create dir
2. Download attachment for table data
3. Run `tar -xzf iceberg.tar.gz && mv tmp/* /tmp/` to put table data into dir
4. Start spark shell
```
/home/ubuntu/Apps/spark-3.5.4-bin-hadoop3/bin/spark-sql \
    --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.9.2\
    --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkCatalog \
    --conf spark.sql.catalog.spark_catalog.type=hadoop \
    --conf spark.sql.catalog.spark_catalog.warehouse=/tmp/spark-warehouse-28428
```
5. Run count(*) it shows 217 rows.
```
spark-sql (default)> select count(*) from tmp_table_gw0_754291685_0;
217
Time taken: 2.33 seconds, Fetched 1 row(s)
```
6. Run ```select * from tmp_table_gw0_754291685_0``` it reports fetching rows not 750 rows.
```
spark-sql (default)> select * from tmp_table_gw0_754291685_0;
...
Time taken: 0.213 seconds, Fetched 327 row(s)
```

The oddest part is that the difference only happens when *the first time* you run `select *` after `select count(*)`, after that when you run `select *` everything is back to normal.

I tested againts 1.6.1, 1.7.2, and 1.9.2, buth all failed.

[iceberg.tar.gz](https://github.com/user-attachments/files/21909932/iceberg.tar.gz)

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [x] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by RussellSpitzer**
Equality delete schemas constructed in DeleteFilter.applyEqDeletes relied on the field order of requiredSchema, which varies depending on the query's projection. When the SparkExecutorCache returned delete records read with one field ordering to a reader expecting another, StructProjection silently misinterpreted the positional data, causing deletes to be skipped.

We fix this by Canonicalize the deleteSchema by sorting fields by field ID. Now every reader produces the same schema for deletes regardless of projection, ensuring cache hits return correctly ordered records.

Coded with the help of Cursor and claude-4.6.opus-high

--
TLDR;

First call read with schema [a,b] for deletes:
read+project(file, [a,b]) → cache_projected_deletes(file) → applyDeletes with [a,b]

Second call reads with Schema [b, a] for deletes:
load_cache_projected_deletes(file) → applyDeletes with [b,a] → mismatch 

Fixes #13873

### CODE REVIEW

File: data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
Comment (RussellSpitzer) [inline data/src/main/java/org/apache/iceberg/data/DeleteFilter.java:218]: Our problem was here. This may grab a cached equality delete that happened to be read with a slightly different delete schema.

For example if one requiredSchema was [a,b] and the next call was [b, a]
We would read the cached [a,b] with schema [b,a] and break everything.

**Review by mxm — APPROVED** [review]
LGTM. Looks like the cache key is the delete file itself, which makes sense, as long as we use a deterministic approach for the schema projection.

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java [hunk 1]
```diff
@@ -738,6 +741,78 @@ public void testEqualityDeleteWithSchemaEvolution() throws IOException {
...
+        FileHelpers.writeDeleteFile(
+            eqTestTable,
+            Files.localOutput(File.createTempFile("junit", null, temp.toFile())),
+            TestHelpers.Row.of(0),
+            deletes,
+            deleteSchema);
+    eqTestTable.newRowDelta().addDeletes(eqFile).commit();
+
+    String tableRef = TableIdentifier.of("default", EQ_CACHE_TABLE).toString();
+    int expectedRows = 7;
```
Comment (pvary) [inline spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java]: nit: maybe a little bit easier to understand?
```suggestion
    int expectedRows = data.size() - delete.size();
```

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java [hunk 2]
```diff
@@ -738,6 +741,78 @@ public void testEqualityDeleteWithSchemaEvolution() throws IOException {
...
+   * cache.
+   */
+  @TestTemplate
+  public void testEqualityDeletesAppliedWithCachedFieldReordering() throws IOException {
+    Schema eqDeleteTestSchema =
+        new Schema(
+            Types.NestedField.optional(1, "id", Types.IntegerType.get()),
+            Types.NestedField.optional(2, "a", Types.IntegerType.get()),
+            Types.NestedField.optional(3, "b", Types.IntegerType.get()));
+    PartitionSpec spec = PartitionSpec.builderFor(eqDeleteTestSchema).bucket("id", 1).build();
```
Comment (pvary) [inline spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java]: Why do we not use an unpartitioned table here?

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java [hunk 3]
```diff
@@ -738,6 +741,78 @@ public void testEqualityDeleteWithSchemaEvolution() throws IOException {
...
+    // table order [a, b].
+    long wideCount =
+        spark.read().format("iceberg").load(tableRef).select("*").collectAsList().size();
+
+    assertThat(narrowCount)
+        .as("Narrow projection should return %d rows after equality deletes", expectedRows)
+        .isEqualTo(expectedRows);
+    assertThat(wideCount)
+        .as("Wide projection should return the same row count as narrow projection")
+        .isEqualTo(narrowCount);
```
Comment (pvary) [inline spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java]: This is a bit strange to me. Maybe

```suggestion
    assertThat(wideCount)
        .as("Wide projection should return %d rows after equality deletes", expectedRows)
        .isEqualTo(expectedRows);
```

**Review by pvary — APPROVED** [review]
Marked a few places where the code could made cleaner

File: data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
Comment (pvary) [reply data/src/main/java/org/apache/iceberg/data/DeleteFilter.java:218]: Shall we leave a comment here?

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java (hunk 2 above)
Comment (RussellSpitzer) [reply spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java]: No reason, I originally had this in a different file where all the tables were partitioned and I didn't want to feel left out. Now that it's here we can remove it

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java (hunk 3 above)
Comment (RussellSpitzer) [reply spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java]: Yeah I have been debating that since the whole test here is in the context of the bug report. I think you are right that we should rephrase it to match the general test here which is that changing the projection shouldn't effect things. It is a bit hand wavey and I'm wondering if we should have a test that a cached equality delete is always in canonical order as well.

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java [hunk 4]
```diff
@@ -738,6 +741,78 @@ public void testEqualityDeleteWithSchemaEvolution() throws IOException {
...
+            TestHelpers.Row.of(0),
+            deletes,
+            deleteSchema);
+    eqTestTable.newRowDelta().addDeletes(eqFile).commit();
+
+    String tableRef = TableIdentifier.of("default", EQ_CACHE_TABLE).toString();
+    int expectedRows = 7;
+
+    // Narrow projection: Spark will not request a or b columns, so the delete columns are appended
+    // in metadata order [b, a]
```
Comment (stevenzwu) [inline spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java]: nit: maybe more specific as `identifier fields definition order`?

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java [hunk 5]
```diff
@@ -738,6 +741,78 @@ public void testEqualityDeleteWithSchemaEvolution() throws IOException {
...
+    long narrowCount =
+        spark.read().format("iceberg").load(tableRef).select("id").collectAsList().size();
+
+    // Wide projection: Spark will request all columns, so the delete columns are already present in
+    // table order [a, b].
```
Comment (stevenzwu) [inline spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java]: nit: maybe more specific `table schema order`?

**Review by stevenzwu — APPROVED** [review]
LGTM. thanks for adding the unit test. just a couple of nit comments

File: data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
Comment (RussellSpitzer) [reply data/src/main/java/org/apache/iceberg/data/DeleteFilter.java:218]: Left a comment above the sort

**Review by huaxingao — APPROVED** [review]

File: data/src/main/java/org/apache/iceberg/data/DeleteFilter.java [hunk 6]
```diff
@@ -210,7 +211,12 @@ private List<Predicate<T>> applyEqDeletes() {
       Set<Integer> ids = entry.getKey();
       Iterable<DeleteFile> deletes = entry.getValue();
 
-      Schema deleteSchema = TypeUtil.select(requiredSchema, ids);
+      // Canonicalize the delete schema by sorting fields by ID so that the same set of equality
+      // field IDs always produces the same schema, regardless of requiredSchema column ordering.
+      Schema selectedSchema = TypeUtil.select(requiredSchema, ids);
+      List<Types.NestedField> sortedFields = Lists.newArrayList(selectedSchema.columns());
+      sortedFields.sort(Comparator.comparingInt(Types.NestedField::fieldId));
+      Schema deleteSchema = new Schema(sortedFields);
```
Comment (rdblue) [inline data/src/main/java/org/apache/iceberg/data/DeleteFilter.java]: Minor: It doesn't seem like this logic needs to be here. It's basically saying that we want `select` to produce a schema that matches the order of `ids` rather than the order of the schema we are projecting. I think that sounds more like a `TypeUtil` helper than just embedding code here.

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java [hunk 7]
```diff
@@ -738,6 +741,75 @@ public void testEqualityDeleteWithSchemaEvolution() throws IOException {
     assertThat(actual).hasSize(expectedRecordCount);
   }
 
+  /**
+   * Covers a bug where equality deletes columns are appended to the required schema in a different
+   * order than the table schema, which can cause different deleteSchema orderings, poisoning the
+   * cache.
+   */
+  @TestTemplate
```
Comment (rdblue) [inline spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java:749]: The actual test makes sense, but I don't see why it is necessary to run this test of a core feature (`DeleteFilter`) in Spark. This should be done in the tests for that class.

**Comment by rdblue** [comment]
@amogh-jahagirdar FYI. Here's another one for the next 1.10.x release.

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java (hunk 7 above)
Comment (RussellSpitzer) [reply spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java:749]: Main reason is I couldn't find a place to fit it in any of those places. I did try but it basically involved writing a custom test cache implementation as well. So while it's possible it basically involves re-implementing everything to get the same behavior. We could add a unit test for sorting though, that's pretty easy

File: data/src/main/java/org/apache/iceberg/data/DeleteFilter.java (hunk 6 above)
Comment (RussellSpitzer) [reply data/src/main/java/org/apache/iceberg/data/DeleteFilter.java]: Added a TypeUtil.selectSorted

Comment (amogh-jahagirdar) [reply data/src/main/java/org/apache/iceberg/data/DeleteFilter.java]: +1 I think I'd just expect a `selectInIDOrder` API to abstract this?

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java (hunk 7 above)
Comment (amogh-jahagirdar) [reply spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java:749]: Yeah it looks like we currently don't have a great place for testing out just the logic within `DeleteFilter`. I think in the current structure, we'd have to have our own implementation of `DeleteFilter` for the test and as @RussellSpitzer said by the time we do all that it's basically just re-implementing what we have in the engine integrations like Spark. I think I agree with the current split of tests, but maybe the fact that we want to test DeleteFilter in isolation means we need to do some refactoring.

File: api/src/main/java/org/apache/iceberg/types/TypeUtil.java [hunk 8]
```diff
@@ -102,6 +103,19 @@ public static Schema select(Schema schema, Set<Integer> fieldIds) {
     return new Schema(ImmutableList.of(), schema.getAliases());
   }
 
+  /**
+   * Selects fields from a schema by ID and returns them ordered by field ID.
+   *
+   * <p>Unlike {@link #select(Schema, Set)}, which preserves the field ordering of the input schema,
+   * this method always returns columns sorted by field ID.
+   */
+  public static Schema selectOrdered(Schema schema, Set<Integer> fieldIds) {
```
Comment (amogh-jahagirdar) [inline api/src/main/java/org/apache/iceberg/types/TypeUtil.java]: Minor: selectInIdOrder?

**Review by amogh-jahagirdar — APPROVED** [review]
This looks right to me, thank you @RussellSpitzer !

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java (hunk 7 above)
Comment (RussellSpitzer) [reply spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java:749]: https://gist.github.com/sfc-gh-rspitzer/e53841222262010847a68aa2ed59dd39 < Here is what Claude thinks that should look like. I haven't really gone through it in depth I just figured if I was writing an implementation of DeleteFilter and DeleteLoader we are going way off track.

Basically we mock just about everything around the load, just to test that the schema is always canonicalized.

**Comment by RussellSpitzer** [comment]
@rdblue Any final thoughts? Are you onboard with the test even though I agree it is quite suboptimal. We may just want to raise another issue to refactor this whole bit of code into something more testable ...

File: api/src/main/java/org/apache/iceberg/types/TypeUtil.java (hunk 8 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/types/TypeUtil.java]: I think the requirement here is that it is ordered consistently, not that it is a particular order.

File: spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java (hunk 7 above)
Comment (rdblue) [reply spark/v4.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java:749]: I didn't realize that the caching part was tied to Spark. This should be okay.

**Review by rdblue — APPROVED** [review]

**Comment by amogh-jahagirdar** [comment]
I'll go ahead and merge, thanks @RussellSpitzer and all for reviewing!
