### PR TITLE
Core: DeleteWithFilter fails on HashCode Collision

### LINKED ISSUE #6670: Random no-op for delete for sequence of similar numeric partition values
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

This is a serious random bug I debugged together with @dramaticlly, it will make metadata deletes silently fail in real environments.

**Setup**

We have a table that is partitioned by two date integers, a and b.  They are both in same format yyyymmdd, and refer to relatively current dates, so the values are not very far from each other.

We find that sometimes doing a `delete from table where date <= a` fails silently to delete files of partition a.

**Problem**

The problem is computing the Iceberg residual, which is the remaining data-filter that is pushed down to the files, after the partition filter has been evaluated.  ManifestFilterManager has a residual cache by partition, which we use to find the residual  for each file under consideration of being deleted.  All files of a partition should use the same residual.  Ref:  https://github.com/apache/iceberg/blob/1.0.x/core/src/main/java/org/apache/iceberg/ManifestFilterManager.java#L511  

But in this case, a hashcode collission causes a file of partition b having residual of AlwaysFalse() for query ```date <= a``` be used when a file of partition a is being evaluated (it should have evaluated to AlwaysTrue() for query ```date <= a```.  Hence the later code skips evaluation of the file and does not proceed to delete it.

**Analysis**

We saw that partition with different but similar range a, b values in this use-case often collide in the hashcode.  We saw it multiple times and were able to come up with an example:

a = 20220728, b = 20220719
a = 20220726, b = 20220801

The problem is the StructWrapper's hash (which is the JavaHash:  Ref:  https://github.com/apache/iceberg/blob/1.0.x/api/src/main/java/org/apache/iceberg/types/JavaHashes.java#L83

It makes a random base depending on len of the struct, but in this case these partition type all have the same len, so there's effectively no randomization.  The only randomization then is, per value, multiplying result by 41 and then adding the next value, ie,

```
result = 41 * result + hash(a)
result = 41 * result + hash(b)
```

but in this case Java int hash of an integer is just itself and so because: 
``` 41*(20220728) + 41*(20220719) = 41*(20220726) + 41*(20220801) ```
we the hash collission.

### PR DESCRIPTION
**Pull request by RussellSpitzer**
Fixes #6670 

When we determine the ResidualEvaluators for manifest entries in file we use a computeIfAbsent method using the file object's PartitionData as a key. The underlying issue here is that when being read using ManifestReader the PartitionData object is reused. This means once placed within the Map the value of the PartitionData changes every time a new entry is read. Because the original hashcode is correct, this isn't a problem until two values collide. Once they do the second key will end up retrieving the value of the first key, the underlying key retrieved will then also be equal because of the ManifestReader Container re-use. If the First Key was "always true" but the second key should be "false" the second key will return true and delete a file it should not.

To fix this we only place a copy of the PartitionData inside the map instead of the PartitionData object itself. We can't use computeIfAbsent unless we want to make a brand new PartitionData object for every entry.

To note the reason this has not been hit frequently before is that we must hit all of following conditions

* There needs to be a conflict of structlikewrapper.wrap(PartitionData) hashcodes
* The two files with the conflicting partition hashcodes MUST be in the same manifest
* They must have different behaviors for the delete condition (eg if both collision values should be delete or not deleted then it isn't a problem)

### CODE REVIEW

**Comment by RussellSpitzer** [comment]
@aokolnychyi + @dramaticlly @szehon-ho

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java [hunk 1]
```diff
@@ -349,6 +352,54 @@ public void testDeleteFilesOnIndependentBranches() {
...
+        "We should have two files",
+        2,
+        Lists.newArrayList(collisionTable.newScan().planFiles().iterator()).size());
+
+    collisionTable.newDelete().deleteFromRowFilter(Expressions.equal("x", "BB")).commit();
+
+    Assert.assertEquals(
+        "We should have deleted one of them",
+        1,
+        Lists.newArrayList(collisionTable.newScan().planFiles().iterator()).size());
```
Comment (dramaticlly) [inline core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:400]: nit: might be a bit redundant, but I am curious if we shall verify the remaining files is correct and we deleted the desired partition instead?

I am thinking about maybe something like 
```java
Assert.assertEquals(
  partitionOne,
  collisionTable.newScan().planFiles().iterator().next().file().partition());
```

**Review by dramaticlly — APPROVED** [review]
Thank you so much @RussellSpitzer for your insight and the fix. So we initially have 2 partitions shall be deleted but ends up running into this bug. We deleted one during our debug session when trying things out and I can confirm that I am able to apply this fix to delete the remaining offending partition. 🥇

File: core/src/main/java/org/apache/iceberg/ManifestFilterManager.java [hunk 2]
```diff
@@ -510,16 +510,19 @@ private Pair<InclusiveMetricsEvaluator, StrictMetricsEvaluator> metricsEvaluator
...
-          partition -> {
-            Expression residual = residualEvaluator.residualFor(partition);
-            InclusiveMetricsEvaluator inclusive =
-                new InclusiveMetricsEvaluator(tableSchema, residual, caseSensitive);
-            StrictMetricsEvaluator strict =
-                new StrictMetricsEvaluator(tableSchema, residual, caseSensitive);
-            return Pair.of(inclusive, strict);
-          });
+      PartitionData partition = (PartitionData) file.partition();
+      if (!metricsEvaluators.containsKey(partition)) {
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:514]: Will the fix still work if we just keep computeIfAbsent, but pass file.partition().copy()?

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java [hunk 3]
```diff
@@ -349,6 +352,54 @@ public void testDeleteFilesOnIndependentBranches() {
...
+        StructLikeWrapper.forType(spec.partitionType()).set(partitionTwo).hashCode());
+
+    Metrics metrics = new Metrics(1L, null, null, null, null);
+
+    DataFile testFileOne =
+        DataFiles.builder(spec)
+            .withPartition(partitionOne)
+            .withPath("/g1.parquet")
+            .withFileSizeInBytes(100)
+            .withMetrics(metrics)
```
Comment (szehon-ho) [inline core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:378]: Is metrics strictly required here?

**Review by szehon-ho — COMMENTED** [review]
Thanks for the fix and repro !  Small comments

Just thinking out loud, would may be safer in general to expose the reuseContainers() configuration and turn off in ManifestFilterManager, in case other maps out there, but not sure if its worth it.

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java (hunk 1 above)
Comment (RussellSpitzer) [reply core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:400]: Sure, that's a great idea.

File: core/src/main/java/org/apache/iceberg/ManifestFilterManager.java (hunk 2 above)
Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:514]: Yes but then we make a copy of every single partition object, so we basically lose all benefit from reuse containers

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java (hunk 3 above)
Comment (RussellSpitzer) [reply core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:378]: Yep (just row count really) but it's required by DeleteFileBuilder

File: core/src/main/java/org/apache/iceberg/ManifestFilterManager.java (hunk 2 above)
Comment (szehon-ho) [reply core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:514]: OK makes sense

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java (hunk 3 above)
Comment (szehon-ho) [reply core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:378]: Can we remove metrics variable to simplify the test?  

I see other DataFiles being built in TableTestBase without it.

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java [hunk 4]
```diff
@@ -349,6 +355,56 @@ public void testDeleteFilesOnIndependentBranches() {
...
+    Assert.assertEquals(
+        "We should have two files",
+        2,
+        Lists.newArrayList(collisionTable.newScan().planFiles().iterator()).size());
+
+    collisionTable.newDelete().deleteFromRowFilter(Expressions.equal("x", "BB")).commit();
+
+    List<StructLike> partitions =
+        Lists.newArrayList(collisionTable.newScan().planFiles().iterator()).stream()
+            .map(s -> ((PartitionData) s.partition()).copy())
```
Comment (RussellSpitzer) [inline core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:401]: Not that it matters here but let's be a good example

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java [hunk 5]
```diff
@@ -349,6 +355,56 @@ public void testDeleteFilesOnIndependentBranches() {
...
+            .collect(Collectors.toList());
+
+    Assert.assertEquals(
+        "We should have deleted partitionTwo of them", ImmutableList.of(partitionOne), partitions);
```
Comment (szehon-ho) [inline core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:405]: Run on here?

**Review by abmo-x — APPROVED** [review]

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java [hunk 6]
```diff
@@ -349,6 +355,56 @@ public void testDeleteFilesOnIndependentBranches() {
...
+            .withFileSizeInBytes(100)
+            .withPath("/g2.parquet")
+            .build();
+
+    collisionTable.newFastAppend().appendFile(testFileOne).appendFile(testFileTwo).commit();
+
+    Assert.assertEquals(
+        "We should have two files",
+        2,
+        Lists.newArrayList(collisionTable.newScan().planFiles().iterator()).size());
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/iceberg/TestDeleteFiles.java:395]: nit: maybe assert on two partitions here? correspond to the assertion after deletion that there is only one partition.

**Review by stevenzwu — APPROVED** [review]

File: core/src/main/java/org/apache/iceberg/ManifestFilterManager.java [hunk 7]
```diff
@@ -510,16 +510,19 @@ private Pair<InclusiveMetricsEvaluator, StrictMetricsEvaluator> metricsEvaluator
...
-          file.partition(),
-          partition -> {
-            Expression residual = residualEvaluator.residualFor(partition);
-            InclusiveMetricsEvaluator inclusive =
-                new InclusiveMetricsEvaluator(tableSchema, residual, caseSensitive);
-            StrictMetricsEvaluator strict =
-                new StrictMetricsEvaluator(tableSchema, residual, caseSensitive);
-            return Pair.of(inclusive, strict);
-          });
+      PartitionData partition = (PartitionData) file.partition();
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:513]: Should we use `StructLikeMap` here instead of relying on `PartitionData` in a regular map? We could use a pattern like in `FanoutWriter` to keep these by partition spec ID.

**Review by rdblue — APPROVED** [review]
Looks correct to me, though we may want to move to `StructLikeMap` that was introduced later.

File: core/src/main/java/org/apache/iceberg/ManifestFilterManager.java (hunk 7 above)
Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:513]: It is a StructLikeMap, this actually causes the collisions to happen more frequently because of the structlikewrapper hashcode function

**Comment by RussellSpitzer** [comment]
> Looks correct to me, though we may want to move to `StructLikeMap` that was introduced later.

`metricsEvaluators` is a struct like map which when putting copies the Wrapper but not the internal struct data. Since the underlying object reference is not copied we have the same issue. 

https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/StructLikeMap.java#L86

and then

https://github.com/apache/iceberg/blob/a76724f7ae7ff3722fea3e1145aa0a978c721b45/core/src/main/java/org/apache/iceberg/util/StructLikeWrapper.java#L59 

Since the "set" method just assigns `this.struct = newStruct` we have this issue.

File: core/src/test/java/org/apache/iceberg/TestDeleteFiles.java (hunk 6 above)
Comment (RussellSpitzer) [reply core/src/test/java/org/apache/iceberg/TestDeleteFiles.java]: Changed this to explicitly check for partitionOne and Two

File: core/src/main/java/org/apache/iceberg/ManifestFilterManager.java (hunk 7 above)
Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:513]: Checking fanout writer, it actually does the same pattern I implemented here, but uses StructCopy.copy instead of the PartitionData.copy method. That may be a safer thing to do since technically we are not guaranteed the PartitionData type.

Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:513]: Using StructCopy is actually going to be a bit of a bigger change if we want to keep the interface package private since we need to move it into the `org.apache.iceberg` package.

Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:513]: Ok I found a bug in StructCopy as well, it doesn't copy FixedByte types and just copies array values so we actually probably need to file a issue for that.

It should be doing this

From PartitionData.copyData
```java
          case FIXED:
            byte[] buffer = (byte[]) data[i];
            copy[i] = Arrays.copyOf(buffer, buffer.length);
            break;
 ```

but instead the StructCopy code always does this
```java
      if (value instanceof StructLike) {
        values[i] = copy((StructLike) value);
      } else {
        values[i] = value;
      }
```

Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/ManifestFilterManager.java:513]: Filed #6685 to track StructCopy bug

**Review by amogh-jahagirdar — APPROVED** [review]
Thanks for the detailed explanation, this fix makes sense to me, thanks @RussellSpitzer ! kudos to others involved in the debugging process, @szehon-ho @dramaticlly this seemed like it would be a tricky issue to debug :)

**Comment by RussellSpitzer** [comment]
Merged! Thanks @amogh-jahagirdar , @rdblue , @stevenzwu , @abmo-x , @szehon-ho, @dramaticlly .

I would also again like to greatly credit Steven and Szehon for their hard work in debugging this issue. Once more, I would like to say Szehon you were right, it was a hashcode collision issue :)
