### PR TITLE
Core: Fix lock acquisition logic in HadoopTableOperations rename

### LINKED ISSUE #9485: [HadoopCatalog]: [HadoopTableOperations]: Commit flow, renameToFinal does not actually check if lock acquired
### Apache Iceberg version

1.4.2 (latest release)

### Query engine

None

### Please describe the bug 🐞

The last part of the commit flow, requires writing the new metadata version file which uses the renameToFinal method.
In this method there's a use of the lock manager to ensure no 2 committers write the same metadata version file.
However, when trying to acquire lock, there's no check if the lock was actually acquired:
```Java
    private void renameToFinal(FileSystem fs, Path src, Path dst, int nextVersion) {
        try {
            this.lockManager.acquire(dst.toString(), src.toString());
            if (fs.exists(dst)) {
                throw new CommitFailedException("Version %d already exists: %s", new Object[]{nextVersion, dst});
            }
            ...
```

In the LockManager interface, acquire documentation states:
```
Try to acquire a lock
Params: entityId – ID of the entity to lock 
              ownerId – ID of the owner if the lock
Returns:
if the lock for the entity is acquired by the owner
```

I'm fairly new to the Iceberg ecosystem, so if I'm misunderstanding something in the code I would greatly appreciate an explanation.

### PR DESCRIPTION
**Pull request by N-o-Z**
Closes #9485

### CODE REVIEW

**Comment by N-o-Z** [comment]
@amogh-jahagirdar, FYI

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java [hunk 1]
```diff
@@ -360,7 +360,10 @@ int findVersion() {
    */
   private void renameToFinal(FileSystem fs, Path src, Path dst, int nextVersion) {
     try {
-      lockManager.acquire(dst.toString(), src.toString());
+      boolean success = lockManager.acquire(dst.toString(), src.toString());
+      if (!success) {
+        throw new CommitFailedException("Failed to acquire lock on file: %s", dst);
+      }
```
Comment (amogh-jahagirdar) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java:366]: Style nit, if we could add a new line after this `if` block separating it from the next `if`! I know in this file it looks like we didn't really follow our normal practice already but at least for new changes we could follow it.

Also I think I'd just inline the boolean so

```
if (!lockManager.acquire(dst.toString(), src.toStrnig()) {
 throw ...
}
```

File: core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java [hunk 2]
```diff
@@ -451,4 +455,39 @@ public void testConcurrentFastAppends(@TempDir File dir) throws Exception {
...
         .hasSize(threadsCount * numberOfCommitedFilesPerThread);
   }
-}
+
+  @Test
+  public void testCommitFailedToAcquire() {
+    table.newFastAppend().appendFile(FILE_A).commit();
+    Configuration conf = new Configuration();
+    LockManager lockManager = new NoLockManager();
+    HadoopTableOperations tops =
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java:464]: Naming nit: I think it's better to be a bit more verbose rather than truncate, since it's more readable imo. Instead of `tops` could we call it `tableOperations` like we do in other places? Also maybe `testCommitFailedToAcquireLock` for the test name?

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java (hunk 1 above)
Comment (amogh-jahagirdar) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java:366]: Also should we include the owner (src) in the exception as well?

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java [hunk 3]
```diff
@@ -383,7 +386,10 @@ private void renameToFinal(FileSystem fs, Path src, Path dst, int nextVersion) {
       }
       throw cfe;
     } finally {
-      lockManager.release(dst.toString(), src.toString());
+      boolean success = lockManager.release(dst.toString(), src.toString());
+      if (!success) {
+        LOG.warn("Failed to release lock on file: {} with owner: {}", dst, src);
+      }
```
Comment (amogh-jahagirdar) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java:392]: Same nit as above, I think we should just inline the boolean.

**Review by amogh-jahagirdar — COMMENTED** [review]
Thanks @N-o-Z , this looks great just some nits!

**Comment by amogh-jahagirdar** [comment]
looks like spotless checks are failing:

if you could run

```
./gradlew spotlessApply
```

before pushing your next changes that would fix it!

**Comment by N-o-Z** [comment]
@amogh-jahagirdar  Done!
