### PR TITLE
API, AWS: Retry S3InputStream reads

### LINKED ISSUE #10340: javax.net.ssl.SSLException: Connection reset on S3 w/ S3FileIO and Apache HTTP client
### Apache Iceberg version

1.3.1

### Query engine

Spark

### Please describe the bug 🐞

```
24/05/15 15:10:31 ERROR [Executor task launch worker for task 34.0 in stage 14.0 (TID 406)] source.BaseReader: Error reading file(s): s3://bucket/.../file.parquete
org.apache.iceberg.exceptions.RuntimeIOException: javax.net.ssl.SSLException: Connection reset
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.advance(ParquetReader.java:153)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.next(ParquetReader.java:130)
	at org.apache.iceberg.io.FilterIterator.advance(FilterIterator.java:65)
	at org.apache.iceberg.io.FilterIterator.hasNext(FilterIterator.java:49)
	at org.apache.iceberg.spark.source.BaseReader.next(BaseReader.java:129)
	at org.apache.spark.sql.execution.datasources.v2.PartitionIterator.hasNext(DataSourceRDD.scala:119)
	at org.apache.spark.sql.execution.datasources.v2.MetricsIterator.hasNext(DataSourceRDD.scala:156)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.$anonfun$hasNext$1(DataSourceRDD.scala:63)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.$anonfun$hasNext$1$adapted(DataSourceRDD.scala:63)
	at scala.Option.exists(Option.scala:376)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:63)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage4.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:412)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1504)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:457)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:358)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1470)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.net.ssl.SSLException: Connection reset
	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1400)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1368)
	at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:962)
	at software.amazon.awssdk.thirdparty.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at software.amazon.awssdk.thirdparty.org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
	at software.amazon.awssdk.thirdparty.org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at software.amazon.awssdk.thirdparty.org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at software.amazon.awssdk.services.s3.checksums.ChecksumValidatingInputStream.read(ChecksumValidatingInputStream.java:112)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at software.amazon.awssdk.core.io.SdkFilterInputStream.read(SdkFilterInputStream.java:66)
	at org.apache.iceberg.aws.s3.S3InputStream.read(S3InputStream.java:109)
	at org.apache.iceberg.shaded.org.apache.parquet.io.DelegatingSeekableInputStream.readFully(DelegatingSeekableInputStream.java:102)
	at org.apache.iceberg.shaded.org.apache.parquet.io.DelegatingSeekableInputStream.readFullyHeapBuffer(DelegatingSeekableInputStream.java:127)
	at org.apache.iceberg.shaded.org.apache.parquet.io.DelegatingSeekableInputStream.readFully(DelegatingSeekableInputStream.java:91)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader$ConsecutivePartList.readAll(ParquetFileReader.java:1850)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader.internalReadRowGroup(ParquetFileReader.java:990)
	at org.apache.iceberg.shaded.org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:940)
	at org.apache.iceberg.parquet.ParquetReader$FileIterator.advance(ParquetReader.java:151)
	... 27 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:355)
		... 50 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)
	at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:237)
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
	... 47 more
```

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
Fixes #10340 

This is an alternative approach to https://github.com/apache/iceberg/pull/4912/files and https://github.com/apache/iceberg/pull/8221/files#diff-0b632866a3b10fac55c442b08178ec0ac72b3b600878243e15d788a8bd031054

for retrying failures encountered when retrying on the reading of input streams.

This approach defines a `RetryableInputStream` class which will wrap underlying input streams returned by object store APIs.
Upon failures a new stream will be created. Custom exceptions can be passed in, but the default retries are on SocketTimeoutException and SSLException. This change integrates this input stream implementation with S3InputStream, but RetryableINputStream should be able to be used for the other input streams implementations that are provided by Iceberg.

This change relies on the [Failsafe dependency](https://failsafe.dev/).

### CODE REVIEW

File: aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java [hunk 1]
```diff
@@ -0,0 +1,227 @@
...
+public class TestFuzzyS3InputStream extends TestS3InputStream {
+
+  private static final int DATA_SIZE = 3 * 1024 * 1024;
+
+  @ParameterizedTest
+  @MethodSource("retryableExceptions")
+  public void testReadWithFuzzyStreamRetrySucceed(IOException exception) throws Exception {
+    testRead(
+        fuzzyStreamClient(new AtomicInteger(3), exception), new S3FileIOProperties(), DATA_SIZE);
+  }
```
Comment (amogh-jahagirdar) [inline aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java:60]: This test takes way too long. That's primarily because it internally tests retrying on just read() which means every byte read will fail and be retried 2 times with a 500 ms in between. So essentially that's a second per byte.

I think what we can do is modularize further and only do buffered read tests + with a much smaller data size test the per byte read.

File: aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+import software.amazon.awssdk.services.s3.model.CreateBucketRequest;
+import software.amazon.awssdk.services.s3.model.CreateBucketResponse;
+import software.amazon.awssdk.services.s3.model.GetObjectRequest;
+import software.amazon.awssdk.services.s3.model.GetObjectResponse;
+import software.amazon.awssdk.services.s3.model.HeadObjectRequest;
+import software.amazon.awssdk.services.s3.model.HeadObjectResponse;
+import software.amazon.awssdk.services.s3.model.PutObjectRequest;
+import software.amazon.awssdk.services.s3.model.PutObjectResponse;
+
+public class TestFuzzyS3InputStream extends TestS3InputStream {
```
Comment (amogh-jahagirdar) [inline aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java:51]: I copied a lot of the test logic from https://github.com/apache/iceberg/pull/4912/files, will mark @jackye1995 as coauthor

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java [hunk 3]
```diff
@@ -139,7 +140,11 @@ private InputStream readRange(String range) {
 
     S3RequestUtil.configureEncryption(s3FileIOProperties, requestBuilder);
 
-    return s3.getObject(requestBuilder.build(), ResponseTransformer.toInputStream());
+    stream =
+        RetryableInputStream.builderFor(
+                () -> s3.getObject(requestBuilder.build(), ResponseTransformer.toInputStream()))
```
Comment (amogh-jahagirdar) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:145]: any failures that occur on the retry during the getObject request (not the stream read) should just be handled by the SDK. Don't think we need to add anything custom for that since the S3 client is already pluggable.

File: gradle/libs.versions.toml [hunk 4]
```diff
@@ -95,7 +96,7 @@ antlr-antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr" }
 antlr-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
 arrow-memory-netty = { module = "org.apache.arrow:arrow-memory-netty", version.ref = "arrow" }
 arrow-vector = { module = "org.apache.arrow:arrow-vector", version.ref = "arrow" }
-avro-avro = { module = "org.apache.avro:avro", version.ref = "avro" }
+avro-avro = { module = "org.apache.avro:avro", version.ref = "avro"}
```
Comment (amogh-jahagirdar) [inline gradle/libs.versions.toml:99]: Shouldn't have changed, I'll undo this

File: gradle/libs.versions.toml [hunk 5]
```diff
@@ -37,6 +37,7 @@ delta-standalone = "3.1.0"
 delta-spark = "3.2.0"
 esotericsoftware-kryo = "4.0.3"
 errorprone-annotations = "2.27.0"
+failsafe = "3.3.2"
```
Comment (amogh-jahagirdar) [inline gradle/libs.versions.toml:40]: This dependency is quite nice in that it's 0 dependency itself, has Apache licensing and I think there's more use cases in Iceberg to leverage it. For example, I think a lot of the complex logic in Tasks can be simplified.

Furthermore, there's some custom retry logic in JDBC connector which we couldn't use tasks for, but now we could use Failsafe. Wonder what others think

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java (hunk 3 above)
Comment (danielcweeks) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:145]: I feel like there's an issue here.  When the stream gets recreated, the stream will reset back to the original position and we continue from there as if we're at the right place in the stream.

The `pos` won't reflect the new position of the stream, if I'm reading this correctly.  I would think the following retry would need to start from `next` to reflect where the next read should start.  There's a small problem with the single byte read method because we increment the positions prior to read, so that would likely need to be adjusted to be after the read like in the range read method.

File: api/src/main/java/org/apache/iceberg/io/RetryableInputStream.java [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+  public static RetryableInputStream.Builder builderFor(Supplier<InputStream> newStreamSupplier) {
+    return new Builder(newStreamSupplier);
+  }
+
+  public static class Builder {
+
+    private InputStream underlyingStream;
+    private final Supplier<InputStream> newStreamProvider;
+    private List<Class<? extends Exception>> retryableExceptions =
+        ImmutableList.of(SSLException.class, SocketTimeoutException.class);
```
Comment (singhpk234) [inline api/src/main/java/org/apache/iceberg/io/RetryableInputStream.java:72]: [QQ] 
- Should we retry this 5xx errors like 503 ?
- will it make sense to make this configurable by any chance ? 
- Also any thoughts about outputstream ?

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java (hunk 3 above)
Comment (amogh-jahagirdar) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:145]: I'll double check this, I think you're right although I'm not sure why the first test case wouldn't surface that (since the content would be different). We may need to seek properly on the input stream initialization during retry.

File: api/src/main/java/org/apache/iceberg/io/RetryableInputStream.java (hunk 6 above)
Comment (danielcweeks) [reply api/src/main/java/org/apache/iceberg/io/RetryableInputStream.java:72]: @singhpk234 I believe the SDK already handles 503 errors and other errors that happen during the initiation of the request.  I believe output stream is different (I don't think we've heard of issues on that side), but I would handle that in a separate PR if necessary.

Comment (singhpk234) [reply api/src/main/java/org/apache/iceberg/io/RetryableInputStream.java:72]: > I believe the SDK already handles 503 errors and other errors that happen during the initiation of the request

yup, they do, but we have defaults of SDK at the moment right ? wondering if we should either expose conf's to overwrite it or control it via here. 

Also was wondering if we can go as exhaustive a retry policy and have it at one place, as this : https://github.com/apache/hadoop/blob/b108e9e2d814cc009c4b663799e056a65bf24766/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ARetryPolicy.java#L193

In past we have been reached for tickets like this : https://github.com/apache/iceberg/issues/9124#issuecomment-1821822583


>  I believe output stream is different (I don't think we've heard of issues on that side), but I would handle that in a separate PR if necessary

+1

**Comment by SandeepSinghGahir** [comment]
When will this merged? I'm getting this issue while reading iceberg tables in glue.

**Review by amogh-jahagirdar — COMMENTED** [review]
>When will this merged? I'm getting this issue while reading iceberg tables in glue.

Sorry about that @SandeepSinghGahir , I drafted this PR and never followed through. I just took a pass and determined next steps so that we can take this to completion since I know a few folks are hitting this issue and I think it's reasonable that Iceberg S3 input stream has some level of retries when reading from the stream. 

I'll also mention, it's really important for changes like this which are on the critical path that they are well tested so I'm also thinking through the test cases as well.

File: aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java (hunk 2 above)
Comment (amogh-jahagirdar) [reply aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java:50]: I saw @xiaoxuandev also had the same tests in https://github.com/apache/iceberg/pull/8221 so I'm marking her as co-author here as well

File: aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java [hunk 7]
```diff
@@ -0,0 +1,224 @@
...
+    public void close() {
+      delegate.close();
+    }
+
+    @Override
+    public <ReturnT> ReturnT getObject(
+        GetObjectRequest getObjectRequest,
+        ResponseTransformer<GetObjectResponse, ReturnT> responseTransformer)
+        throws AwsServiceException, SdkClientException {
+      return delegate.getObject(getObjectRequest, responseTransformer);
```
Comment (amogh-jahagirdar) [inline aws/src/test/java/org/apache/iceberg/aws/s3/TestFuzzyS3InputStream.java:130]: I was going to track the start ranges that were requested on each getObject and assert that the positions being retried are as expected but this ends up really complicating the tests for what I think is not too much additional value because actually the `testRead` we are inheriting verifies the contents actually being read in each `readAndCheck`. If there's a retry that's being performed to an incorrect position, this would mean that the contents would be incorrect and tests would fail and we know that the retry path is being exercised given the presence of the fuzzy stream client.

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java (hunk 3 above)
Comment (amogh-jahagirdar) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:145]: I updated this, the RetryableInputStream offers two builder APIs, one for specifying just a new stream initialization and one for a stream initialization plus a position supplier. The stream initialization function takes in a position (the position can be null to handle the range based requests since for range reads with explicit begin/end we don't care about the current position in the stream). cc @danielcweeks

File: gradle/libs.versions.toml (hunk 5 above)
Comment (nastra) [reply gradle/libs.versions.toml:41]: I like this a lot

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java [hunk 8]
```diff
@@ -92,13 +93,13 @@ public void seek(long newPos) {
   public int read() throws IOException {
     Preconditions.checkState(!closed, "Cannot read: already closed");
     positionStream();
-
+    int bytesRead = stream.read();
```
Comment (nastra) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:96]: I'm guessing this is just aligning things with the other `read` method and isn't a strictly necessary change?

**Comment by edgarRd** [comment]
@amogh-jahagirdar Any reason why not handling retries in `S3OutputStream` as well? We've internally seen issues with `UncheckedIOExceptions` during `putObject` for manifest objects. I believe https://github.com/apache/iceberg/pull/8221 aimed at addressing both input and output streams.

**Comment by jackye1995** [comment]
The S3 team (@ookumuso) just published what they have developed internally and is now used in Amazon EMR, Athena, GlueETL distributions: #11052, is there a way we can see how we could collaborate on this?

**Comment by jackye1995** [comment]
> I believe https://github.com/apache/iceberg/pull/8221 aimed at addressing both input and output streams. Is there an existing PR for output stream retries?

@edgarRd based on our later evaluation, the AWS SDK will handle all output stream retries, so I think input stream retry is sufficient.

**Comment by amogh-jahagirdar** [comment]
> The S3 team (@ookumuso) just published what they have developed internally and is now used in Amazon EMR, Athena, GlueETL distributions of Iceberg: #11052, is there a way we can see how we could collaborate on this?

Sorry for the late reply, Absolutely @jackye1995 ! So it seems like the overlap between this and #11052 is primarily the retrying of the reading of the input stream. #11052 also includes some configurable properties and different configurations for the S3Client.

For the retrying of the input stream, I think the key thing I was trying to achieve was adding the RetryableInputStream primitive so that other FileIOs like GCS/Azure can also use that. How do we feel about that @jackye1995 @ookumuso ? And then the other PR we can talk about the configuration/default updates?

**Comment by amogh-jahagirdar** [comment]
> > I believe #8221 aimed at addressing both input and output streams. Is there an existing PR for output stream retries?
> 
> @edgarRd based on our later evaluation, the AWS SDK will handle all output stream retries, so I think input stream retry is sufficient.

This is interesting. Didn't know that the AWS SDK already handles the outputstream retries, if that's the case then I think that's even more of a case not to introduce an additional retry logic.

**Comment by ookumuso** [comment]
> > The S3 team (@ookumuso) just published what they have developed internally and is now used in Amazon EMR, Athena, GlueETL distributions of Iceberg: #11052, is there a way we can see how we could collaborate on this?
> 
> Sorry for the late reply, Absolutely @jackye1995 ! So it seems like the overlap between this and #11052 is primarily the retrying of the reading of the input stream. #11052 also includes some configurable properties and different configurations for the S3Client.
> 
> For the retrying of the input stream, I think the key thing I was trying to achieve was adding the RetryableInputStream primitive so that other FileIOs like GCS/Azure can also use that. How do we feel about that @jackye1995 @ookumuso ? And then the other PR we can talk about the configuration/default updates?

No worries and thanks for following up! I am okay with using the RetryableInputStream as long as we can we can close this out soonish since there seems to be a lot of people hitting the same issue. Have 2 options here:

- I can exclude the InputStream changes entirely from my PR and just keep the s3-retry config changes. Might be good to use the same retry configs that we provide in your RetryableInputStream as well
- I can keep both depending on your timelines but can be replaced by your change, tests are mostly same but might give you some conflicts on InputStream.

What do you think @jackye1995 @amogh-jahagirdar ?

**Comment by amogh-jahagirdar** [comment]
> > > The S3 team (@ookumuso) just published what they have developed internally and is now used in Amazon EMR, Athena, GlueETL distributions of Iceberg: #11052, is there a way we can see how we could collaborate on this?
> > 
> > 
> > Sorry for the late reply, Absolutely @jackye1995 ! So it seems like the overlap between this and #11052 is primarily the retrying of the reading of the input stream. #11052 also includes some configurable properties and different configurations for the S3Client.
> > For the retrying of the input stream, I think the key thing I was trying to achieve was adding the RetryableInputStream primitive so that other FileIOs like GCS/Azure can also use that. How do we feel about that @jackye1995 @ookumuso ? And then the other PR we can talk about the configuration/default updates?
> 
> No worries and thanks for following up! I am okay with using the RetryableInputStream as long as we can we can close this out soonish since there seems to be a lot of people hitting the same issue. Have 2 options here:
> 
> * I can exclude the InputStream changes entirely from my PR and just keep the s3-retry config changes. Might be good to use the same retry configs that we provide in your RetryableInputStream as well
> * I can keep both depending on your timelines but can be replaced by your change, tests are mostly same but might give you some conflicts on InputStream.
> 
> What do you think @jackye1995 @amogh-jahagirdar ?

Sounds good, yeah let me get this to closure soon since it has been open for a while. I think I'd propose option 1 and we rebase #11052  on top of that. My only take is we really should try and minimize as much configuration as possible in Iceberg since the S3 properties is already quite complex. But I think we can address that in the other PR since not retrying the input stream is a concrete issue that quite a few folks are hitting.

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java (hunk 8 above)
Comment (amogh-jahagirdar) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:96]: It's actually also required for correctness because when we retry the input stream we retry from the current position. Previously in this method we advance the position before actually reading the single byte. If we left it as is, upon retry we would read from the position 1 byte ahead of where we needed to re-open the stream from. It's not a problem when there's no retries because if stream.read() fails, it would just fail.

**Comment by SandeepSinghGahir** [comment]
> > > > The S3 team (@ookumuso) just published what they have developed internally and is now used in Amazon EMR, Athena, GlueETL distributions of Iceberg: #11052, is there a way we can see how we could collaborate on this?
> > > 
> > > 
> > > Sorry for the late reply, Absolutely @jackye1995 ! So it seems like the overlap between this and #11052 is primarily the retrying of the reading of the input stream. #11052 also includes some configurable properties and different configurations for the S3Client.
> > > For the retrying of the input stream, I think the key thing I was trying to achieve was adding the RetryableInputStream primitive so that other FileIOs like GCS/Azure can also use that. How do we feel about that @jackye1995 @ookumuso ? And then the other PR we can talk about the configuration/default updates?
> > 
> > 
> > No worries and thanks for following up! I am okay with using the RetryableInputStream as long as we can we can close this out soonish since there seems to be a lot of people hitting the same issue. Have 2 options here:
> > 
> > * I can exclude the InputStream changes entirely from my PR and just keep the s3-retry config changes. Might be good to use the same retry configs that we provide in your RetryableInputStream as well
> > * I can keep both depending on your timelines but can be replaced by your change, tests are mostly same but might give you some conflicts on InputStream.
> > 
> > What do you think @jackye1995 @amogh-jahagirdar ?
> 
> Sounds good, yeah let me get this to closure soon since it has been open for a while. I think I'd propose option 1 and we rebase #11052 on top of that. My only take is we really should try and minimize as much configuration as possible in Iceberg since the S3 properties is already quite complex. But I think we can address that in the other PR since not retrying the input stream is a concrete issue that quite a few folks are hitting.

Sounds good. Yes, a lot of folks are hitting this issue, also mentioned here: https://github.com/apache/iceberg/issues/10340

Do we have any expected time to merge this PR?

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java (hunk 3 above)
Comment (amogh-jahagirdar) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:145]: Discussed with @danielcweeks , for the range read cases since we're using IOUtil readFully/readRemaining which will read the range in a buffered manner. On retries we would read from the beginning position but the internal stream tracking in readFully/readRemaining would not reset to the right position in the buffer to read so that's still an issue.

What we can do is to just not retry the RangeReadable methods for now since they're not actually exercised anywhere.  Down the line, we could just use FailSafe and retry on the whole method.

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java [hunk 9]
```diff
@@ -178,18 +183,23 @@ private void positionStream() throws IOException {
...
+                    GetObjectRequest.Builder requestBuilder =
+                        GetObjectRequest.builder()
+                            .bucket(location.bucket())
+                            .key(location.key())
+                            .range(String.format("bytes=%s-", rangeStart));
+                    S3RequestUtil.configureEncryption(s3FileIOProperties, requestBuilder);
+                    return s3.getObject(
+                        requestBuilder.build(), ResponseTransformer.toInputStream());
+                  },
+                  () -> pos)
```
Comment (amogh-jahagirdar) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:201]: Discussed with @danielcweeks, we can just simplify this to remove the extra position supplier parameter to the builderFor API and just pass in the pos as part of the stream supplier

File: core/src/main/java/org/apache/iceberg/io/RetryableInputStream.java [hunk 10]
```diff
@@ -0,0 +1,130 @@
...
+import java.util.function.Supplier;
+import javax.net.ssl.SSLException;
+import org.apache.iceberg.relocated.com.google.common.base.Preconditions;
+import org.apache.iceberg.relocated.com.google.common.collect.ImmutableList;
+import org.apache.iceberg.relocated.com.google.common.collect.Lists;
+
+/**
+ * RetryableInputStream wraps over an underlying InputStream and retries failures encountered when
+ * reading through the stream. On retries, the underlying streams will be reinitialized.
+ */
```
Comment (danielcweeks) [inline core/src/main/java/org/apache/iceberg/io/RetryableInputStream.java:40]: I think that we need to document that the `newStreamSupplier` must track the position within the stream and restart it at the appropriate location.  This class will not track/reposition the stream upon recreation.

File: aws/src/test/java/org/apache/iceberg/aws/s3/TestFlakyS3InputStream.java [hunk 11]
```diff
@@ -0,0 +1,194 @@
...
+    }
+
+    @Override
+    public CreateBucketResponse createBucket(CreateBucketRequest createBucketRequest)
+        throws AwsServiceException, SdkClientException {
+      return delegate.createBucket(createBucketRequest);
+    }
+  }
+
+  static class FlakyInputStream extends InputStream {
```
Comment (amogh-jahagirdar) [inline aws/src/test/java/org/apache/iceberg/aws/s3/TestFlakyS3InputStream.java:149]: I slimmed down this input stream implementation so that we only implement read/close that's required for the tests.

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java [hunk 12]
```diff
@@ -56,7 +63,15 @@ class S3InputStream extends SeekableInputStream implements RangeReadable {
...
-  private int skipSize = 1024 * 1024;
+  private int skipSize = 1024 * 1024;;
+  private RetryPolicy<Object> retryPolicy =
+      RetryPolicy.builder()
+          .handle(
+              ImmutableList.of(
+                  SSLException.class, SocketTimeoutException.class, SocketException.class))
+          .onFailure(failure -> openStream(true))
+          .withMaxRetries(3)
+          .build();
```
Comment (amogh-jahagirdar) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:74]: I ended up removing RetryableInputStream for now; GCS is channel based and we should probably verify the Azure SDK doesn't already retry internally. We can always add the abstraction later if it ends up being needed but there's arguably not a compelling case for adding it up front when inlining Failsafe is simple. cc @danielcweeks

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java [hunk 13]
```diff
@@ -195,14 +230,20 @@ private void openStream() throws IOException {
...
       // call abort() so we don't read the remaining data with the Apache HTTP client
       abortStream();
       try {
         stream.close();
       } catch (IOException e) {
+        if (closeQuietly) {
+          stream = null;
+          LOG.warn("An error occurred while closing the stream", e);
+          return;
+        }
```
Comment (amogh-jahagirdar) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:245]: This is needed so that IOException failures on close during the retry don't count against the retry on the read. It can just be a best effort close.

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java [hunk 14]
```diff
@@ -57,6 +64,14 @@ class S3InputStream extends SeekableInputStream implements RangeReadable {
   private final Counter readOperations;
 
   private int skipSize = 1024 * 1024;
+  private RetryPolicy<Object> retryPolicy =
+      RetryPolicy.builder()
+          .handle(
+              ImmutableList.of(
+                  SSLException.class, SocketTimeoutException.class, SocketException.class))
+          .onFailure(failure -> openStream(true))
+          .withMaxRetries(3)
```
Comment (amogh-jahagirdar) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:73]: We can make these configurable down the line if needed but this covers all the cases that have been reported so far

**Comment by SandeepSinghGahir** [comment]
@amogh-jahagirdar  Any tentative timeline on merging of this PR?

File: core/src/main/java/org/apache/iceberg/io/RetryableInputStream.java (hunk 10 above)
Comment (amogh-jahagirdar) [reply core/src/main/java/org/apache/iceberg/io/RetryableInputStream.java]: Removing RetryableInputStream so we don't need this anymoe

File: aws/src/test/java/org/apache/iceberg/aws/s3/TestS3InputStream.java [hunk 15]
```diff
@@ -52,18 +52,15 @@ public void before() {
     createBucket("bucket");
   }
 
-  @Test
```
Comment (amogh-jahagirdar) [inline aws/src/test/java/org/apache/iceberg/aws/s3/TestS3InputStream.java:55]: Mistake here in my recent push this morning, the test method needs to be called passing in the client.

**Review by danielcweeks — APPROVED** [review]
Thanks for all the work and revisions @amogh-jahagirdar!

**Comment by amogh-jahagirdar** [comment]
Thanks for the reviews @danielcweeks! Merging.

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java [hunk 16]
```diff
@@ -57,6 +64,14 @@ class S3InputStream extends SeekableInputStream implements RangeReadable {
   private final Counter readOperations;
 
   private int skipSize = 1024 * 1024;
+  private RetryPolicy<Object> retryPolicy =
+      RetryPolicy.builder()
+          .handle(
+              ImmutableList.of(
+                  SSLException.class, SocketTimeoutException.class, SocketException.class))
```
Comment (tedyu) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:71]: Should `software.amazon.awssdk.core.exception.SdkClientException` be included in the exception list ?
It  indicates issues with the client-side networking stack, such as network timeouts.

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java (hunk 14 above)
Comment (tedyu) [inline aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:73]: It seems we can use jitter so that simultaneous retries don't overwhelm the system:
```
.withBackoff(1, 10, TimeUnit.SECONDS, BackoffJitter.random())
```

Comment (ookumuso) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:73]: EqualJitterBackoffStrategy adds the jitter internallly on every retry: software.amazon.awssdk.core.retry.backoff.EqualJitterBackoffStrategy

File: aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java (hunk 16 above)
Comment (ookumuso) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:71]: Judging by the comment in the SdkClientException class, it should not be retryable as there might be multiple reasons for it 

```
Base type for all client exceptions thrown by the SDK. This exception is thrown when service could not be contacted for a response, or when client is unable to parse the response from service.
Exceptions that extend SdkClientException are assumed to be not retryable, with a few exceptions:
RetryableException - usable when calls should explicitly be retried
Exceptions mentioned as a retryable exception in SdkDefaultRetrySetting
See Also:
SdkServiceException
```

Is there a more specific one that you were thinking?

Comment (tedyu) [reply aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java:71]: Looking at https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.html, we can add `RETRYABLE_EXCEPTIONS` to the list.
