### PR TITLE
Core: Ensure reactivated view version uses correct timestamp

### LINKED ISSUE #12809: View's VersionLog uses wrong timestamp if ViewVersions are reused
### Apache Iceberg version

1.8.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Lets assume the following changes:
1. ViewVersion 1 is added and set active
2. View Version 2 is added and set active
3. View Version 1 is set active.

This resulted in the following `version_log`:
```json
    "version-log": [
        {
            "version-id": 1,
            "timestamp-ms": 1744716416168
        },
        {
            "version-id": 2,
            "timestamp-ms": 1744716449754
        },
        {
            "version-id": 1,
            "timestamp-ms": 1744716416168
        }
    ],
```

Note that the last and first entries have the same timestamp, namely the timestamp of the initial ViewVersion creation.

I believe this is undesired in a history, where we are interested when a certain change became active. It makes sense to use the exact timestamp of the ViewVersion if it was added in the same set of changes, but re-enabling a previously used view version (maybe years ago) should not add a history for this past timestamp.

Fix in Rust: https://github.com/apache/iceberg-rust/pull/1218

The problematic line in Java is here:
https://github.com/apache/iceberg/blob/cc4fe4cc50043ccba89700f7948090ff87a5baee/core/src/main/java/org/apache/iceberg/view/ViewMetadata.java#L254

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by lliangyu-lin**
### Description
* Fixes #12809
* Apply the fixes from https://github.com/apache/iceberg-rust/pull/1218 by @c-thiel

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java [hunk 1]
```diff
@@ -249,9 +249,23 @@ public Builder setCurrentVersionId(int newVersionId) {
         changes.add(new MetadataUpdate.SetCurrentViewVersion(newVersionId));
       }
 
+      // Use the timestamp from the view version if it was added in current set of changes;
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:252]: I would slightly update/simplify this to 
```
       // Use the timestamp from the view version if it was added in current set of changes;
       // otherwise, use the current system time. This handles cases where the view version
-      // was created in a past commit and is being re-activated.
+      // was set as current in the past and is being re-activated.
       boolean versionAddedInThisChange =
-          changes.stream()
-              .anyMatch(
-                  change ->
-                      change instanceof MetadataUpdate.AddViewVersion
-                          && ((MetadataUpdate.AddViewVersion) change).viewVersion().versionId()
-                              == newVersionId);
-
-      long timestamp =
-          versionAddedInThisChange ? version.timestampMillis() : System.currentTimeMillis();
+          changes(MetadataUpdate.AddViewVersion.class)
+              .anyMatch(added -> added.viewVersion().versionId() == newVersionId);

       this.historyEntry =
           ImmutableViewHistoryEntry.builder()
-              .timestampMillis(timestamp)
+              .timestampMillis(
+                  versionAddedInThisChange ? version.timestampMillis() : System.currentTimeMillis())
               .versionId(version.versionId())
               .build();
```

File: core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java [hunk 2]
```diff
@@ -396,6 +397,47 @@ public void viewVersionHistoryIsCorrectlyRetained() {
...
+    ViewMetadata viewMetadata =
+        ViewMetadata.builder()
+            .setLocation("location")
+            .addSchema(new Schema(Types.NestedField.required(1, "x", Types.LongType.get())))
+            .addVersion(viewVersionOne)
+            .setCurrentVersionId(1)
+            .build();
+
+    // Update view metadata with multiple view versions in the same builder
+    ViewMetadata updated =
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java:420]: I think it's a good idea to also test how the history looks in between. Could you please update the code to 
```
diff --git a/core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java b/core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java
index cae1dbd02c..de39833c78 100644
--- a/core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java
+++ b/core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java
@@ -24,7 +24,6 @@ import static org.assertj.core.api.Assertions.assertThatThrownBy;
 import java.util.List;
 import java.util.Map;
 import java.util.UUID;
-import java.util.stream.Collectors;
 import org.apache.iceberg.MetadataUpdate;
 import org.apache.iceberg.Schema;
 import org.apache.iceberg.catalog.Namespace;
@@ -43,9 +42,13 @@ public class TestViewMetadata {
   }
 
   private ViewVersion newViewVersion(int id, int schemaId, String sql) {
+    return newViewVersion(id, schemaId, System.currentTimeMillis(), sql);
+  }
+
+  private ViewVersion newViewVersion(int id, int schemaId, long timestampMillis, String sql) {
     return ImmutableViewVersion.builder()
         .versionId(id)
-        .timestampMillis(System.currentTimeMillis())
+        .timestampMillis(timestampMillis)
         .defaultCatalog("prod")
         .defaultNamespace(Namespace.of("default"))
         .putSummary("user", "some-user")
@@ -398,44 +401,66 @@ public class TestViewMetadata {
   }
 
   @Test
-  public void versionHistoryEntryMaintainCorrectTimeline() {
-    ViewVersion viewVersionOne = newViewVersion(1, "select * from ns.tbl");
-    ViewVersion viewVersionTwo = newViewVersion(2, "select count(*) from ns.tbl");
-    ViewVersion viewVersionThree = newViewVersion(3, "select count(*) as count from ns.tbl");
-
-    long ts1 = viewVersionOne.timestampMillis();
-    long ts2 = viewVersionTwo.timestampMillis();
-    long ts3 = viewVersionThree.timestampMillis();
+  public void viewHistoryMaintainsCorrectTimeline() {
+    ViewVersion viewVersionOne = newViewVersion(1, 0, 1000, "select * from ns.tbl");
+    ViewVersion viewVersionTwo = newViewVersion(2, 0, 2000, "select count(*) from ns.tbl");
+    ViewVersion viewVersionThree =
+        newViewVersion(3, 0, 3000, "select count(*) as count from ns.tbl");
 
-    // Create initial view metadata
     ViewMetadata viewMetadata =
         ViewMetadata.builder()
             .setLocation("location")
             .addSchema(new Schema(Types.NestedField.required(1, "x", Types.LongType.get())))
             .addVersion(viewVersionOne)
-            .setCurrentVersionId(1)
-            .build();
-
-    // Update view metadata with multiple view versions in the same builder
-    ViewMetadata updated =
-        ViewMetadata.buildFrom(viewMetadata)
             .addVersion(viewVersionTwo)
-            .addVersion(viewVersionThree)
-            .setCurrentVersionId(3)
+            .setCurrentVersionId(1)
             .build();
 
-    // Reactivate an old view version as current version
-    ViewMetadata reactiveOldView = ViewMetadata.buildFrom(updated).setCurrentVersionId(1).build();
-    List<ViewHistoryEntry> history = reactiveOldView.history();
-
-    List<Integer> versionIds =
-        history.stream().map(ViewHistoryEntry::versionId).collect(Collectors.toList());
-    assertThat(versionIds).containsExactly(1, 3, 1);
-
-    // Verify timestamps in the history entries
-    assertThat(history.get(0).timestampMillis()).isEqualTo(ts1).isLessThanOrEqualTo(ts2);
-    assertThat(history.get(1).timestampMillis()).isEqualTo(ts3).isGreaterThanOrEqualTo(ts2);
-    assertThat(history.get(2).timestampMillis()).isGreaterThanOrEqualTo(ts3);
+    // setting an existing view version as the new current should update the timestamp in the
+    // history
+    ViewMetadata updated = ViewMetadata.buildFrom(viewMetadata).setCurrentVersionId(2).build();
+    List<ViewHistoryEntry> history = updated.history();
+    assertThat(history)
+        .hasSize(2)
+        .element(0)
+        .isEqualTo(ImmutableViewHistoryEntry.builder().versionId(1).timestampMillis(1000).build());
+    assertThat(history)
+        .element(1)
+        .satisfies(
+            v -> {
+              assertThat(v.versionId()).isEqualTo(2);
+              assertThat(v.timestampMillis())
+                  .isGreaterThan(3000)
+                  .isLessThanOrEqualTo(System.currentTimeMillis());
+            });
+
+    // adding a new view version and setting it as current should use the view version's timestamp
+    // in the history (which has been set to a fixed value for testing)
+    updated =
+        ViewMetadata.buildFrom(updated).addVersion(viewVersionThree).setCurrentVersionId(3).build();
+    List<ViewHistoryEntry> historyTwo = updated.history();
+    assertThat(historyTwo)
+        .hasSize(3)
+        .containsAll(history)
+        .element(2)
+        .isEqualTo(ImmutableViewHistoryEntry.builder().versionId(3).timestampMillis(3000).build());
+
+    // setting an older view version as the new current (aka doing a rollback) should update the
+    // timestamp in the history
+    ViewMetadata reactiveOldViewVersion =
+        ViewMetadata.buildFrom(updated).setCurrentVersionId(1).build();
+    List<ViewHistoryEntry> historyThree = reactiveOldViewVersion.history();
+    assertThat(historyThree)
+        .hasSize(4)
+        .containsAll(historyTwo)
+        .element(3)
+        .satisfies(
+            v -> {
+              assertThat(v.versionId()).isEqualTo(1);
+              assertThat(v.timestampMillis())
+                  .isGreaterThan(3000)
+                  .isLessThanOrEqualTo(System.currentTimeMillis());
+            });
   }
 

```

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java (hunk 1 above)
Comment (lliangyu-lin) [reply core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:252]: @nastra Thanks for the review! I'll apply the comments and raise a revision.
But some concerns I have right now is that the change breaks existing unit tests like
https://github.com/apache/iceberg/blob/9fc49e187069c7ec2493ac0abf20f73175b3df89/core/src/test/java/org/apache/iceberg/view/TestViewMetadataParser.java#L218-L239
In `.setCurrentVersionId(2)`, it's in different builder and have no local `changes`, causing the activation of view version to set to current timestamp even though version 2 never set as current before. And in the comment, we are trying to say only `view version was set as current in the past` with use current ts.

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java [hunk 3]
```diff
@@ -249,9 +249,17 @@ public Builder setCurrentVersionId(int newVersionId) {
...
+      // Otherwise, use the current system time. This handles cases where the view version
+      // was set as current in the past and is being re-activated.
+      boolean versionAddedInThisChange =
+          changes(MetadataUpdate.AddViewVersion.class)
+              .anyMatch(added -> added.viewVersion().versionId() == newVersionId);
+
       this.historyEntry =
           ImmutableViewHistoryEntry.builder()
-              .timestampMillis(version.timestampMillis())
+              .timestampMillis(
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:261]: in hindsight I'm actually thinking whether it's more correct to always set this to `System.currentTimeMillis()` after re-reading the spec in https://iceberg.apache.org/view-spec/#version-log. @rdblue wdyt?

Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:261]: If the version was added in the current request to change current-version-id, then it should use the timestamp from the version so it all matches. With timestamps there is no "correct" -- we want to have predictable and reasonable behavior. Making the timestamps match makes sense so that you don't have to reason about things that were "probably" part of the same change.

Comment (nastra) [reply core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:261]: thanks for the input here @rdblue

**Review by nastra — APPROVED** [review]
LGTM, thanks @lliangyu-lin

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java (hunk 1 above)
Comment (nastra) [reply core/src/main/java/org/apache/iceberg/view/ViewMetadata.java]: changing the unit test with the changes you have here in order to match the `version-log` that we compare against (we compare against a fixed timestamp defined in `ValidViewMetadata.json`) makes sense to me as this is a consequence of using the current time millis instead of the view version's time when setting the view version from 1 to 2 without actually adding view version 2 in the same builder.
