### PR TITLE
Core, Hive: Double check commit status in case of commit conflict for NoLock

### LINKED ISSUE #11814: Table corruption using lock-free Hive commits
### Apache Iceberg version

1.6.1

### Query engine

Spark

### Please describe the bug 🐞

We observed the following situation happen a few times now when using lock-free Hive catalog commits introduced in https://github.com/apache/iceberg/pull/6570:

 We run an `ALTER TABLE table SET TBLPROPERTIES ('key' = 'value')` or any other operation that results in an Iceberg commit, either Spark or any other engine. For whatever reason the connection to the Hive metastore is broken and the HMS operation fails during the first attempt:
```
WARN org.apache.hadoop.hive.metastore.RetryingMetaStoreClient: MetaStoreClient lost connection. Attempting to reconnect (1 of 1) after 1s. alter_table_with_environmentContext
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
<...>
at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_alter_table_with_environment_context(ThriftHiveMetastore.java:1693)
<...>
at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169)
<...>
at org.apache.iceberg.hive.MetastoreUtil.alterTable(MetastoreUtil.java:78)
at org.apache.iceberg.hive.HiveOperationsBase.lambda$persistTable$0(HiveOperationsBase.java:112)
<...>
at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:239)
at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:135)
<...>
at org.apache.iceberg.spark.SparkCatalog.alterTable(SparkCatalog.java:345)
<...>
```
but the operation actually succeeds and updates the metadata location, which means that when the `RetryingMetaStoreClient` attempts resubmitting the operation, it fails with:
```
MetaException(message:The table has been modified. The parameter value for key 'metadata_location' is '<new>'. The expected was value was '<previous>')
```
The Iceberg commit is then considered failed and the new metadata file is cleaned up in the `finally` block [here](https://github.com/apache/iceberg/blob/b428fbc59bd1579f4dc918a5cd48fce667d81ce1/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L320) before retrying the commit. But the problem is that the Hive table has the new metadata location set, so when Iceberg tries refreshing the table it fails, because the new metadata file no longer exists, leaving the table in a corrupted state.

I suppose a fix could be checking the exception and ignoring the case when the already set location is equal to the new metadata location, but parsing the error message sounds very hacky.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by lirui-apache**
Fixes #11814

### CODE REVIEW

**Comment by lirui-apache** [comment]
I need to make these changes to enable a test with NoLock:
1. Allow direct SQL in test metastore, because the transactional altering table now relies on direct SQL as of [HIVE-28121](https://issues.apache.org/jira/browse/HIVE-28121)
2. Change the type of `TABLE_PARAMS.PARAM_VALUE` from `CLOB` to `VARCHAR(32672)`. This is because derby doesn't allow comparing clob type with a string, so the direct SQL will fail. I believe tests in Hive can run because Hive initializes the underlying DB with the [JDO mapping](https://github.com/apache/hive/blob/rel/release-2.3.10/metastore/src/model/package.jdo#L173) instead of the metastore SQL script.

If these changes turn out to be unacceptable, I suppose we can just mock the exception in the HMS client.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java [hunk 1]
```diff
@@ -63,6 +64,31 @@ protected CommitStatus checkCommitStatus(
       String newMetadataLocation,
       Map<String, String> properties,
       Supplier<Boolean> commitStatusSupplier) {
+    if (metadataLocationCommitted(
+            tableOrViewName, newMetadataLocation, properties, commitStatusSupplier)
+        .orElse(false)) {
+      return CommitStatus.SUCCESS;
+    }
+    return CommitStatus.UNKNOWN;
```
Comment (pvary) [inline core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:72]: Why did you decide to create a new method?

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java [hunk 2]
```diff
@@ -287,15 +277,25 @@ protected void doCommit(TableMetadata base, TableMetadata metadata) {
...
-        commitStatus =
-            BaseMetastoreOperations.CommitStatus.valueOf(
-                checkCommitStatus(newMetadataLocation, metadata).name());
+        if (e.getMessage() != null
+            && e.getMessage()
+                .contains(
+                    "The table has been modified. The parameter value for key '"
+                        + HiveTableOperations.METADATA_LOCATION_PROP
+                        + "' is")) {
+          commitStatus = handleConcurrentModification(e, newMetadataLocation, metadata);
```
Comment (pvary) [inline hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:286]: Is it better to call this `handlePossibleConcurrentModification`?

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java [hunk 3]
```diff
@@ -287,15 +277,25 @@ protected void doCommit(TableMetadata base, TableMetadata metadata) {
...
-            "Cannot tell if commit to {}.{} succeeded, attempting to reconnect and check.",
-            database,
-            tableName,
-            e);
-        commitStatus = BaseMetastoreOperations.CommitStatus.UNKNOWN;
-        commitStatus =
-            BaseMetastoreOperations.CommitStatus.valueOf(
-                checkCommitStatus(newMetadataLocation, metadata).name());
+        if (e.getMessage() != null
+            && e.getMessage()
```
Comment (pvary) [inline hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:281]: Could we have a same issue here than with #11576?
If there is a new exception during the `handleConcurrentModification` call, then the commit status is unset, and the metadata will be removed.

Maybe leave the
```
commitStatus = BaseMetastoreOperations.CommitStatus.UNKNOWN;
```
line before the `if` statement?

Comment (pvary) [reply hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:281]: Also, we could add a comment there. It took me a while the understand the reasoning behind it 😄

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java [hunk 4]
```diff
@@ -324,6 +324,25 @@ protected void doCommit(TableMetadata base, TableMetadata metadata) {
         "Committed to table {} with the new metadata location {}", fullName, newMetadataLocation);
   }
 
+  private BaseMetastoreOperations.CommitStatus handleConcurrentModification(
+      Throwable throwable, String newMetadataLocation, TableMetadata metadata) {
```
Comment (pvary) [inline hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:328]: What is the difference between the `checkCommitStatus` and the `handleConcurrentModification`?

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java (hunk 1 above)
Comment (lirui-apache) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:72]: Because `checkCommitStatus` never returns `CommitStatus.FAILURE`, which is required so that we know when to throw a CommitFailedException. And since it's kind of a public API, so I added metadataLocationCommitted which returns false if the new metadata location cannot be found.

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java (hunk 3 above)
Comment (lirui-apache) [reply hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:281]: Good catch, will do

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java (hunk 4 above)
Comment (lirui-apache) [reply hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:328]: Same here as in the previous comment: `checkCommitStatus` doesn't return FAILURE which is required by `handleConcurrentModification `

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java (hunk 1 above)
Comment (lirui-apache) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:72]: Hmm interesting... But I think we don't have to worry about that in our case, because the double check happens after HMS explicitly returns an exception, which means it has finished processing right?

Comment (lirui-apache) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:72]: I don't think we can return UNKNOWN if the metadata location is not found. Because UNKNOWN leads to a CommitStateUnknownException and it won't be retried, which basically means concurrent commit is not possible with NoLock mode.

Comment (pvary) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:72]: > Hmm interesting... But I think we don't have to worry about that in our case, because the double check happens after HMS explicitly returns an exception, which means it has finished processing right?

There could me multiple HMS instances, and another one might still working on serving the previous request

Comment (pvary) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:72]: > >Hmm interesting... But I think we don't have to worry about that in our case, because the double check happens after HMS explicitly returns an exception, which means it has finished processing right?
> There could me multiple HMS instances, and another one might still working on serving the previous request

But that will fail... Let me think a bit about this.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java [hunk 5]
```diff
@@ -63,6 +64,31 @@ protected CommitStatus checkCommitStatus(
...
+   *
+   * @param tableOrViewName full name of the Table/View
+   * @param newMetadataLocation the path of the new commit file
+   * @param properties properties for retry
+   * @param commitStatusSupplier check if the latest metadata presents or not using metadata
+   *     location for table.
+   * @return Empty if locations cannot be checked, e.g. unable to refresh. True if the new location
+   *     is committed, false otherwise.
+   */
+  protected Optional<Boolean> metadataLocationCommitted(
```
Comment (pvary) [inline core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:87]: Instead of returning an `Optional<Boolean>`, would it be better to return the current commit status?
Like:
```
  /**
   * Attempt to load the content and see if any current or past metadata location matches the one we
   * were attempting to set. This is used as a last resort when we are dealing with exceptions that
   * may indicate the commit has failed and don't have proof that this is the case, but we can be sure that
   * no retry attempts for the commit will be successful later. Note that all the previous locations must also
   * be searched on the chance that a second committer was able to successfully commit on top of our commit.
   * When the {@code newMetadataLocation} is not in the history the method returns
   * {@link CommitStatus.FAILURE}, when the {@link commitStatusSupplier} fails repeatedly the method returns 
   * {@link CommitStatus.UNKNOWN}.
   *
   * @param tableOrViewName full name of the Table/View
   * @param newMetadataLocation the path of the new commit file
   * @param properties properties for retry
   * @param commitStatusSupplier check if the latest metadata presents or not using metadata
   *     location for table.
   * @return Commit Status of Success, Failure or Unknown
   */
  protected CommitStatus checkCommitStatusStrict(
      String tableOrViewName,
      String newMetadataLocation,
      Map<String, String> properties,
      Supplier<Boolean> commitStatusSupplier) {
```

And we need to update the javadoc for the `checkCommitStatus` too, to describe that it will never return `CommitStatus.FAILURE`, like:
```
  /**
   * Attempt to load the content and see if any current or past metadata location matches the one we
   * were attempting to set. This is used as a last resort when we are dealing with exceptions that
   * may indicate the commit has failed but don't have proof that this is the case. Note that all
   * the previous locations must also be searched on the chance that a second committer was able to
   * successfully commit on top of our commit. When the {@code newMetadataLocation} is not in the
   * history or the {@link commitStatusSupplier} fails repeatedly the method returns
   * {@link CommitStatus.UNKNOWN}, because possible pending retires might still commit the change.
   *
   * @param tableOrViewName full name of the Table/View
   * @param newMetadataLocation the path of the new commit file
   * @param properties properties for retry
   * @param commitStatusSupplier check if the latest metadata presents or not using metadata
   *     location for table.
   * @return Commit Status of Success or Unknown
   */
```

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java [hunk 6]
```diff
@@ -324,6 +331,24 @@ protected void doCommit(TableMetadata base, TableMetadata metadata) {
...
+    if (locationCommitted.isPresent()) {
+      if (locationCommitted.get()) {
+        return BaseMetastoreOperations.CommitStatus.SUCCESS;
+      } else {
+        return BaseMetastoreOperations.CommitStatus.FAILURE;
+      }
+    }
+    return BaseMetastoreOperations.CommitStatus.UNKNOWN;
+  }
+
```
Comment (pvary) [inline hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:351]: We can get rid of this method, if we have something like `checkCommitStatusStrict` method

File: hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java [hunk 7]
```diff
@@ -40,16 +40,10 @@ private HiveMetastoreExtension(String databaseName, Map<String, String> hiveConf
...
-      for (Map.Entry<String, String> kv : hiveConfOverride.entrySet()) {
-        hiveConfWithOverrides.set(kv.getKey(), kv.getValue());
-      }
-    }
+    metastore = new TestHiveMetastore(hiveConfOverride);
 
-    metastore.start(hiveConfWithOverrides);
-    metastoreClient = new HiveMetaStoreClient(hiveConfWithOverrides);
+    metastore.start(new HiveConf(TestHiveMetastore.class));
+    metastoreClient = new HiveMetaStoreClient(metastore.hiveConf());
```
Comment (pvary) [inline hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java:46]: Why do we add this change?

Comment (pvary) [inline hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java:46]: Why is this change?

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java (hunk 5 above)
Comment (lirui-apache) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:87]: Yeah but I would like `checkCommitStatusStrict` and `checkCommitStatus` to share the same underlying check logic. The difference is `checkCommitStatusStrict` treats false as `CommitStatus.FAILURE` while `checkCommitStatus` treats false as `CommitStatus.UNKNOWN`. So I think we can keep the method returning `Optional<Boolean>`, but make it private?

File: hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java (hunk 7 above)
Comment (lirui-apache) [reply hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java:46]: `METASTORE_TRY_DIRECT_SQL` is hard coded to false in `TestHiveMetastore::initConf`. This change is to make it possible to override the config in our test.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java [hunk 8]
```diff
@@ -310,7 +310,7 @@ protected CommitStatus checkCommitStatus(String newMetadataLocation, TableMetada
    * @return true if the new metadata location is the current metadata location or present within
    *     previous metadata files.
    */
-  private boolean checkCurrentMetadataLocation(String newMetadataLocation) {
+  protected boolean checkCurrentMetadataLocation(String newMetadataLocation) {
```
[the remark this answers is not in the document]
Comment (lirui-apache) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java]: Added checkCommitStatusStrict instead. It seems more consistent with current APIs. Thanks~

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java (hunk 5 above)
Comment (pvary) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java]: Or could we just call the `checkCommitStatusStrict` inside the `checkCommitStatus` and reinterpret the result?

File: hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java (hunk 7 above)
Comment (pvary) [reply hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java:46]: Could you please try to set this globally, and see if there is an issue with it? This is just test code, and I would like to try to keep it as simple as possible.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java (hunk 5 above)
Comment (lirui-apache) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java]: Oh yes, good idea!

File: hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java (hunk 7 above)
Comment (lirui-apache) [reply hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java:46]: OK I'll try setting the default value to true, if everything is fine, I'll revert this change

Comment (lirui-apache) [reply hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java:46]: Enabling direct SQL globally seems to fix the [weird test case](https://github.com/apache/iceberg/blob/af99da6c2daa8e53876638c839b0f729f2f3a86e/spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java#L741). I did some debug and believe it's because direct SQL gets the partition filter pushdown correct and retrieves the corresponding partitions. Should I update the test cases here, or leave it to another PR?

File: hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql [hunk 9]
```diff
@@ -130,7 +130,7 @@ CREATE TABLE "APP"."TAB_COL_STATS"(
     "BIT_VECTOR" BLOB
 );
 
-CREATE TABLE "APP"."TABLE_PARAMS" ("TBL_ID" BIGINT NOT NULL, "PARAM_KEY" VARCHAR(256) NOT NULL, "PARAM_VALUE" CLOB);
```
Comment (pvary) [inline hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql:133]: Do we want to change the other `CLOB`s in this file as well?

File: core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java [hunk 10]
```diff
@@ -98,11 +136,7 @@ protected CommitStatus checkCommitStatus(
                     newMetadataLocation);
                 status.set(CommitStatus.SUCCESS);
               } else {
-                LOG.warn(
-                    "Commit status check: Commit to {} of {} unknown, new metadata location is not current "
-                        + "or in history",
-                    tableOrViewName,
-                    newMetadataLocation);
```
Comment (pvary) [inline core/src/main/java/org/apache/iceberg/BaseMetastoreOperations.java:105]: Keep this, it is still useful

**Comment by pvary** [comment]
Thanks @lirui-apache for all your work on this!
Last changes and we are golden.

We can ping Russell when we are ready, but if he doesn't have time, then I will be happy to merge it later this week.

File: hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql (hunk 9 above)
Comment (lirui-apache) [reply hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql:133]: Add more changes to be consistent with HIVE-16667 and HIVE-25574

**Review by pvary — APPROVED** [review]
+1 pending tests

**Comment by pvary** [comment]
Looks good to me. 
@RussellSpitzer: Do you want to review this before merge?

File: hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql (hunk 9 above)
Comment (deniskuzZ) [reply hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql:133]: FYI CLOB handling was fixed in https://github.com/apache/hive/pull/5386/files#diff-bcca13f6cc251df321e8fe80568ef0334a1d44f7e5e7ff2fcaa06ab4f05bbdf9R3387

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java [hunk 11]
```diff
@@ -287,15 +277,33 @@ protected void doCommit(TableMetadata base, TableMetadata metadata) {
...
+            throw new CommitFailedException(
+                e, "The table %s.%s has been modified concurrently", database, tableName);
+          }
+        } else {
+          LOG.error(
+              "Cannot tell if commit to {}.{} succeeded, attempting to reconnect and check.",
+              database,
+              tableName,
+              e);
+          commitStatus =
```
Comment (deniskuzZ) [inline hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:302]: why do we need this weird casting? Note, it's skipped when we don't hit the else branch

Comment (lirui-apache) [reply hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java:302]: I believe it was introduced in #10001 when we had two enums: `BaseMetastoreTableOperations::CommitStatus` and `BaseMetastoreOperations::CommitStatus`, and is not needed anymore. I'd be happy to remove it in this PR if you think that's better.

File: hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql (hunk 9 above)
Comment (lirui-apache) [reply hive-metastore/src/test/resources/hive-schema-3.1.0.derby.sql:133]: Good to know the direct SQL is made more robust. Maybe we can revisit this change when we upgrade our hive dependency.

File: hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java (hunk 11 above)
Comment (lirui-apache) [reply hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java]: I updated to address this issue. At least I think the new `checkCommitStatusStrict` should not follow this pattern. @pvary please let me know if you think otherwise.

**Comment by lirui-apache** [comment]
Thanks to @pvary and @deniskuzZ for reviewing and merging the PR!
