### PR TITLE
AWS: Retain Glue Catalog column comment after updating Iceberg table

### LINKED ISSUE #10220: AWS: Updating Glue catalog table removes column descriptions
### Apache Iceberg version

main (development)

### Query engine

Spark

### Please describe the bug 🐞

In AWS Glue Catalog, user can set arbitrary descriptions to the table and its columns via Web UI or even from Amazon Athena. However, the descriptions are deleted after upgrading the table.

I submitted a patch to retain the table description in https://github.com/apache/iceberg/pull/10199, but I would like to retain column descriptions as well in a separate PR later.

### PR DESCRIPTION
**Pull request by lawofcycles**
## What this PR does
This PR addresses the issue where column comments in the Glue catalog are not retained when updating an existing Iceberg table schema. It fixes the problem by modifying the IcebergToGlueConverter.setTableInputInformation method to preserve existing column comments from the Glue table when creating a new TableInput for an update operation.
  
When an existing Glue table is provided, the modified method retrieves the comments from its columns and applies them to the corresponding columns in the new TableInput, but only if the Iceberg table's column does not already have a comment.  
   
This change ensures that any user-defined column comments in the Glue catalog are carried over during table updates, preventing unintentional loss of documentation.
## Testing

Added a new unit test method testSetTableInputInformationWithExistingTable to verify that column comments from an existing Glue table are correctly preserved when creating a new TableInput.  
I'll also add Integration Tests same as [#10199](https://github.com/apache/iceberg/pull/10199).
  
Fixes #10220

### CODE REVIEW

**Comment by lawofcycles** [comment]
I built the jars and manually tested on Amazon EMR as a Spark runtime.

**Comment by lawofcycles** [comment]
Hi @geruh would you review this PR?

File: aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java [hunk 1]
```diff
@@ -234,8 +259,26 @@ static void setTableInputInformation(
       Optional.ofNullable(properties.get(GLUE_DESCRIPTION_KEY))
           .ifPresent(tableInputBuilder::description);
 
+      List<Column> columns = toColumns(metadata);
+      if (existingTable != null) {
+        List<Column> existingColumns = existingTable.storageDescriptor().columns();
+        Map<String, Column> existingColumnMap =
```
Comment (geruh) [inline aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java:265]: What do you think about making this a map of column name to comment here. Since we aren't using any additional information from the existing comments

File: aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java [hunk 2]
```diff
@@ -501,6 +501,97 @@ public void testColumnCommentsAndParameters() {
     assertThat(actualColumns).isEqualTo(expectedColumns);
   }
 
+  @Test
+  public void testGlueTableColumnCommentsPreserved() {
```
Comment (geruh) [inline aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java:505]: What about the case where we drop a column from a table. I believe today we keep those columns and descriptions. Should we add a test for that?

**Review by geruh — COMMENTED** [review]
Looks great, @lawofcycles! I've taken an initial pass. Thanks for the solid work!

**Comment by lawofcycles** [comment]
@geruh Thank you for your review! 
I have pushed the changes addressing your review comments.
Could you please take another look when you have a chance?

File: aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java [hunk 3]
```diff
@@ -234,8 +258,26 @@ static void setTableInputInformation(
       Optional.ofNullable(properties.get(GLUE_DESCRIPTION_KEY))
           .ifPresent(tableInputBuilder::description);
```
Comment (aajisaka) [inline aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java:259]: Hi @lawofcycles thank you for your patch!

Now this method has the existing table information, so I think it would be better to move the function to keep the table description https://github.com/aajisaka/iceberg/blob/58c61241bd61de7a4062dbf664691f05eeb2ea53/aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java#L319-L321 into this method.

Comment (lawofcycles) [reply aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java]: Thank you for your review!
I moved keeping the table description logic to IcebergToGlueConverter.

**Comment by lawofcycles** [comment]
Hi @geruh would you review the latest change?

File: aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java [hunk 4]
```diff
@@ -231,11 +255,33 @@ static void setTableInputInformation(
...
-      Optional.ofNullable(properties.get(GLUE_DESCRIPTION_KEY))
-          .ifPresent(tableInputBuilder::description);
+      String description = properties.get(GLUE_DESCRIPTION_KEY);
+      if (description != null) {
+        tableInputBuilder.description(description);
+      } else if (existingTable != null) {
+        Optional.ofNullable(existingTable.description()).ifPresent(tableInputBuilder::description);
+      }
+
+      List<Column> columns = toColumns(metadata);
```
Comment (aajisaka) [inline aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java:265]: I'm thinking we can simplify the implementation by creating `existingColumnMap` first and use it inside `addColumnWithDedupe` method. In this way we don't have to replace the new columns.

Comment (lawofcycles) [reply aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java]: I merged existing column comment processing into creating column set on to `toColumns` and `addColumnWithDedupe` method

**Review by aajisaka — APPROVED** [review]
Thank you @lawofcycles

**Comment by lawofcycles** [comment]
Hi @amogh-jahagirdar would you review the latest change?

**Comment by lawofcycles** [comment]
Hi @amogh-jahagirdar,

I hope this message finds you well. I wanted to kindly follow up on this PR, which addresses an important issue with preserving Glue Catalog column comments when updating Iceberg tables (#10220).

Could you please take a look when you have a moment? Thank you for your time and consideration.

**Comment by amogh-jahagirdar** [comment]
Really sorry for the delayed review @lawofcycles , I'll take a look today.

File: aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java [hunk 5]
```diff
@@ -231,11 +256,27 @@ static void setTableInputInformation(
...
+      if (existingTable != null) {
+        List<Column> existingColumns = existingTable.storageDescriptor().columns();
+        existingColumnMap =
+            existingColumns.stream()
+                .filter(column -> column.comment() != null)
+                .collect(Collectors.toMap(Column::name, Column::comment));
+      } else {
+        existingColumnMap = Collections.emptyMap();
+      }
+      List<Column> columns = toColumns(metadata, existingColumnMap);
```
Comment (amogh-jahagirdar) [inline aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java:276]: Nit: Newline after the else

File: aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java [hunk 6]
```diff
@@ -311,4 +312,81 @@ public void testSetTableDescription() {
...
+                                        IcebergToGlueConverter.ICEBERG_FIELD_ID, "3",
+                                        IcebergToGlueConverter.ICEBERG_FIELD_OPTIONAL, "false",
+                                        IcebergToGlueConverter.ICEBERG_FIELD_CURRENT, "true"))
+                                .build()))
+                    .build())
+            .build();
+
+    Assertions.assertThat(actualTableInput.storageDescriptor().columns())
+        .as("Columns should match")
+        .isEqualTo(expectedTableInput.storageDescriptor().columns());
```
Comment (amogh-jahagirdar) [inline aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java:390]: Double checking to make sure this test is strong, `equals` for columns will properly compare against all the fields of the column right? It may be better to explicitly assert the fields we want.

File: aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java [hunk 7]
```diff
@@ -219,6 +221,29 @@ static String getTableName(TableIdentifier tableIdentifier, boolean skipNameVali
...
+   * Iceberg metadata file defined by the metadata_location table property.
+   *
+   * <p>If an existing Glue table is provided, the comments from its columns will be preserved in
+   * the resulting Glue TableInput. This is useful when updating an existing Glue table to retain
+   * any user-defined comments on the columns.
+   *
+   * @param tableInputBuilder Glue TableInput builder
+   * @param metadata Iceberg table metadata
+   * @param existingTable optional existing Glue table, used to preserve column comments
+   */
```
Comment (amogh-jahagirdar) [inline aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java:244]: Wow thank you for this comment! Appreciate that

File: aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java (hunk 6 above)
Comment (amogh-jahagirdar) [reply aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java:390]: Seems like it based on the unit test for testDropColumn, so we should be good.

**Review by amogh-jahagirdar — APPROVED** [review]
@lawofcycles I think this is pretty good, just had some questions and nits. I'll wait a bit if @geruh @rahil-c have any concerns and if not I'll go ahead and merge

File: aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java (hunk 5 above)
Comment (lawofcycles) [reply aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java:277]: fixed!

File: aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java [hunk 8]
```diff
@@ -221,6 +221,69 @@ public void testUpdateTable() {
...
+        tableName,
+        column -> {
+          if (column.name().equals("c3")) {
+            return column.toBuilder().comment("updated from Glue API").build();
+          } else {
+            return column;
+          }
+        });
+
+    table.updateSchema().deleteColumn("c2").deleteColumn("c3").commit();
```
Comment (rahil-c) [inline aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java:246]: @lawofcycles For my own understanding but when you do the deleteColums and commit shouldn't this sync to catalog and these columns not be present anymore from glue? Or is this commit only changing the iceberg metadata in S3, and thus thats why the assertion is working correctly below as the catalog still has not the updated view of the table and contains the comments?

Comment (lawofcycles) [reply aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java:246]: @rahil-c  
> Or is this commit only changing the iceberg metadata in S3

Yes.
On current Iceberg's Glue integration, Glue Data Catalog holds all the column info that are registered in Iceberg Table even if these are deleted. IcebergToGlueConverter always try to sync all the historical column to Glue Data Catalog every time schema is updated.
For example, following scenario is expected behaviour.
 
1. Create Table with column x, y, z with Iceberg DDL using Glue Data Catalog as Iceberg Catalog
2. drop column y with Iceberg DDL  -> column y remain on Glue Data Catalog
3. drop column y, z from Glue Data Catalog API
4. add column y2 with Iceberg DDL  ->  column y, z appeared again on Glue Data Catalog in addition to column y2

I think those Information will be used to refer the historical columns on AWS Console when user query tables from such as Athena.

Comment (rahil-c) [reply aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java:246]: Thanks for the explanation!

**Review by rahil-c — APPROVED** [review]

**Comment by Fokko** [comment]
Let's get this in, thanks @lawofcycles for working on this, and @amogh-jahagirdar and @rahil-c for the review!

**Comment by lawofcycles** [comment]
Thanks for reviewing @amogh-jahagirdar , @aajisaka , @geruh and @rahil-c !!

**Comment by lawofcycles** [comment]
Thank you for merging @Fokko !
