### PR TITLE
Parquet: Fixes Incorrect Skipping of RowGroups with NaNs

### LINKED ISSUE #6516: Parquet: Metric Row Group Filter handles Undefined Min/Max incorrectly Missing Rows
### Apache Iceberg version

1.1.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Summary:
This effects files where the parquet statistics mark either the min or max of a given column to NaN with Float or Double type (I have not checked other types) which will have their row groups skipped incorrectly. 

In this case our evaluators are handling undefined min/max statistics incorrectly. When one of these two stats is **NaN** parquet will set hasNonNull equal to false.

https://github.com/apache/parquet-mr/blob/433de8df33fcf31927f7b51456be9f53e64d48b9/parquet-column/src/main/java/org/apache/parquet/column/statistics/Statistics.java#L89-L92

```java
        // Drop min/max values in case of NaN as the sorting order of values is undefined for this case
        if (min.isNaN() || max.isNaN()) {
          stats.setMinMax(0.0f, 0.0f);
          ((Statistics<?>) stats).hasNonNullValue = false;
```

Unfortunately when evaluating `gt` we check whether this is "false" and return "rows won't match" if it is. 

See
https://github.com/apache/iceberg/blob/cf00f6a06b256e9c4defe226b6a37aa83c40f561/parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java#L279-L281

I'm unsure what the intent in the Parquet code is here and it seems to be a bug to me in the parquet library. I'm not sure why having a NaN would mean that the statistics should report there are no non-null values. According to the Java Doc in the parquet library 

```java
  /**
   * Returns whether there have been non-null values added to this statistics
   *
   * @return true if the values contained at least one non-null value
   */
```

Which implies to me that this should not be false if we added a NaN.

While we probably should try to fix this on the Parquet Side I think we can fix this on the iceberg side by not using the "hasNonNull" in our metric checks if the value count is > 0? 

Thanks John Pugliesi for reporting this and providing a repo 🙇

### PR DESCRIPTION
**Pull request by RussellSpitzer**
Previously, the RowGroupFilter would skip any RowGroups whose min or max value was set as NaN because Parquet would report that those row groups "hasNonNull" as false. When the statistics are not empty and hasNonNull is false this actually indicates that the min and max are undefined, not that there are no non nulls.

Fixes #6516

### CODE REVIEW

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java [hunk 1]
```diff
@@ -580,6 +608,10 @@ static boolean hasNonNullButNoMinMax(Statistics statistics, long valueCount) {
         && (statistics.getMaxBytes() == null || statistics.getMinBytes() == null);
   }
 
+  static boolean minMaxUndefined(Statistics statistics) {
+    return !statistics.isEmpty() && !statistics.hasNonNullValue();
```
Comment (zhongyujiang) [inline parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:612]: This [unit test](https://github.com/apache/iceberg/issues/6516#issuecomment-1370862183) fails, I think it's because when all values are all null , min max will be null(undefined) too, seems we should handle the case of all values first.

Comment (zhongyujiang) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:612]: I am thinking we can simplify the handling of unreliable statistics by moving the judgment of all-null situation forward, as I mentioned [here](https://github.com/apache/iceberg/issues/6516#issuecomment-1370862183)，we can use `Statistics#getNumNulls() = ColumnChunkMetadata#getValueCount()` to determine if all values are null (which will not be affected by null or undinfined min max statistics); Then we handle the case of `statistics.hasNonNullValue()` is false(when statistics has null min max or unreliable min max), we should always return `ROWS_MIGHT_MATCH` when `statistics.hasNonNullValue()` is false bacause that means statistics is not reliable; Finally we can safely use min max for comparative evaluation.

Comment (RussellSpitzer) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:612]: I think that sounds good, I was basing this determination off of the code here from Statistics.java in Parquet
```java
  @Override
  public String toString() {
    if (this.hasNonNullValue()) {
      if (isNumNullsSet()) {
        return String.format("min: %s, max: %s, num_nulls: %d", minAsString(), maxAsString(), this.getNumNulls());
      } else {
        return String.format("min: %s, max: %s, num_nulls not defined", minAsString(), maxAsString());
      }
    } else if (!this.isEmpty())
      return String.format("num_nulls: %d, min/max not defined", this.getNumNulls());
    else
      return "no stats for this column";
  }
  ```
  Which similarly checks for the numNulls stat first

Comment (RussellSpitzer) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java]: I simplified this a bit further since I don't think we have to handle the CDH special case in the same way. Now we basically just have a two step check

1) Are all the values null? This is only true if nullCount is set and it is equal to the value count from the chunk stats.

2) We check if min/max are defined for the stats
   a. For normal parquet stats this means that the stats are not empty && hasNonNull is false
   b. For the old CDH version this means the stats are not empty but min and max are set to null. I think the "a" case may also cover this based on my old notes but I figured since this check will be short circuited it doesn't hurt to leave it in.

**Review by zhongyujiang — APPROVED** [review]
Looks great to me, thanks for fixing this!

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java [hunk 2]
```diff
@@ -560,24 +560,26 @@ private <T> T max(Statistics<?> statistics, int id) {
...
    */
-  static boolean hasNonNullButNoMinMax(Statistics statistics, long valueCount) {
-    return statistics.getNumNulls() < valueCount
-        && (statistics.getMaxBytes() == null || statistics.getMinBytes() == null);
+  static boolean nullMinMax(Statistics statistics) {
+    return statistics.getMaxBytes() == null || statistics.getMinBytes() == null;
+  }
+
+  static boolean minMaxUndefined(Statistics statistics) {
+    return (!statistics.isEmpty() && !statistics.hasNonNullValue()) || nullMinMax(statistics);
```
Comment (szehon-ho) [inline parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:578]: So for my understanding its more like other stats are defined but not min/max?  Its not strictly what the method name says, so maybe worth a javadoc?

Also I spent some time to explore this:
```
(!statistics.isEmpty() && !statistics.hasNonNullValue())
```
I noticed statistics.isEmpty() internally is (!statistics.hasNonNullValue() && !isNumNullsSet), so I think after some math it simplifies down then to : 
(stats.isNumNullSet && !stats.hasNonNullValue)

It could be clearer this way, although I guess its safer to use isEmpty if statistitcs.isEmpty definition ever changes.

Comment (RussellSpitzer) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:578]: This is actually a direct reference to the logic in Parquet Statistics.java . I'm doing the same check they do which is "!IsEmpty && !nonNullValue" see

https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/statistics/Statistics.java#L454

Comment (RussellSpitzer) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:582]: I added a comment to explain this, but I want to stick to parquet-mr at the moment. Ideally we would have some well-defined api for this but I don't believe we do.

**Comment by RussellSpitzer** [comment]
Retest this please

**Review by aokolnychyi — APPROVED** [review]
This seems correct to me but it is really unfortunate we inherit this unreliable Parquet logic.

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java (hunk 2 above)
Comment (szehon-ho) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:582]: Sounds good to me, I was just doing a sanity check by exploding the logic (!statistics.hasNonNullValue() && !isNumNullsSet) || !statistics.hasNonNullValue() , and it checks out.  I think I saw your comment of toString() and was not sure if its that reliable as a source of truth.

**Review by szehon-ho — APPROVED** [review]

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java (hunk 2 above)
Comment (rdblue) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:582]: I agree with @szehon-ho's simplification of the logic, and I'm debating whether I prefer that or using `isEmpty`, which is really unclear.

I also think that we may be adding a case to unknown when it is actually known. Since the check becomes `isNumNullSet` and not `hasNonNullValue` because NaN values trigger `hasNonNullValue = false`, are we including cases where `hasNonNullValue` is actually false because the null count is zero? This would be good to make sure tests cover.

Otherwise I think the logic in this PR looks good.

**Review by szehon-ho — APPROVED** [review]

**Comment by RussellSpitzer** [comment]
If no one has any more comments on this PR I'd like to merge it

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java (hunk 2 above)
Comment (rdblue) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java]: Sounds good. It's odd that this is not based on the number of values and number of nulls. Okay though, I guess it's just a strange API.

Comment (RussellSpitzer) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java]: It is quite strange
