### PR TITLE
Core: Write `null` for `current-snapshot-id` for V3+

### LINKED ISSUE #12310: Serialize `null` for `current-snapshot-id` when there is no current snapshot for ≥V3
### Apache Iceberg version

https://lists.apache.org/thread/gqqsnww6nqc50pddwn29blzghmb0m0h3

### Query engine

None

### Please describe the bug 🐞

Actually reinstating https://github.com/apache/iceberg/pull/11560 for 2.0

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by Fokko**
See https://lists.apache.org/thread/gqqsnww6nqc50pddwn29blzghmb0m0h3

Closes #12310

### CODE REVIEW

File: core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java [hunk 1]
```diff
@@ -58,71 +59,73 @@ public void missingFields() {
...
-            .assignUUID(uuid)
-            .setLocation("location")
-            .setCurrentSchema(
-                new Schema(Types.NestedField.required(1, "x", Types.LongType.get())), 1)
-            .addPartitionSpec(PartitionSpec.unpartitioned())
-            .addSortOrder(SortOrder.unsorted())
-            .discardChanges()
-            .withMetadataLocation("metadata-location")
-            .build();
+    for (int formatVersion : Arrays.asList(2, 3)) {
```
Comment (Fokko) [inline core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java:62]: I don't want to run all the tests for each format, let me know if there is a better way to do this.

Comment (nastra) [reply core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java:62]: it's probably good to annotate the test with `@ParameterizedTest` and pass the format version as an argument. This makes it also easier to debug in case it fails with one format version but not with the other

Comment (Fokko) [reply core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java]: Exactly what I was looking for, thanks!

File: core/src/main/java/org/apache/iceberg/TableMetadataParser.java [hunk 2]
```diff
@@ -216,9 +216,15 @@ public static void toJson(TableMetadata metadata, JsonGenerator generator) throw
     // write properties map
     JsonUtil.writeStringMap(PROPERTIES, metadata.properties(), generator);
 
-    generator.writeNumberField(
-        CURRENT_SNAPSHOT_ID,
-        metadata.currentSnapshot() != null ? metadata.currentSnapshot().snapshotId() : -1);
+    if (metadata.currentSnapshot() != null) {
+      generator.writeNumberField(CURRENT_SNAPSHOT_ID, metadata.currentSnapshot().snapshotId());
+    } else {
+      if (metadata.formatVersion() >= 3) {
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/TableMetadataParser.java:222]: I'd prefer we tie this to a constant,

MIN_NULL_CURRENT_SNAPSHOT_VERSION or something like that. I just want to have all of these tweaks in one place so we can see all the behavior changes in a constant list.

**Review by RussellSpitzer — APPROVED** [review]
Minor nit around putting version gating in a constant, lgtm otherwise

File: core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java [hunk 3]
```diff
@@ -56,11 +59,14 @@ public void missingFields() {
         .hasMessage("Cannot parse missing field: metadata");
   }
 
-  @Test
-  public void roundTripSerde() {
+  private static int[] tableVersions = IntStream.range(2, 3).toArray();
+
+  @ParameterizedTest
+  @FieldSource("tableVersions")
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java:65]: having `@ValueSource(ints = {2, 3})` is probably easier here than having to define a separate field for the input params

Comment (Fokko) [reply core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java]: It certainly is, less is more 👍

**Review by nastra — APPROVED** [review]

File: core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java [hunk 4]
```diff
@@ -56,11 +58,12 @@ public void missingFields() {
         .hasMessage("Cannot parse missing field: metadata");
   }
 
-  @Test
-  public void roundTripSerde() {
+  @ParameterizedTest
+  @ValueSource(ints = {2, 3})
```
Comment (RussellSpitzer) [inline core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java:62]: We could just use @FieldSource("org.apache.iceberg.TestHelpers#ALL_VERSIONS")

Comment (RussellSpitzer) [reply core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java:62]: Or if we need to do a range --
```java
  private static int[] supportedInitialDefault =
      IntStream.rangeClosed(DEFAULT_VALUES_MIN_FORMAT_VERSION, MAX_FORMAT_VERSION).toArray();
      `1``
      
      Something like that ^

Comment (Fokko) [reply core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java]: @RussellSpitzer The V1 table format is pretty different. `schema`, `partition-spec` etc are required for V1, where V2+ uses `schemas`, `partitions-specs` etc. If you like I can add it as a separate test.

`DEFAULT_VALUES_MIN_FORMAT_VERSION` is private, but `MAX_FORMAT_VERSION` is a great suggestion 👍

Comment (RussellSpitzer) [reply core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java]: Ah sorry Default Values min format version was just an example, for this test you could probably just use 2 if you think 1 isn't worth testing in this suite.

Comment (Fokko) [reply core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java]: No worries, just explaining why I can't use that one. There is also no other constant available, so I've reinstated just `2`. I've added V1 as well for completeness 👍

File: core/src/main/java/org/apache/iceberg/TableMetadataParser.java (hunk 2 above)
Comment (Fokko) [reply core/src/main/java/org/apache/iceberg/TableMetadataParser.java]: I missed this comment, but I've added it 👍

**Comment by Fokko** [comment]
Moving this forward, thanks @nastra and @RussellSpitzer
