### PR TITLE
Core: Fix circular call in BaseMetastoreCatalog

### LINKED ISSUE #2318: Basemetastore Name StackOverflow
Catalog's default name() calls toString:
https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/catalog/Catalog.java#L44

BaseMetastoreCatalog's toString calls name:
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java#L149

Without overrides, results in:
```
        java.lang.StackOverflowError
            at org.apache.iceberg.BaseMetastoreCatalog.toString(BaseMetastoreCatalog.java:149)
            at org.apache.iceberg.catalog.Catalog.name(Catalog.java:44)
            at org.apache.iceberg.BaseMetastoreCatalog.toString(BaseMetastoreCatalog.java:149)
            at org.apache.iceberg.catalog.Catalog.name(Catalog.java:44)
```

Is this expected?

### PR DESCRIPTION
**Pull request by uncleGen**
fix #2318

### CODE REVIEW

File: api/src/main/java/org/apache/iceberg/catalog/Catalog.java [hunk 1]
```diff
@@ -40,9 +40,7 @@
    *
    * @return this catalog's name
    */
-  default String name() {
-    return toString();
-  }
+  String name();
```
Comment (aokolnychyi) [inline api/src/main/java/org/apache/iceberg/catalog/Catalog.java:43]: This breaks the public API. Is there a way to handle it differently? Can we maybe just drop `name` from the default implementation of `toString` in the base metastore catalog? Or any other option that keeps the old API.

Comment (uncleGen) [reply api/src/main/java/org/apache/iceberg/catalog/Catalog.java:43]: make sense!

**Comment by rdblue** [comment]
Thanks for fixing this, @uncleGen! And thanks for catching the API issue, @aokolnychyi!
