### PR TITLE
API: required nested fields within optional structs can produce null

### LINKED ISSUE #13328: Required fields within optional fields cause incorrect results in Trino
### Apache Iceberg version

1.9.1 (latest release)

### Query engine

Trino

### Please describe the bug 🐞

In Spark, we create a nested struct `address.street`. The outermost field `address` is optional, but the innermost field `street` is required. When querying with trino with condition `address.street is null` with projection pushdown disabled, trino reads the entire file and returns those fields where address is null (and thus `address.street` is null). However, when using projection pushdown, Trino delegates the planning decision to Iceberg and it seems to get no eligible files to read, leading to no rows returned.

I can't find anything in the docs that says what's the right behavior here (as in, does `address.street is null` mean that `address` exists and `address.street` is null or that `address.street` is not set in that row in any way), but agreement between iceberg and Trino is essential. 

Here is the spark-sql commands that I used to create the table
```
spark-sql>  CREATE TABLE default.dejan_test (
  id INT NOT NULL,
  name STRING NOT NULL,
  age INT NOT NULL,
  address STRUCT<street: STRING NOT NULL, address_info: STRUCT<city: STRING NOT NULL, county: STRING NOT NULL, state: STRING NOT NULL>>)
USING iceberg;
spark-sql> INSERT INTO default.dejan_test (id, name, age, address)
VALUES (
  0, 
  'Jane Doe', 
  27, 
  NULL
);
spark-sql> INSERT INTO default.dejan_test (id, name, age, address)
VALUES (
  1, 
  'John Doe', 
  30, 
  STRUCT(
    '123 Main St',
    STRUCT('San Francisco', 'San Francisco County', 'California')
  )
);
```

Here are the two different results we get from Trino:
```
trino> 
set session iceberg.projection_pushdown_enabled=false;
SET SESSION
trino> 
select
  id
from
  iceberg.default.dejan_test
where
  address.street is null;
 id 
----
  0 
(1 row)

Query 20250613_033713_00001_xn59q, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
2.85 [2 rows, 4.43KiB] [0 rows/s, 1.56KiB/s]


trino> 
set session iceberg.projection_pushdown_enabled=true;
SET SESSION
trino> 
select
  id
from
  iceberg.default.dejan_test
where
  address.street is null;
 id 
----
(0 rows)

Query 20250613_034027_00008_xn59q, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.36 [0 rows, 0B] [0 rows/s, 0B/s]
```

Full issue and reproduction steps can be found here: https://github.com/trinodb/trino/issues/20511#issuecomment-2968932230

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [x] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by dejangvozdenac**
producesNull check is used when binding isNull and notNull predicate. Currently, the logic states that a field can produce null if and only if that field is optional. This is not true, however, in the case of required fields nested within optional structs. The field itself can produce nulls if the parent struct is null despite it being required.

I'm able to reproduce this case in Trino and Spark by creating the following schema and adding rows to it:
```
spark-sql>  CREATE TABLE default.dejan_test (
  id INT NOT NULL,
  name STRING NOT NULL,
  age INT NOT NULL,
  address STRUCT<street: STRING NOT NULL, address_info: STRUCT<city: STRING NOT NULL, county: STRING NOT NULL, state: STRING NOT NULL>>)
USING iceberg;
spark-sql> INSERT INTO default.dejan_test (id, name, age, address)
VALUES (
  0, 
  'Jane Doe', 
  27, 
  NULL
);
spark-sql> INSERT INTO default.dejan_test (id, name, age, address)
VALUES (
  1, 
  'John Doe', 
  30, 
  STRUCT(
    '123 Main St',
    STRUCT('San Francisco', 'San Francisco County', 'California')
  )
);
```
address.street is null for row 0, but trino/spark using iceberg api disagree:
```
trino> 
set session iceberg.projection_pushdown_enabled=true;
SET SESSION
trino> 
select
  id
from
  iceberg.default.dejan_test
where
  address.street is null;
 id 
----
(0 rows)

Query 20250613_034027_00008_xn59q, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.36 [0 rows, 0B] [0 rows/s, 0B/s]
```

You can see that when Trino reads the entire file, it correctly determines the row:
```
trino> 
set session iceberg.projection_pushdown_enabled=false;
SET SESSION
trino> 
select
  id
from
  iceberg.default.dejan_test
where
  address.street is null;
 id 
----
  0 
(1 row)

Query 20250613_033713_00001_xn59q, FINISHED, 1 node
Splits: 2 total, 2 done (100.00%)
2.85 [2 rows, 4.43KiB] [0 rows/s, 1.56KiB/s]
```

This also leads to unexpected behavior where null or not null check behaves differently based on the binding order:
```
spark-sql (default)> select
                   >   count(*)
                   > from
                   >   default.dejan_test;
2

spark-sql (default)> select
                   >   count(*)
                   > from
                   >   default.dejan_test
                   > where
                   >   address.street is null or address.street is not null;
2


spark-sql (default)> select
                   >   count(*)
                   > from
                   >   default.dejan_test
                   > where
                   >   address.street is not null;
1

spark-sql (default)> select
                   >   count(*)
                   > from
                   >   default.dejan_test
                   > where
                   >   address.street is null;
0
```

After this change, iceberg can find the null row:
```
trino> 
set session iceberg.projection_pushdown_enabled=true;
SET SESSION
trino> 
select
  id
from
  iceberg.default.dejan_test
where
  address.street is null;
 id 
----
  0 
(1 row)

Query 20250813_413537_00001_qn1a9, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
2.15 [1 rows, 2.03KiB] [0 rows/s, 969B/s]
```

Closes #13328 (and relatedly https://github.com/trinodb/trino/issues/20511)

### CODE REVIEW

**Comment by stevenzwu** [comment]
@dejangvozdenac thanks for reporting and fixing the issue. I agree that `my_struct.nested_field` should be evaluated to null if `my_struct` is null.

can you add unit test in Spark module to cover the scenario you described?

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+  }
+
+  @Test
+  public void testRequiredLeafNoOptionalAncestors() {
+    // schema: requiredAncestor -> requiredLeaf
+    Schema schema =
+        new Schema(
+            required(
+                1,
+                "requiredAncestor",
```
Comment (stevenzwu) [inline api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java]: nit: SQL field names should be snake case (not camel case)

File: api/src/main/java/org/apache/iceberg/Accessors.java [hunk 2]
```diff
@@ -59,11 +59,13 @@ private static class PositionAccessor implements Accessor<StructLike> {
     private final int position;
     private final Type type;
     private final Class<?> javaClass;
+    private final boolean hasOptionalFieldInPath;
 
-    PositionAccessor(int pos, Type type) {
+    PositionAccessor(int pos, boolean isOptional, Type type) {
```
Comment (stevenzwu) [inline api/src/main/java/org/apache/iceberg/Accessors.java]: nit: add new arg in the end for consistency as your other changes

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+  }
+
+  @Test
+  public void testRequiredLeafWithOptionalIntermediateAncestor() {
+    // schema: requiredRoot -> optionalIntermediate -> requiredIntermediate -> requiredLeaf
+    Schema schema =
+        new Schema(
+            required(
+                1,
+                "requiredRoot",
```
Comment (stevenzwu) [inline api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java]: nit: following the style from `TestAccessors`, can we call the struct field name as s1, s2, s3 etc. where the number indicates the nested level? for optional, maybe name it as `s2_optional`.

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+import static org.apache.iceberg.types.Types.NestedField.required;
+import static org.assertj.core.api.Assertions.assertThat;
+
+import org.apache.iceberg.Accessor;
+import org.apache.iceberg.Schema;
+import org.apache.iceberg.StructLike;
+import org.apache.iceberg.types.Types;
+import org.junit.jupiter.api.Test;
+
+public class TestBoundReferenceProducesNull {
```
Comment (stevenzwu) [inline api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java]: nit: call it `TestBoundedReference`?

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java [hunk 5]
```diff
@@ -0,0 +1,131 @@
...
+                                Types.StructType.of(
+                                    required(4, "requiredLeaf", Types.IntegerType.get()))))))));
+
+    Types.NestedField requiredLeafField = schema.findField(4);
+    Accessor<StructLike> accessor = schema.accessorForField(4);
+
+    BoundReference<Integer> ref = new BoundReference<>(requiredLeafField, accessor, "requiredLeaf");
+    assertThat(ref.producesNull()).isTrue();
+  }
+}
```
Comment (stevenzwu) [inline api/src/test/java/org/apache/iceberg/expressions/TestBoundReferenceProducesNull.java]: let's also add a test with 4 nested level. see `TestAccessors.nested4` so that `WrapperPositionAccessor` is also covered.

File: api/src/main/java/org/apache/iceberg/expressions/BoundReference.java [hunk 6]
```diff
@@ -57,7 +57,9 @@ public Type type() {
 
   @Override
   public boolean producesNull() {
-    return field.isOptional();
+    // A leaf required field can evaluate to null if it is optional itself or any
+    // ancestor on the path is optional.
+    return field.isOptional() || accessor.hasOptionalFieldInPath();
```
Comment (stevenzwu) [inline api/src/main/java/org/apache/iceberg/expressions/BoundReference.java]: `field.isOptional()` is not needed anymore? it should be already covered by the `accessor.hasOptionalFieldInPath()`?

File: .palantir/revapi.yml [hunk 7]
```diff
@@ -1254,6 +1254,10 @@ acceptedBreaks:
       new: "method void org.apache.iceberg.data.parquet.BaseParquetWriter<T>::<init>()"
       justification: "Changing deprecated code"
   "1.9.0":
+    org.apache.iceberg:iceberg-api:
+    - code: "java.method.addedToInterface"
+      new: "method boolean org.apache.iceberg.Accessor<T>::hasOptionalFieldInPath()"
+      justification: "All subclasses implement name"
```
Comment (stevenzwu) [inline .palantir/revapi.yml]: nit: copy and paste error on `name`. maybe just `All subclasses implement the new method`?

File: parquet/src/test/java/org/apache/iceberg/parquet/TestBloomRowGroupFilter.java [hunk 8]
```diff
@@ -322,9 +320,7 @@ public void testIsNull() {
     shouldRead =
         new ParquetBloomRowGroupFilter(SCHEMA, isNull("struct_not_null.int_field"))
             .shouldRead(parquetSchema, rowGroupMetadata, bloomStore);
-    assertThat(shouldRead)
-        .as("Should skip: this field is required and are always not-null")
-        .isFalse();
+    assertThat(shouldRead).as("Should read: bloom filter doesn't help").isTrue();
```
Comment (stevenzwu) [inline parquet/src/test/java/org/apache/iceberg/parquet/TestBloomRowGroupFilter.java]: nit: maybe add a comment line that explains the scenario of required nested field inside an optional struct can still be evaluated to null.

**Comment by dejangvozdenac** [comment]
thanks for the review @stevenzwu, I appreciate it! I addressed all the comments, let me know if anything further is needed.

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java [hunk 9]
```diff
@@ -578,6 +578,28 @@ public void testFilterPushdownWithSpecialFloatingPointPartitionValues() {
...
+        "CREATE TABLE %s (id INT NOT NULL, address STRUCT<street: STRING NOT NULL>)"
+            + "USING iceberg ",
+        tableName);
+    configurePlanningMode(planningMode);
+
+    sql("INSERT INTO %s VALUES (0, NULL)", tableName);
+    sql("INSERT INTO %s VALUES (1, STRUCT('123 Main St'))", tableName);
+
+    checkOnlyIcebergFilters(
+        "address is null" /* query predicate */,
```
Comment (stevenzwu) [inline spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java]: we should also test predicate on nested field, right? that is what this PR tries to fix.
```
address.street is null
```

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java [hunk 10]
```diff
@@ -0,0 +1,151 @@
...
+import static org.apache.iceberg.types.Types.NestedField.required;
+import static org.assertj.core.api.Assertions.assertThat;
+
+import org.apache.iceberg.Accessor;
+import org.apache.iceberg.Schema;
+import org.apache.iceberg.StructLike;
+import org.apache.iceberg.types.Types;
+import org.junit.jupiter.api.Test;
+
+public class TestBoundReference {
```
Comment (stevenzwu) [inline api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java:37]: this test should probably cover these two dimensions
1) nest level: 1, 2, 3, 4
2) with or without optional struct in the path. this can potentially be parametrized. e.g. just a boolean parameter, which can be used to set one ancestor struct to optional or required.

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java (hunk 9 above)
Comment (dejangvozdenac) [reply spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java]: ah shoot that's what I wanted to use. fixed.

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java (hunk 10 above)
Comment (dejangvozdenac) [reply api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java:37]: parameterized! I wanted to test a few more cases (such as multiple optionals, optionals not being at the very root of the chain). let me know if that's an overkill and I can implement (nest_level, all_required) parameterization.

Comment (stevenzwu) [reply api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java:37]: I like the new structure. more concise and cover different scenarios.

**Comment by dejangvozdenac** [comment]
> LGTM. We will need 2 or 3 more committers' approval, since this modifies critical api code.

awesome, thanks for the quick review @stevenzwu. what's the usually process here? should I tag 2-3 people in who have reviewed code under api or do you have suggestions?

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java [hunk 11]
```diff
@@ -578,6 +578,28 @@ public void testFilterPushdownWithSpecialFloatingPointPartitionValues() {
         ImmutableList.of(row(4, Double.NEGATIVE_INFINITY)));
   }
 
+  @TestTemplate
+  public void testFilterPushdownWithRequiredNestedFieldInOptionalStruct() {
```
Comment (huaxingao) [inline spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java]: nit: Probably we don’t want to add this test to `TestFilterPushDown`, since that suite is mainly for verifying whether filters are pushed down. In your case, the filter `address.street is null` is already pushed down—the issue is that it returns the wrong value (incorrectly false). I think it's probably better to place the test in another suite, for example, `TestSelect`.

Comment (dejangvozdenac) [reply spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java]: agreed! done!

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java [hunk 12]
```diff
@@ -613,4 +613,21 @@ public void testComplexTypeFilter() {
     assertEquals("Should return all expected rows", ImmutableList.of(row(1)), result);
     sql("DROP TABLE IF EXISTS %s", complexTypeTableName);
   }
+
+  @TestTemplate
+  public void testRequiredNestedFieldInOptionalStructFilter() {
+    String nestedStructTable = tableName("nested_struct_table");
+    sql(
+        "CREATE TABLE %s (id INT NOT NULL, address STRUCT<street: STRING NOT NULL>)"
```
Comment (huaxingao) [inline spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java]: nit: add an empty space in the end?

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java [hunk 13]
```diff
@@ -613,4 +613,21 @@ public void testComplexTypeFilter() {
...
+            + "USING iceberg ",
```
Comment (huaxingao) [inline spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java]: nit: remove the empty space from the end?

**Review by huaxingao — APPROVED** [review]

**Comment by dejangvozdenac** [comment]
@singhpk234 @pvary @nastra do you mind taking a look? I see you're familiar with this part of the code and @stevenzwu mentioned we need more reviews.

File: .palantir/revapi.yml [hunk 14]
```diff
@@ -1254,6 +1254,10 @@ acceptedBreaks:
       new: "method void org.apache.iceberg.data.parquet.BaseParquetWriter<T>::<init>()"
       justification: "Changing deprecated code"
   "1.9.0":
+    org.apache.iceberg:iceberg-api:
```
Comment (nastra) [inline .palantir/revapi.yml]: we shouldn't be breaking the API when introducing new methods (see also https://iceberg.apache.org/contribute/#adding-new-functionality-without-breaking-apis). Please add a default impl to the method and remove the API breakage exception from this file

File: api/src/main/java/org/apache/iceberg/Accessor.java [hunk 15]
```diff
@@ -25,4 +25,7 @@ public interface Accessor<T> extends Serializable {
   Object get(T container);
 
   Type type();
+
+  /** Returns true if the current field or any ancestor in the access path is optional. */
+  boolean hasOptionalFieldInPath();
```
Comment (nastra) [inline api/src/main/java/org/apache/iceberg/Accessor.java]:
```suggestion
  default boolean hasOptionalFieldInPath() { return false; }
```

this will avoid breaking the API and you'll be able to revert the revapi changes

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java [hunk 16]
```diff
@@ -0,0 +1,103 @@
...
+import org.junit.jupiter.params.provider.MethodSource;
+
+public class TestBoundReference {
+  // Build a schema with a single nested struct with optionalList.size() levels with the following
+  // structure:
+  // s1: struct(s2: struct(s3: struct(..., sn: struct(leaf: int))))
+  // where each s{i} is an optional struct if optionalList.get(i) is true and a required struct if
+  // false
+  private static Schema buildSchemaFromOptionalList(List<Boolean> optionalList, String leafName) {
+    if (optionalList == null || optionalList.isEmpty()) {
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java]: nit: you could also use `Preconditions.checkArgument` here, which would be shorter

File: api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java [hunk 17]
```diff
@@ -0,0 +1,103 @@
...
+              optionalList.get(i) ? optional(id, name, current) : required(id, name, current));
+    }
+
+    return new Schema(current.fields());
+  }
+
+  private static Stream<Arguments> producesNullCases() {
+    return Stream.of(
+        // basic fields, no struct levels
+        Arguments.of(Arrays.asList(false), false),
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/expressions/TestBoundReference.java:73]: can you please add a short comment that indicates what false/true means in the arguments?

File: api/src/main/java/org/apache/iceberg/Accessors.java [hunk 18]
```diff
@@ -117,6 +126,11 @@ public Class<?> javaClass() {
       return javaClass;
     }
 
+    @Override
+    public boolean hasOptionalFieldInPath() {
```
Comment (pvary) [inline api/src/main/java/org/apache/iceberg/Accessors.java:130]: Should we add some test for this in the API module?

Comment (pvary) [reply api/src/main/java/org/apache/iceberg/Accessors.java:130]: Ok, I have found them

File: .palantir/revapi.yml (hunk 14 above)
Comment (dejangvozdenac) [reply .palantir/revapi.yml]: makes sense! done

**Comment by dejangvozdenac** [comment]
Thanks for the reviews @nastra / @pvary , the comments should all be addressed.

**Comment by dejangvozdenac** [comment]
Hey @pvary , mind taking a look? @stevenzwu mentioned we need at least 3 reviewers on this.

**Comment by dejangvozdenac** [comment]
Sorry wrong tag, meant to tag @nastra

**Comment by dejangvozdenac** [comment]
@nastra might be busy. @pvary or @singhpk234 mind taking a look?

**Comment by dejangvozdenac** [comment]
@stevenzwu we have three approvals now, would this be ready to merge?

**Comment by dejangvozdenac** [comment]
hey @stevenzwu @pvary @nastra @huaxingao , gentle ping on this

**Comment by stevenzwu** [comment]
@nastra you want to take another look before we merge this?

**Comment by ebyhr** [comment]
@dejangvozdenac Thank you for fixing this issue! I've verified that this change resolves the correctness issue in Trino. A regression test is included in https://github.com/trinodb/trino/pull/26640.
