### PR TITLE
Core: Disallow creation of invalid PartitionSpec

### LINKED ISSUE #12870: Disallow creation of invalid PartitionSpec
### Bug

The specification says in relationship to [partitioning](https://iceberg.apache.org/spec/#partitioning):

>  The source columns, selected by ids, must be a primitive type and cannot be contained in a map or list, but may be nested in a struct.

The java implementation provides the necessary safety checks around the "primitive type" part of this statement, but does not provide safety checks for the "contained in a map or list" part.

```java
final Schema schema =
    new Schema(
        NestedField.required(
            2, "MyList", Types.ListType.ofRequired(1, Types.IntegerType.get())));
// Does not currently fail, but ideally should
PartitionSpec.builderFor(schema).identity("MyList.element").build();
```

I've got a branch with changes to [TestPartitionSpecValidation.java](https://github.com/apache/iceberg/compare/main...devinrsmith:iceberg:partition-spec-leniency-example#diff-a101be1d61ec7b3b95b6b2925b42d9ef0c77aa97c27a881eb5e9f39086bfa388) that further demonstrates the current behavior.

### Query engine

None

### Willingness to contribute

- [x] I can contribute this improvement/feature independently
- [ ] I would be willing to contribute this improvement/feature with guidance from the Iceberg community
- [ ] I cannot contribute this improvement/feature at this time

### PR DESCRIPTION
**Pull request by devinrsmith**
Closes #12870

### CODE REVIEW

File: api/src/main/java/org/apache/iceberg/PartitionSpec.java [hunk 1]
```diff
@@ -644,6 +646,16 @@ static void checkCompatibility(PartitionSpec spec, Schema schema) {
...
+        // The only valid parent types for a PartitionField are StructTypes. This must be checked
+        // recursively.
+        int fieldId = field.sourceId();
+        Integer parentId;
+        while ((parentId = parents.get(fieldId)) != null) {
+          Type parentType = schema.findType(parentId);
+          ValidationException.check(
+              parentType.isStructType(), "Invalid partition field parent: %s", parentType);
+          fieldId = parentId;
+        }
```
Comment (Fokko) [inline api/src/main/java/org/apache/iceberg/PartitionSpec.java:658]: Nit, I think this is easier to read:
```suggestion
        Integer parentId = parents.get(fieldId);
        while (parentId != null) {
          Type parentType = schema.findType(parentId);
          ValidationException.check(
              parentType.isStructType(), "Invalid partition field parent: %s", parentType);
          parentId =  parents.get(parentId);
        }
```

**Review by Fokko — APPROVED** [review]
Thanks @devinrsmith for cleaning this up 👍

**Comment by devinrsmith** [comment]
@Fokko, not sure what the process is to get this merged in.

**Review by singhpk234 — APPROVED** [review]
LGTM as well !
