### PR TITLE
Test: Verify variant logical type annotation of Parquet writer

### LINKED ISSUE #13498: [Parquet][Variant] The Parquet writer should set the `VARIANT` `logicalType` on the produced parquet files.
### Apache Iceberg version

1.9.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

As defined by the [VariantEncoding](https://github.com/apache/parquet-format/blob/master/VariantEncoding.md) spec, the top-level Variant group should be annotated with the `VARIANT` logical type.
> The Variant group must be annotated with the VARIANT logical type.

Currently the Variant group is identified using the iceberg type, because it isn't written with a `LogicalTypeAnnotation` attached:
```java
    } else {
      // if not a primitive, the typeId must be a group
      GroupType group = type.asGroupType();
      LogicalTypeAnnotation annotation = group.getLogicalTypeAnnotation();
      if (annotation instanceof ListLogicalTypeAnnotation) {
        return visitList(iType, group, visitor);
      } else if (annotation instanceof MapLogicalTypeAnnotation) {
        return visitMap(iType, group, visitor);
      } else if (iType != null && iType.isVariantType()) {
        // when Parquet has a VARIANT logical type, use it here
        return visitVariant(iType.asVariantType(), group, visitor);
      }
```

Parquet has a VARIANT logical type, it was introduced in this PR:
https://github.com/apache/parquet-format/pull/460

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [x] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by ebyhr**
Follow-up of #13941

Closes #13498

### CODE REVIEW

**Comment by huaxingao** [comment]
cc @aihuaxu

File: parquet/src/test/java/org/apache/iceberg/parquet/TestVariantWriters.java [hunk 1]
```diff
@@ -248,6 +251,18 @@ private static List<Record> writeAndRead(
...
 
+    try (ParquetFileReader reader =
+        ParquetFileReader.open(ParquetIO.file(outputFile.toInputFile()))) {
+      MessageType schema = reader.getFileMetaData().getSchema();
+      for (Types.NestedField column : SCHEMA.columns()) {
+        if (column.type() == Types.VariantType.get()) {
+          int fieldIndex = schema.getFieldIndex(column.name());
+          assertThat(schema.getFields().get(fieldIndex).getLogicalTypeAnnotation())
+              .isEqualTo(LogicalTypeAnnotation.variantType(Variant.VARIANT_SPEC_VERSION));
+        }
```
Comment (singhpk234) [inline parquet/src/test/java/org/apache/iceberg/parquet/TestVariantWriters.java:262]: nit:
can we club this read with the read below ?

Comment (ebyhr) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestVariantWriters.java:262]: Maybe no? The subsequent `Parquet` reader doesn't expose logical type annotations.

I assume we intentionally use `Parquet.read` instead of the low-level `ParquetFileReader` because it's the primary API intended for third-party developers.

**Comment by ebyhr** [comment]
@huaxingao @singhpk234 Gentle reminder.

**Comment by ebyhr** [comment]
@huaxingao @singhpk234  Can we merge this PR?

**Comment by huaxingao** [comment]
Thanks @ebyhr for the PR! Thanks @aihuaxu @singhpk234 for the review!
