### PR TITLE
Fix IndexOutOfBounds exception in FileFormat#fromFileName

### LINKED ISSUE #12300: IndexOutOfBounds in FileFormat#fromFileName
### Apache Iceberg version

1.8.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

`FileFormat#fromFileName` doesn't account for short file names [here](https://github.com/apache/iceberg/blob/bcbbd0344623ffea5b092e2de5debb0bc12892a1/api/src/main/java/org/apache/iceberg/FileFormat.java#L64). When a file name is shorter than the longest file format extension (`metadata.json`), we get an error like this one:
```
begin -6, end 8, length 8
java.lang.StringIndexOutOfBoundsException: begin -6, end 8, length 8
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at java.base/java.lang.String.subSequence(String.java:2745)
	at org.apache.iceberg.FileFormat.fromFileName(FileFormat.java:64)
	at org.apache.iceberg.FileFormatTest.fromFileName(FileFormatTest.java:40)
```

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by rshkv**
Closes #12300.

`FileFormat#fromFileName` should account for file names that are shorter than a file format extension.

### CODE REVIEW

File: api/src/test/java/org/apache/iceberg/FileFormatTest.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+        arguments("dir/file.csv", null),
+        // No format
+        arguments("file", null),
+        arguments("dir", null),
+        // File names match format names but no extension
+        arguments("puffin", null),
+        arguments("orc", null),
+        arguments("parquet", null),
+        arguments("avro", null),
+        arguments("metadata.json", null));
```
Comment (RussellSpitzer) [inline api/src/test/java/org/apache/iceberg/FileFormatTest.java:63]: We are a bit confusing by considering this a "no extension" but I understand.

File: api/src/test/java/org/apache/iceberg/FileFormatTest.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+import java.util.stream.Stream;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.Arguments;
+import org.junit.jupiter.params.provider.MethodSource;
+
+class FileFormatTest {
+
+  @ParameterizedTest
+  @MethodSource
```
Comment (RussellSpitzer) [inline api/src/test/java/org/apache/iceberg/FileFormatTest.java:32]: I have a slight preference for FieldSource here because we don't actually need to dynamically create this.

@FieldSource("...")

Also we previously established in some other files that we wouldn't use implicit sources for tests and wanted to name them explicitly (even if it was the same as the implicit name). cc: @nastra

File: api/src/main/java/org/apache/iceberg/FileFormat.java [hunk 3]
```diff
@@ -60,9 +60,10 @@ public String addExtension(String filename) {
   public static FileFormat fromFileName(CharSequence filename) {
     for (FileFormat format : VALUES) {
       int extStart = filename.length() - format.ext.length();
-      if (Comparators.charSequences()
-              .compare(format.ext, filename.subSequence(extStart, filename.length()))
-          == 0) {
+      if (extStart > 0
```
Comment (RussellSpitzer) [inline api/src/main/java/org/apache/iceberg/FileFormat.java:63]: Do we want to fail if the file name is just an extension? I think this is a reasonable choice because the only weird case I can imagine is setting your file name to metadata.json. All the other extensions are pretty much useless without another part to the name.

**Review by RussellSpitzer — APPROVED** [review]
Looks good to me, left a tiny nit on the test

File: api/src/test/java/org/apache/iceberg/FileFormatTest.java (hunk 2 above)
Comment (rshkv) [reply api/src/test/java/org/apache/iceberg/FileFormatTest.java]: Updated: [574c40f](https://github.com/apache/iceberg/pull/12301/commits/574c40fa3cd939bfb63f55287ebf65a664d8f591)

File: api/src/main/java/org/apache/iceberg/FileFormat.java (hunk 3 above)
Comment (rshkv) [reply api/src/main/java/org/apache/iceberg/FileFormat.java:63]: Yeah, let's follow the common definition of an extension being "the bit after the last dot" (e.g., [commons-io](https://github.com/apache/commons-io/blob/4988e4b0697f6b6bdead3f3465c1e3c16fe2e33f/src/main/java/org/apache/commons/io/FilenameUtils.java#L629-L630)).

I think my test cases with `parquet` as filename were silly. Removed those

File: api/src/test/java/org/apache/iceberg/FileFormatTest.java [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+
+  @ParameterizedTest
+  @FieldSource("FILE_NAMES")
+  void fromFileName(String fileName, FileFormat expected) {
+    FileFormat actual = FileFormat.fromFileName(fileName);
+
+    assertThat(actual).isEqualTo(expected);
+  }
+
+  static Stream<Arguments> fromFileName() {
```
Comment (ebyhr) [inline api/src/test/java/org/apache/iceberg/FileFormatTest.java:60]: Why do we need both `FILE_NAMES` constant and this method?

File: api/src/test/java/org/apache/iceberg/FileFormatTest.java [hunk 5]
```diff
@@ -0,0 +1,86 @@
...
+
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.junit.jupiter.params.provider.Arguments.arguments;
+
+import java.util.stream.Stream;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.Arguments;
+import org.junit.jupiter.params.provider.FieldSource;
+
+class FileFormatTest {
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/FileFormatTest.java:29]:
```suggestion
class TestFileFormat {
```

File: api/src/test/java/org/apache/iceberg/TestFileFormat.java [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.FieldSource;
+
+class TestFileFormat {
+
+  private static final Object[][] FILE_NAMES =
+      new Object[][] {
+        // Files with format
+        {"file.puffin", FileFormat.PUFFIN},
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/TestFileFormat.java:31]: https://github.com/apache/iceberg/issues/12300 mentions that there's an issue with file names where the prefix is shorter than the file format suffix, but those things aren't tested here. The params should be updated to include `x.puffin` / `x.orc` / `x.parquet` / `x.avro` to cover that

File: api/src/test/java/org/apache/iceberg/TestFileFormat.java [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+        {"file.avro", FileFormat.AVRO},
+        {"dir/file.avro", FileFormat.AVRO},
+        {"v1.metadata.json", FileFormat.METADATA},
+        {"dir/v1.metadata.json", FileFormat.METADATA},
+        // Unsupported formats
+        {"file.csv", null},
+        {"dir/file.csv", null},
+        // No format
+        {"file", null},
+        {"dir", null},
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/TestFileFormat.java:46]: we should also test where the filename is `null` or an empty string

File: api/src/main/java/org/apache/iceberg/FileFormat.java (hunk 3 above)
Comment (RussellSpitzer) [reply api/src/main/java/org/apache/iceberg/FileFormat.java:63]: I think if we did that we should just make a new version of the method, I don't think it's great to change the underlying perf semantics of the method in the API module. If it takes CharSequence we shouldn't change it to a string.

File: api/src/test/java/org/apache/iceberg/TestFileFormat.java (hunk 6 above)
Comment (RussellSpitzer) [reply api/src/test/java/org/apache/iceberg/TestFileFormat.java:31]: @nastra our longest "extension" is `metadata.json` so a lot of these are too short for that :)

**Comment by pvary** [comment]
I understand that this PR is just a fix for an existing method, but I have concerns about the original intention of the method. We are relying on the filename to deduce the actual file format. This seems brittle to me. For example many of our test are generating parquet files without extensions.

I have faced a similar issue here: https://github.com/apache/iceberg/pull/11216#discussion_r1939040414

The Iceberg specification have a `file_format` field for data files specifying the actual file format. Shouldn't we rely on these fields instead of trying to find out the format from the location of the file? If we want to allow metadata files to use different file formats, we might want to add a file_format field to the metadata descriptors too.

**Comment by rshkv** [comment]
> I understand that this PR is just a fix for an existing method, but I have concerns about the original intention of the method. We are relying on the filename to deduce the actual file format. This seems brittle to me. For example many of our test are generating parquet files without extensions.

Yeah, I guess there's an argument to not use this method when you can rely on a better source for the file type. For what it's worth, we use `FileFormat#fromFileName` in remote signing where we just have the URL.

**Comment by pvary** [comment]
> Yeah, I guess there's an argument to not use this method when you can rely on a better source for the file type. For what it's worth, we use `FileFormat#fromFileName` in remote signing where we just have the URL.

Why do you need the file format to sign an URL?

**Comment by rshkv** [comment]
> Why do you need the file format to sign an URL?

I think that doesn't quite matter for this PR. But it helps us make granular access decisions based on file type (e.g., treating metadata differently than data files). We could obviously get the extension without this. But we appreciate there's some utility that extracts "Iceberg types".

**Comment by rshkv** [comment]
@nastra let's merge?

File: api/src/test/java/org/apache/iceberg/TestFileFormat.java [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+package org.apache.iceberg;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.FieldSource;
+
+class TestFileFormat {
+
+  private static final Object[][] FILE_NAMES =
```
Comment (nastra) [inline api/src/test/java/org/apache/iceberg/TestFileFormat.java:28]: can you please add `@SuppressWarnings("unused")` right above this line

File: api/src/test/java/org/apache/iceberg/TestFileFormat.java (hunk 6 above)
Comment (nastra) [reply api/src/test/java/org/apache/iceberg/TestFileFormat.java:31]: > Can you double-check? I've undone the fix locally and get these test failures, all with out-of-bounds indexes:
> 
> Screenshot 2025-02-18 at 18 00 49
> E.g., for the `file.csv` case:
> 
> * It goes through the list of file formats in enum order, the last is `metadata.json` with 13 characters
> * From length of `file.csv` (8 characters), subtract 13 characters for `.metadata.json` and 1 for the dot
> * Your start index is -6 and you get an `IndexOutOfBoundsException`

Yes I'm aware of that. My point is that we should just add some test cases where we're expecting a valid `FileFormat` to show that the same issue happens e.g. with `x.orc` too and not just unsupported file formats like csv. 

@rshkv can you please add 
```
        {"x.parquet", FileFormat.PARQUET},
        {"x.puffin", FileFormat.PUFFIN},
        {"x.orc", FileFormat.ORC},
        {"x.avro", FileFormat.AVRO},
```
in the right order to the argument list?

Comment (rshkv) [reply api/src/test/java/org/apache/iceberg/TestFileFormat.java:32]: Ah, I get you now. We'd hit out of bounds if `x.avro` was compared against `.parquet` which happens because `PARQUET` is before the `AVRO` enum value.

Updated

**Review by nastra — APPROVED** [review]
