### PR TITLE
Core: Add validation for table commit properties

### LINKED ISSUE #11435: Bad Table Properties cause commit failure
### Apache Iceberg version

1.6.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Today iceberg does not validate the type of table properties values on and this can be problematic if those table properties value are used for commit. 

Example setup
```
                sql(
                    "CREATE TABLE foo.bar "
                        + "(id BIGINT NOT NULL, data STRING) "
                        + "USING iceberg "
                        + "TBLPROPERTIES ('commit.retry.num-retries'='x', p2='x')",
```

See the value for `commit.retry.num-retries` is accidentally set to some non-integer value, we will unable to rectify this through either spark SQL or iceberg API 

```
table.updateProperties.remove("commit.retry.max-wait-ms").apply.commit

table.updateProperties.remove("commit.retry.max-wait-ms").commit
java.lang.NumberFormatException: For input string: "commit.retry.max-wait-ms"
  at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
  at java.base/java.lang.Integer.parseInt(Integer.java:668)
  at java.base/java.lang.Integer.parseInt(Integer.java:786)
  at org.apache.iceberg.util.PropertyUtil.propertyAsInt(PropertyUtil.java:64)
  at org.apache.iceberg.TableMetadata.propertyAsInt(TableMetadata.java:472)
  at org.apache.iceberg.PropertiesUpdate.commit(PropertiesUpdate.java:105)
  ... 48 elided
```

After some look, I believe this block of code might be the problem: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/PropertiesUpdate.java#L100-L114, where  propertyAsInt will throw NumberFormatException before commit can proceed to rectify or remove incorrectly set table properties. 

Current workaround is move back to previous table metadata before the table properties change, but I plan to contribute the patch to fix the problem in 2 ways
1. add validation for new table where commit related table properties need to have value type checked (as integer)
2. relax the condition in `PropertiesUpdate` class to allow update when existing value is corrupted, this help with existing table to move forward. 

### Willingness to contribute

- [X] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by dramaticlly**
close #11435 

Total of 2 Changes proposed here

1. Add validation for creating new table where commit related table properties need to have value type checked (as integer) and value is non-negative. This apply to following 4 table properties as those are common set of properties to be used on commit for metadata changes
    1. commit.retry.num-retries
    1. commit.retry.min-wait-ms
    1. commit.retry.max-wait-ms
    1. commit.retry.total-timeout-ms
1. Relax the constrain of [PendingUpdate](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/PropertiesUpdate.java#L100-L114) so that existing table with such corrupted table properties can proceed with correction (see example below)

    - ~~achieved by using [NumberUtils::toInt](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/math/NumberUtils.html#toInt(java.lang.String,int)) where return the default value if the conversion fails.~~

This allow for 
```java
// some mistake at first
table
    .updateProperties()
    .set(TableProperties.COMMIT_MAX_RETRY_WAIT_MS, "foo")
    .commit();
// fail before, pass after
table.updateProperties().remove(TableProperties.COMMIT_MAX_RETRY_WAIT_MS).commit();
```

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/TableProperties.java [hunk 1]
```diff
@@ -95,6 +95,13 @@ private TableProperties() {}
   public static final String COMMIT_TOTAL_RETRY_TIME_MS = "commit.retry.total-timeout-ms";
   public static final int COMMIT_TOTAL_RETRY_TIME_MS_DEFAULT = 30 * 60 * 1000; // 30 minutes
 
+  public static final Set<String> COMMIT_PROPERTIES =
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/TableProperties.java:98]: No need for public?

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java [hunk 2]
```diff
@@ -100,6 +102,30 @@ public static String propertyAsString(
     return defaultValue;
   }
 
+  /**
+   * Validate the table commit related properties to have non-negative integer on table creation to
+   * prevent commit failure
+   *
+   * @param properties input map
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/util/PropertyUtil.java:109]: nit: more descriptive param doc , like key-value map of properties, or just remove this ?

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java [hunk 3]
```diff
@@ -100,6 +102,30 @@ public static String propertyAsString(
...
+   */
+  public static void validateCommitProperties(Map<String, String> properties) {
+    for (String commitProperty : TableProperties.COMMIT_PROPERTIES) {
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/util/PropertyUtil.java:112]: entirely stylistic, will stream, filter be cleaner?

File: core/src/main/java/org/apache/iceberg/TableMetadata.java [hunk 4]
```diff
@@ -486,6 +489,10 @@ public int propertyAsInt(String property, int defaultValue) {
     return PropertyUtil.propertyAsInt(properties, property, defaultValue);
   }
 
+  public int propertyTryAsInt(String property, int defaultValue) {
+    return NumberUtils.toInt(property, defaultValue);
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/TableMetadata.java:493]: Looks like we do not want unnecessary dependencies, and commons.lang3 was explicitly removed once:  https://github.com/apache/iceberg/issues/2100.  so let's just manually code it here

**Review by szehon-ho — COMMENTED** [review]
This is a great find, thanks @dramaticlly !

Left some comments.

File: core/src/main/java/org/apache/iceberg/TableProperties.java (hunk 1 above)
Comment (dramaticlly) [reply core/src/main/java/org/apache/iceberg/TableProperties.java]: Moved as private within PropertyUtil

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java (hunk 2 above)
Comment (dramaticlly) [reply core/src/main/java/org/apache/iceberg/util/PropertyUtil.java]: I was copying from method below but not really needed this, removed.

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java (hunk 3 above)
Comment (dramaticlly) [reply core/src/main/java/org/apache/iceberg/util/PropertyUtil.java]: Actually with exception handling and validation throwing new exceptions in the code, I think for each loop shall be fine. Let me know if you hate it

File: core/src/main/java/org/apache/iceberg/TableMetadata.java (hunk 4 above)
Comment (dramaticlly) [reply core/src/main/java/org/apache/iceberg/TableMetadata.java]: Removed and changed to something similar in PropertyUtil, but I do realize that we have a few places use the StringUtil from `apache.commons.lang3` per https://github.com/search?q=repo%3Aapache%2Ficeberg%20import%20org.apache.commons.lang3&type=code,

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java [hunk 5]
```diff
@@ -57,6 +67,19 @@ public static double propertyAsDouble(
...
   }
 
+  public static int propertyTryAsInt(
+      Map<String, String> properties, String property, int defaultValue) {
+    String value = properties.get(property);
+    if (value != null) {
+      try {
+        return Integer.parseInt(value);
+      } catch (NumberFormatException e) {
+        return defaultValue;
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/util/PropertyUtil.java:77]: Nit: can we remove this line and fall to the same return later?

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java [hunk 6]
```diff
@@ -100,6 +123,28 @@ public static String propertyAsString(
     return defaultValue;
   }
 
+  /**
+   * Validate the table commit related properties to have non-negative integer on table creation to
+   * prevent commit failure
+   */
+  public static void validateCommitProperties(Map<String, String> properties) {
+    for (String commitProperty : COMMIT_PROPERTIES) {
+      if (properties.containsKey(commitProperty)) {
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/util/PropertyUtil.java:132]: how about doing it the way you do in the above method?  I think slightly less calls to properties?

int value = properties.get()
if (value != null) {
  int parsedValue;
  ...
}

File: core/src/main/java/org/apache/iceberg/TableMetadata.java (hunk 4 above)
Comment (szehon-ho) [reply core/src/main/java/org/apache/iceberg/TableMetadata.java]: Yea I think it is unfortunate it crept in, but I guess we could remove it later.

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java (hunk 5 above)
Comment (dramaticlly) [reply core/src/main/java/org/apache/iceberg/util/PropertyUtil.java]: I feel a bit weird about empty catch clause as hurt readability a bit, so I tried to invert the if condition so that we still have 3 return statement but reads better. what do you think?

**Review by szehon-ho — APPROVED** [review]
Sounds good to me, thanks @dramaticlly

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java [hunk 7]
```diff
@@ -57,6 +67,19 @@ public static double propertyAsDouble(
...
+  public static int propertyTryAsInt(
+      Map<String, String> properties, String property, int defaultValue) {
+    String value = properties.get(property);
+    if (value == null) {
+      return defaultValue;
+    }
+    try {
+      return Integer.parseInt(value);
+    } catch (NumberFormatException ignored) {
+      return defaultValue;
```
Comment (szehon-ho) [inline core/src/main/java/org/apache/iceberg/util/PropertyUtil.java:79]: @dramaticlly sorry forgot to ask, should we log a warning here

**Review by szehon-ho — APPROVED** [review]
Looks good to me.

I think follow up can investigate how to protect the updateProperties() method

**Comment by szehon-ho** [comment]
Merged, thanks @dramaticlly !
