### PR TITLE
Spark: refactor serialization test suites

### LINKED ISSUE #1279: Spark: Kyro throws exception on deserializing BaseCombinedScanTask
I've encountered the issue against Spark 3 with Iceberg master branch (aad99b5f7954678193ee6c3fa69f68392b8b81dd) + custom patches (to change Hadoop/Hive/Spark versions).

Ran below code on spark-shell:

```
import org.apache.iceberg.catalog.TableIdentifier
import org.apache.iceberg.hive.HiveCatalog
import org.apache.iceberg.actions.{Actions, RewriteDataFilesActionResult}

val dbName = "default"
val tableName = "table3"

val catalog = new HiveCatalog(spark.sessionState.newHadoopConf)
val table = catalog.loadTable(TableIdentifier.of(dbName, tableName))
val actions: Actions = Actions.forTable(table)
val result: RewriteDataFilesActionResult = actions.rewriteDataFiles().execute()

println(s"Added data files: ${result.addedDataFiles.size}")
println(s"Deleted data files: ${result.deletedDataFiles.size}")
```

Stack trace follows:

```
20/07/31 04:00:59 ERROR util.Utils: Exception encountered
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
tasks (org.apache.iceberg.BaseCombinedScanTask)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:391)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:302)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
        at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:35)
        at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:23)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
        at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:296)
        at org.apache.spark.rdd.ParallelCollectionPartition.$anonfun$readObject$2(ParallelCollectionRDD.scala:80)
        at org.apache.spark.rdd.ParallelCollectionPartition.$anonfun$readObject$2$adapted(ParallelCollectionRDD.scala:80)
        at org.apache.spark.util.Utils$.deserializeViaNestedStream(Utils.scala:170)
        at org.apache.spark.rdd.ParallelCollectionPartition.$anonfun$readObject$1(ParallelCollectionRDD.scala:80)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1343)
        at org.apache.spark.rdd.ParallelCollectionPartition.readObject(ParallelCollectionRDD.scala:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:405)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException
        at org.apache.iceberg.relocated.com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:244)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
        ... 35 more
```

As I mentioned, I'm using custom version of Iceberg where Hadoop/Hive/Spark versions are different with Iceberg's dependency, but the issue seems to be known one in Guava & Kyro, so I guess this is general one.

### PR DESCRIPTION
**Pull request by HeartSaVioR**
This patch refactors to deduplicate the code:

* Comparing BaseCombinedScanTask needs compare of DataFile, which we already have the method for this, but in other test suite. I created a new helper class to move out comparison methods so that they can be co-used.

### CODE REVIEW

File: spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+    Assert.assertEquals("starting position doesn't match", expected.start(), actual.start());
+
+    Assert.assertEquals("the number of bytes to scan doesn't match", expected.start(), actual.start());
+
+    // simplify comparison on residual expression via comparing toString
+    Assert.assertEquals("Residual expression doesn't match",
+        expected.residual().toString(), actual.residual().toString());
+  }
+
+  public static void checkDataFile(DataFile expected, DataFile actual) {
```
Comment (HeartSaVioR) [inline spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java:67]: This is identical to `TestDataFileSerialization.checkDataFile` - just moved to here.

File: spark/src/test/java/org/apache/iceberg/actions/TestRewriteDataFilesAction.java [hunk 2]
```diff
@@ -311,6 +324,64 @@ public void testRewriteLargeTableHasResiduals() {
     Assert.assertEquals("Rows must match", records, actualRecords);
   }
 
+  @Test
```
Comment (HeartSaVioR) [inline spark/src/test/java/org/apache/iceberg/actions/TestRewriteDataFilesAction.java:327]: I decided to add the serde tests of BaseCombinedScanTask here, because it seems to require non-trivial efforts to create BasedCombinedScanTask by hand. I can move out if we'd like to have separate suite with manually crafted test objects.

**Comment by HeartSaVioR** [comment]
This is rebased after merging #1285.

File: spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+  }
+
+  private static List<FileScanTask> getFileScanTasksInFilePathOrder(BaseCombinedScanTask task) {
+    return task.files().stream()
+        // use file path + start position to differentiate the tasks
+        .sorted(Comparator.comparing(o -> o.file().path().toString() + "##" + o.start()))
+        .collect(Collectors.toList());
+  }
+
+  public static void checkFileScanTask(FileScanTask expected, FileScanTask actual) {
```
Comment (HeartSaVioR) [inline spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java:52]: This is moved from `TestScanTaskSerialization.java. checkFileScanTask`.

File: spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java [hunk 4]
```diff
@@ -0,0 +1,93 @@
...
+import java.util.Comparator;
+import java.util.List;
+import java.util.stream.Collectors;
+import org.junit.Assert;
+
+public final class SerializationCheckHelper {
+  private SerializationCheckHelper() {
+  }
+
+  public static void checkBaseCombinedScanTask(BaseCombinedScanTask expected, BaseCombinedScanTask actual) {
```
Comment (HeartSaVioR) [inline spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java:31]: This is moved from `TestScanTaskSerialization.checkBaseCombinedScanTask`.

File: spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+        expectedTasks.size(), actualTasks.size());
+
+    for (int i = 0; i < expectedTasks.size(); i++) {
+      FileScanTask expectedTask = expectedTasks.get(i);
+      FileScanTask actualTask = actualTasks.get(i);
+      checkFileScanTask(expectedTask, actualTask);
+    }
+  }
+
+  private static List<FileScanTask> getFileScanTasksInFilePathOrder(BaseCombinedScanTask task) {
```
Comment (HeartSaVioR) [inline spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java:45]: This is moved from `TestScanTaskSerialization.getFileScanTasksInFilePathOrder`.

File: spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+ */
+
+package org.apache.iceberg;
+
+import java.util.Comparator;
+import java.util.List;
+import java.util.stream.Collectors;
+import org.junit.Assert;
+
+public final class SerializationCheckHelper {
```
Comment (rdblue) [inline spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java:27]: It looks like these are mostly equivalent to `assertEquals`. In that case, they don't necessarily need to be used to validate serialization. To make them easier to find and reuse, how about naming this class `TaskCheckHelper`?

File: spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java (hunk 4 above)
Comment (rdblue) [inline spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java:31]: You might consider renaming these methods to `assertEquals` if that's what they are doing. That makes them more generic and easier for read because it tells the reader exactly what it validated. Otherwise, someone that wants to reuse these methods needs to look at what the check does.

**Comment by rdblue** [comment]
Thanks for updating this, @HeartSaVioR! Looks great. I merged it.

**Comment by HeartSaVioR** [comment]
Thanks for reviewing and merging!
