### PR TITLE
Fix date and timestamp transforms

### LINKED ISSUE #1680: Spec: document partition transforms for timestamps before 1970
The Java implementation uses `ChronoUnit.between` to calculate years, months, days, and hours transforms for timestamp and date types. For dates and timestamps before 1970, the values are off by 1 because units are rounded down.

For example, 1969-12-31 23:59:59.000000 is -1,000,000 in microseconds. When that value is converted to hours by dividing by 3,600,000,000 microseconds per hour, the value is 0 instead of -1. But 1 second after new year 1970 results in the same value, 0. This affects all timestamp transforms and the year/month date transforms (days with date values is correct because the interval is a whole number of days).

This was discussed in the community and the consensus was to document the current behavior of the `year`, `month`, `day`, and `hour` transforms in the spec so that any existing data can be read correctly. Then, new transforms without this issue should be introduced and used by default for v2 tables.

### PR DESCRIPTION
**Pull request by rdblue**
This fixes incorrect values produced by date and time transforms and adds tests.

This also updates date and timestamp transform projection methods to include incorrectly transformed values.

Fixes #1680.

### CODE REVIEW

File: api/src/test/java/org/apache/iceberg/transforms/TestTimestampsProjection.java [hunk 1]
```diff
@@ -74,22 +74,22 @@ public void assertProjectionStrictValue(PartitionSpec spec, UnboundPredicate<?>
...
-    Assert.assertEquals(projection.op(), expectedOp);
+    Assert.assertEquals(expectedOp, projection.op());
   }
 
   public void assertProjectionInclusive(PartitionSpec spec, UnboundPredicate<?> filter,
                                         Expression.Operation expectedOp, String expectedLiteral) {
     Expression projection = Projections.inclusive(spec).project(filter);
     UnboundPredicate<?> predicate = assertAndUnwrapUnbound(projection);
 
-    Assert.assertEquals(predicate.op(), expectedOp);
```
Comment (rdblue) [inline api/src/test/java/org/apache/iceberg/transforms/TestTimestampsProjection.java:92]: More tests need to be added here. I just wanted to get this up for review since I'm going to be out for a couple of days.

File: api/src/main/java/org/apache/iceberg/transforms/Timestamps.java [hunk 2]
```diff
@@ -52,12 +52,19 @@ public Integer apply(Long timestampMicros) {
...
+    if (timestampMicros >= 0) {
+      OffsetDateTime timestamp = Instant
+          .ofEpochSecond(Math.floorDiv(timestampMicros, 1_000_000), Math.floorMod(timestampMicros, 1_000_000))
+          .atOffset(ZoneOffset.UTC);
+      return (int) granularity.between(EPOCH, timestamp);
+    } else {
+      // add 1 micro to the value to account for the case where there is exactly 1 unit between the timestamp and epoch
+      // because the result will always be decremented.
+      OffsetDateTime timestamp = Instant
+          .ofEpochSecond(Math.floorDiv(timestampMicros, 1_000_000), Math.floorMod(timestampMicros + 1, 1_000_000))
```
Comment (yyanyy) [inline api/src/main/java/org/apache/iceberg/transforms/Timestamps.java:64]: I think the second argument in `Instant.ofEpochSecond` is nanosecond instead of microsecond? Although this doesn't change the outcome of this method since we don't accept nanosecond in the first place, and inputing microsecond for nanosecond field just makes the field smaller than it should be, which is already enough to address the case when `Math.floorMod()` == 0

File: api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java [hunk 3]
```diff
@@ -254,4 +257,124 @@ private ProjectionUtil() {
     return predicate(predicate.op(), fieldName,
         Iterables.transform(predicate.asSetPredicate().literalSet(), transform::apply));
   }
+
+  static UnboundPredicate<Integer> fixInclusiveTimeProjection(UnboundPredicate<Integer> projected) {
+    if (projected == null) {
+      return projected;
+    }
+
+    // adjust the predicate for values that were 1 larger than the correct transformed value
```
Comment (yyanyy) [inline api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java:266]: I think the mention of "correct" and "incorrect" in these comments might not be obvious to understand outside the context of this PR, as the reader has no prior knowledge of the issue we are fixing here from looking at the code base itself. Do we want to add some more explanation/link to the issue?

File: api/src/test/java/org/apache/iceberg/transforms/TestDatesProjection.java [hunk 4]
```diff
@@ -142,6 +161,24 @@ public void testMonthStrictUpperBound() {
...
+    assertProjectionStrictValue(spec, lessThan("date", date), Expression.Operation.FALSE);
+    assertProjectionStrictValue(spec, lessThanOrEqual("date", date), Expression.Operation.FALSE);
+    assertProjectionStrict(spec, greaterThan("date", date), Expression.Operation.GT, "1969-12");
+    assertProjectionStrict(spec, greaterThanOrEqual("date", date), Expression.Operation.GT, "1969-12");
+    assertProjectionStrict(spec, notEqual("date", date), Expression.Operation.NOT_IN, "[1969-12, 1970-01]");
+    assertProjectionStrictValue(spec, equal("date", date), Expression.Operation.FALSE);
+
+    Integer anotherDate = (Integer) Literal.of("1970-01-01").to(TYPE).value();
+    assertProjectionStrict(spec, notIn("date", date, anotherDate),
+        Expression.Operation.NOT_IN, "[1969-12, 1970-01]");
```
Comment (yyanyy) [inline api/src/test/java/org/apache/iceberg/transforms/TestDatesProjection.java:178]: I think this is testing the same thing for `NOT_IN` in `testNegativeMonthStrictLowerBound`, do we want to change 1970-01-01 to an earlier time?

**Review by yyanyy — COMMENTED** [review]
Thank you for making this change!

To make sure I understand correctly, changes in projection methods ensure that both behaviors before and after this fix will be accounted for by the projection, so that we might not need to have separate implementations for format v1 versus v2, with a slight penalty that in v2 we may scan more data than we have to?

**Comment by rdblue** [comment]
> To make sure I understand correctly, changes in projection methods ensure that both behaviors before and after this fix will be accounted for by the projection, so that we might not need to have separate implementations for format v1 versus v2, with a slight penalty that in v2 we may scan more data than we have to?

Yes, this fixes the transforms and ensures that predicate projection includes the partitions that were written with bad values. That means that we won't need different implementations for v2, but it also means that we can avoid scanning the extra partitions in the future. Because this is fixed before v2, we can ensure that all v2 tables have been fixed. So if a table is created as v2, we should be able to know that no older writers with the bug have written to the table. The only case where a v2 table would have bad metadata is when a v1 table has been converted. We should add a flag to signal that the table was converted from v1 or one that signals it was created as v2 that allows us to skip the extra partitions.

File: api/src/main/java/org/apache/iceberg/transforms/Timestamps.java (hunk 2 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/transforms/Timestamps.java:64]: Fixed.

File: api/src/test/java/org/apache/iceberg/transforms/TestDatesProjection.java (hunk 4 above)
Comment (rdblue) [reply api/src/test/java/org/apache/iceberg/transforms/TestDatesProjection.java:178]: I updated the other test to use a lower bound that is not 1970-01-01 and also added tests specifically for epoch values. This still conflicted with the epoch test, so I changed it to use 1969-11-01.

File: api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java (hunk 3 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java:275]: I added docs to explain what "correct" and "incorrect" mean.

File: api/src/main/java/org/apache/iceberg/transforms/Timestamps.java [hunk 5]
```diff
@@ -52,12 +52,23 @@ public Integer apply(Long timestampMicros) {
...
-    OffsetDateTime timestamp = Instant
-        .ofEpochSecond(timestampMicros / 1_000_000)
-        .atOffset(ZoneOffset.UTC);
-
-    return (int) granularity.between(EPOCH, timestamp);
+    if (timestampMicros >= 0) {
+      OffsetDateTime timestamp = Instant
+          .ofEpochSecond(
+              Math.floorDiv(timestampMicros, 1_000_000),
+              Math.floorMod(timestampMicros, 1_000_000) * 1000)
```
Comment (jun-he) [inline api/src/main/java/org/apache/iceberg/transforms/Timestamps.java:59]: nit: extract `1_000_000` and `1000` to be a constant with meaningful name or use predefined ones in java library.

File: api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java [hunk 6]
```diff
@@ -254,4 +257,145 @@ private ProjectionUtil() {
...
+          Integer value = lit.value();
+          fixedSet.add(value);
+          if (value < 0) {
+            hasNegativeValue = true;
+            fixedSet.add(value + 1);
+          }
+        }
+
+        if (hasNegativeValue) {
+          return Expressions.in(projected.term(), fixedSet);
```
Comment (RussellSpitzer) [inline api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java:317]: why not just always return this new expression? We build up fixedSet no matter what?

Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java:317]: If there is no negative value, then there is no need to fixup the expression and we can return the original. That avoids some object allocation?

**Comment by boroknagyz** [comment]
Thanks for fixing this, I've just run into this issue with Impala. (And this fix is also a prerequisite for issue #2043)

So the plan is that 0.11+ writers will write the correct transformation values IIUC. Does it also mean that pre-0.11 readers will not be able to read the new files correctly when the data is before the epoch?

E.g. new writer writes '1969-12-31 23:05:00' with YEAR partition transform (so ts_year=-1), old reader scans for 'ts > 1969-12-31 23:00:00' (so with old transform the projected predicate is ts_year >=0), and the file will be skipped because the partition data has ts_year=-1.

I just want to clarify this, because with Impala I'm planning to write V1 files with the fixed transforms.

**Comment by rdblue** [comment]
> Does it also mean that pre-0.11 readers will not be able to read the new files correctly when the data is before the epoch?

Yes. Older readers will still have the bug. I think we can only make a backward-compatible fix for this.

**Comment by danielcweeks** [comment]
So, the best I can follow, this looks good, but there's one issue I'm not clear on.  If we're just expanding the projection to include possible matches (e.g. equality case), doesn't this cause a problem where the partition values are joined in (i.e. not materialized in the data like converted Hive tables)?

I assume we don't have a way to correct for that case since the recorded transform is incorrect and we cannot materialize the correct data to filter later?

**Review by danielcweeks — APPROVED** [review]
+1 LGTM

File: api/src/main/java/org/apache/iceberg/transforms/Dates.java [hunk 7]
```diff
@@ -99,11 +107,24 @@ public boolean satisfiesOrderOf(Transform<?, ?> other) {
 
     if (pred.isUnaryPredicate()) {
       return Expressions.predicate(pred.op(), fieldName);
+
     } else if (pred.isLiteralPredicate()) {
-      return ProjectionUtil.truncateInteger(fieldName, pred.asLiteralPredicate(), this);
+      UnboundPredicate<Integer> projected = ProjectionUtil.truncateInteger(fieldName, pred.asLiteralPredicate(), this);
+      if (this != DAY) {
```
[the remark this answers is not in the document]
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/transforms/Dates.java:113]: There are only 4 instance of this, and they call 2 different fix methods. I don't think it would be worth adding 2 methods just to dedup 4 lines here.

**Comment by rdblue** [comment]
Thanks for the reviews, @danielcweeks, @yyanyy, @RussellSpitzer, @jun-he, and @boroknagyz!
