### PR TITLE
Core: Deep copy Record values for equality deletes

### LINKED ISSUE #11239: BaseDeleteLoader may ignore delete records for binary columns
### Apache Iceberg version

1.6.1 (latest release)

### Query engine

None

### Please describe the bug 🐞

In case of a binary column, Iceberg Equality Delete loader, `BaseDeleteLoader` reuses the underlying ByteBuffer used to read the delete records. In some situations it leads to overwriting previously read records from the delete file and in turn produces duplicates in the output.

Unfortunately, I can't share the exact code to reproduce the bug, but here is the table that contains the issue - [9a264a21-cc2f-4f13-8e7d-4d899a31ca2f 2.zip](https://github.com/user-attachments/files/17196281/9a264a21-cc2f-4f13-8e7d-4d899a31ca2f.2.zip). A read from that table will contain duplicates as the equality delete reader will miss one of the 2 records present in the delete file.

In principle, it should be easy to reproduce with a table having a binary column and doing an overwrite on it. Unfortunately, I am new to Iceberg and couldn't find working instructions on how to set up a local environment and do an overwrite using equality deletes. If someone helps me with a local setup, I will be happy to provide a more actionable example.

Here are the pointers in the code to show how/why the overwrite happens:

* Parquet reader configuration for delete files set up to reuse the `ByteBuffer`: https://github.com/apache/iceberg/blob/09370ddbc39fc3920fb8cbd3dff11b377dd37e40/data/src/main/java/org/apache/iceberg/data/BaseDeleteLoader.java#L197-L203

* `ParquetValueReaders` that reuses the same ByteByffer:

https://github.com/apache/iceberg/blob/09370ddbc39fc3920fb8cbd3dff11b377dd37e40/parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java#L366-L380

* And finally, `InternalRecordWrapper` copies the pointer to that ByteBuffer (instead of its content) leading to the overwrite:
https://github.com/apache/iceberg/blob/09370ddbc39fc3920fb8cbd3dff11b377dd37e40/data/src/main/java/org/apache/iceberg/data/InternalRecordWrapper.java#L76-L78
* Reading subsequent records from the delete file overwrites previously read records if the newer records fit into the buffer. 

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by hsingh574**
Closes #11239

### CODE REVIEW

**Review by RussellSpitzer — CHANGES_REQUESTED** [review]
Currently failing tests are all related to equality deletes so this may not be doing what it should be. I'm also a little concerned about not-reusing containers, that makes me feel like the consumer of this iterator is not working correctly and not that we shouldn't be re-using containers?

**Comment by hsingh574** [comment]
Thanks for taking a look. I made an incorrect update to that unit test which caused the failure. Updated in the latest commit and it passed locally.

Regarding container reuse in general, I don't see how to generate a set of all equality delete records (for ByteBuffers for example) without copying at some point (for positional deletes afaict we don't reuse anything anyways). We could introduce a "ContainerPool" which has several different sized containers to choose from that can be reused, but seems like we still need a copy at some point to avoid overwriting data. 

Maybe there's a way to change the contract of DeleteLoader to avoid this problem?

**Comment by RussellSpitzer** [comment]
Don't we already define materialization as part of the `loadEqualityDeletes` interface? 

This code
https://github.com/apache/iceberg/blob/main/data/src/main/java/org/apache/iceberg/data/BaseDeleteLoader.java#L110-L133
Should be making the copies we require from the underlying file reads right?

**Comment by hsingh574** [comment]
Yeah making the Record copy "deep" would also fix this problem (note this has to work for StructTypes as well for example). I wanted to avoid any concerns with implementing that deep copy correctly so opted for this approach, but agree that it does obscure the true issue a bit.

So would you recommend doing the deep copy? If so, do you have an implementation in mind? (e.g. serialize then deserialize)

**Comment by RussellSpitzer** [comment]
I definitely think we should be fixing Record copy. That's the intent of the code here unless we want to completely change the guarentees of this api. Again changing the API would change behavior for equality and position deletes so I'm not comfortable with just changing it at a low level. Instead we should focus on what is a real bug (record copy doesn't actually copy the record)

**Comment by hsingh574** [comment]
@RussellSpitzer Updated with a deepCopy method. Tried to use existing code wherever possible, let me know if there's a better approach.

File: core/src/main/java/org/apache/iceberg/data/GenericRecord.java [hunk 1]
```diff
@@ -65,13 +68,36 @@ private GenericRecord(StructType struct) {
     this.nameToPos = NAME_MAP_CACHE.get(struct);
   }
 
-  private GenericRecord(GenericRecord toCopy) {
+  private GenericRecord(GenericRecord toCopy, boolean deepCopyValues) {
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/data/GenericRecord.java:71]: I don't think we should have a flag for this and I think we should have the code a bit more similar to the other classes where we implement this same logic for example

https://github.com/apache/iceberg/blob/fb02bd2d713c9bef8b8ccee334f6d65087c344b2/core/src/main/java/org/apache/iceberg/PartitionData.java#L227-L253

I'm not sure why we need to do conversions for the time types?

File: core/src/main/java/org/apache/iceberg/data/GenericRecord.java [hunk 2]
```diff
@@ -65,13 +68,36 @@ private GenericRecord(StructType struct) {
...
+      for (int i = 0; i < toCopy.values.length; i++) {
+        this.values[i] = deepCopyValue(this.struct.fields().get(i).type(), toCopy.values[i]);
+      }
+    } else {
+      this.values = Arrays.copyOf(toCopy.values, toCopy.values.length);
+    }
     this.nameToPos = toCopy.nameToPos;
   }
 
+  private Object deepCopyValue(Type type, Object value) {
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/data/GenericRecord.java:85]: I don't think we have to be this careful, the main thing we need to handle is just ByteBuffers which I think we can do a bit more explicitly if you see the PartitionData example I posted above

Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/data/GenericRecord.java:85]: Are we worried about the underlying object state changing for those types? I believe we should probably consider all of those other types immutable, byte buffer is our real problem here. I would focus on our byte-buffer issue here since we know it is broken.

Comment (hsingh574) [reply core/src/main/java/org/apache/iceberg/data/GenericRecord.java:85]: I added a unit test for struct which fails without this change. Map and list look to have the same problem because they’re also relying on the reused container (at least in the Parquet impl I checked), but had some trouble unit testing them.

Happy to scope the change to ByteBuffer for now, but I do think the issue is broader.

Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/data/GenericRecord.java:85]: I don't think it should be an issue for Map or List, what kind of test are you writing? You should be able to test this with the "generics" implementation since it also can read into genericRecords. (Same issue for ByteBuffers)

Comment (hsingh574) [reply core/src/main/java/org/apache/iceberg/data/GenericRecord.java:85]: I believe the unit tests I added for binary and struct types in the DeleteReadTests class are using the generics implementation 

https://github.com/apache/iceberg/blob/242717c8c516dcc49bc4368b77cd3f3af40720c8/data/src/test/java/org/apache/iceberg/data/TestGenericReaderDeletes.java#L51

For list and map using a similar setup I was running into exceptions like: 
```
org.apache.iceberg.exceptions.ValidationException: Invalid schema: multiple fields for name mapData.key: 7 and 7
```

which looks like its coming from ids of list map types not being projected

https://github.com/apache/iceberg/blob/242717c8c516dcc49bc4368b77cd3f3af40720c8/api/src/main/java/org/apache/iceberg/types/GetProjectedIds.java#L49

which leads to `missingIds` being containing the map/list column id

http://github.com/apache/iceberg/blob/242717c8c516dcc49bc4368b77cd3f3af40720c8/data/src/main/java/org/apache/iceberg/data/DeleteFilter.java#L286

and Schema creation failing because the column id was added twice

https://github.com/apache/iceberg/blob/242717c8c516dcc49bc4368b77cd3f3af40720c8/data/src/main/java/org/apache/iceberg/data/DeleteFilter.java#L317

Am I missing something or would equality deletes for map/list not work due to this constraint?

Anyways, I'll scope the change to ByteBuffer and GenericRecord types for now.

**Comment by hsingh574** [comment]
@RussellSpitzer requesting review on the latest changes.

File: api/src/main/java/org/apache/iceberg/data/Record.java [hunk 3]
```diff
@@ -34,6 +34,8 @@ public interface Record extends StructLike {
 
   Record copy();
 
+  Record deepCopyValues();
```
Comment (RussellSpitzer) [inline api/src/main/java/org/apache/iceberg/data/Record.java:37]: I don't think we need a new method here, we can just modify copy

Comment (hsingh574) [reply api/src/main/java/org/apache/iceberg/data/Record.java:37]: Was a bit concerned about introducing overhead to other usages of copy() in case they didn’t necessarily care about the deep copy. Assuming that’s not an issue I’ll make the change.

File: data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java [hunk 4]
```diff
@@ -586,6 +595,75 @@ public void testEqualityDeleteByNull() throws IOException {
...
+        (i) -> {
+          Record structRecord =
+              GenericRecord.create(table.schema().findType("structData").asStructType());
+          structRecord.setField("structInnerData", "structInnerData_" + i);
+          return structRecord;
+        });
+  }
+
+  private <T> void testEqualityDeleteWithColumn(
+      String targetFieldName, Function<Integer, T> targetFieldValueSupplier) throws IOException {
```
Comment (RussellSpitzer) [inline data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java:618]: Let's avoid a functional interface if we can. Seems like the only thing we are actually avoiding is defining dataDeletes? 

I would suggest refactoring this so that instead to either look like the testEqualityDateDeletes or generating another test method
testEqualityDeletes(List<record> data, List<Record> equalityDeletes, List<Record> expected)?

Something like that

File: core/src/test/java/org/apache/iceberg/data/GenericRecordCopyTest.java [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+
+    GenericRecord shallowCopy = original.copy();
+    for (Types.NestedField field : schema.columns()) {
+      assertThat(shallowCopy.getField(field.name()) == original.getField(field.name())).isTrue();
+    }
+
+    GenericRecord deepCopy = original.deepCopyValues();
+    for (Types.NestedField field : schema.columns()) {
+      assertThat(deepCopy.getField(field.name())).isEqualTo(original.getField(field.name()));
+      assertThat(deepCopy.getField(field.name()) == original.getField(field.name())).isFalse();
```
Comment (RussellSpitzer) [inline core/src/test/java/org/apache/iceberg/data/GenericRecordCopyTest.java:56]: see .isSameAs(Object expected)

File: core/src/test/java/org/apache/iceberg/data/GenericRecordCopyTest.java [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+
+    GenericRecord original = GenericRecord.create(schema);
+    original.setField("binaryData", ByteBuffer.wrap("binaryData_0".getBytes()));
+    Record structRecord = GenericRecord.create(schema.findType("structData").asStructType());
+    structRecord.setField("structInnerData", "structInnerData_1");
+    original.setField("structData", structRecord);
+
+    GenericRecord shallowCopy = original.copy();
+    for (Types.NestedField field : schema.columns()) {
+      assertThat(shallowCopy.getField(field.name()) == original.getField(field.name())).isTrue();
```
Comment (RussellSpitzer) [inline core/src/test/java/org/apache/iceberg/data/GenericRecordCopyTest.java:50]: I don't think we should preserve the original copy behavior, but if we do want to do that I would use `isSameAs` here for the comparison

File: data/src/test/java/org/apache/iceberg/data/TestGenericReaderDeletes.java [hunk 7]
```diff
@@ -47,12 +48,13 @@ protected void dropTable(String name) {
 
   @Override
   public StructLikeSet rowSet(String name, Table table, String... columns) throws IOException {
-    StructLikeSet set = StructLikeSet.create(table.schema().asStruct());
```
Comment (RussellSpitzer) [inline data/src/test/java/org/apache/iceberg/data/TestGenericReaderDeletes.java:50]: This change looks correct to me, but is it related to this pr?

Comment (hsingh574) [reply data/src/test/java/org/apache/iceberg/data/TestGenericReaderDeletes.java:50]: This was needed when introducing new optional columns to the schema because `Iterators.addAll` needs to do a hashCode calculation which ends up looking for a value at every position in the schema, and the optional column values don't exist for the other tests.

File: core/src/main/java/org/apache/iceberg/data/GenericDataUtil.java [hunk 8]
```diff
@@ -54,7 +54,6 @@ public static Object internalToGeneric(Type type, Object value) {
       case FIXED:
         return ByteBuffers.toByteArray((ByteBuffer) value);
     }
-
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/data/GenericDataUtil.java:57]: unrelated white space change?

File: data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java [hunk 9]
```diff
@@ -586,6 +595,94 @@ public void testEqualityDeleteByNull() throws IOException {
...
+            structDataDelete.copy("structData", structRecord0),
+            structDataDelete.copy("structData", structRecord1),
+            structDataDelete.copy("structData", structRecord2));
+    StructLikeSet expected = rowSetWithoutIds(table, allRecords, 200, 201, 202);
+    testEqualityDeletes(equalityDeletes, expected);
+  }
+
+  private void testEqualityDeletes(List<Record> equalityDeletes, StructLikeSet expected)
+      throws IOException {
+    if (equalityDeletes.isEmpty()) {
```
Comment (RussellSpitzer) [inline data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java:637]: We use Preconditions for things like this, 
Example
```java
    Preconditions.checkArgument(null != fileFormat, "Invalid file format: null");
```

File: data/src/test/java/org/apache/iceberg/data/TestGenericRecord.java [hunk 10]
```diff
@@ -58,4 +60,27 @@ public void testGetIncorrectClassInstance() {
         .isInstanceOf(IllegalStateException.class)
         .hasMessage("Not an instance of java.lang.CharSequence: 10");
   }
+
+  @Test
+  public void deepCopyValues() {
```
Comment (RussellSpitzer) [inline data/src/test/java/org/apache/iceberg/data/TestGenericRecord.java:65]: nit: testDeepCopyValues()

File: data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java [hunk 11]
```diff
@@ -586,6 +595,94 @@ public void testEqualityDeleteByNull() throws IOException {
...
+            equalityDeletes,
+            equalityDeletes.get(0).struct().asSchema());
+    table.newRowDelta().addDeletes(eqDeletes).commit();
+
+    StructLikeSet actual = rowSet(tableName, table, "*");
+    assertThat(actual).as("Table should contain expected rows").isEqualTo(expected);
+    checkDeleteCount(equalityDeletes.size());
+  }
+
+  private List<Record> appendOptionalColumnRecords() throws IOException {
```
Comment (RussellSpitzer) [inline data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java:654]: Not sure on the name here?  Why are they optional?

File: data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java [hunk 12]
```diff
@@ -586,6 +595,94 @@ public void testEqualityDeleteByNull() throws IOException {
...
+    }
+    DataFile binaryDataFile =
+        FileHelpers.writeDataFile(
+            table,
+            Files.localOutput(File.createTempFile("junit", null, temp.toFile())),
+            Row.of(0),
+            optionalColumnRecords);
+
+    table.newAppend().appendFile(binaryDataFile).commit();
+    List<Record> allRecords = Lists.newArrayList(records);
```
Comment (RussellSpitzer) [inline data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java:681]: In general, I would try not to add a secondary behavior here (writing + getting the full table data). In tests it's probably ok to do this, but I don't think most users would expect that "appendRecords" would return all records and not just those appended.

**Review by RussellSpitzer — APPROVED** [review]
I have a few more nits, but I think this is looking pretty good!

File: data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java (hunk 12 above)
Comment (hsingh574) [reply data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java]: ack. In the latest revision I just added to the `records` set.

**Comment by hsingh574** [comment]
@RussellSpitzer Appreciate the reviews! Addressed the nits in the latest revision.

**Comment by RussellSpitzer** [comment]
Looking good! I'm waiting on the tests to pass and then I'll merge. Thanks so much @hsingh574 for the patch.
