### PR TITLE
API: Fix TableIdentifier.toLowerCase to use Locale.ROOT for namespace levels (#15956)

### LINKED ISSUE #15956: API: Fix Locale for namespace in TableIdentifier
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

This is related to [#9276](https://github.com/apache/iceberg/issues/9276). This ensures consistent identifier resolution (fix for namespace) across different system locales, specifically preventing the 'Turkish I' problem where 'I' maps to 'ı' instead of 'i'

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by Govindarajan-D**
Fixes #15956

Replaced locale-dependent toLowerCase() calls with toLowerCase(Locale.ROOT) in TableIdentifier. This ensures consistent identifier resolution across different system locales, specifically preventing the 'Turkish I' problem where 'I' maps to 'ı' instead of 'i'

### CODE REVIEW

File: api/src/test/java/org/apache/iceberg/catalog/TestTableIdentifier.java [hunk 1]
```diff
@@ -52,6 +53,18 @@ public void testToLowerCase() {
         .isEqualTo(TableIdentifier.of("Catalog", "dB", "TBL").toLowerCase());
   }
 
+  @Test
+  public void testToLowerCaseIsLocaleIndependent() {
+    Locale defaultLocale = Locale.getDefault();
```
Comment (ebyhr) [inline api/src/test/java/org/apache/iceberg/catalog/TestTableIdentifier.java]: The default location is stored in global state, so changing it could affect other tests if they run concurrently. To avoid this, we could use JUnit Pioneer, which is already used by TestAliyunClientFactories.
```java
  @Test
  @DefaultLocale(language = "tr")
  public void testToLowerCaseIsLocaleIndependent() {
    assertThat(TableIdentifier.of("information", "db", "tbl"))
            .isEqualTo(TableIdentifier.of("INFORMATION", "DB", "TBL").toLowerCase());
  }
```
The library isolates any test that has the `@DefaultLocale` annotation.

Comment (Govindarajan-D) [reply api/src/test/java/org/apache/iceberg/catalog/TestTableIdentifier.java]: Thanks for the feedback @ebyhr. Will change the code accordingly.

File: build.gradle [hunk 2]
```diff
@@ -334,6 +334,8 @@ project(':iceberg-api') {
     testImplementation libs.avro.avro
     testImplementation libs.esotericsoftware.kryo
     testImplementation libs.awaitility
+    testImplementation libs.junit.pioneer
+
```
Comment (ebyhr) [inline build.gradle]: You can remove a redundant empty line.

Comment (Govindarajan-D) [reply build.gradle]: Thanks again!

File: api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java [hunk 3]
```diff
@@ -80,7 +80,9 @@ public String name() {
 
   public TableIdentifier toLowerCase() {
     String[] newLevels =
-        Arrays.stream(namespace().levels()).map(String::toLowerCase).toArray(String[]::new);
```
Comment (ebyhr) [inline api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java:83]: I think we should ban toLowerCase/toUpperCase without locale parameter. Opened #15960

Comment (Govindarajan-D) [reply api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java:83]: That is true. https://github.com/apache/iceberg/issues/9276 was created previously, but I guess not all methods were changed.

**Review by nastra — APPROVED** [review]
LGTM, thanks for fixing this @Govindarajan-D
