### PR TITLE
Core: Fixes OOM caused by Avro decoder caching

### LINKED ISSUE #5652: DecoderResolver may lead to OOM of flink jobs writing to iceberg tables
### Apache Iceberg version

0.13.1

### Query engine

Flink

### Please describe the bug 🐞

I have a flink job writing to iceberg tables. When the job runs for several days, an OOM occurs. The reason is described below:

The DecoderResolver holds a ThreadLocal variable of a two-layer map:
```
    private static final ThreadLocal<Map<Schema, Map<Schema, ResolvingDecoder>>> DECODER_CACHES = ThreadLocal.withInitial(() -> {
        return (new MapMaker()).weakKeys().makeMap();
    });

    private static ResolvingDecoder resolve(Decoder decoder, Schema readSchema, Schema fileSchema) throws IOException {
        Map<Schema, Map<Schema, ResolvingDecoder>> cache = (Map)DECODER_CACHES.get();
        Map<Schema, ResolvingDecoder> fileSchemaToResolver = (Map)cache.computeIfAbsent(readSchema, (k) -> {
            return Maps.newHashMap();
        });
...
    }
```

The outer map has a weak key while the inner map has a strong one. As the inner map holds a reference to a Schema object, the outer map holding the same weak reference to the Schema object will not release the weak key. That leads to the OOM.

What I suggest is to change the inner map to one with weak key, too:
```
        Map<Schema, ResolvingDecoder> fileSchemaToResolver = (Map)cache.computeIfAbsent(readSchema, (k) -> {
//            return Maps.newHashMap();
            return new WeakHashMap<>();
        });
```

So far it seems working with my jobs.

### PR DESCRIPTION
**Pull request by ConeyLiu**
Closes #5652

This memory leak especially happens flink sink job which could lead there are many schema and decoders cached in memory and OOM in the end. Such as the following heap dumps:

image

Here are two problems at here:
1.  The guava map uses identity to compare the key when using the weak key. Here are the details: https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/MapMaker.java#LL58C39-L58C39. 
2. Copied from #5652 

> The DecoderResolver holds a ThreadLocal variable of a two-layer map. The outer map has a weak key while the inner map has a strong one. As the inner map holds a reference to a Schema object, the outer map holding the same weak reference to the Schema object will not release the weak key. That leads to the OOM.

### CODE REVIEW

**Comment by ConeyLiu** [comment]
Hi @stevenzwu @nastra @rdblue @Fokko @aokolnychyi, could you help to review this when you are free? Thanks in advance.

**Comment by Fokko** [comment]
Thanks @ConeyLiu for raising this, and sorry for the long wait. Did you confirm with the new `WeakHashMap` that the problem has been resolved?

At Avro, we had a similar issue: https://lists.apache.org/thread/8q3g304thhjgsfk7d6l62w706y365616 And the fix: https://github.com/apache/avro/pull/2090/

**Comment by ConeyLiu** [comment]
Thanks @Fokko for the review. 

> Did you confirm with the new WeakHashMap that the problem has been resolved?

It needs to run several weeks or months to trigger the problem. I tested locally and the caching works as expected.

> Do you think it is possible to add a check to see if the HashMap actually removes objects that are garbage collected? It would be nice to check its behavior now, but also we make sure that we keep this behavior in the future (it was broken in Avro along the way).

Add the new UTs to cover this. Please take another look when you are free.

File: core/src/main/java/org/apache/iceberg/data/avro/DecoderResolver.java [hunk 1]
```diff
@@ -49,11 +50,12 @@ public static <T> T resolveAndRead(
...
   }
 
-  private static ResolvingDecoder resolve(Decoder decoder, Schema readSchema, Schema fileSchema)
+  @VisibleForTesting
+  static ResolvingDecoder resolve(Decoder decoder, Schema readSchema, Schema fileSchema)
       throws IOException {
     Map<Schema, Map<Schema, ResolvingDecoder>> cache = DECODER_CACHES.get();
     Map<Schema, ResolvingDecoder> fileSchemaToResolver =
-        cache.computeIfAbsent(readSchema, k -> Maps.newHashMap());
+        cache.computeIfAbsent(readSchema, k -> new WeakHashMap<>());
```
Comment (ConeyLiu) [inline core/src/main/java/org/apache/iceberg/data/avro/DecoderResolver.java:58]: Change to `WeakHashMap` to solve the problems mentioned in problem 2.

File: core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+    assertThat(resolvingDecoder2).isNotSameAs(resolvingDecoder);
+
+    assertThat(DecoderResolver.DECODER_CACHES.get().size()).isEqualTo(2);
+    assertThat(DecoderResolver.DECODER_CACHES.get().get(fileSchema2).size()).isEqualTo(1);
+    checkCached(fileSchema2, fileSchema2);
+
+    fileSchema = null;
+    System.gc();
+    // Wait the weak reference keys are GCed
+    Thread.sleep(1000);
```
Comment (pvary) [inline core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java:74]: nit: Do we want to use Awaitility, like mentioned here: #7773?

Comment (ConeyLiu) [reply core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java]: Thanks @pvary for reviewing. Replaced with Awaitility.

**Comment by pvary** [comment]
@ConeyLiu: One last question: Did we run any performance tests to check how the changed caching effects the performance?

**Comment by ConeyLiu** [comment]
@pvary Thanks for pointing that out. This is really needed and found the potential problems.

Previously, we use `java.util.WeakHashMap` to replace the `MapMaker().weakKeys().makeMap()`, while the key equally checking is really slow compared with identity. The result is as follows:
```
// java.util.WeakHashMap
Benchmark                               Mode  Cnt   Score   Error  Units
ManifestReadBenchmark.readManifestFile    ss    5  12.896 ± 1.155   s/op

// MapMaker().weakKeys().makeMap()
Benchmark                               Mode  Cnt  Score   Error  Units
ManifestReadBenchmark.readManifestFile    ss    5  6.180 ± 0.067   s/op
```

Because for each avro record, we need to call the [DecoderResolver.resolveAndRead](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java#L72). So I keep the top map with `MapMaker().weakKeys().makeMap()` while the inner map changed to `java.util.WeakHashMap`.
Here is the benchmarks:
```
// Master
Benchmark                               Mode  Cnt   Score   Error  Units
ManifestReadBenchmark.readManifestFile    ss    5  12.896 ± 1.155   s/op

// This change
Benchmark                               Mode  Cnt  Score   Error  Units
ManifestReadBenchmark.readManifestFile    ss    5  6.190 ± 0.069   s/op
```

**Comment by ConeyLiu** [comment]
Actually, I am not sure why we need [DecoderResolver.resolveAndRead](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java#L72) for each record reading. Maybe we could create a `ResolvingDecoder` for a given AvroReader instance because for each instance the [readSchema](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java#L35) and [fileSchema](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java#L55) are unchanged.

**Review by pvary — APPROVED** [review]

File: core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+  private Schema avroSchema(String... columns) {
+    if (columns.length == 0) {
+      return AvroSchemaUtil.convert(ManifestFile.schema(), "manifest_file");
+    } else {
+      return AvroSchemaUtil.convert(ManifestFile.schema().select(columns), "manifest_file");
+    }
+  }
+
+  private void checkCached(Schema readSchema, Schema fileSchema) {
+    assertThat(DecoderResolver.DECODER_CACHES.get().containsKey(readSchema)).isTrue();
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java:143]: nit: should we change to style like `assertThat(DecoderResolver.DECODER_CACHES.get()).containsKey(readSchema)`

File: core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java [hunk 4]
```diff
@@ -0,0 +1,167 @@
...
+import org.apache.avro.io.DecoderFactory;
+import org.apache.avro.io.ResolvingDecoder;
+import org.apache.iceberg.ManifestFile;
+import org.apache.iceberg.avro.AvroSchemaUtil;
+import org.apache.iceberg.relocated.com.google.common.collect.Sets;
+import org.awaitility.Awaitility;
+import org.junit.Before;
+import org.junit.Test;
+
+public class TestDecoderResolver {
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java:36]: nice test

File: core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+
+  private int getActualSize() {
+    // The size of keys included the GCed keys
+    Set<Schema> keys = DecoderResolver.DECODER_CACHES.get().keySet();
+    Set<Schema> identityKeys = Sets.newIdentityHashSet();
+    identityKeys.addAll(keys);
+    return identityKeys.size();
+  }
+
+  private void checkCachedSize(int expected) {
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java:156]: wondering if this can be flaky on CI builds where servers are quite often overloaded. we can keep an eye on this. not a concern right now.

**Review by stevenzwu — APPROVED** [review]

File: core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java (hunk 3 above)
Comment (ConeyLiu) [reply core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java]: Updated

**Comment by pvary** [comment]
Merged the change as there are 3 approvals, and no comments for quite a while.

Thanks @ConeyLiu for the PR and @Fokko and @stevenzwu for the reviews!

**Comment by ConeyLiu** [comment]
Thanks @pvary for merging this, and also thanks @Fokko @stevenzwu @pvary for reviewing.
