### PR TITLE
Core: Fix JDBC Catalog table commit when migrating from schema V0 to V1

### LINKED ISSUE #10046: [JDBC Catalog] Table commit fails if iceberg_type field is NULL
### Apache Iceberg version

1.5.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Table commit fails with an error `org.apache.iceberg.exceptions.CommitFailedException: Failed to update table test.test_table from catalog rest_backend` when committing to a table that has `iceberg_type` NULL in the underlying JDBC catalog.

```
2024-03-27T06:57:32.785 ERROR [org.apache.iceberg.rest.RESTCatalogServlet] - Error processing REST request
org.apache.iceberg.exceptions.RESTException: Unhandled error: ErrorResponse(code=409, type=CommitFailedException, message=Failed to update table test.test_table from catalog rest_backend)
org.apache.iceberg.exceptions.CommitFailedException: Failed to update table test.test_table from catalog rest_backend
```
iceberg_type is a new column, introduced in 1.5.0 to support iceberg views. Tables that were created in the previous Iceberg versions have a NULL value in iceberg_type field.
This behaviour is expected, but it seems to cause commits to fail.

**How to reproduce the issue?**

**1. Create an environment with a rest-catalog, postgresql and spark. Sample docker-compose for convenience:**
```
version: '3.8'

services:
  spark:
    ports:
    - "15002:15002"
    - "4040:4040"
    image: spark:3.5.1
    entrypoint: >
      /opt/spark/bin/spark-submit
      --class org.apache.spark.sql.connect.service.SparkConnectServer
      --packages org.apache.spark:spark-connect_2.12:3.5.1,org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0
      --conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog
      --conf spark.sql.catalog.iceberg.catalog-impl=org.apache.iceberg.rest.RESTCatalog
      --conf spark.sql.catalog.iceberg.uri=http://rest-catalog:8181
      --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
      --conf spark.jars.ivy=/tmp
    networks:
    - app-network

  rest-catalog:
    image: tabulario/iceberg-rest:1.5.0
    environment:
      CATALOG_JDBC_USER: rest_catalog
      CATALOG_JDBC_PASSWORD: rest_catalog
      CATALOG_URI: jdbc:postgresql://postgres:5432/rest_catalog
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "rest_catalog"
      POSTGRES_PASSWORD: "rest_catalog"
      POSTGRES_DB: "rest_catalog"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Mount init script directory
    ports:
      - "5432:5432"
    networks:
      - app-network

  db-init:
    image: postgres:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: "rest_catalog"
      POSTGRES_PASSWORD: "rest_catalog"
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "rest_catalog"
    networks:
      - app-network
    command: >
      sh -c "
        until pg_isready -h postgres -p 5432; do
          echo 'Waiting for PostgreSQL to become ready...'
          sleep 1
        done;
        echo 'PostgreSQL is ready. Executing init script.';
        PGPASSWORD=$$POSTGRES_PASSWORD psql -h $$POSTGRES_HOST -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'GRANT ALL PRIVILEGES ON DATABASE $$POSTGRES_DB TO $$POSTGRES_USER;'
      "
networks:
  app-network:
    driver: bridge
volumes:
  postgres-data:
```

**2. Use Spark Connect to create a table and insert sample data:**
```
    ./bin/pyspark --remote "sc://localhost"
     >> spark.sql("create schema iceberg.test")
     >> spark.sql("create table iceberg.test.test_table (one string, two string, three string)")
     >> spark.sql("insert into iceberg.test.test_table VALUES ("I", "LOVE", "ICEBERG")
```

**3. Connect to the postgreSQL database and replace `iceberg_type` field with `NULL`**
```
      >> PGPASSWORD="rest_catalog" ./psql -h localhost -p 5432 -U rest_catalog -d rest_catalog -c "UPDATE iceberg_tables SET iceberg_type=NULL"
```
**4. Try inserting again:**
```
 >> spark.sql("insert into iceberg.test.test_table VALUES ('I', 'LOVE', 'ICEBERG')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/spark350/python/pyspark/sql/connect/session.py", line 550, in sql
    data, properties = self.client.execute_command(cmd.command(self._client))
  File "/opt/spark350/python/pyspark/sql/connect/client/core.py", line 982, in execute_command
    data, _, _, _, properties = self._execute_and_fetch(req)
  File "/opt/spark350/python/pyspark/sql/connect/client/core.py", line 1282, in _execute_and_fetch
    for response in self._execute_and_fetch_as_iterator(req):
  File "/opt/spark350/python/pyspark/sql/connect/client/core.py", line 1263, in _execute_and_fetch_as_iterator
    self._handle_error(error)
  File "/opt/spark350/python/pyspark/sql/connect/client/core.py", line 1502, in _handle_error
    self._handle_rpc_error(error)
  File "/opt/spark350/python/pyspark/sql/connect/client/core.py", line 1538, in _handle_rpc_error
    raise convert_exception(info, status.message) from None
pyspark.errors.exceptions.connect.SparkConnectGrpcException: (org.apache.iceberg.exceptions.CommitFailedException) Commit failed: Failed to update table test.test_table from catalog rest_backend


The same issue is observed in both Spark and Trino.

### PR DESCRIPTION
**Pull request by jbonofre**
This PR fixes table commit on the JDBC Catalog.

When upgrading JDBC Catalog SQL schema from `V0` to `V1`, the `iceberg_type` column is added with `NULL` value by default.
However, the SQL statement to update table (updating metadata location for instance) expects `iceberg_type` contains `TABLE`. It doesn't test if `iceberg_type` is `NULL`.

This PR updates the SQL statement to deal with `NULL` or `TABLE` for `iceberg_type`.

This closes #10046

### CODE REVIEW

**Comment by jbonofre** [comment]
I'm preparing tests to illustrate the original problem and demonstrate this fix works.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java [hunk 1]
```diff
@@ -54,7 +54,29 @@ enum SchemaVersion {
...
+          + CATALOG_NAME
+          + " = ? AND "
+          + TABLE_NAMESPACE
+          + " = ? AND "
+          + TABLE_NAME
+          + " = ? AND "
+          + JdbcTableOperations.METADATA_LOCATION_PROP
+          + " = ? AND ("
+          + RECORD_TYPE
+          + " = ?"
```
Comment (ajantha-bhat) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java:75]: Should we hardcode the record type to TABLE since it is only called for table?
Similar comment for the `V1_DO_COMMIT_VIEW_SQL`.

or may be we just have to add "OR RECORD_TYPE IS NULL" to previous `V1_DO_COMMIT_SQL` without new changes.

Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java:75]: Yes I can hardcode. Just adding the or clause won't work as we need the parenthesis.

**Comment by jbonofre** [comment]
@nastra @ajantha-bhat @danielcweeks The PR is ready for review. It fixes the commit issue on migrated tables (from `V0` to `V1` schema, where `iceberg_type` is `NULL`). I added a test to illustrate the issue (where it was failing before the fix on the SQL statement).

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java [hunk 2]
```diff
@@ -45,4 +51,97 @@ public void testFilterAndRemovePrefix() {
...
+        tables.next();
+        assertThat(tables.getString(JdbcUtil.TABLE_NAME)).isEqualTo("table1");
+        tables.next();
+        assertThat(tables.getString(JdbcUtil.TABLE_NAME)).isEqualTo("table2");
+      }
+
+      // updating the schema from V0 to V1
+      connections.newClient().prepareStatement(JdbcUtil.V1_UPDATE_CATALOG_SQL).execute();
+
+      // trying to add a table on the updated schema
```
Comment (ajantha-bhat) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:97]: can we add create one view after table3? and update it Because code is changed for view commit SQL also and tests can cover it.

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java [hunk 3]
```diff
@@ -45,4 +51,97 @@ public void testFilterAndRemovePrefix() {
...
+              JdbcUtil.SchemaVersion.V1,
+              connections,
+              "TEST",
+              TableIdentifier.of(Namespace.of("namespace1"), "table3"),
+              "newLocation",
+              "testLocation");
+      assertThat(updated).isEqualTo(1);
+
+      // update a table (commit) migrated from V0 schema
+      // this was failing before the fix from PR #10111
```
Comment (ajantha-bhat) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:135]: nit: PR comment is enough for reviewer. Maybe no need of code comment.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java [hunk 4]
```diff
@@ -54,7 +54,31 @@ enum SchemaVersion {
   static final String TABLE_RECORD_TYPE = "TABLE";
   static final String VIEW_RECORD_TYPE = "VIEW";
 
-  private static final String V1_DO_COMMIT_SQL =
```
Comment (ajantha-bhat) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java:57]: Do we also need to handle the same for `V1_DO_COMMIT_CREATE_SQL` ?

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java [hunk 5]
```diff
@@ -45,4 +51,97 @@ public void testFilterAndRemovePrefix() {
...
+
+      // inserting tables
+      JdbcUtil.doCommitCreateTable(
+          JdbcUtil.SchemaVersion.V0,
+          connections,
+          "TEST",
+          Namespace.of("namespace1"),
+          TableIdentifier.of(Namespace.of("namespace1"), "table1"),
+          "testLocation");
+      JdbcUtil.doCommitCreateTable(
```
[the remark this answers is not in the document]
Comment (jbonofre) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:75]: You mean `table1` is enough for the test ?

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java (hunk 2 above)
Comment (jbonofre) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:97]: Good point, I will add this.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java (hunk 4 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java:57]: It's not necessary as it creates the record, so populating cleanly the `iceberg_type`. The problem is just with the update where `iceberg_type` is used in the `WHERE` clause.

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (ajantha-bhat) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:75]: yeah

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java (hunk 4 above)
Comment (ajantha-bhat) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java:57]: Yeah, True. I just saw the pattern and commented (could have checked more). It is not needed here as it is an insert statement and not the query.

**Review by ajantha-bhat — APPROVED** [review]
some minor nits for tests. overall LGTM

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java [hunk 6]
```diff
@@ -45,4 +51,114 @@ public void testFilterAndRemovePrefix() {
 
     assertThat(expected).isEqualTo(actual);
   }
+
+  @Test
+  public void testV0toV1SqlStatements() throws Exception {
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:56]: I think it would make sense to have such a test where the Catalog API is used to create a table/view rathen than the underlying SQL statements

Comment (jbonofre) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:56]: I can do that in the `TestJdbcCatalog` using the API. The reason of this test was to focus on SQL statements.

Let me move this test in `TestJdbcCatalog`.

NB: I will check if the `TestTableCatalog` covers the commit workflow/use case.

Comment (nastra) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:56]: it's probably ok to keep these tests here, but users will always interact via the Catalog API, so we need to make sure that stuff works when such an upgrade is done and the Catalog API is used

Comment (jbonofre) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:56]: Agree, let me add a new test in `TestJdbcCatalog` using the facing API. Thanks @nastra !

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java (hunk 3 above)
Comment (amogh-jahagirdar) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:142]: Agree with @ajantha-bhat , I'd just remove the comment on 142. IMO It doesn't add useful info to someone who's reading the test.

Comment (jbonofre) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java:142]: OK, no problem. Let me remove this comment.

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 7]
```diff
@@ -239,6 +240,9 @@ public void testSchemaIsMigratedToAddViewSupport() throws Exception {
         .create();
 
     assertThat(jdbcCatalog.listViews(Namespace.of("namespace1"))).hasSize(1).containsExactly(view);
+
+    // testing append datafile to check commit, it should not throw an exception
+    jdbcCatalog.loadTable(tableOne).newAppend().appendFile(FILE_A).commit();
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:245]: I think we should also make sure that we can create a new table after migration and that the tables can be loaded. Something like this:

```
    TableIdentifier tableThree = TableIdentifier.of("namespace2", "table3");
    jdbcCatalog.createTable(tableThree, SCHEMA);
    assertThat(jdbcCatalog.tableExists(tableThree)).isTrue();

    // testing append datafile to check commit, it should not throw an exception
    jdbcCatalog.loadTable(tableOne).newAppend().appendFile(FILE_A).commit();
    jdbcCatalog.loadTable(tableTwo).newAppend().appendFile(FILE_B).commit();

    assertThat(jdbcCatalog.tableExists(tableOne)).isTrue();
    assertThat(jdbcCatalog.tableExists(tableTwo)).isTrue();
```

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 8]
```diff
@@ -1024,7 +1028,49 @@ public void report(MetricsReport report) {
...
+      result.next();
+      return result.getString(JdbcTableOperations.METADATA_LOCATION_PROP);
+    }
+  }
+
   private void initLegacySchema(String jdbcUrl) throws SQLException {
+    TableIdentifier table1 = TableIdentifier.of(Namespace.of("namespace1"), "table1");
+    TableIdentifier table2 = TableIdentifier.of(Namespace.of("namespace2"), "table2");
+
+    String table1MetadataLocation = createMetadataLocationViaJdbcCatalog(table1);
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:1071]: I don't have a strong opinion here but I think to get the `legacy` schema we might want to consider creating the table via the Catalog API and then dropping the `iceberg_type` field. It seems a bit odd to actually create the table just to fetch its metadata location so that we can insert it here.
I'm curious what others think here /cc @amogh-jahagirdar @danielcweeks

**Review by nastra — COMMENTED** [review]
the fix itself LGTM, just a few small comments around testing

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java (hunk 8 above)
Comment (amogh-jahagirdar) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:1079]: I'm also not super opinionated since I see that the current test does ultimately test the behavior we want to validate. 
I think @nastra suggestion of 
>get the legacy schema we might want to consider creating the table via the Catalog API and then dropping the iceberg_type field. 

 is probably cleaner, because I think it removes the need for the insert into statement with all the metadata file details etc. The only additional code would be the one to drop the `iceberg_type` field but I think that would be quite small in comparison (again all theoretical in my head :) ) ? So overall seems like that approach would be a net reduction in the test code and still be readable.

Either way not super opinionated, for the purpose of this PR I think we're good; we can cleanup in a follow on.

**Review by amogh-jahagirdar — APPROVED** [review]
Overall, the fix looks good to me. Thanks for taking this @jbonofre !

**Review by danielcweeks — APPROVED** [review]

**Comment by amogh-jahagirdar** [comment]
Looks like Flink CI timed out when running actions/cache before even running the actual tests. I'm going to retrigger and merge.
