### PR TITLE
API: add hashcode cache in StructType

### LINKED ISSUE #11763: Performance Regression Caused by Schema Hash in Spark PartitionPruning with Wide Tables
### Apache Iceberg version

1.5.0

### Query engine

Spark

### Please describe the bug 🐞

**Description**:
In Spark’s optimization rule *PartitionPruning*, the method `SparkBatchQueryScan#filterAttributes` is called, which triggers the computation of `Set<PartitionSpec> specs`. During this process, it iterates over each file and parses the jsonString into `PartitionSpec`. To avoid repeated parsing, a cache map was added in `org.apache.iceberg.PartitionSpecParser#fromJson` with  `(schema, jsonStr) -> PartitionSpec`.

However, when dealing with tables containing a large number of files and columns, **calculating the schema hash can consume significant CPU time**.

**Proposed Solution**:
Avro Schema mitigates this issue by **caching the schema’s hashCode** to avoid repeated computations. A similar optimization could be applied to Iceberg’s schema to reduce the performance regression caused by frequent schema hash calculations.

**Reproduction Example**:
I added a timer to the method `org.apache.iceberg.spark.source.SparkPartitioningAwareScan`

```java
  protected Set<PartitionSpec> specs() {
    if (specs == null) {
      long ts = System.currentTimeMillis();
      // avoid calling equals/hashCode on specs as those methods are relatively expensive
      IntStream specIds = tasks().stream().mapToInt(task -> task.spec().specId()).distinct();
      this.specs = specIds.mapToObj(id -> table().specs().get(id)).collect(Collectors.toSet());
      LOG.warn("Scanned {} specs in {} ms", specs.size(), System.currentTimeMillis() - ts);
    }

    return specs;
  }
```

and tested the following SQL query on a table with 900,000 files and 1500+ columns:

```sql
SELECT SUM(HASH(s.reqId + t.reqId)) 
FROM table s
JOIN table t
ON s.reqId = t.reqId and s.partition = 'part1' and t.partition = 'part1'
```

This query triggers `org.apache.spark.sql.execution.dynamicpruning.PartitionPruning` optimization rule twice. Before the task execution, **the driver spends approximately 150 seconds on pre-execution preparation, with over 140 seconds consumed in calculating PartitionSpec**.

**Flame Graph**:

**Thread Dump**:
```
java.base@17.0.9/java.util.Arrays.hashCode(Arrays.java:4499)
java.base@17.0.9/java.util.Objects.hash(Objects.java:133)
org.apache.iceberg.types.Types$NestedField.hashCode(Types.java:523)
java.base@17.0.9/java.util.Arrays.hashCode(Arrays.java:4499)
java.base@17.0.9/java.util.Objects.hash(Objects.java:133)
org.apache.iceberg.types.Types$ListType.hashCode(Types.java:763)
java.base@17.0.9/java.util.Arrays.hashCode(Arrays.java:4499)
java.base@17.0.9/java.util.Objects.hash(Objects.java:133)
org.apache.iceberg.types.Types$NestedField.hashCode(Types.java:523)
java.base@17.0.9/java.util.Arrays.hashCode(Arrays.java:4499)
org.apache.iceberg.types.Types$StructType.hashCode(Types.java:630)
java.base@17.0.9/java.util.Arrays.hashCode(Arrays.java:4499)
org.apache.iceberg.relocated.com.google.common.base.Objects.hashCode(Objects.java:79)
org.apache.iceberg.util.Pair.hashCode(Pair.java:117)
java.base@17.0.9/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2370)
org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
org.apache.iceberg.PartitionSpecParser.fromJson(PartitionSpecParser.java:86)
org.apache.iceberg.BaseContentScanTask.spec(BaseContentScanTask.java:71) => holding Monitor(org.apache.iceberg.BaseFileScanTask@520850087)
org.apache.iceberg.BaseFileScanTask.spec(BaseFileScanTask.java:34)
org.apache.iceberg.spark.source.SparkPartitioningAwareScan.lambda$specs$1(SparkPartitioningAwareScan.java:165)
org.apache.iceberg.spark.source.SparkPartitioningAwareScan$$Lambda$3617/0x00007f58ed482c28.applyAsInt(Unknown Source)
java.base@17.0.9/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
java.base@17.0.9/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
java.base@17.0.9/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
java.base@17.0.9/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
java.base@17.0.9/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
java.base@17.0.9/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.base@17.0.9/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
org.apache.iceberg.spark.source.SparkPartitioningAwareScan.specs(SparkPartitioningAwareScan.java:166)
org.apache.iceberg.spark.source.SparkBatchQueryScan.filterAttributes(SparkBatchQueryScan.java:103)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$.$anonfun$getFilterableTableScan$1(PartitionPruning.scala:82)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$$$Lambda$3616/0x00007f58ed48c3b0.apply(Unknown Source)
app//scala.Option.flatMap(Option.scala:271)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$.getFilterableTableScan(PartitionPruning.scala:62)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$$anonfun$prune$1.$anonfun$applyOrElse$1(PartitionPruning.scala:258)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$$anonfun$prune$1.$anonfun$applyOrElse$1$adapted(PartitionPruning.scala:241)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$$anonfun$prune$1$$Lambda$3615/0x00007f58ed48bfd0.apply(Unknown Source)
app//scala.collection.immutable.List.foreach(List.scala:431)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$$anonfun$prune$1.applyOrElse(PartitionPruning.scala:241)
app//org.apache.spark.sql.execution.dynamicpruning.PartitionPruning$$anonfun$prune$1.applyOrElse(PartitionPruning.scala:219)
```

**Environment**:
I tested this issue on Iceberg 1.5.0, and it is expected to persist in the latest version as well.

### Willingness to contribute

- [X] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by wzx140**
close #11763

### CODE REVIEW

**Comment by singhpk234** [comment]
Q: does it completely mitigate the flatness observed ? can you please attach the flame graph now ? 
Interesting find @wzx140

**Comment by wzx140** [comment]
> Q: does it completely mitigate the flatness observed ? can you please attach the flame graph now ? Interesting find @wzx140

**Performance Comparison After Adding Cache**

| Metric                      | Before Adding Cache | After Adding Cache |
|-----------------------------|---------------------|--------------------|
| Pre-execution Preparation Time | 154s                | 18s                |
| Scan Spec Time              | 142s                | 5s                 |

Pre-execution Preparation Time: the time interval from the first table load to the start of the first stage execution
Scan Spec Time: added a timer to the method SparkPartitioningAwareScan#specs


**Flame Graph**
Before Adding Cache: https://drive.google.com/file/d/1o68Q6n1c-BD7xwfM7ETO6fjbC3jjrlOr/view?usp=drive_link
After Adding Cache: https://drive.google.com/file/d/1YnGnEZ06Es7xs4fGVIZgnjDFS3L4cSR2/view?usp=drive_link

File: api/src/main/java/org/apache/iceberg/types/Types.java [hunk 1]
```diff
@@ -824,7 +827,10 @@ public boolean equals(Object o) {
 
     @Override
     public int hashCode() {
-      return Objects.hash(NestedField.class, Arrays.hashCode(fields));
+      if (hashCode == NO_HASHCODE) {
+        hashCode = Objects.hash(NestedField.class, Arrays.hashCode(fields));
+      }
+      return hashCode;
```
Comment (singhpk234) [inline api/src/main/java/org/apache/iceberg/types/Types.java:833]: can this have a multi-threaded access ? if yes can we have double check locking ? to avoid recompute

**Comment by singhpk234** [comment]
> Pre-execution Preparation Time: the time interval from the first table load to the start of the first stage execution
Scan Spec Time: added a timer to the method SparkPartitioningAwareScan#specs

sounds really promising, thank you for sharing @wzx140

File: api/src/main/java/org/apache/iceberg/types/Types.java (hunk 1 above)
Comment (wzx140) [reply api/src/main/java/org/apache/iceberg/types/Types.java:833]: In this scenario, there is no multi-threaded access, but the method `structType.hashCode` might be accessed by multiple threads in other contexts. 

I think the main purpose of this cache is to reduce a significant amount of redundant computation. Introducing additional complexity to completely avoid redundant computation might not be necessary, as even with multi-threaded access, the redundant computation would only occur a few times (up to the number of threads), which should be negligible.

Comment (amogh-jahagirdar) [reply api/src/main/java/org/apache/iceberg/types/Types.java:833]: Agreed, I don't think it's worth the complexity of double checked locking to avoid a little bit of redundant computation in the multi-threaded case.

File: api/src/main/java/org/apache/iceberg/types/Types.java [hunk 2]
```diff
@@ -723,6 +723,9 @@ public int hashCode() {
 
   public static class StructType extends NestedType {
     private static final Joiner FIELD_SEP = Joiner.on(", ");
+    private static final int NO_HASHCODE = Integer.MIN_VALUE;
+
+    private transient int hashCode = NO_HASHCODE;
```
Comment (amogh-jahagirdar) [inline api/src/main/java/org/apache/iceberg/types/Types.java:728]: Thanks for making this transient, when I saw this PR that's the one aspect I wanted to make sure was the case. We really don't want any weird issues that will happen in a distributed setting where the cached hashcode on one struct type is different than the hashcode for the same struct type that's on a different node (which can easily happen since hashcodes across JVMS can be different)

Making it transient will avoid all those kinds of issues.

**Review by amogh-jahagirdar — DISMISSED** [review]
Thanks @wzx140 this is a great finding! I'll hold before merging in case @aokolnychyi had any feedback.

File: api/src/main/java/org/apache/iceberg/types/Types.java [hunk 3]
```diff
@@ -723,6 +723,9 @@ public int hashCode() {
 
   public static class StructType extends NestedType {
     private static final Joiner FIELD_SEP = Joiner.on(", ");
+    private static final int NO_HASHCODE = Integer.MIN_VALUE;
```
Comment (amogh-jahagirdar) [inline api/src/main/java/org/apache/iceberg/types/Types.java:726]: I was originally going to suggest we follow the same pattern we do in `CharSequenceWrapper` where we have two fields, the hashCode and a boolean `hashIsZero` flag. This way in case the hashCode is actually zero we don't recompute it. 

In the current implementation, we would recompute the hashCode if it's actually Integer.MIN_VALUE but arguably not worth the complexity to handle that for this case.

**Review by Fokko — APPROVED** [review]

**Comment by amogh-jahagirdar** [comment]
I'm going to go ahead and merge this, it's been ready for a while and didn't want to miss this change going in for the next release! Thank you @wzx140 and thank you @singhpk234 @Fokko for reviewing.
