### PR TITLE
Core: Only validate the current partition specs

### LINKED ISSUE #5676: Core: Dropping an old partition column causes NPE (and corrupt metadata on v2 tables)
### Apache Iceberg version

0.14.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

On a format version 2 table, dropping an old partition column on an iceberg table causes a `NullPointerException` in `PartitionSpecBuilder`, and every subsequent operation on the table throws the same exception.

```java
java.lang.NullPointerException: Cannot find source column: 2
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:963)
	at org.apache.iceberg.PartitionSpec$Builder.add(PartitionSpec.java:517)
	at org.apache.iceberg.UnboundPartitionSpec.copyToBuilder(UnboundPartitionSpec.java:56)
	at org.apache.iceberg.UnboundPartitionSpec.bind(UnboundPartitionSpec.java:44)
	at org.apache.iceberg.PartitionSpecParser.fromJson(PartitionSpecParser.java:87)
```

On a v1 table, the table is still accessible after, but the `ALTER TABLE` throws the same NPE.

The issue is easily reproducible using the following script in a Spark Shell:

```sql
CREATE TABLE data.test_table (ts timestamp not null, day_of_ts date) USING iceberg PARTITIONED BY (day_of_ts);
ALTER TABLE data.test_table SET TBLPROPERTIES ('format-version' = '2');
ALTER TABLE data.test_table REPLACE PARTITION FIELD day_of_ts WITH days(ts);
ALTER TABLE data.test_table DROP COLUMN day_of_ts;
REFRESH TABLE data.test_table;
SELECT * FROM data.test_table;
```

On closer inspection of the metadata, I see that on a v1 table, the metadata is not updated when dropping the old partition field, which explains why the table is still working on v1 after, but I also don't see what the issue is with the v2 metadata.

I am using Spark Shell on Spark 3.3.0 with Iceberg 0.14.0

### PR DESCRIPTION
**Pull request by Fokko**
If a field is being deleted that used to be part of a partition spec, that will throw an error because it cannot resolve the field anymore. See the issue for more details.

Closes #5676

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/TableMetadataParser.java [hunk 1]
```diff
@@ -380,7 +380,12 @@ static TableMetadata fromJson(FileIO io, String metadataLocation, JsonNode node)
       // parse the spec array
       ImmutableList.Builder<PartitionSpec> builder = ImmutableList.builder();
       for (JsonNode spec : specArray) {
-        builder.add(PartitionSpecParser.fromJson(schema, spec));
+        UnboundPartitionSpec unboundSpec = PartitionSpecParser.fromJson(spec);
+        if (unboundSpec.specId() == defaultSpecId) {
+          builder.add(unboundSpec.bind(schema));
```
[the remark this answers is not in the document]
Comment (Fokko) [reply core/src/main/java/org/apache/iceberg/TableMetadataParser.java:385]: @singhpk234 Can you elaborate a bit more? I'm not sure that I understand the issue.

For V1, using the `spec` instead of `specs`, nothing changes. Since it takes the other branch: https://github.com/apache/iceberg/blob/24d5a53a0f90b47203eb3b93b0d141e154c36abe/core/src/main/java/org/apache/iceberg/TableMetadataParser.java#L393-L402

[the remark this answers is not in the document]
Comment (singhpk234) [reply core/src/main/java/org/apache/iceberg/TableMetadataParser.java:385]: Apologies for not being clear, 
What I meant here was, mapping the current specId to the current spec might still cause issue as in case of table of V1 format, (Considering the UT in this PR, last DDL) The current spec will have a void transform for `day_of_ts` since `day_of_ts` is dropped from partitioning (in V1 format, we replace this transform with a void transform). Now when we attempt to bind current schema with current partition spec, current schema will not have `day_of_ts`, but in `PartitionSpec#checkCompatibility` we will try to find `schema.findType(field.sourceId())`, from current schema for void transform of `day_of_ts` and it will fail, as we have removed `day_of_ts` from current schema.


A sample UT for repro (modified from this PR) : 

```java
  @Test
  public void testDropColumnOfOldPartitionField() {
    // default table created in v1 format
    sql(
        "CREATE TABLE %s (id bigint NOT NULL, ts timestamp, day_of_ts date) USING iceberg PARTITIONED BY (day_of_ts)",
        tableName);

    sql("ALTER TABLE %s REPLACE PARTITION FIELD day_of_ts WITH days(ts)", tableName);
    sql("ALTER TABLE %s DROP COLUMN day_of_ts", tableName);
  }
```

[the remark this answers is not in the document]
Comment (Fokko) [reply core/src/main/java/org/apache/iceberg/TableMetadataParser.java:385]: @singhpk234 Thanks for the thorough explanation. I wasn't aware of the replacement by a void transform, and it indeed has a similar issue:

image

[the remark this answers is not in the document]
Comment (singhpk234) [reply core/src/main/java/org/apache/iceberg/TableMetadataParser.java:385]: @Fokko , This [explanation](https://github.com/apache/iceberg/pull/924#issue-600524755) from @rdblue, nicely explains the motivation behind introducing void transforms in v1 format.

[the remark this answers is not in the document]
Comment (Fokko) [reply core/src/main/java/org/apache/iceberg/TableMetadataParser.java:385]: Thanks for linking @singhpk234, and that is indeed a very clear explanation and it makes a lot of sense.

I've added a condition to skip the validation when we encounter a `VoidTransform`. Since it is almost always compatible, I think we should be okay with that, but curious to hear what others think.

File: spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java [hunk 2]
```diff
@@ -421,6 +421,31 @@ public void testSparkTableAddDropPartitions() throws Exception {
         "spark table partition should be empty", 0, sparkTable().partitioning().length);
   }
 
+  @Test
+  public void testDropColumnOfOldPartitionFieldV1() {
+    // default table created in v1 format
+    sql(
+        "CREATE TABLE %s (id bigint NOT NULL, ts timestamp, day_of_ts date) USING iceberg PARTITIONED BY (day_of_ts)",
```
Comment (marton-bod) [inline spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java:428]: Shall we explicitly set format-version=1, in case the default changes in the future?

File: spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java [hunk 3]
```diff
@@ -421,6 +421,31 @@ public void testSparkTableAddDropPartitions() throws Exception {
...
+        tableName);
+
+    sql("ALTER TABLE %s REPLACE PARTITION FIELD day_of_ts WITH days(ts)", tableName);
+
+    sql("ALTER TABLE %s DROP COLUMN day_of_ts", tableName);
```
Comment (marton-bod) [inline spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java:433]: Can we also include a sql to read back the data from the table after the drop? We have noticed the same issue in Trino, but for us the drop column still succeeds, it's the subsequent read operations that start failing

Comment (Fokko) [reply spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java:433]: Thanks @marton-bod, the `ALTER TABLE` threw an exception before, but you are right that subsequent reads are also failing. Digging into this

Comment (ajantha-bhat) [reply spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java:433]: Hmm, Interesting. This is what I assumed would happen and went with spec change (disruptive change)

@marton-bod: I have tagged you in one of the slack discussions. Where I proposed spec change to handle this.  
If Fokko doesn't find an easy way to fix this, we can discuss my approach after his experiment.

File: spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java (hunk 2 above)
Comment (rdblue) [reply spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java:428]: @Fokko, it doesn't look like this change was pushed?

File: spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java [hunk 4]
```diff
@@ -421,6 +421,31 @@ public void testSparkTableAddDropPartitions() throws Exception {
         "spark table partition should be empty", 0, sparkTable().partitioning().length);
   }
 
+  @Test
+  public void testDropColumnOfOldPartitionFieldV1() {
```
Comment (rdblue) [inline spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java:425]: I don't think this is the right place to test this. There are partition spec evolution tests in core, which is a much better place than here.

**Review by rdblue — APPROVED** [review]
I think that this looks good as a first step. We should also add a test or two to exercise the read path and see if anything needs to be fixed there.

**Comment by rdblue** [comment]
Thanks for fixing this, @Fokko! I like this version of the fix.

File: spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java (hunk 2 above)
Comment (Fokko) [reply spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java:428]: I was working on a follow-up to fix the other issue in the read-path. I waited with pushing until I had a proper fix for this but turns out that it is a bit more complicated than I originally anticipated. I've created a new PR https://github.com/apache/iceberg/pull/5907

**Comment by hashhar** [comment]
after this change while you can drop partition columns such tables become broken if they hadn't been optimized before dropping the column. Basically see https://github.com/apache/iceberg/issues/4563
