### PR TITLE
Delta Migration: Handle delta lake's automatic log clean and VACUUM

### LINKED ISSUE #6781: Fix migration of Delta table that has performed VACUUM
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

based on offline discussion with @JonasJ-ap , VACUUM will mess up with delta log and some files cannot be found during migration. Because unlike Iceberg that cleans up snapshot entries, Delta still keeps all the logs. We should verify if that is a concern or not and provide a fix if necessary.

### PR DESCRIPTION
**Pull request by JonasJ-ap**
## Issue Fixed
This PR fixes #6781 .

The automatic log clean whenever a new checkpoint is created and the manual data file clean by `VACUUM` sometimes lead to inconsistency between the first constructable delta lake version and the earliest delta lake version in the table. The inconsistency will cause file not found errors during the migration.

This PR fix the issue by forcing the snapshot delta lake action to start from the first constructable delta lake version instead of the earliest version.

## Test
Added Integration tests to mock the file clean scenario.

### CODE REVIEW

File: delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java [hunk 1]
```diff
@@ -113,6 +124,8 @@ public static Object[][] parameters() {
   @Rule public TemporaryFolder temp3 = new TemporaryFolder();
   @Rule public TemporaryFolder temp4 = new TemporaryFolder();
   @Rule public TemporaryFolder temp5 = new TemporaryFolder();
+  @Rule public TemporaryFolder temp6 = new TemporaryFolder();
+  @Rule public TemporaryFolder temp7 = new TemporaryFolder();
```
Comment (jackye1995) [inline delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java:128]: can we try to avoid creating more temp folders? We should be able to reuse the same one for each test

**Review by jackye1995 — COMMENTED** [review]
thanks for the fix, overall looks good to me, just nit for test

**Comment by jackye1995** [comment]
This seems needed as a fix for Delta conversion to work properly, because most users run VACUUM against the table. Mark it as required for 1.2 release

File: delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java [hunk 2]
```diff
@@ -213,6 +218,52 @@ private PartitionSpec getPartitionSpecFromDeltaSnapshot(Schema schema) {
...
+          filesToAdd.add(dataFile);
+        }
+
+        // AppendFiles case
+        AppendFiles appendFiles = transaction.newAppend();
+        filesToAdd.forEach(appendFiles::appendFile);
+        appendFiles.commit();
+
+        return constructableStartVersion;
+      } catch (NotFoundException | IllegalArgumentException | DeltaStandaloneException e) {
```
Comment (amogh-jahagirdar) [inline delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java:258]: Just want to confirm we don't need to explicitly handle `IOException` here for when the file isn't found, we'll get a `NotFoundException`?

File: delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java [hunk 3]
```diff
@@ -213,6 +218,52 @@ private PartitionSpec getPartitionSpecFromDeltaSnapshot(Schema schema) {
...
+   * @return the initial version of the delta lake table that is successfully committed to iceberg
+   */
+  private long commitInitialDeltaSnapshotToIcebergTransaction(
+      long latestVersion, Transaction transaction) {
+    long constructableStartVersion = deltaStartVersion;
+    while (constructableStartVersion <= latestVersion) {
+      try {
+        List<AddFile> initDataFiles =
+            deltaLog.getSnapshotForVersionAsOf(constructableStartVersion).getAllFiles();
+        List<DataFile> filesToAdd = Lists.newArrayList();
```
[the remark this answers is not in the document]
Comment (amogh-jahagirdar) [reply delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java:246]: Actually nvm, this is not possible, this will end up being the files for a single initial snapshot.

File: delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java (hunk 2 above)
Comment (JonasJ-ap) [reply delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java:258]: Thank you for pointing this out. The `HadoopFileIO` re-throw `FileNotFoundExceptiion` as `NotFoundException` and general `IOException` as `RuntimeIOException`.

https://github.com/apache/iceberg/blob/b5a31a14d56c1ee24bad87e1ac7f119d638ee320/core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java#L159-L170

In this case, I think we only need to handle the `NotFoundException` since `VACUUM` may delete the data file. I've added a code block in `buildDataFileFromAction` to explicitly check file existence and throw `NotFoundException` if necessary.

Please let me know if you have any other concern here.

File: delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java (hunk 1 above)
Comment (JonasJ-ap) [reply delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java]: Thank you for your suggestion. I misunderstood the logic of this temp folder. I revised the code to reuse the same one for each test

File: delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java [hunk 4]
```diff
@@ -310,6 +351,11 @@ private DataFile buildDataFileFromAction(Action action, Table table) {
 
     FileFormat format = determineFileFormatFromPath(fullFilePath);
     InputFile file = deltaLakeFileIO.newInputFile(fullFilePath);
+    if (!file.exists()) {
+      throw new NotFoundException(
+          "The file %s does not exist in the Delta Lake table at %s",
+          fullFilePath, deltaTableLocation);
```
Comment (JonasJ-ap) [inline delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java:357]: I think checking file existence explicitly here can make the code logic more clear and have more reasonable error message

File: delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java [hunk 5]
```diff
@@ -122,28 +129,36 @@ public TestSnapshotDeltaLakeTable(
...
     externalDataFilesIdentifier = destName(defaultSparkCatalog, externalDataFilesTableName);
     typeTestIdentifier = destName(defaultSparkCatalog, typeTestTableName);
+    vacuumTestIdentifier = destName(defaultSparkCatalog, vacuumTestTableName);
+    logCleanTestIdentifier = destName(defaultSparkCatalog, logCleanTestTableName);
 
     spark.sql(String.format("DROP TABLE IF EXISTS %s", partitionedIdentifier));
     spark.sql(String.format("DROP TABLE IF EXISTS %s", unpartitionedIdentifier));
     spark.sql(String.format("DROP TABLE IF EXISTS %s", externalDataFilesIdentifier));
     spark.sql(String.format("DROP TABLE IF EXISTS %s", typeTestIdentifier));
+    spark.sql(String.format("DROP TABLE IF EXISTS %s", vacuumTestIdentifier));
```
Comment (jackye1995) [inline delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java:160]: Instead of creating one subfolder for each table, I think we can just create tabes within the test, and do a `DROP DATABASE CASCADE` call in the end to remove all the tables after all tests

File: delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java (hunk 4 above)
Comment (jackye1995) [reply delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java:357]: nit: we can be more precise about the message, something like "File %s is referenced in Delta lake metadata but cannot be found in storage"

File: delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java (hunk 5 above)
Comment (JonasJ-ap) [reply delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java]: Thank you for your suggestions. I refactored integration tests to create tables within the test and remove redundant sql commands.

File: delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java [hunk 6]
```diff
@@ -65,26 +68,23 @@ public class TestSnapshotDeltaLakeTable extends SparkDeltaLakeSnapshotTestBase {
...
-  private final String partitionedTableName = "partitioned_table";
-  private final String unpartitionedTableName = "unpartitioned_table";
-  private final String externalDataFilesTableName = "external_data_files_table";
-  private final String typeTestTableName = "type_test_table";
-  private final String snapshotPartitionedTableName = "iceberg_partitioned_table";
-  private final String snapshotUnpartitionedTableName = "iceberg_unpartitioned_table";
-  private final String snapshotExternalDataFilesTableName = "iceberg_external_data_files_table";
-  private final String snapshotNewTableLocationTableName = "iceberg_new_table_location_table";
-  private final String snapshotAdditionalPropertiesTableName =
+  private static final String partitionedTableName = "partitioned_table";
```
Comment (jackye1995) [inline delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java:71]: as best practice for testing, we can just hard code these names to individual tests, no need to make them static variables

File: delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java [hunk 7]
```diff
@@ -121,91 +117,28 @@ public TestSnapshotDeltaLakeTable(
...
-    spark.sql(
-        String.format(
-            "DROP TABLE IF EXISTS %s",
-            destName(icebergCatalogName, snapshotAdditionalPropertiesTableName)));
-    spark.sql(
-        String.format(
-            "DROP TABLE IF EXISTS %s", destName(icebergCatalogName, snapshotTypeTestTableName)));
-
-    spark.sql(String.format("DROP DATABASE IF EXISTS %s", NAMESPACE));
+    spark.sql(String.format("DROP DATABASE IF EXISTS %s CASCADE", NAMESPACE));
```
Comment (jackye1995) [inline delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java:130]: this should be in @AfterClass hook instead of @After

**Comment by JonasJ-ap** [comment]
Thanks @jackye1995, @amogh-jahagirdar for reviewing this. I added the file existence check and refactored the integration tests based on your suggestions. @amogh-jahagirdar May I ask if you could review this PR again? Thank you in advance for your help!

File: delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java [hunk 8]
```diff
@@ -454,7 +472,7 @@ private Dataset<Row> typeTestDataFrame() {
         .withColumn("structCol", expr("STRUCT(mapCol, arrayCol)"));
   }
 
-  private Dataset<Row> nestedDataFrame() {
+  private static Dataset<Row> nestedDataFrame() {
```
Comment (jackye1995) [inline delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java:475]: this can be a static variable instead of a static method

Comment (JonasJ-ap) [reply delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java]: Thank you for your suggestion. I moved the dataframe initialization code blocks to `BeforeClass`.

**Review by jackye1995 — APPROVED** [review]
looks good to me!

**Review by yyanyy — APPROVED** [review]

**Comment by jackye1995** [comment]
Merging, thanks for the fix @JonasJ-ap , and thanks for the review @yyanyy and @amogh-jahagirdar !
