### PR TITLE
Core: Lower the log level of warning message on refresh() for NoSuchIcebergTableException

### LINKED ISSUE #1428: Misleading warning message is logged for Spark Session Catalog with Hive type when end users query to non-Iceberg table
```
scala> spark.sql("select * from test").show()
20/08/27 20:10:35 WARN iceberg.BaseMetastoreTableOperations: Could not find the table during refresh, setting current metadata to null
org.apache.iceberg.exceptions.NoSuchIcebergTableException: Not an iceberg table: spark_catalog.default.test (type=null)
	at org.apache.iceberg.exceptions.NoSuchIcebergTableException.check(NoSuchIcebergTableException.java:32)
	at org.apache.iceberg.hive.HiveTableOperations.validateTableIsIceberg(HiveTableOperations.java:310)
	at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:114)
	at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:75)
	at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:59)
	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:135)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
	at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:66)
	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:124)
	at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:78)
	at org.apache.iceberg.spark.SparkSessionCatalog.loadTable(SparkSessionCatalog.java:117)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.loadTable(CatalogV2Util.scala:283)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.loaded$lzycompute$1(Analyzer.scala:1010)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.loaded$1(Analyzer.scala:1010)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.$anonfun$lookupRelation$3(Analyzer.scala:1022)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveRelations$$lookupRelation(Analyzer.scala:1021)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:977)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$9.applyOrElse(Analyzer.scala:962)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$3(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:72)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:90)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$2(AnalysisHelper.scala:87)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:399)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:237)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:397)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:350)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsUp$1(AnalysisHelper.scala:87)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp(AnalysisHelper.scala:86)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsUp$(AnalysisHelper.scala:84)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsUp(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:962)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:934)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:149)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:146)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:138)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:138)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:176)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:170)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:130)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:116)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:116)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:154)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:153)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:71)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:136)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:136)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:71)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:69)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:61)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:607)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:764)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:602)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:24)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:28)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:30)
	at $line16.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:32)
	at $line16.$read$$iw$$iw$$iw$$iw.<init>(<console>:34)
	at $line16.$read$$iw$$iw$$iw.<init>(<console>:36)
	at $line16.$read$$iw$$iw.<init>(<console>:38)
	at $line16.$read$$iw.<init>(<console>:40)
	at $line16.$read.<init>(<console>:42)
	at $line16.$read$.<init>(<console>:46)
	at $line16.$read$.<clinit>(<console>)
	at $line16.$eval$.$print$lzycompute(<console>:7)
	at $line16.$eval$.$print(<console>:6)
	at $line16.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:894)
	at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:762)
	at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:464)
	at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:485)
	at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:239)
	at org.apache.spark.repl.Main$.doMain(Main.scala:78)
	at org.apache.spark.repl.Main$.main(Main.scala:58)
	at org.apache.spark.repl.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
+---+-----+                                                                     
| id| data|
+---+-----+
|  3|abcde|
|  2| abcd|
|  1|  abc|
+---+-----+
```

If you only look at the output then the behavior is correct, but the warning message logged from Iceberg can be misleading, especially what the log level says. That exception is "expected" for such case, hence shouldn't be logged as warn message.

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Closes #1428 

This patch adjusts the log level on NoSuchTableException in refresh() with HiveCatalog, specific to the NoSuchIcebergTableException, which can be occurred in the "normal" case, like below:

1. Use default spark catalog with type=hive
2. Read non-iceberg table

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java [hunk 1]
```diff
@@ -75,7 +76,14 @@ public TableMetadata refresh() {
     try {
       doRefresh();
     } catch (NoSuchTableException e) {
-      LOG.warn("Could not find the table during refresh, setting current metadata to null", e);
+      // Adjust log level according to the type of exception, as it might be intentional to call
+      // the method without determining the type of table in prior (like SparkSessionCatalog),
+      // and in such case it may not be an error case if the table is not an Iceberg table.
+      if (e instanceof NoSuchIcebergTableException) {
```
Comment (HeartSaVioR) [inline core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:82]: It's also OK for me to just lower down the log level for NoSuchTableException, but would like to hear the voice first before applying it.

Comment (kbendick) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:82]: I'm also curious about the code flow here and hoping you can help me better understand it possibly @HeartSaVioR.

I see that the call to `refresh` here calls the pr`doRefresh` which is not implemented in this abstract class `BaseMetastoreTableOperations`, and I can't find any corresponding code that does implement `doRefresh` which extends this class (or even anywhere). However, I see similar classes that inherit from the higher up `TableOperations` interface which this also inherits from which implements their own version of `refresh` which does not rely on this abstract class. The example I'm thinking of is  [HadoopTableOperations](https://github.com/apache/iceberg/blob/c28d1c8ba6322af07f0206c4cf3fdad875f37ac1/core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java#L92).

In any case, if this call to `doRefresh` throws a `NoSuchTableException`, currently it logs it, resets some of the private fields to null / their respective empty values (e.g. -1 for `version` in this abstract class when it's an int, though in `HadoopTableOperations` which implements `TableOperations` it's not an `int` but a `volatile Integer` whose empty value is `null`). 

I guess my question is, I can't quite see where this call to this particular version of `refresh` is being accessed. When do we use `BaseMetastoreTableOperations` as opposed to one of the other implementations of `TableOperations` such as `HadoopTableOperations`? How can I determine when a specific `TableOperations` is being used? Additionally, as this class is marked as abstract but yet I can't find anything that extends / implements it, why do we have it? I also see that there is a python version of this class, so is it possible that the python version of the class is why this particular abstract class exists?

Additionally, In the `log.debug` case you're adding, I imagine that it is likely still necessary to set the current metadata and related fields to null / their empty values. However, do we still intend to rethrow the exception like it currently is done? Looking through the code, I think it would possibly break things if we don't rethrow, such as [BaseTransaction#commitReplaceTransaction(boolean orCreate)](https://github.com/apache/iceberg/blob/454101c3573acb9cd94d6d9a306ed99a5a324ed9/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L273) in the case that we're expecting the table to already exist (e.g. when the transaction is not allowed to create the table, that is if the transaction is not of type `CREATE_OR_REPLACE_TABLE` when calling `commitReplaceTransaction`).

So I have a few questions:
1) Why do we have this abstract base class `BaseMetastoreTableOperations` if nothing implements / extends it? I've mentioned a few reasons above, particularly the corresponding python class which is somewhat more complete.
2) How can we be sure when this version of `TableOperations` is in play vs any other? I'm assuming that when we're connected to an actual Hive Metastore (vs using Hadoop filesystem and table properties for the metadata), then this class comes into play, but since it's abstract and not extended I fail to see how that's possible.
3) The current behavior is to rethrow the exception. In the case that we are using the debug log, do we know that the upstream callers will catch this and not additionally add their own logs of a higher level and/or are we concerned that we are rethrowing the `NoSuchIcebergTableException`?

Please let me know if you need me to clean up / reexplain some of my questioning, as I know it's somewhat convoluted. I'm doing my best to understand when this class comes into play and how but a little bit of assistance from somebody who knows much more than I do (or a link to possible documentation about it) would really help me out. Thanks for all of the work you put in @HeartSaVioR!

Comment (kbendick) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:82]: Oh. I wasn't also considering all of the various `Catalog` classes, which don't implement `TableOperations` but rely on them pretty heavily.  My question of when is it useful to have an abstract class that is not extended still stands (question 1 above), but I can see now more of the places where this code likely comes into play. Thanks so much for helping me get up to speed on the parts of codebase that I'm less familiar with. As I gain more practical experience using Iceberg, I'm sure it will become much more clear to me. Fortunately, I've finally gotten it all running on a modified k8s cluster somewhere for my own personal practice. 👍

Comment (HeartSaVioR) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:82]: Oh probably there's some miscommunication here.

I'm a contributor (same as you) and don't know about the rationalization/intention of the codebase around here. My changes so far have been intended to fix something I encountered during experiments, not from learning on the codebase and making something beauty. (I'd love to if I'm qualified, but I lack of knowledge on the codebase so far.)

Also I'm trying to change smaller while contributing so that I don't break any intentions behind the wall. I'm self-commenting in the PR to ask about the viewpoint from committers, to confirm before making change.

Back to the question, it might be OK to just remove the log message if we have faith on the callers to handle the exception well. We are throwing the exception in the method which says callers also have a chance to log it properly, swallow if it doesn't worth to log. That is also a question for reviewers as well.

Comment (HeartSaVioR) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:82]: The reason I lower down the log level only for NoSuchIcebergTableException is to avoid noisy and misleading log message for this case; 1) use default catalog in Spark 3, with hive catalog 2) try to load the table which is "not" the iceberg table.

... and probably we just want to lower down the log level (or not log at all) with NoSuchTableException, as the condition 2) has two different situations 2.a) table exists in HMS but isn't an iceberg table 2.b) table doesn't exist. 2.b is probably also the valid case if Spark doesn't connect with Hive via remote HMS, which we also don't want to let end users see this noise.

WDYT? (for all reviewers)

**Comment by rdblue** [comment]
+1 for fixing this when called from a different catalog. We see these exceptions all the time in normal use and I've been meaning to implement a fix for it.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java (hunk 1 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:82]: To answer most of @kbendick's questions: this is extended by `HiveTableOperations`. It is also the recommended way to support a [custom metastore](http://iceberg.apache.org/custom-catalog/), which is what we do at Netflix.

The reason why this warning exists is to catch the case where a table is deleted concurrently. The Hive implementation throws the exception when [current metadata is not null but the table doesn't exist](https://github.com/apache/iceberg/blob/454101c3573acb9cd94d6d9a306ed99a5a324ed9/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L125). The table instance needs to be in a consistent state if it is reused for a create, which is why we set the metadata to null. At the time, we considered `NoSuchTableException` to be more rare than it is with the wrapped catalogs.

I think a better solution is to log the warning only when the table previously had metadata. What we could do is check before calling `doRefresh` whether `currentMetadata` is null. If it is not, then we want to log the warning. Otherwise, we should let it go through. We always want to re-throw because the caller is responsible for handling the exception. This is supposed to be helpful context.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java [hunk 2]
```diff
@@ -72,10 +73,14 @@ public int currentVersion() {
...
+    boolean currentMetadataWasAvailable = currentMetadata != null;
     try {
       doRefresh();
     } catch (NoSuchTableException e) {
-      LOG.warn("Could not find the table during refresh, setting current metadata to null", e);
+      if (currentMetadataWasAvailable) {
+        LOG.warn("Could not find the table during refresh, setting current metadata to null", e);
+      }
+
       currentMetadata = null;
```
Comment (HeartSaVioR) [inline core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:84]: I'm not 100% certain that re-setting fields is valid only for when the if statement is true. If then we can move things into if statement, but otherwise I guess it can be left as it is. At least leaving it as it is won't hurt anything.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java (hunk 1 above)
Comment (HeartSaVioR) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java]: Thanks for the suggestion! I've applied your review comment.

Probably worth leaving a code comment to explain the context around existence of warning message, but we can simply skip it if we feel it's now straightforward. WDYT?

File: core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java (hunk 2 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java:83]: I think this is okay as it is.

File: core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java (hunk 1 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java]: I think it looks good now. I'll merge this. Thanks!

**Comment by rdblue** [comment]
Merged! Thanks for this fix, @HeartSaVioR. It's been annoying me.

**Comment by HeartSaVioR** [comment]
Thanks all for reviewing and merging!
