### PR TITLE
Fix variant type filtering in ParquetMetricsRowGroupFilter

### LINKED ISSUE #14071: Filtering on VARIANT fields does not return expected results Iceberg 1.10.0 Spark 4.0.0
### Apache Iceberg version

1.10.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

When using try_variant_get (or variant_get) to extract fields from a VARIANT column in Iceberg, filtering on the extracted field in the WHERE clause does not return the expected results, even though the field can be successfully selected and shows the correct type in the schema.

Create a users Iceberg table with a VARIANT column:
```
spark.sql("""
CREATE TABLE IF NOT EXISTS dev.default.users (
    id BIGINT,
    properties VARIANT
)
USING iceberg
TBLPROPERTIES ('format-version' = '3')
""")

```

Insert sample data:
```

from pyspark.sql.functions import col, parse_json

users_data = [
    (1, '{ "name": "Alice", "age": 30, "address": {"city": "Wonderland"} }'),
    (2, '{ "name": "Bob", "age": 40, "address": {"city": "Builderland"} }'),
    (3, '{ "name": "Charlie", "age": 28, "address": {"city": "Dreamtown"} }')
]

df_users = spark.createDataFrame(users_data, ["id", "json_string"])
df_users_variant = df_users.withColumn("properties", parse_json(col("json_string"))).drop("json_string")
df_users_variant.writeTo("dev.default.users").overwritePartitions()

```

```
df = spark.sql("""
SELECT
  try_variant_get(properties, '$.name', 'string') AS name,
  try_variant_get(properties, '$.age', 'int') AS age,
  try_variant_get(properties, '$.address.city', 'string') AS city
FROM dev.default.users
""")

df.printSchema()
df.show()


root
 |-- name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- city: string (nullable = true)

+-------+---+-----------+
|   name|age|       city|
+-------+---+-----------+
|Charlie| 28|  Dreamtown|
|  Alice| 30| Wonderland|
|    Bob| 40|Builderland|
+-------+---+-----------+

```

Attempt to filter on the extracted field:
```
spark.sql("""
SELECT
  try_variant_get(properties, '$.name', 'string') AS name,
  try_variant_get(properties, '$.age', 'int') AS age,
  try_variant_get(properties, '$.address.city', 'string') AS city
FROM dev.default.users
WHERE try_variant_get(properties, '$.age', 'int') >= 28
""").show(truncate=False)
+---+----+---+----+
|id |name|age|city|
+---+----+---+----+
+---+----+---+----+

```

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by geruh**
Fixes #14071

Variant types were not handled correctly in Parquet row group filtering. The `ParquetMetricsRowGroupFilter.notNull()` needs to account for variant types which require post scan evaluation to access shredded statistics for nested field filtering, similar to structs are handled.

This change ensures variant columns are properly handled during Parquet metrics evaluation, allowing row groups with variant data to be correctly included for post-scan filtering rather than being incorrectly filtered out at the row group level.

### Testing 
  - testVariantFilterNotNull(): test with mixed variant/null data
  - testAllNullsVariantNotNull(): Edge case with all-null variant columns
  - TestInclusiveMetricsEvaluatorWithExtract.java already provides extensive coverage of variant extract expressions

### CODE REVIEW

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java [hunk 1]
```diff
@@ -988,6 +993,97 @@ public void testTransformFilter() {
...
+          VariantMetadata metadata = Variants.metadata("field");
+          ShreddedObject obj = Variants.object(metadata);
+          obj.put("field", Variants.of("value" + i));
+          Variant variant = Variant.of(metadata, obj);
+          record.setField("variant_field", variant);
+        }
+
+        appender.add(record);
+      }
+    }
```
Comment (amogh-jahagirdar) [inline data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: Why do we need to write records in these tests? At this level of abstraction, I think we should just create the row group filter with the `notNull("variant_field")` and it assert that shouldRead is true.

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java [hunk 2]
```diff
@@ -988,6 +993,97 @@ public void testTransformFilter() {
...
+            .build()) {
+
+      for (int i = 0; i < 10; i++) {
+        GenericRecord record = GenericRecord.create(variantSchema);
+        record.setField("id", i);
+        record.setField("variant_field", null);
+        appender.add(record);
+      }
+    }
+
```
Comment (amogh-jahagirdar) [inline data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: Same as above, don't think we need to actually write parquet files in these tests

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java [hunk 3]
```diff
@@ -157,8 +157,10 @@ public <T> Boolean notNull(BoundReference<T> ref) {
 
       // When filtering nested types notNull() is implicit filter passed even though complex
       // filters aren't pushed down in Parquet. Leave all nested column type filters to be
-      // evaluated post scan.
-      if (schema.findType(id) instanceof Type.NestedType) {
+      // evaluated post scan. Variant types also need to be evaluated post scan to access
+      // shredded statistics.
```
Comment (amogh-jahagirdar) [inline parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java]: I'd remove the "variant types also need to be evaluated post scan to access shredded statistics". I'd just update to reflect the current state of things which is in that first sentence, "When filtering nested types or variant...." and the second sentence to be "Leave these type filters...".


For shredded stats pruning, the core library already contains `BoundExtract`, what we need is the translation/plumbing from engines to that extract, and then I think we can do pruning based on the shredded stats. For now though , I'd just leave it out of comments since I think it's more confusing and a bit inaccurate.

**Comment by amogh-jahagirdar** [comment]
I also think this is something that should go into a 1.10.1 patch release since it's unfortunately a correctness issue

**Comment by amogh-jahagirdar** [comment]
cc @aihuaxu

**Review by amogh-jahagirdar — COMMENTED** [review]
Also can we double check some of the other cases like `eq`, `in`..? The spark tests would surface that as well

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java [hunk 4]
```diff
@@ -157,8 +157,10 @@ public <T> Boolean notNull(BoundReference<T> ref) {
...
+      Type type = schema.findType(id);
+      if (type instanceof Type.NestedType || type.isVariantType()) {
```
Comment (RussellSpitzer) [inline parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java:162]: +1

File: parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java (hunk 3 above)
Comment (aihuaxu) [reply parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java]: +1 on this.

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java (hunk 1 above)
Comment (aihuaxu) [reply data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: +1. Seems we don't need to write to the files.

Comment (geruh) [reply data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: Thanks for the feedback Amogh! 

Good point about avoiding file writing at this level. I initially wrote the tests this way because this test class shares a schema for writing out data files in both ORC and Parquet. We're now in a situation where ORC doesn't have full support for variant types while Parquet does, so adding variant fields to the shared schema would break the existing ORC tests.

That said, it probably makes sense to use separate schemas for Parquet and ORC given the differnt levels of support.  and write the tests to reflect that.

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java (hunk 2 above)
Comment (geruh) [reply data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: addressed above

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java (hunk 1 above)
Comment (amogh-jahagirdar) [reply data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: Talked with @geruh offline and I also poked around refactoring this class, and while I think we should (this mixture of orc/parquet both trying to test "row group filtering" is leading to weird tests), it's a big change especially for something going into a patch release.

Also while technically the implementation of filtering with variant doesn't depend on the actual contents of the file, after some more thought I concluded that it's better to write a more realistic test which does contain the records like @geruh was doing before.

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java [hunk 5]
```diff
@@ -988,6 +1004,158 @@ public void testTransformFilter() {
...
+        record.setField("id", i);
+
+        if (i % 2 == 0) {
+          VariantMetadata metadata = Variants.metadata("field");
+          ShreddedObject obj = Variants.object(metadata);
+          obj.put("field", Variants.of("value" + i));
+          Variant variant = Variant.of(metadata, obj);
+          record.setField("variant_field", variant);
+        }
+
```
Comment (amogh-jahagirdar) [inline data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: Can we have a helper that just takes in the list of records and writes the parquet file:

```
private File writeParquetFile(String namePrefix, Schema schema, List<GenericRecord> records) throws IOException {
    File parquetFile = new File(tempDir, namePrefix + System.nanoTime());
    OutputFile outFile = Files.localOutput(parquetFile);
    try (FileAppender<GenericRecord> appender =
            Parquet.write(outFile)
                   .schema(schema)
                   .createWriterFunc(GenericParquetWriter::create)
                   .build()) {
        for (GenericRecord record : records) {
            appender.add(record);
        }
    }
    parquetFile.deleteOnExit(); // Optional: ensure cleanup
    return parquetFile;
}
```

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java [hunk 6]
```diff
@@ -600,7 +654,7 @@ private void checkFilters(
     if (sparkFilter != null) {
       assertThat(planAsString)
           .as("Post scan filter should match")
-          .contains("Filter (" + sparkFilter + ")");
+          .containsAnyOf("Filter (" + sparkFilter + ")", "Filter " + sparkFilter);
```
Comment (amogh-jahagirdar) [inline spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java:672]: Are the filters on variant missing the parens?

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java (hunk 5 above)
Comment (geruh) [reply data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]: That is already above? Unless I'm missing something.

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java (hunk 6 above)
Comment (geruh) [reply spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java:672]: No this is specific to the spark filters. I added this so we can capture a simple spark filter. e.g. when spark doesn't apply a `NOT NULL` check to a filter. This is observed with `IN` predicates where Spark doesn't add the implicit `IS NOT NULL` check, resulting in simpler filter expressions without parentheses.

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java [hunk 7]
```diff
@@ -79,6 +80,12 @@ protected void assertEquals(String context, Object[] expectedRow, Object[] actua
         } else {
           assertEquals(newContext, (Object[]) expectedValue, (Object[]) actualValue);
         }
+      } else if (expectedValue instanceof VariantVal && actualValue instanceof VariantVal) {
+        // Spark VariantVal comparison is based on raw byte[] comparison, which can fail
+        // if Spark uses trailing null bytes. so, we compare their JSON representation instead.
+        assertThat((actualValue).toString())
+            .as("%s contents should match (VariantVal JSON)", context)
+            .isEqualTo((expectedValue).toString());
```
Comment (amogh-jahagirdar) [inline spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java]: Discussed offline, I think it's reasonable to compare the JSON representation to determine if the logical variant is equivalent.

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java [hunk 8]
```diff
@@ -988,6 +1004,67 @@ public void testTransformFilter() {
...
+        record.setField("variant_field", variant);
+      }
+      records.add(record);
+    }
+
+    File parquetFile = writeParquetFile("test-variant", VARIANT_SCHEMA, records);
+    InputFile inFile = Files.localInput(parquetFile);
+    try (ParquetFileReader reader = ParquetFileReader.open(parquetInputFile(inFile))) {
+      BlockMetaData blockMetaData = reader.getRowGroups().get(0);
+      MessageType fileSchema = reader.getFileMetaData().getSchema();
```
Comment (amogh-jahagirdar) [inline data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java:1029]: Non-blocking nit: I also feel like we can abstract reading the parquet block metadata/schema in a helper too.

File: spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java [hunk 9]
```diff
@@ -79,6 +80,12 @@ protected void assertEquals(String context, Object[] expectedRow, Object[] actua
         } else {
           assertEquals(newContext, (Object[]) expectedValue, (Object[]) actualValue);
         }
+      } else if (expectedValue instanceof VariantVal && actualValue instanceof VariantVal) {
+        // Spark VariantVal comparison is based on raw byte[] comparison, which can fail
+        // if Spark uses trailing null bytes. so, we compare their JSON representation instead.
+        assertThat((actualValue).toString())
```
Comment (nastra) [inline spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java]:
```suggestion
        assertThat(actualValue).asString()
```

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java [hunk 10]
```diff
@@ -988,6 +1004,67 @@ public void testTransformFilter() {
...
+
+    try (ParquetFileReader reader = ParquetFileReader.open(parquetInputFile(inFile))) {
+      BlockMetaData blockMetaData = reader.getRowGroups().get(0);
+      MessageType fileSchema = reader.getFileMetaData().getSchema();
+
+      ParquetMetricsRowGroupFilter rowGroupFilter =
+          new ParquetMetricsRowGroupFilter(VARIANT_SCHEMA, notNull("variant_field"), true);
+      boolean shouldRead = rowGroupFilter.shouldRead(fileSchema, blockMetaData);
+
+      assertThat(shouldRead)
```
Comment (nastra) [inline data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]:
```suggestion
      assertThat(rowGroupFilter.shouldRead(fileSchema, blockMetaData))
```

File: data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java [hunk 11]
```diff
@@ -988,6 +1004,67 @@ public void testTransformFilter() {
...
+
+    File parquetFile = writeParquetFile("test-variant", VARIANT_SCHEMA, records);
+    InputFile inFile = Files.localInput(parquetFile);
+    try (ParquetFileReader reader = ParquetFileReader.open(parquetInputFile(inFile))) {
+      BlockMetaData blockMetaData = reader.getRowGroups().get(0);
+      MessageType fileSchema = reader.getFileMetaData().getSchema();
+      ParquetMetricsRowGroupFilter rowGroupFilter =
+          new ParquetMetricsRowGroupFilter(VARIANT_SCHEMA, notNull("variant_field"), true);
+      boolean shouldRead = rowGroupFilter.shouldRead(fileSchema, blockMetaData);
+      assertThat(shouldRead)
```
Comment (nastra) [inline data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java]:
```suggestion
      assertThat(rowGroupFilter.shouldRead(fileSchema, blockMetaData))
```

**Comment by amogh-jahagirdar** [comment]
Thanks @geruh! Thank you @aihuaxu @RussellSpitzer @nastra for reviewing.
