### PR TITLE
Core: Check table UUID in RESTTableOperations

### LINKED ISSUE #14337: RESTTableOperations refresh does not enforce Table UUID check
### Apache Iceberg version

1.10.0 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

HiveTableOperations (BaseMetastoreTableOperations) does enforce Table UUID check when refreshing TableMetadata

[https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L205](https://urldefense.com/v3/__https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java*L205__;Iw!!GjvTz_vk!Uvj5WnOtY_qAZa_DQJg_x11_VIfd1vSyyeRtXqdrMtfW92ybk56CuCkk7EvRwVAy8L7950jh$)

 

However, RESTTableOperations does not enforce Table UUID check when refreshing TableMetadata

[https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java#L172](https://urldefense.com/v3/__https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java*L172__;Iw!!GjvTz_vk!Uvj5WnOtY_qAZa_DQJg_x11_VIfd1vSyyeRtXqdrMtfW92ybk56CuCkk7EvRwVAy8KAyWJpA$)

A table can be dropped and recreated under the same name (but under a new UUID) on the RESTCatalog server side, clients shall receive exceptions in such case instead of silently accepting new TableMetadata corresponding to the new UUID.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [x] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #14337

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java [hunk 1]
```diff
@@ -175,12 +175,25 @@ private TableMetadata updateCurrentMetadata(LoadTableResponse response) {
     // safely ignored. there is no requirement to update config on refresh or commit.
     if (current == null
         || !Objects.equals(current.metadataFileLocation(), response.metadataLocation())) {
-      this.current = response.tableMetadata();
+      this.current = checkUUID(current, response.tableMetadata());
```
Comment (singhpk234) [inline core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java:250]: This seems reasonable to me

File: core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java [hunk 2]
```diff
@@ -175,12 +175,25 @@ private TableMetadata updateCurrentMetadata(LoadTableResponse response) {
...
+    String newUUID = newMetadata.uuid();
+    if (currentMetadata != null && currentMetadata.uuid() != null && newUUID != null) {
+      Preconditions.checkState(
+          newUUID.equals(currentMetadata.uuid()),
+          "Table UUID does not match: current=%s != refreshed=%s",
+          currentMetadata.uuid(),
+          newUUID);
+    }
+
+    return newMetadata;
```
Comment (singhpk234) [inline core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java:266]: [optional to consider] wonder if we can move this to some place common `validate(current, newMetadata)` so that both BaseMetaStoreOperation and TableOperation (may be an util or just default impl of TableOps) can share it, but seems too much for ROI.

File: core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java (hunk 1 above)
Comment (huaxingao) [reply core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java:250]: +1 for this fix. Also +1 for adding a test

Comment (ebyhr) [reply core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java:250]: Thanks for the suggestion. Added a unit test.

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 3]
```diff
@@ -2884,6 +2885,48 @@ public void testETagWithRegisterTable() {
...
 
+  @Test
+  void testDifferentTableUUID() {
+    RESTCatalogAdapter adapter = Mockito.spy(new RESTCatalogAdapter(backendCatalog));
+    RESTCatalog catalog = catalog(adapter);
+
+    catalog.createNamespace(TABLE.namespace());
+    catalog.createTable(TABLE, SCHEMA);
+
+    // inject the wrong table UUID
```
Comment (singhpk234) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java]: nit: simulate drop and re-create the table with same name

**Review by huaxingao — APPROVED** [review]

**Comment by ebyhr** [comment]
Rebased on main to resolve conflicts.

**Comment by ebyhr** [comment]
@singhpk234 @huaxingao Can we merge this PR?

**Comment by huaxingao** [comment]
Thanks @ebyhr for the PR! Thanks @singhpk234 for the review!
