### PR TITLE
API, Build: Explicitly pass version into Git Properties Plugin

### LINKED ISSUE #12926: Core, Release: 1.9.0 Build Version() returns Unspecified due to incorrect packaged iceberg-build.properties
### Apache Iceberg version

1.9.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

Apache Iceberg 1.9.0 (java library)

iceberg-api-1.9.0.jar contains iceberg-build.properties

The contents of `iceberg-build.properties` is incorrect 

```
$ cat iceberg-build.properties 

```

Output:
```
git.branch=1.9.x
git.build.version=unspecified
git.closest.tag.name=apache-iceberg-1.9.0-rc2
git.commit.id=7dbafb438ee1e68d0047bebcb587265d7d87d8a1
git.commit.id.abbrev=7dbafb4
git.commit.message.short=API\: Don't check underlying error msg on AIOOBE (\#12867)
git.commit.time=2025-04-22T15\:14\:07+0200
git.tags=apache-iceberg-1.9.0-rc2
```

🏓  "git.build.version" should be "1.9.0"

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [x] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by RussellSpitzer**
Fixes #12926

The underlying issue is that we automatically bumped the Git Properties plugin which now uses a slightly different mechanism for determining what the version of the project is from before. To avoid any issues in the future, I decided to just explicitly pass in our custom version function to the plugin. 

I then added a few tests to check that we don't have an undefined value and if a version.txt file is present make sure it matches.

### CODE REVIEW

File: api/src/test/java/org/apache/iceberg/TestIcebergBuild.java [hunk 1]
```diff
@@ -37,6 +41,26 @@ public void testFullVersion() {
...
+
+  /**
+   * This test is for Source Releases. When we have a source release we use a version.txt file in
+   * the parent directory of this module to actually set the "version" which should be included in
+   * the gradle build properties used by IcebergBuild.
+   */
+  @Test
+  public void testVersionMatchesFile() throws IOException {
+    Path versionPath = Paths.get("../version.txt").toAbsolutePath();
+    assumeThat(java.nio.file.Files.exists(versionPath)).isTrue();
```
Comment (ajantha-bhat) [inline api/src/test/java/org/apache/iceberg/TestIcebergBuild.java:57]: nit: 

If we set the `project.version` in the system property for tests in `build.gradle`

```
test {
    systemProperty "project.version", project.version
}
```

we can always check 

```
assertThat(IcebergBuild.version())
        .isEqualTo(System.getProperty("project.version"))
```

This way we don't need two testcase and also it won't be a conditional test.

**Review by HonahX — APPROVED** [review]
LGTM!

File: api/src/test/java/org/apache/iceberg/TestIcebergBuild.java [hunk 2]
```diff
@@ -37,6 +41,34 @@ public void testFullVersion() {
                 + ")");
   }
 
+  @Test
+  public void testVersionNotUnspecified() {
+    assertThat(IcebergBuild.version()).isNotEqualTo("unspecified");
+  }
+
+  @Test
```
Comment (RussellSpitzer) [inline api/src/test/java/org/apache/iceberg/TestIcebergBuild.java:49]: @ajantha-bhat Added this test, all good?

**Review by amogh-jahagirdar — APPROVED** [review]
Thanks @RussellSpitzer!

**Comment by amogh-jahagirdar** [comment]
I'll go ahead and merge, thank you @RussellSpitzer for digging into it, and thanks @ajantha-bhat @singhpk234 @HonahX for reviewing. Thank you @sullis for reporting this issue as well!

**Review by jbonofre — COMMENTED** [review]
LGTM (sorry I'm just waking up :)).

**Review by sullis — COMMENTED** [review]
lgtm

File: api/src/test/java/org/apache/iceberg/TestIcebergBuild.java (hunk 2 above)
Comment (ajantha-bhat) [reply api/src/test/java/org/apache/iceberg/TestIcebergBuild.java:49]: Thanks
