### PR TITLE
Core: Add validation for row-level deletes with rewrites

### LINKED ISSUE #2308: Handle the case that RewriteFiles and RowDelta commit the transaction at the same time
Since we've introduced row-level delete in format v2, so we will encounter the problem that RewriteFiles and RowDelta commit the transaction at the same time.

Assume that we have an iceberg table `test`, and has the following events: 

```python
INSERT   <1, 'AAA'>
INSERT   <2, 'BBB'>
DELETE   <1, 'AAA'>
```

At the timestamp `t1`,  someone start a rewrite action to rewrite the whole table. 

At the timestamp `t2`,  someone start another transaction to update the rows in table `test`: 

```python
DELETE <2, 'BBB'>
```

At the timestamp `t3`,  the update txn (which started from `t2`) commit the txn successfully. 

At the timestamp `t4`,  the rewrite action commit the txn successfully.

Finally, the table will have one row `<2, 'BBB'>`, while in fact we should have no rows.  That's an unexpected bug after introducing format v2,  and we will need solution to handle it.

### PR DESCRIPTION
**Pull request by rdblue**
This adds a new validation for `RewriteFiles` that checks whether delete files have been added for any of the files that are being rewritten. The check constructs a delete file index for all the delete files in snapshots written since a starting snapshot and filters the delete file entries using the sequence number of the starting snapshot to ensure that only delete files that were added after the starting snapshot are indexed. Next, if any data file being replaced matches a delete file in the index, a validation exception is thrown.

This also updates actions to correctly set the starting snapshot ID for validation.

This fixes #2308.

### CODE REVIEW

**Comment by rdblue** [comment]
@cwsteinbach FYI

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java [hunk 1]
```diff
@@ -62,6 +63,9 @@
       ImmutableSet.of(DataOperations.OVERWRITE, DataOperations.REPLACE, DataOperations.DELETE);
   private static final Set<String> VALIDATE_DATA_FILES_EXIST_SKIP_DELETE_OPERATIONS =
       ImmutableSet.of(DataOperations.OVERWRITE, DataOperations.REPLACE);
+  // delete files are only added in "overwrite" operations
```
Comment (chenjunjiedada) [inline core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:66]: The rewrite deletes action will replace old deletes with new ones. Does that count add deletes operation?

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java [hunk 2]
```diff
@@ -297,6 +283,38 @@ protected void validateAddedDataFiles(TableMetadata base, Long startingSnapshotI
     }
   }
 
+  /**
+   * Validates that no new delete files have been added to the table since a starting snapshot.
```
Comment (chenjunjiedada) [inline core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:287]: I think this is no new delete files of _the specified data files_ have been added to the table.

File: api/src/main/java/org/apache/iceberg/RewriteFiles.java [hunk 3]
```diff
@@ -54,12 +54,23 @@ default RewriteFiles rewriteFiles(Set<DataFile> filesToDelete, Set<DataFile> fil
...
    * @return this for method chaining.
    */
-  RewriteFiles rewriteFiles(Set<DataFile> dataFilesToDelete, Set<DeleteFile> deleteFilesToDelete,
+  RewriteFiles rewriteFiles(Set<DataFile> dataFilesToReplace, Set<DeleteFile> deleteFilesToReplace,
                             Set<DataFile> dataFilesToAdd, Set<DeleteFile> deleteFilesToAdd);
+
+  /**
+   * Set the snapshot ID used in any reads for this operation.
+   * <p>
+   * Validations will check changes after this snapshot ID. If the from snapshot is not set, all ancestor snapshots
```
Comment (openinx) [inline api/src/main/java/org/apache/iceberg/RewriteFiles.java:69]: Nit:  `If the from snapshot is not set`,   do we miss a `ID` in this line ?

File: core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java [hunk 4]
```diff
@@ -63,15 +67,16 @@ private void verifyInputAndOutputFiles(Set<DataFile> dataFilesToDelete, Set<Dele
   }
 
   @Override
-  public RewriteFiles rewriteFiles(Set<DataFile> dataFilesToDelete, Set<DeleteFile> deleteFilesToDelete,
+  public RewriteFiles rewriteFiles(Set<DataFile> dataFilesToReplace, Set<DeleteFile> deleteFilesToReplace,
                                    Set<DataFile> dataFilesToAdd, Set<DeleteFile> deleteFilesToAdd) {
-    verifyInputAndOutputFiles(dataFilesToDelete, deleteFilesToDelete, dataFilesToAdd, deleteFilesToAdd);
+    verifyInputAndOutputFiles(dataFilesToReplace, deleteFilesToReplace, dataFilesToAdd, deleteFilesToAdd);
```
Comment (openinx) [inline core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java:72]: As we've already changed the `dataFilesToDelete` and `deleteFilesToDelete` to `dataFilesToReplace` & `deleteFilesToReplace`,  then I think we should also change the all the variables & arguments in `verifyInputAndOutputFiles` for consistence ?

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java [hunk 5]
```diff
@@ -322,31 +365,25 @@ protected void validateDataFilesExist(TableMetadata base, Long startingSnapshotI
 
       if (matchingOperations.contains(currentSnapshot.operation())) {
         newSnapshots.add(currentSnapshotId);
-        for (ManifestFile manifest : currentSnapshot.dataManifests()) {
-          if (manifest.snapshotId() == (long) currentSnapshotId) {
-            manifests.add(manifest);
+        if (content == ManifestContent.DATA) {
+          for (ManifestFile manifest : currentSnapshot.dataManifests()) {
+            if (manifest.snapshotId() == (long) currentSnapshotId) {
```
Comment (openinx) [inline core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:370]: Is it possible that the `manifest.snapshotId()` returns a `null` value  ? If so, then we'd better to change this line to `Objects.equals(manifest.snapshotId(), currentSnapshotId)` ?

File: api/src/main/java/org/apache/iceberg/RewriteFiles.java [hunk 6]
```diff
@@ -54,12 +54,23 @@ default RewriteFiles rewriteFiles(Set<DataFile> filesToDelete, Set<DataFile> fil
...
+   * through the table's initial snapshot are validated.
+   *
+   * @param snapshotId a snapshot ID
+   * @return this for method chaining
+   */
+  RewriteFiles validateFromSnapshot(long snapshotId);
```
Comment (openinx) [inline api/src/main/java/org/apache/iceberg/RewriteFiles.java:75]: I see all the `snapshotId` are set to be `ops.current().snapshotId()`  except the test cases ?   I'm thinking is there neccesary to introduce a method that validating since a older history snaphsot id.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java [hunk 7]
```diff
@@ -309,6 +327,31 @@ protected void validateDataFilesExist(TableMetadata base, Long startingSnapshotI
...
+
+    ManifestGroup matchingDeletesGroup = new ManifestGroup(ops.io(), manifests, ImmutableList.of())
+        .filterManifestEntries(entry -> entry.status() != ManifestEntry.Status.ADDED &&
+            newSnapshots.contains(entry.snapshotId()) && requiredDataFiles.contains(entry.file().path()))
+        .specsById(base.specsById())
+        .ignoreExisting();
+
+    try (CloseableIterator<ManifestEntry<DataFile>> deletes = matchingDeletesGroup.entries().iterator()) {
+      if (deletes.hasNext()) {
+        throw new ValidationException("Cannot commit, missing data files: %s",
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:343]: "Cannot commit, deletes have been added to the table which refer to data files which no longer exist"?

I think I go that right here ... It would help me a lot if the message here was a bit more explanatory about what went wrong and why.

File: core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java (hunk 4 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java:72]: @openinx, I had a version where I did that and fixed the error messages, but it ended up being too many unrelated test changes so I'll do that in a follow-up.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 5 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:370]: No, there should never be a null snapshot ID returned from `ManifestFile`. `null` was allowed because manifest lists were added later, but manifest metadata is read any time a table is written so that the manifest data is reliable.

File: api/src/main/java/org/apache/iceberg/RewriteFiles.java (hunk 6 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/RewriteFiles.java:75]: This is necessary because the current snapshot's ID may not be the one that was used for the operation. This `RewriteFiles` operation may be created significantly later than the original planning that is done for compaction. For example, in the new Spark compaction code, the rewrite is created when a group is ready to commit. The table state may have changed from that time so using the current snapshot ID could easily skip delta commits that were interleaved, leaving the same issue that we are fixing here.

File: api/src/main/java/org/apache/iceberg/RewriteFiles.java (hunk 3 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/RewriteFiles.java:69]: I think it is clear from context that the snapshot this refers to is he one identified by the snapshot ID. It may be more clear to change it to "If this method is not called" though.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 1 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:66]: No. A rewrite may not change the data in the table. As a result, delete rewrites may rewrite an equality delete file to position deletes, or may rewrite position deletes in a more efficient file layout. That cannot change the actual deletes. A compaction operation must apply or carry forward any deletes to the data files that are rewritten, so it must be aware of any existing deletes at the start of the operation. That means a compaction already knows about all of the deletes rewritten by a concurrent delete rewrite, and so it is safe for the two to happen at the same time.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 7 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:344]: This is an existing error message. We can fix it, but I'd prefer to do it in a separate commit so that we don't have changes to more test cases than necessary. I also plan to fix the initial validation in `RewriteFiles` later for the same reason. Is it okay to leave this as-is?

File: api/src/main/java/org/apache/iceberg/RewriteFiles.java (hunk 6 above)
Comment (rdblue) [reply api/src/main/java/org/apache/iceberg/RewriteFiles.java:75]: You can also see this in the test case, where we actually create commits and then run the rewrite differently to simulate concurrent operations: https://github.com/apache/iceberg/pull/2865/files#diff-b914d99ace31a09150792c10e3b0f1e40331edb1c24233ee6912d4608cfde0c4R615-R643

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java [hunk 8]
```diff
@@ -62,6 +63,9 @@
       ImmutableSet.of(DataOperations.OVERWRITE, DataOperations.REPLACE, DataOperations.DELETE);
   private static final Set<String> VALIDATE_DATA_FILES_EXIST_SKIP_DELETE_OPERATIONS =
       ImmutableSet.of(DataOperations.OVERWRITE, DataOperations.REPLACE);
+  // delete files are only added in "overwrite" operations
+  private static final Set<String> VALIDATE_REPLACED_DATA_FILES_OPERATIONS =
+      ImmutableSet.of(DataOperations.OVERWRITE);
```
Comment (aokolnychyi) [inline core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:68]: I wonder whether we should introduce a new `DataOperation` for row deltas before adopting v2. Right now, we use `OVERWRITE` for deltas as well as other operations such copy-on-write MERGE and replace partitions. This means the new validation logic will apply to operations that cannot produce delete files.

It probably does not matter much in this particular use case as the delete index will be empty but it is something we should do now or never.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java [hunk 9]
```diff
@@ -62,6 +63,9 @@
       ImmutableSet.of(DataOperations.OVERWRITE, DataOperations.REPLACE, DataOperations.DELETE);
   private static final Set<String> VALIDATE_DATA_FILES_EXIST_SKIP_DELETE_OPERATIONS =
       ImmutableSet.of(DataOperations.OVERWRITE, DataOperations.REPLACE);
+  // delete files are only added in "overwrite" operations
+  private static final Set<String> VALIDATE_REPLACED_DATA_FILES_OPERATIONS =
```
Comment (aokolnychyi) [inline core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:67]: nit: I am not sure the var name conveys its purpose and does not follow the convention compared used in 2 vars above. If I understand correctly, this is a set of operations that may produce delete files.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java [hunk 10]
```diff
@@ -297,6 +283,39 @@ protected void validateAddedDataFiles(TableMetadata base, Long startingSnapshotI
...
+        validationHistory(base, startingSnapshotId, VALIDATE_REPLACED_DATA_FILES_OPERATIONS, ManifestContent.DELETES);
+    List<ManifestFile> deleteManifests = history.first();
+
+    long startingSequenceNumber = startingSnapshotId == null ? 0 : base.snapshot(startingSnapshotId).sequenceNumber();
+    DeleteFileIndex deletes = DeleteFileIndex.builderFor(ops.io(), deleteManifests)
+        .afterSequenceNumber(startingSequenceNumber)
+        .specsById(ops.current().specsById())
+        .build();
+
+    for (DataFile dataFile : dataFiles) {
```
Comment (aokolnychyi) [inline core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:311]: nit: Do we have to iterate through data files if the index is empty and we did not find any delete manifests? This logic will be triggered during various operations including copy-on-write MERGE.

**Review by aokolnychyi — APPROVED** [review]
LGTM.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 10 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:311]: The data files here are the ones that are in memory because they are being replaced. I don't think that this is going to be a significant slow-down since we're just doing an index check, but we can follow up with a couple improvements to make it faster.

One improvement I'd opt for before avoiding this loop is to only read manifest files that were created in the new snapshots. That is, when the snapshot ID of the delete file is one of the snapshots newer than the starting snapshot. We don't currently do that because the delete file index builder doesn't support it and it looked more invasive to update the index builder (and we're trying to get 0.12.0 out).

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 8 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:68]: I've considered this before and keep coming back to not splitting the existing operations. Right now, the operations convey what's happening to the table at a logical level. An append never removes rows, a delete never adds rows, and a replace never changes rows. Then overwrite is used for anything that adds and removes rows in the same commit. I think those definitions are easy to understand and reason about.

If we added an operation for deltas, then we would either add a single "delta" operation or "delta-delete", "delta-overwrite", and "delta-replace" operations. If we use just "delta" then it wouldn't be clear what was happening logically, so we'd lose the ability to ignore a row-level deletes in a logical replace/rewrite. So I would conclude that we can either introduce 3 new operations or no new operations.

So far, I don't think there's a strong justification for adding the 3 new operations because the existing ones already cover what you're doing to the data logically. We would only be adding more information about how that logical operation is carried out with files. There may be some value there, but I'd probably instead add a new property to signal that row-level deletes were used so that we don't alter the contract of `DataOperation`.

Then the question becomes whether it is useful to know that row-level deletes are present. If so, we can add a property for it. In this case, it would save us some time reading the manifest list for an overwrite or delete. Do you think we should add something to signal this?

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 9 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:67]: I'll update this. And I'll also add "delete" as an operation. Just because we only create "overwrite" commits for row-level deletes today doesn't mean that we won't create "delete" commits later. I considered updating the `RowDelta` operation so that it created delete commits if only delete files were added, but didn't end up doing it because we don't do that for overwrites that only remove data files.

We can discuss whether to convert overwrite commits to delete commits that later, but for now I think that we should add "delete" to this list because it would be a valid commit. Just because the reference implementation doesn't produce them doesn't mean it isn't valid.

Comment (aokolnychyi) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:67]: I had the same thought about using DELETE operation types when we just add delete files.

Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:67]: Actually, I think the variable name does follow the convention. If we are validating replaced data files then those are the types of commits that are needed for validation.

I'm going to update this by adding `delete`, but not renaming.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 2 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java]: I updated the wording here to mention that it tests the data files.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 8 above)
Comment (aokolnychyi) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java]: I agree with your interpretation of `DataOperations`. If it describes what happens to the table from a logical perspective, then whether we use delete files or not is indeed an implementation detail. I think this detail may be important as we move forward as there will be a bigger focus on the performance. I'd opt for having that flag and being able to distinguish such cases. If we had that, we would be able to skip more snapshots during the validation added in this PR.

But I am sometimes too paranoid about extra work during commits so it may be just me.

File: core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java (hunk 10 above)
Comment (aokolnychyi) [reply core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java:311]: Oh, that would be way more important than skipping this loop.

File: api/src/main/java/org/apache/iceberg/RewriteFiles.java (hunk 6 above)
Comment (openinx) [reply api/src/main/java/org/apache/iceberg/RewriteFiles.java:75]: OK, that make sense !

File: core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java [hunk 11]
```diff
@@ -85,4 +90,18 @@ public RewriteFiles rewriteFiles(Set<DataFile> dataFilesToDelete, Set<DeleteFile
...
+  public RewriteFiles validateFromSnapshot(long snapshotId) {
+    this.startingSnapshotId = snapshotId;
+    return this;
+  }
+
+  @Override
+  protected void validate(TableMetadata base) {
+    if (replacedDataFiles.size() > 0) {
+      // if there are replaced data files, there cannot be any new row-level deletes for those data files
+      validateNoNewDeletesForDataFiles(base, startingSnapshotId, replacedDataFiles);
```
Comment (openinx) [inline core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java:104]: I think we should also handle the case : 

* t1:  table has FILE_A and EQ_DELETE_FILE_B;
* t2:  RewriteFiles action to convert the EQ_DELETE_FILE_B to POS_DELETE_FILE_C which hold the file_id and offset from FILE_A,  just start the txn but not commit;
* t3:  DeleteFiles action committed the txn which deletes  the FILE_A;
* t4:  Try to commit the RewriteFiles action. 

At timestamp `t4`,  the RewriteFiles txn should be aborted because the data file FILE_A which is relied by POS_DELETE_FILE_C has been deleted. 

Do we plan to add this validation in the following PR, or did not consider this case because we currently don't have introduced any RewriteFiles action that converting equality delete files into positional delete files ?

Comment (openinx) [reply core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java:104]: In my thought,   the data conflicts between REPLACE operation and APPEND/OVERWRITE/DELETE operations is because of the dependency relationship from positional delete files to data files. Then there will be two cases:

1.  The REPLACE operation remove the data files that was relied by other committed APPEND/OVERWRITE/DELTE  operations ( among the three operations,  currently only the RowDelta will introduce new positional delete files which reference to committed data files).  I think we handle this case perfectly in this PR.
2. The APPEND/OVERWRITE/DELETE operations remove the data files that was relied by other committed REPLACE operation.  The above [comment](https://github.com/apache/iceberg/pull/2865/files#r677072072) is an example. 

As a final solution,  I think we should handle both the cases perfectly, so that we won't encounter any unexpected interruption when reading the iceberg table.

File: core/src/main/java/org/apache/iceberg/DeleteFileIndex.java [hunk 12]
```diff
@@ -312,6 +312,7 @@ static Builder builderFor(FileIO io, Iterable<ManifestFile> deleteManifests) {
   static class Builder {
     private final FileIO io;
     private final Set<ManifestFile> deleteManifests;
+    private long minSequenceNumber = 0L;
```
Comment (openinx) [inline core/src/main/java/org/apache/iceberg/DeleteFileIndex.java:315]: I remember the sequence number 0 is kept for the data files for iceberg v1, so in theory the sequence number from delete files should start from 1.   So setting it to 0 as the default value sounds correct.

**Review by openinx — APPROVED** [review]
The current validation looks good to me ,  but I left several comment to discuss the future validations.

**Comment by rdblue** [comment]
Thanks for the reviews, everyone!

@openinx, I agree that we should handle the other case you pointed out. I'm going to open a new PR for that case later today.

File: core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java (hunk 11 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java:104]: @openinx, I opened a draft PR, https://github.com/apache/iceberg/pull/2892, for to fix this, but I'm not sure that we actually want to merge it.

Originally, I copied the `validateDataFilesExist` implementation from `RowDelta` and added tests. That works great and is a fairly simple commit if we want it. But as I was testing it, I added cases for delete, overwrite, rewrite, and a transactional delete and append to overwrite.

Then I realized that not all of those cases apply. For example, if I delete a file that has row deltas, that's perfectly okay. The operation actually deletes all rows that weren't already deleted and any dangling positional deletes will just never get applied. Similarly, an overwrite from, for example, a MERGE INTO operation that replaces a file will need to first read that file and then build its replacement. The read must merge the existing deletes, so the rows will already be removed from the replacement file. Then the deletes in that case are also fine to leave dangling even if they are rewritten into a new file.

I ended up leaving a validation that the data files are not rewritten, but I also think that may not be necessary because I don't think it would be reasonable to rewrite a data file without also applying the deletes. If we build a compaction operation we will probably apply deletes during compaction. We could also build one that compacts just data files, but in order for that operation to be correct it would also need to rewrite delete files (that are pointing to the compacted data files) or use an older sequence number with equality deletes. If it rewrote delete files, then the delete rewrite would fail. If it changed sequence numbers, then we would have a lot more validation to do when building that plan.

After thinking about it, I don't think that we actually need to handle any cases where a compaction and delete file rewrite are concurrent, at least not from the delete file rewrite side. Any compaction should handle deletes as part of the compaction.

Comment (openinx) [reply core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java:104]: > We could also build one that compacts just data files, but in order for that operation to be correct it would also need to rewrite delete files (that are pointing to the compacted data files) or use an older sequence number with equality deletes

You mean people will need to know whether the  data-files-only compaction will break the existing data set ? This puts too much burden on users ?  I think we still need to provide the validation because we developers are sure that those cases will break the data correctness ...

Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java:104]: > You mean people will need to know whether the data-files-only compaction will break the existing data set ? This puts too much burden on users ? I think we still need to provide the validation because we developers are sure that those cases will break the data correctness ...

The contract of the `RewriteFiles` operation is that it does not change the table data. That is explicitly stated in the `rewriteFiles` configuration method's javadoc:

> Add a rewrite that replaces one set of files with another set that **contains the same data**.

I think that is a reasonable requirement for the operation. Compacting only data files without accounting for deletes would change the table data, even without a concurrent delete file rewrite. For example, if I have

| `file-a.parquet` |
| -- |
| `1, 'x'` |
| `2, 'y'` |

| `file-b.parquet` |
| -- |
| `3, 'z'` |

| `file-a-deletes.parquet` |
| -- |
| `'file-a.parquet', 0` |

Compacting `file-a.parquet` and `file-b.parquet` together would undelete row `id=1`. There is no way for Iceberg to check whether the rewrite ignored `file-a-deletes.parquet` or applied the deletes. The correctness problem is entirely in the compaction operation.

We have to trust the `RewriteFiles` caller to do the right thing and preserve correctness.

That means either the caller must do one of the following:
1. Remove the deleted row
2. Rewrite `file-a-deletes.parquet` to point the delete at the new data file
3. Write the new data file with a compatible sequence number (only valid if the deletes are equality deletes so they would still apply)

If the caller uses option 1, then it doesn't matter to concurrent operations that are rewriting the delete. It becomes a dangling delete that doesn't need to be applied. If the caller uses option 2, then there is a new file tracking the delete that would not be part of a concurrent rewrite operation; a concurrent rewrite may contain a dangling delete.

The only case we would need to worry about is option 3, and only if a concurrent delete rewrites an equality delete as a positional delete. To be careful, we could merge #2892 to be able to validate this case. But I'm skeptical that altering the sequence number of the compacted file is a good idea. It may not even be possible if the sequence number of a delete that must be applied is between the sequence numbers of the starting data files.

As I said, I'm okay not merging the validation for option 3 because I think it is unlikely that this is going to be a viable strategy. But I'm fine merging #2892 if you think it is needed.
