### PR TITLE
Don't check row filter when deciding whether to copy data file with stats

### LINKED ISSUE #5706: Not dropping stats when scanning all columns caused Spark driver exceeding GC limit
### Apache Iceberg version

0.13.1

### Query engine

Spark

### Please describe the bug 🐞

We recently migrated a Spark parquet table to Iceberg table. With the same query scanning all columns and return 10 rows, the Spark job after migration failed due to driver exceeding GC limit.

```sql
select * from iceberg_table limit 10;
```

The driver memory is set to 4g. After dumping the driver memory, I find it's most taken up by the stats like `lowerBounds` maps from the `GenericDataFile`. 

That has lead me to https://github.com/apache/iceberg/blob/apache-iceberg-0.13.1/core/src/main/java/org/apache/iceberg/ManifestReader.java#L292 where stats are returned when scanning all columns.

```java
  static boolean dropStats(Expression rowFilter, Collection<String> columns) {
    // Make sure we only drop all stats if we had projected all stats
    // We do not drop stats even if we had partially added some stats columns, except for record_count column.
    // Since we don't want to keep stats map which could be huge in size just because we select record_count, which
    // is a primitive type.
    if (rowFilter != Expressions.alwaysTrue() && columns != null &&
        !columns.containsAll(ManifestReader.ALL_COLUMNS)) {
      Set<String> intersection = Sets.intersection(Sets.newHashSet(columns), STATS_COLUMNS);
      return intersection.isEmpty() || intersection.equals(Sets.newHashSet("record_count"));
    }
    return false;
  }
```

The issue is resolved by either removing `!columns.containsAll(ManifestReader.ALL_COLUMNS)` or not scanning all columns.

### PR DESCRIPTION
**Pull request by manuzhang**
This fixes #5706

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/ManifestReader.java [hunk 1]
```diff
@@ -268,8 +268,7 @@ CloseableIterable<ManifestEntry<F>> liveEntries() {
   /** @return an Iterator of DataFile. Makes defensive copies of files before returning */
   @Override
   public CloseableIterator<F> iterator() {
-    return CloseableIterable.transform(
-            liveEntries(), e -> e.file().copy(!dropStats(rowFilter, columns)))
+    return CloseableIterable.transform(liveEntries(), e -> e.file().copy(!dropStats(columns)))
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/ManifestReader.java:271]: I realize that this isn't changing what's already done, but I think it would be better to have a variable for the result of `dropStats`. That's not going to change and we don't need to evaluate whether to drop stats for the columns every time this runs!

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks, @manuzhang! Good to have this fixed. There's another issue I noticed if you're interested in fixing that as well!

**Comment by manuzhang** [comment]
Thanks @rdblue! I'll follow up on that issue.

**Comment by manuzhang** [comment]
@rdblue I've submitted https://github.com/apache/iceberg/pull/5836. Please help review.
