### PR TITLE
Core: Fix JDBC schema version when initialization is disabled

### LINKED ISSUE #9764: `JdbcCatalog` `add-view-support` should be evaluated individually from `initializeCatalogTables` flag
### Apache Iceberg version

None

### Query engine

None

### Please describe the bug 🐞

We added `jdbc.add-view-support` flag to the JDBC catalog to support view. If the user don't set this flag to `true`, then the schema is not updated (still running `V0` version). 
Unfortunately, `add-view-support` is only evaluated if the `initializeCatalogTables` flag is set to `true`, meaning that the schema is considered as `V1` and eventually updated (where it should not). `add-view-support` should be evaluated "outside" of `initializeCatalogTables`.

### PR DESCRIPTION
**Pull request by jbonofre**
This closes #9764

### CODE REVIEW

**Comment by jbonofre** [comment]
@nastra @ajantha-bhat as discussed together: this PR checks the SQL schema version (and eventually update) independently from the `initialize` flag.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 1]
```diff
@@ -199,21 +198,29 @@ private void initializeCatalogTables() throws InterruptedException, SQLException
...
-    } else {
-      if (PropertyUtil.propertyAsBoolean(
-          catalogProperties, JdbcUtil.ADD_VIEW_SUPPORT_PROPERTY, false)) {
-        connection.prepareStatement(JdbcUtil.UPDATE_CATALOG_SQL).execute();
-      } else {
-        LOG.warn(VIEW_WARNING_LOG_MESSAGE);
-        schemaVersion = JdbcUtil.SchemaVersion.V0;
-      }
-    }
+  private void updateCatalogTables() throws SQLException, InterruptedException {
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:201]: what about naming this `checkAndMaybeUpdateSchema` (or anything else). `updateCatalogTables` doesn't fully represent what this method is doing internally

Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:201]: Good point, let me rename and add a couple of tests.

Comment (nastra) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:201]: also we should have a test where the catalog is initialized with `initializeCatalogTables = false`. That test would then initialize legacy schema and read and create tables (similar to `testLegacySchemaSupport()`)

Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java]: Agree, I'm working on it now.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 2]
```diff
@@ -199,21 +198,29 @@ private void initializeCatalogTables() throws InterruptedException, SQLException
...
-    } else {
-      if (PropertyUtil.propertyAsBoolean(
-          catalogProperties, JdbcUtil.ADD_VIEW_SUPPORT_PROPERTY, false)) {
-        connection.prepareStatement(JdbcUtil.UPDATE_CATALOG_SQL).execute();
-      } else {
-        LOG.warn(VIEW_WARNING_LOG_MESSAGE);
-        schemaVersion = JdbcUtil.SchemaVersion.V0;
-      }
-    }
+  private void checkAndMaybeUpdateSchema() throws SQLException, InterruptedException {
```
Comment (amogh-jahagirdar) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:201]: Nit: It feels a bit weird to have "maybe" in a method name like this, could we call this `updateSchemaIfRequired`

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 3]
```diff
@@ -199,21 +198,29 @@ private void initializeCatalogTables() throws InterruptedException, SQLException
...
+    LOG.trace(
+        "Checking the SQL schema version and eventually update if {} is true",
+        JdbcUtil.ADD_VIEW_SUPPORT_PROPERTY);
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:204]: There is no need for a log message here. All this is doing is logging that this method was called. That's information that comes from a stack trace if needed.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 4]
```diff
@@ -199,21 +198,29 @@ private void initializeCatalogTables() throws InterruptedException, SQLException
...
+          if (typeColumn.next()) {
+            LOG.debug("{} already supports views", JdbcUtil.CATALOG_TABLE_VIEW_NAME);
+            return true;
+          } else {
+            if (PropertyUtil.propertyAsBoolean(
+                catalogProperties, JdbcUtil.ADD_VIEW_SUPPORT_PROPERTY, false)) {
+              return conn.prepareStatement(JdbcUtil.UPDATE_CATALOG_SQL).execute();
+            } else {
+              LOG.warn(VIEW_WARNING_LOG_MESSAGE);
+              schemaVersion = JdbcUtil.SchemaVersion.V0;
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:219]: Instead of downgrading the schema, I think it should start at `V0` and be upgraded if needed. That's more conservative, in case there are any more unintended uses that don't run the check.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 3 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:204]: OK, I just mimic the same as in `initializeCatalogTables()` method.
Let me remove it (maybe worth to remove the `trace` in `initializeCatalogTables()` as well.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 2 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:201]: OK, no problem. I don't mind to change the name especially for a `private` method 😄

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 5]
```diff
@@ -140,6 +139,7 @@ public void initialize(String name, Map<String, String> properties) {
       if (initializeCatalogTables) {
         initializeCatalogTables();
       }
+      checkAndMaybeUpdateSchema();
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:142]: I think it is odd that this always initializes the catalog with view support when not all clients support views. Instead of an upgrade flag, I would expect this to be configured by a schema version using something like `schema.version={0,1}` that defaults to 0. Then initialization would always know which table to create and upgrading would be done with `schema.version` changes.

Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:142]: I think the error handling is incorrect here. The errors state that the schema could not be initialized, but that applies only to `initializeCatalogTables`. I think the try/catch should move into the `initializeCatalogTables` method and `updateSchemaIfRequired` should have its own error handling.

Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:142]: Is it not problematic in terms of backward compatibility and impact of our users ? That's the reason why I tried to limit the change.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 2 above)
Comment (nastra) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:201]: +1 on `updateSchemaIfRequired`

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 4 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:219]: In that case it would mean that we should init the schema with `V0` when initialize is `true` and update in second step, right ?

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 5 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:142]: Correct, thanks I will fix that.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 4 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:216]: Yes. I think we should init with the most conservative option and upgrade it iff we detect that the later version can be used.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 5 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java]: I think it would just be better if we were explicit about the version. I think this creates a loophole where people can hit the errors that we are trying to avoid (older clients failing on views) when they initialize without making a conscious choice.

Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java]: OK, I will then replace `add-view-support` by `schema.version`. Thanks.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 4 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:216]: That makes sense. I will add the SQL statement to create the `V0` schema and eventually update in a second step. Thanks !

**Comment by jbonofre** [comment]
@rdblue @danielcweeks @nastra @ajantha-bhat I did a first update of the PR according to Ryan's comments. I'm still working on a new test (the PR will be updated soon with this test).

**Comment by ajantha-bhat** [comment]
Keeping to V0 as default seems to be the right choice 👍 . 

I think only thing missing is a testcase with `initializeCatalogTables = false` as Eduard requested.  
We can parameterise `testInitSchemaV0` to have initializeCatalogTables true,false.

Otherwise good to go.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 6]
```diff
@@ -199,21 +212,31 @@ private void initializeCatalogTables() throws InterruptedException, SQLException
...
+          if (typeColumn.next()) {
+            LOG.debug("{} already supports views", JdbcUtil.CATALOG_TABLE_VIEW_NAME);
+            schemaVersion = JdbcUtil.SchemaVersion.V1;
+            return true;
+          } else {
+            if (PropertyUtil.propertyAsString(
+                    catalogProperties,
+                    JdbcUtil.SCHEMA_VERSION_PROPERTY,
+                    JdbcUtil.SchemaVersion.V0.name())
+                .equals(JdbcUtil.SchemaVersion.V1.name())) {
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:230]: nit: equalsIgnoreCase maybe here?

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 7]
```diff
@@ -199,21 +212,31 @@ private void initializeCatalogTables() throws InterruptedException, SQLException
...
+              LOG.debug("{} is updating to support views", JdbcUtil.CATALOG_TABLE_VIEW_NAME);
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:231]:
```suggestion
              LOG.debug("{} is updated to support views", JdbcUtil.CATALOG_TABLE_VIEW_NAME);
```

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 8]
```diff
@@ -161,6 +163,40 @@ public void testInitialize() {
     jdbcCatalog.initialize("test_jdbc_catalog", properties);
   }
 
+  @Test
+  public void testInitSchemaV0() throws Exception {
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:167]:
```suggestion
  public void testInitSchemaV0() {
```

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 9]
```diff
@@ -161,6 +163,40 @@ public void testInitialize() {
...
+    Table table =
+        jdbcCatalog
+            .buildTable(tableIdent, SCHEMA)
+            .withPartitionSpec(PARTITION_SPEC)
+            .withProperties(null)
+            .withProperty("key1", "value1")
+            .withProperties(ImmutableMap.of("key2", "value2"))
+            .create();
+
+    assertThat(table.schema()).hasToString(SCHEMA.toString());
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:186]:
```suggestion
    assertThat(table.schema().asStruct()).isEqualTo(SCHEMA.asStruct());
```

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 10]
```diff
@@ -161,6 +163,40 @@ public void testInitialize() {
...
+    JdbcCatalog jdbcCatalog = new JdbcCatalog();
+    jdbcCatalog.setConf(conf);
+    jdbcCatalog.initialize("v0catalog", properties);
+
+    TableIdentifier tableIdent = TableIdentifier.of("db", "ns1", "ns2", "tbl");
+    Table table =
+        jdbcCatalog
+            .buildTable(tableIdent, SCHEMA)
+            .withPartitionSpec(PARTITION_SPEC)
+            .withProperties(null)
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:181]:
```suggestion
```

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 11]
```diff
@@ -161,6 +163,40 @@ public void testInitialize() {
...
+            .withProperty("key1", "value1")
+            .withProperties(ImmutableMap.of("key2", "value2"))
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:183]:
```suggestion
            .withProperty("key2", "value2")
```

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 12]
```diff
@@ -161,6 +163,40 @@ public void testInitialize() {
...
+            .create();
+
+    assertThat(table.schema()).hasToString(SCHEMA.toString());
+    assertThat(table.spec().fields()).hasSize(1);
+    assertThat(table.properties()).containsEntry("key1", "value1").containsEntry("key2", "value2");
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:188]: I would probably just add a `listTables()` check here, to make sure the created table can be found

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 1 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java]: I added a `ParameterizedTest` test to test with `initializeCatalogTables` `true|false`.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 6 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:230]: Yeah, good idea, just in case the user does a type :)

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 7 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:231]: I used `updating` because the actual update is performed after the log message (I would have used `updated` if the log message is after the update statement).

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 13]
```diff
@@ -150,6 +150,20 @@ public void initialize(String name, Map<String, String> properties) {
       Thread.currentThread().interrupt();
       throw new UncheckedInterruptedException(e, "Interrupted in call to initialize");
     }
+
+    try {
+      updateSchemaIfRequired();
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:155]: Ryan mentioned in https://github.com/apache/iceberg/pull/9765#discussion_r1496224382 that the error handling should move inside `updateSchemaIfRequired()` and we should probably do the same for `initializeCatalogTables()`. Otherwise the `initialize()` method gets quite bloated

Comment (nastra) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:155]: >  I think the try/catch should move into the `initializeCatalogTables` method and `updateSchemaIfRequired` should have its own error handling.

Based on this it's what I mentioned previously: the error handling should move *into* `initializeCatalogTables` + `updateSchemaIfRequired` should have its own (and in that case I would also move it into the method itself)

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 7 above)
Comment (nastra) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:231]: `...is updating to...` sounds like something is missing. What about `...is being updated to support views`

Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:231]: Fair enough 😄

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 13 above)
Comment (jbonofre) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:155]: Catcha, let me move the error handling in the methods.

**Review by nastra — APPROVED** [review]
LGTM, thanks @jbonofre. I'll merge once CI passes

**Review by ajantha-bhat — APPROVED** [review]
