### PR TITLE
Api, Spark: Make StrictMetricsEvaluator not fail on nested column predicates

### LINKED ISSUE #7065: Cannot delete column with nested field filter
### Query engine

Spark

### Question

I have a table with some nested fields, and tried to delete rows on spark sql.
But the operation was field with error like:
`java.lang.NullPointerException: Cannot filter by nested column`

For simplify I wrote scala test code
```scala
class NestedDeleteTest extends AnyFunSuite with Matchers {

  test("delete with nested field") {
    val catalogName = "hadoop"
    val dbName      = "test_db"
    val tableName   = "test_table"
    val tableId = s"$catalogName.$dbName.$tableName"

    val warehouse = s"${System.getProperty("user.dir")}/warehouse"

    val spark = SparkSession.builder
      .master("local[1]")
      .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
      .config(s"spark.sql.catalog.$catalogName", "org.apache.iceberg.spark.SparkCatalog")
      .config(s"spark.sql.catalog.$catalogName.type", "hadoop")
      .config(s"spark.sql.catalog.$catalogName.warehouse", warehouse)
      .getOrCreate()

    val rows = List(
      """{"nested":{"id":1},"timestamp":1}""",
      """{"nested":{"id":2},"timestamp":1}""",
      """{"nested":{"id":1},"timestamp":2}"""
    )

    val df = spark.read.json(spark.createDataset(spark.sparkContext.parallelize(rows))(Encoders.STRING))

    df.writeTo(tableId).createOrReplace()

    val before = spark.table(tableId)
    before.show()
    before.count() shouldBe 3

    val sql = s"DELETE FROM $tableId WHERE nested.id=1 AND timestamp=2"
    spark.sql(sql)

    val after = spark.table(tableId)
    after.show()
    after.count() shouldBe 2
  }
}
```

Then, the problem is reproduced.

stacktrace:
```
java.lang.NullPointerException: Cannot filter by nested column: 5: id: optional long
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:994)
	at org.apache.iceberg.expressions.StrictMetricsEvaluator$MetricsEvalVisitor.eq(StrictMetricsEvaluator.java:305)
	at org.apache.iceberg.expressions.StrictMetricsEvaluator$MetricsEvalVisitor.eq(StrictMetricsEvaluator.java:83)
	at org.apache.iceberg.expressions.ExpressionVisitors$BoundExpressionVisitor.predicate(ExpressionVisitors.java:162)
	at org.apache.iceberg.expressions.ExpressionVisitors.visitEvaluator(ExpressionVisitors.java:390)
	at org.apache.iceberg.expressions.ExpressionVisitors.visitEvaluator(ExpressionVisitors.java:405)
	at org.apache.iceberg.expressions.StrictMetricsEvaluator$MetricsEvalVisitor.eval(StrictMetricsEvaluator.java:101)
	at org.apache.iceberg.expressions.StrictMetricsEvaluator$MetricsEvalVisitor.access$100(StrictMetricsEvaluator.java:83)
	at org.apache.iceberg.expressions.StrictMetricsEvaluator.eval(StrictMetricsEvaluator.java:77)
	at org.apache.iceberg.spark.source.SparkTable.lambda$canDeleteUsingMetadata$2(SparkTable.java:300)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterators.all(Iterators.java:710)
	at org.apache.iceberg.relocated.com.google.common.collect.Iterables.all(Iterables.java:645)
	at org.apache.iceberg.spark.source.SparkTable.canDeleteUsingMetadata(SparkTable.java:289)
	at org.apache.iceberg.spark.source.SparkTable.canDeleteWhere(SparkTable.java:269)
	at org.apache.spark.sql.execution.datasources.v2.OptimizeMetadataOnlyDeleteFromTable$$anonfun$apply$1.applyOrElse(OptimizeMetadataOnlyDeleteFromTable.scala:53)
	at org.apache.spark.sql.execution.datasources.v2.OptimizeMetadataOnlyDeleteFromTable$$anonfun$apply$1.applyOrElse(OptimizeMetadataOnlyDeleteFromTable.scala:44)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transform(TreeNode.scala:425)
	at org.apache.spark.sql.execution.datasources.v2.OptimizeMetadataOnlyDeleteFromTable$.apply(OptimizeMetadataOnlyDeleteFromTable.scala:44)
	at org.apache.spark.sql.execution.datasources.v2.OptimizeMetadataOnlyDeleteFromTable$.apply(OptimizeMetadataOnlyDeleteFromTable.scala:40)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:211)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:208)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:200)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:200)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:179)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:88)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:179)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$optimizedPlan$1(QueryExecution.scala:125)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:183)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:183)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:121)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:117)
	at org.apache.spark.sql.execution.QueryExecution.assertOptimized(QueryExecution.scala:135)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:153)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:150)
	at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:201)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:246)
	at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:215)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:97)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:93)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:93)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:78)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
```

Is it normal operation?
I am confused because I found test case for delete with nested column
https://github.com/apache/iceberg/blob/39a2c12b843f6f16e3389e738531e24a32f5bf39/spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java#L383-L397

### PR DESCRIPTION
**Pull request by zhongyujiang**
Currently, the `StrictMetricsEvaluator` fails when evaluating expressions with nested columns, causing Spark's `DELETE FROM` statement to throw an exception if the `WHERE` condition uses nested columns as predicates.

The `StrictMetricsEvaluator` requires null count data for columns during evaluation, but the null count data for nested columns collected in the current metadata might be incorrect (see #8611). Therefore, the `StrictMetricsEvaluator` cannot support the evaluation of filters on nested columns.

However, I think we can at least return `ROWS_MIGHT_NOT_MATCH` when encountering filters with nested columns instead of directly throwing exceptions and causing job failures. We are currently alreadt doing this in the evaluation of `startsWith`:
 https://github.com/apache/iceberg/blob/5922b4bbc431131e9dfd112f751b796c5200a35e/api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java#L464-L467

This fixes #7065.

@aokolnychyi @szehon-ho @RussellSpitzer @Fokko can you please take a look when you have time? Thanks.

### CODE REVIEW

**Comment by blakewhatley82** [comment]
This issue is still around in spark 3.5 and would really be a big capability to have for data that is all in structured format

**Comment by Leonti** [comment]
Same here, we have a big dataset and almost all of the data is in nested structs. Now we need to delete data based on the nested struct value and this issue is blocking us.

File: api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java [hunk 1]
```diff
@@ -60,7 +57,6 @@ public StrictMetricsEvaluator(Schema schema, Expression unbound) {
   }
 
   public StrictMetricsEvaluator(Schema schema, Expression unbound, boolean caseSensitive) {
-    this.schema = schema;
```
Comment (amogh-jahagirdar) [inline api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java:63]: Why are we removing this?

Comment (amogh-jahagirdar) [reply api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java:63]: Ah nvm, I see that it was only used for the purpose of resolving if a field was nested or not

**Review by amogh-jahagirdar — COMMENTED** [review]
I think this change is logically sound, thank you @zhongyujiang! 
I'll want to double check though why this wasn't done originally, that's a bit intriguing to me. I'll take a look with fresh eyes tomorrow.

File: api/src/test/java/org/apache/iceberg/expressions/TestStrictMetricsEvaluator.java [hunk 2]
```diff
@@ -627,4 +638,47 @@ public void testIntegerNotIn() {
...
+        new StrictMetricsEvaluator(
+                SCHEMA, lessThanOrEqual("struct.nested_col_no_stats", INT_MAX_VALUE))
+            .eval(FILE);
+    assertThat(shouldRead).as("Should not match: nested column").isFalse();
+
+    shouldRead =
+        new StrictMetricsEvaluator(SCHEMA, isNull("struct.nested_col_no_stats")).eval(FILE);
+    assertThat(shouldRead).as("Should not match: nested column").isFalse();
+
+    shouldRead =
```
Comment (amogh-jahagirdar) [inline api/src/test/java/org/apache/iceberg/expressions/TestStrictMetricsEvaluator.java:660]: Is it possible to separate these into 2 test methods, one for no stats and the other with stats? Could we also update the messages to be more precise, instead of just "Should not match: nested column", I think "isNull nested column should not match"

File: spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java [hunk 3]
```diff
@@ -1401,6 +1401,22 @@ public void testDeleteToCustomWapBranchWithoutWhereClause() throws NoSuchTableEx
...
+    sql("INSERT INTO TABLE %s VALUES (1, named_struct(\"c1\", 3, \"c2\", \"v1\"))", tableName);
+    sql("INSERT INTO TABLE %s VALUES (2, named_struct(\"c1\", 2, \"c2\", \"v2\"))", tableName);
+
+    sql("DELETE FROM %s WHERE complex.c1 = 3", tableName);
+    assertEquals(
+        "Should have expected rows", ImmutableList.of(row(2)), sql("SELECT id FROM %s", tableName));
+
+    sql("DELETE FROM %s t WHERE t.complex.c1 = 2", tableName);
+    assertEquals(
+        "Should have expected rows", ImmutableList.of(), sql("SELECT id FROM %s", tableName));
```
Comment (amogh-jahagirdar) [inline spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java:1417]: Could we add a case where the filter results in nothing being deleted?

**Review by amogh-jahagirdar — COMMENTED** [review]
Overall @zhongyujiang I think the change is good, just some cleanup in tests would be great before we get this in!

**Comment by zhongyujiang** [comment]
@amogh-jahagirdar Thanks for reviewing, tests updated.

**Review by amogh-jahagirdar — APPROVED** [review]
Thanks @zhongyujiang, from my side the changes look good. I'll give some time for others to review before merging

**Review by nastra — APPROVED** [review]
LGTM, thanks for fixing this @zhongyujiang

**Comment by blakewhatley82** [comment]
@zhongyujiang @nastra @amogh-jahagirdar  great to see this merged! Is it known the timeline for 1.6.2 iceberg release and will this be for spark 3.3x?

**Comment by zhongyujiang** [comment]
@blakewhatley82 I am not clear on the timeline for the 1.6.2 release. This fix is effective for all Spark versions.

**Comment by nastra** [comment]
The community is planning a 1.7.0 release end of October, so this will be shipped with that
