### PR TITLE
Core: fix deadlock in CachingCatalog

### LINKED ISSUE #3791: Deadlock when using CachingCatalog with Iceberg 0.13.0-SNAPSHOT
Hi all!

When running maintenance procedures with spark sql, namely `expire_snapshots, rewrite_data_files, rewrite_manifests and remove_orphan_files`, I'm getting a deadlock within the caffeine cache in CachingCatalog. This does not happen for every run, but happens for most of them (specifically when running the `rewrite_data_files` procedure).

The blocked threads and their traces are below:
```

"ForkJoinPool.commonPool-worker-13" #1103 daemon prio=5 os_prio=0 cpu=7.93ms elapsed=674.73s tid=0x000055c8bb5e9000 nid=0x5a0 waiting for monitor entry  [0x00007f0291ee4000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@11.0.12/ConcurrentHashMap.java:1814)
        - waiting to lock <0x00000006c9b9fca0> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2102)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.invalidateAll(LocalCache.java:121)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.invalidateAll(LocalManualCache.java:145)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:101)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:92)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$evictEntry$2(BoundedLocalCache.java:937)
        - locked <0x00000006c7576498> (a org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.PDA)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$4879/0x0000000801e49440.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@11.0.12/ConcurrentHashMap.java:1822)
        - locked <0x00000006cf86f1c8> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntry(BoundedLocalCache.java:905)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:818)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.expireAfterAccessEntries(BoundedLocalCache.java:802)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.expireEntries(BoundedLocalCache.java:782)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1479)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1448)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:3293)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.exec(BoundedLocalCache.java:3280)
        at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.12/ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.12/ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.12/ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.12/ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.12/ForkJoinWorkerThread.java:183)

   Locked ownable synchronizers:
        - <0x00000006c5103038> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"HiveServer2-Background-Pool: Thread-1682" #1682 prio=5 os_prio=0 cpu=13.77ms elapsed=412.87s tid=0x00007f02a8034800 nid=0x845 waiting for monitor entry  [0x00007f01ed9ee000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.computeIfPresent(java.base@11.0.12/ConcurrentHashMap.java:1814)
        - waiting to lock <0x00000006cf86f1c8> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2102)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.invalidateAll(LocalCache.java:121)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.invalidateAll(LocalManualCache.java:145)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:101)
        at org.apache.iceberg.CachingCatalog$MetadataTableInvalidatingCacheWriter.delete(CachingCatalog.java:92)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2368)
        - locked <0x00000006c9a0f0d8> (a org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.PDA)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$2256/0x00000008014aac40.apply(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.compute(java.base@11.0.12/ConcurrentHashMap.java:1932)
        - locked <0x00000006c9b9fca0> (a java.util.concurrent.ConcurrentHashMap$Node)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2342)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2325)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at org.apache.iceberg.shaded.com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
        at org.apache.iceberg.CachingCatalog.loadTable(CachingCatalog.java:168)
        at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:490)
        at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:135)
        at org.apache.iceberg.spark.SparkCatalog.loadTable(SparkCatalog.java:92)
        at org.apache.iceberg.spark.procedures.BaseProcedure.loadSparkTable(BaseProcedure.java:115)
        at org.apache.iceberg.spark.procedures.BaseProcedure.execute(BaseProcedure.java:82)
        at org.apache.iceberg.spark.procedures.BaseProcedure.modifyIcebergTable(BaseProcedure.java:74)
        at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.call(RewriteDataFilesProcedure.java:94)
        at org.apache.spark.sql.execution.datasources.v2.CallExec.run(CallExec.scala:33)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
        - locked <0x00000006d8f18c68> (a org.apache.spark.sql.execution.datasources.v2.CallExec)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
        at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1$$Lambda$1933/0x00000008012b3840.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1941/0x00000008012b7440.apply(Unknown Source)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.execution.SQLExecution$$$Lambda$1934/0x00000008012b3c40.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.trees.TreeNode$$Lambda$1923/0x00000008012ad840.apply(Unknown Source)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
        - locked <0x00000006d8f18ea8> (a org.apache.spark.sql.execution.QueryExecution)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:219)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:99)
        at org.apache.spark.sql.Dataset$$$Lambda$1551/0x0000000800f6cc40.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:96)
        at org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:618)
        at org.apache.spark.sql.SparkSession$$Lambda$1471/0x0000000800f28840.apply(Unknown Source)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:613)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:291)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.$anonfun$run$2(SparkExecuteStatementOperation.scala:230)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3$$Lambda$2166/0x00000008013e5440.apply$mcV$sp(Unknown Source)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties(SparkOperation.scala:79)
        at org.apache.spark.sql.hive.thriftserver.SparkOperation.withLocalProperties$(SparkOperation.scala:63)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.withLocalProperties(SparkExecuteStatementOperation.scala:43)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:230)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2$$anon$3.run(SparkExecuteStatementOperation.scala:225)
        at java.security.AccessController.doPrivileged(java.base@11.0.12/Native Method)
        at javax.security.auth.Subject.doAs(java.base@11.0.12/Subject.java:423)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$2.run(SparkExecuteStatementOperation.scala:239)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.12/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.12/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.12/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.12/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)

   Locked ownable synchronizers:
        - <0x00000006d8f19118> (a java.util.concurrent.ThreadPoolExecutor$Worker)

```

Full thread dump available [here](https://gist.github.com/racevedoo/e90a23ffdad3534522773501f47efb04)

From what I'm seeing, this happens when running multiple procedure calls in a row (sequentially) and for multiple tables. Running a single `rewrite_data_files` works fine (probably because the cache has not expired yet).

The workaround on my end was to disable caching.

Environment details: Spark 3.2 and Iceberg 0.13.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by racevedoo**
Uses caffeine's `RemovalListener` to expire metadata tables asynchronously, avoiding modifying cache entries during `compute` HashMap functions (which cause deadlocks).
For more details, check #3791

Fixes #3791

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 1]
```diff
@@ -86,33 +86,32 @@ protected CachingCatalog(Catalog catalog, boolean caseSensitive, long expiration
...
-    public void write(TableIdentifier tableIdentifier, Table table) {
-    }
-
-    @Override
-    public void delete(TableIdentifier tableIdentifier, Table table, RemovalCause cause) {
+    public void onRemoval(TableIdentifier tableIdentifier, Table table, @NonNull RemovalCause cause) {
+      identLoggingRemovalListener.onRemoval(tableIdentifier, table, cause);
       if (RemovalCause.EXPIRED.equals(cause)) {
-        if (!MetadataTableUtils.hasMetadataTableName(tableIdentifier)) {
+        if (tableIdentifier != null && !MetadataTableUtils.hasMetadataTableName(tableIdentifier)) {
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:99]: Why would `tableIdentifier` be null?

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 2]
```diff
@@ -36,6 +35,7 @@
 import org.apache.iceberg.exceptions.AlreadyExistsException;
 import org.apache.iceberg.relocated.com.google.common.base.Preconditions;
 import org.apache.iceberg.relocated.com.google.common.collect.ImmutableList;
+import org.checkerframework.checker.nullness.qual.NonNull;
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:38]: Can you remove this? I we don't typically use these annotations.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 1 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:99]: That's when the entry is GC'ed (according to caffeine javadocs:
image

Since we're dealing only with the `EXPIRED` cause, it's safe. I'll remove this check

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 2 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:38]: sure :smile:

Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java]: done

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 1 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java]: done

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java [hunk 3]
```diff
@@ -252,9 +254,9 @@ public void testCacheExpirationEagerlyRemovesMetadataTables() throws IOException
     ticker.advance(HALF_OF_EXPIRATION);
     Assertions.assertThat(catalog.cache().asMap()).doesNotContainKey(tableIdent);
 
-    Arrays.stream(metadataTables(tableIdent)).forEach(metadataTable ->
-        Assert.assertFalse("When a data table expires, its metadata tables should expire regardless of age",
-            catalog.cache().asMap().containsKey(metadataTable)));
+    // Removal of metadata tables from cache is async, use awaitility
+    await().untilAsserted(() ->
+        Assertions.assertThat(catalog.cache().asMap()).doesNotContainKeys(metadataTables(tableIdent)));
```
Comment (kbendick) [inline core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:259]: Question: Since you're introducing `Awaitility`, do you want to try to remove the call to `cleanUp` in the `TestableCachingCatalog` (the `cleanUp` call was added to handle the async expiration).
 https://github.com/apache/iceberg/blob/9c3e340cd67699c3d2499762d794ab1bc1ee7f45/core/src/test/java/org/apache/iceberg/TestableCachingCatalog.java#L46-L51
 
 This could likely be done in a separate PR though.

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java [hunk 4]
```diff
@@ -252,9 +254,9 @@ public void testCacheExpirationEagerlyRemovesMetadataTables() throws IOException
     ticker.advance(HALF_OF_EXPIRATION);
     Assertions.assertThat(catalog.cache().asMap()).doesNotContainKey(tableIdent);
 
-    Arrays.stream(metadataTables(tableIdent)).forEach(metadataTable ->
-        Assert.assertFalse("When a data table expires, its metadata tables should expire regardless of age",
-            catalog.cache().asMap().containsKey(metadataTable)));
+    // Removal of metadata tables from cache is async, use awaitility
```
Comment (kbendick) [inline core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:257]: Nit: I don't think this comment is necessary. The use of awaitility on the next line somewhat signifies this.

Also, as mentioned, the `TestableCachingCatalog` (which is used here in the tests) already has a comment to that effect.

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 3 above)
Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:259]: Actually, this will balloon up the PR and this is an important fix. I'd say let's move everything in this test suite to awaitility in a separate PR (though the use of awaitlity is fine here).

That way we can review this change and get it out without having to review the much larger diff that will come from adding `awaitility` to a lot of this file.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 5]
```diff
@@ -105,14 +103,14 @@ public void delete(TableIdentifier tableIdentifier, Table table, RemovalCause ca
   }
 
   private Cache<TableIdentifier, Table> createTableCache(Ticker ticker) {
+    boolean hasExpiration = expirationIntervalMillis > 0;
     Caffeine<TableIdentifier, Table> cacheBuilder = Caffeine
         .newBuilder()
         .softValues()
-        .removalListener(identLoggingRemovalListener);
+        .removalListener(hasExpiration ? new MetadataTableInvalidatingRemovalListener() : identLoggingRemovalListener);
```
Comment (kbendick) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:110]: Nit: all of the stuff that gets added due to expiration should ideally be inside of the `if (hasExpiration)` block or in the return statement after that section if it's for non-expiring cache (i.e. the `identLoggingRemovalListener` here).

Can you split this line into that block (and the block after it for the `identLoggingRemovalListener`.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 6]
```diff
@@ -86,16 +85,15 @@ protected CachingCatalog(Catalog catalog, boolean caseSensitive, long expiration
   }
 
   /**
-   * CacheWriter class for removing metadata tables when their associated data table is expired
+   * RemovalListener class for removing metadata tables when their associated data table is expired
    * via cache expiration.
+   *
+   * @see com.github.benmanes.caffeine.cache.RemovalListener
```
Comment (kbendick) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:91]: Nit: This `@see` doesn't seem necessary  to me given that we're directly implementing `RemovalListener` on the next line.

**Review by kbendick — COMMENTED** [review]
Thank you for quickly reporting this issue and then also finding a fix.

I've been out of office due to the holidays. In addition to the unit test, can you please verify that this change actually fixes the issue that you reported (e.g. compile it and use the jar from  your local build)? That would be the best form of verification (in addition to the test).

Thank you again @racevedoo!

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 7]
```diff
@@ -86,16 +85,15 @@ protected CachingCatalog(Catalog catalog, boolean caseSensitive, long expiration
...
-  class MetadataTableInvalidatingCacheWriter implements CacheWriter<TableIdentifier, Table> {
+  class MetadataTableInvalidatingRemovalListener implements RemovalListener<TableIdentifier, Table> {
     @Override
-    public void write(TableIdentifier tableIdentifier, Table table) {
-    }
-
-    @Override
-    public void delete(TableIdentifier tableIdentifier, Table table, RemovalCause cause) {
+    public void onRemoval(TableIdentifier tableIdentifier, Table table, RemovalCause cause) {
+      identLoggingRemovalListener.onRemoval(tableIdentifier, table, cause);
```
Comment (kbendick) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:96]: Nit: Instead of relying on `identLoggingRemovalListener`, since we're already inside of an `onRemoval` function, would it make sense to cut out the overhead and just add the log statement here if need be?

The double `onRemoval` call makes me nervous about more potential race conditions etc by looking like a double callback.

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 4 above)
Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:257]: If we update the Caffeine library from 2.8.4 to [2.8.5](https://github.com/ben-manes/caffeine/releases/tag/v2.8.5) and make the proposed changes, we won't have to introduce `Awaitility` yet, because the `TestableCachingCatalog` calls `cleanUp` on the cache already. I was wondering why this change was needed and noticed this bug fix in 2.8.5.

```
Fixed expiration delay for scheduled cleanup
```

But as mentioned, I think we should stick with the `Awaitility` introduction and remove the call to `cleanUp` and depend on `Awaitility` entirely in a separate PR.

I also have another PR open to upgrade the `caffeine` library version, as there are some important bug fixes for us and since we've been mucking around in here, we might as well upgrade instead of stay behind. https://github.com/apache/iceberg/pull/3803

Comment (kbendick) [inline core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:257]: Nit: This comment seems unnecessary, as we're using `awaitility` immediately below.

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 3 above)
Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:259]: Thinking on it further, **Can we upgrade Caffeine**  to the next minor version (2.8.5) in this PR, which makes this `Awaitility` introduction unnecessary?

My reasoning is that the bug that causes you to have to use `Awaitility` here, is fixed byy upgrading to Caffeine 2.8.5. This indicates that the write path we're going through _also_ receives the fix and so we should provide that fix to our actual code too (even if we're not explicitly calling `cleanUp` ever, the bug could still affect us).

It's the[ only patch mentioned in the release notes](https://github.com/ben-manes/caffeine/releases/tag/v2.8.5) for 2.8.4 -> 2.8.5

We can and should still convert this to not call `cleanUp` in the `TestableCachingCache`, but I think it's best that the fix from 2.8.5 is also applied to the final code as it's a scheduling bug that could affect our new write path for this cache as well. This way also, we can introduce `Awaitility` in a follow up PR and focus only on this bug.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 5 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java]: Sure! Just had to change to `Caffeine<Object, Object>` on cache creation as we don't have the type yet

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 6 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java]: removed

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 7 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java]: removed `identLoggingRemovalListener`

**Comment by racevedoo** [comment]
Oops, I missed some of the comments/edits.

@kbendick from my perspective, the proper fix is indeed upgrading to caffeine 2.9.x and using `evictionListener`. This would get us rid of awaitility and the `cleanUp` calls. I still have to check if the test in #3798 passes though

**Comment by racevedoo** [comment]
Actually `evictionListener` seems to be called only within the `cleanUp` task. I'm not sure if I understood correctly, but I guess we should move forward with the upgrade to caffeine 2.8.5 and keep the `cleanUp` in `cache()` until we investigate this in more detail

**Comment by racevedoo** [comment]
Caffeine upgraded to 2.8.5

> I've been out of office due to the holidays. In addition to the unit test, have you verified that this change actually fixes the issue that you reported (e.g. compile it and use the jar from your local build)? That would be the best form of verification, but given the reproduction test case in #3798, that's not required.

I'm out of office too, so I haven't verified if this change fixes the issue, but I guess the unit test is good enough

**Comment by racevedoo** [comment]
Actually when using `evictionListener` we don't need awaitility, so I upgraded to caffeine 2.9.x and removed awaitility.

**Comment by racevedoo** [comment]
Guys, sorry for the lots of force-pushes. The main changes/discoveries from the previous state are:
- Upgraded to caffeine 2.9.x
- Added the test present in #3798 (I guess we can close that PR if the test is fine)
- Kept using `removalListener` since `evictionListener` is synchronous and also causes the deadlock (the test fails)
- Kept awaitility since removalListener is async

**Comment by kbendick** [comment]
Thanks for the follow up @racevedoo! No worries on the force pushes, just be sure to rebase off of master when needed. 

Also, @racevedoo and I are syncing up offline about some of the changes in the tests. Will comment here with more detail later. 🙂

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 3 above)
Comment (ben-manes) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:264]: The evictionListener replaces CacheWriter’s delete for an atomic action under the map’s computation. Since your previous code wrote back into the cache I think you would suffer the same problem if switching.

Since you don’t use a scheduler, I don’t see how that bug fix affects you.

You can use Caffeine.executor(Runnable::run) to disable async, which simplifies tests.

Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:264]: Oh awesome thank you! You're right, after running the tests again several more times on 2.8.5, it didn't fix the issue. I just somehow got lucky and was able to get several successful runs in a row.

Appreciate the input regarding disabling async!

Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:264]: We typically don't expect to see a _huge_ amount of cache usage. It's for caching tables that are accessed, and a job usually accesses a table via the catalog one time at the start of the job when query planning happens.

There are cases where they can be accessed several times (as mentioned in the issue), but it's usually a pretty limited number of values and times to use it.

Would it be a terrible idea to use `Caffeine.executor(Runnable::run)` to disable async in the actual production code? Ideally the tables we're removing in the `RemovalListener` would expire synchronously when the main table they reference expires.

Thanks again for your input and the great library @ben-manes!

Comment (ben-manes) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:264]: It would be perfectly fine to disable async in production code (Redhat's Infinispan does that, for example). The async is primarily because we don't know the cost of running user-supplied callbacks like the removal listener, which might impact user-facing latencies. The cache's own logic is very fast and strictly uses amortized O(1) algorithms.

Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:264]: Great. Our work in the callback is relatively negligible (building a list of maybe and disabling async would be the desired behavior. Really appreciate the input and knowledge sharing! 😊

Comment (racevedoo) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java]: just updated the code to use `Runnable::run` :smile:

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 8]
```diff
@@ -86,16 +79,13 @@ protected CachingCatalog(Catalog catalog, boolean caseSensitive, long expiration
   }
 
   /**
-   * CacheWriter class for removing metadata tables when their associated data table is expired
+   * RemovalListener class for removing metadata tables when their associated data table is expired
    * via cache expiration.
+   *
```
Comment (kbendick) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:84]: Nit: Unneeded extra line.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 9]
```diff
@@ -105,14 +95,14 @@ public void delete(TableIdentifier tableIdentifier, Table table, RemovalCause ca
...
         .newBuilder()
-        .softValues()
-        .removalListener(identLoggingRemovalListener);
+        .softValues();
 
     if (expirationIntervalMillis > 0) {
       return cacheBuilder
-          .writer(new CachingCatalog.MetadataTableInvalidatingCacheWriter())
+          .removalListener(new MetadataTableInvalidatingRemovalListener())
+          .executor(Runnable::run)
```
Comment (kbendick) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:105]: Can you put a comment inline next to this so we don't forget why we did this in the future?

```
      return cacheBuilder
          .removalListener(new MetadataTableInvalidatingRemovalListener())
          .executor(Runnable::run)  // Makes the callbacks to removal listener synchronous
```

**Review by kbendick — APPROVED** [review]
This looks great, thank you so much @racevedoo!

Just a few minor nits.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 8 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:84]: removed

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 9 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:105]: done :D

**Review by kbendick — APPROVED** [review]
+1 this looks great. Thank you @racevedoo for the report and the quick fix. Hugely appreciated, especially during the holidays.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 10]
```diff
@@ -47,10 +44,6 @@
  */
 public class CachingCatalog implements Catalog {
 
-  private static final Logger LOG = LoggerFactory.getLogger(CachingCatalog.class);
-  private static final RemovalListener<TableIdentifier, Table> identLoggingRemovalListener =
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:51]: Should we be logging this in the new removal listener?

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 11]
```diff
@@ -105,14 +94,14 @@ public void delete(TableIdentifier tableIdentifier, Table table, RemovalCause ca
   }
 
   private Cache<TableIdentifier, Table> createTableCache(Ticker ticker) {
-    Caffeine<TableIdentifier, Table> cacheBuilder = Caffeine
+    Caffeine<Object, Object> cacheBuilder = Caffeine
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:97]: Is there a reason we need the generic types here?

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java [hunk 12]
```diff
@@ -257,6 +264,44 @@ public void testCacheExpirationEagerlyRemovesMetadataTables() throws IOException
             catalog.cache().asMap().containsKey(metadataTable)));
   }
 
+  @Test
+  @Ignore("reproduces https://github.com/apache/iceberg/issues/3791")
```
Comment (RussellSpitzer) [inline core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:268]: This test should pass now right, so should we turn this on?

**Review by RussellSpitzer — COMMENTED** [review]
Had a few questions, but in general this looks good to me. I'll need some time after break to really dig into the Caffine library but invalidating cache in the removal listener seems to make more sense to mel

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 11 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:97]: Yes there is. We need it because caffeine has no way of determining the type based only in `Caffeine.newBuilder().softValues()`. Previously we specified the removalListener here, so it could get the specific types

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 12 above)
Comment (racevedoo) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:268]: That's an open question. I think we should enable it, as it runs relatively fast (~2 seconds) and we would be getting the safety of not hitting the deadlock issue again.

I guess @kbendick thinks differently though

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 10 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:51]: I'll put it back again

Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:51]: done :D

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 11 above)
Comment (kbendick) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:101]: So technically it works if you put the types, but intellij does kind of freak out (even if you put the types on the right side and the left).

This is normal, to use `<Object, Object>` until something gives it type definitions (after which there are strict rules about using that chained fluent builder because it stores type info from the responseListener, which doesn't come until later now).

Starting with `<Object, Object>` is very normal with Caffeine's builder.

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 12 above)
Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:268]: I figured to turn it off normally since it uses a lot of threads. I was hoping that we might come up with a system of tagging tests as resource intensive etc that we run nightly or something.

I've seen a handful of tests lately that start many threads and that seems not great for CI.

But if we're ok with running this on every push, we can remove the `Ignore`. We could either open an issue for expensive tests that we flag or hold off on that as we might not be there yet.

But tests that spawn 20+ threads make me nervous about increasing oddities in CI like HMS timeouts etc.

**Comment by kbendick** [comment]
> Had a few questions, but in general this looks good to me. I'll need some time after break to really dig into the Caffine library but invalidating cache in the removal listener seems to make more sense to me

Agreed on digging into Caffeine. I've begun doing that as well and plan to upgrade our version after this PR. It is ubiquitous in the rest of our stack too so it's worth knowing well.

But given that the snapshot currently can deadlock, I'd prefer to ship this and then revisit it if need be. If the deadlock doesn't happen anymore with the snapshot, that will be great.

Then we'll just need to revisit with more knowledge the choice of executor service (possibly making it optionally not synchronous or something). But the deadlock seems important to fix as soon as possible.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java [hunk 13]
```diff
@@ -86,16 +82,13 @@ protected CachingCatalog(Catalog catalog, boolean caseSensitive, long expiration
...
-  class MetadataTableInvalidatingCacheWriter implements CacheWriter<TableIdentifier, Table> {
-    @Override
-    public void write(TableIdentifier tableIdentifier, Table table) {
-    }
-
+  class MetadataTableInvalidatingRemovalListener implements RemovalListener<TableIdentifier, Table> {
     @Override
-    public void delete(TableIdentifier tableIdentifier, Table table, RemovalCause cause) {
+    public void onRemoval(TableIdentifier tableIdentifier, Table table, RemovalCause cause) {
+      LOG.debug("Evicted {} from the table cache ({})", tableIdentifier, cause);
```
Comment (kbendick) [inline core/src/main/java/org/apache/iceberg/CachingCatalog.java:91]: Given that this inner class is the only thing that uses the Logger, should we make the call to LoggerFactory.getLogger here instead?

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 12 above)
Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:268]: If it's just 2 seconds, I'd say enable it. We share infra with all of ASF,  but arguably we have a lot of Spark tests that should be refactored that are more resource intensive than this. The risk of thread thrashing is likely minimal and we can deal with it if it comes up.

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java [hunk 14]
```diff
@@ -257,6 +264,44 @@ public void testCacheExpirationEagerlyRemovesMetadataTables() throws IOException
...
+  public void testDeadlock() throws IOException, InterruptedException {
+    HadoopCatalog underlyingCatalog = hadoopCatalog();
+    TestableCachingCatalog catalog = TestableCachingCatalog.wrap(underlyingCatalog, Duration.ofSeconds(1), ticker);
+    Namespace namespace = Namespace.of("db", "ns1", "ns2");
+    int numThreads = 20;
+    for (int i = 0; i < numThreads; i++) {
+      TableIdentifier tableIdent = TableIdentifier.of(namespace, "tbl" + i);
+      catalog.createTable(tableIdent, SCHEMA, SPEC, ImmutableMap.of("key", "value"));
```
Comment (kbendick) [inline core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:276]: Nit / being good citizens: Please make sure all of these tables get dropped at the end test! Maybe make a list of table names and then you can place a finally block or an `@After` function somehow.

Let me know if you'd like any help in sorting that out structurally etc 🙂

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java [hunk 15]
```diff
@@ -257,6 +264,44 @@ public void testCacheExpirationEagerlyRemovesMetadataTables() throws IOException
             catalog.cache().asMap().containsKey(metadataTable)));
   }
 
+  @Test
+  @Ignore("reproduces https://github.com/apache/iceberg/issues/3791")
+  public void testDeadlock() throws IOException, InterruptedException {
+    HadoopCatalog underlyingCatalog = hadoopCatalog();
+    TestableCachingCatalog catalog = TestableCachingCatalog.wrap(underlyingCatalog, Duration.ofSeconds(1), ticker);
+    Namespace namespace = Namespace.of("db", "ns1", "ns2");
+    int numThreads = 20;
```
Comment (kbendick) [inline core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:273]: Would it make sense to use fewer threads, so the space for collision / hitting the deadlock is smaller? And then iterating like you are a few extra times? This way the `Random.nextInt` calls are more likely to collide and we don't have to spawn so many threads.

Comment (ben-manes) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:273]: Can you hack the hashCode (e.g. make constant) to coerce collisions?

Comment (kbendick) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:273]: I don't mean to take up too much of your time, but you mean for the cache key's (the TableIdentifier)?

Would it be equivalent to just make one cache entry and then just only operate on that? That would make dropping the table (cache entry) free.

Comment (ben-manes) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:273]: Yes, the key. The map locks on a hashbin so locking multiple in an unpredictable order is a classic deadlock case. I don’t know if a single entry would suffice or if you need threads performing ABA vs BAB to get the desired test case.

**Review by RussellSpitzer — APPROVED** [review]
I think this looks good to me  for the fix, I think we should aim to try to get a more deterministic test, the faking of the hash value seems pretty doable but if that's not possible I am fine with the current state. Let's try to get that test cleaned up a bit and make sure it doesn't leave to much junk behind when it is done.

File: core/src/main/java/org/apache/iceberg/CachingCatalog.java (hunk 13 above)
Comment (racevedoo) [reply core/src/main/java/org/apache/iceberg/CachingCatalog.java:91]: static declarations are not supported in inner classes :(

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 14 above)
Comment (racevedoo) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:276]: done. I simply got the table names and dropped them at the end of this test. Maybe we can add a `@After` function that lists the tables and drops them all, but it's probably better to do it in a separate PR

File: core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java (hunk 15 above)
Comment (racevedoo) [reply core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java:272]: The thing here is to make the cache miss (from my tests). I changed this a little to get rid of the random stuff, making cache misses more certain.

**Comment by racevedoo** [comment]
> I think this looks good to me for the fix, I think we should aim to try to get a more deterministic test, the faking of the hash value seems pretty doable but if that's not possible I am fine with the current state. Let's try to get that test cleaned up a bit and make sure it doesn't leave to much junk behind when it is done.

I changed the test a little to remove the random stuff and cleanup the created tables :smile:

**Comment by rdblue** [comment]
Looks good. Thanks for getting this done, @racevedoo!
