### PR TITLE
Core: Fix metadata table scans with useRef by preserving metadata schema

### LINKED ISSUE #15273: Cannot query metadata table on a branch
### Apache Iceberg version

main (development)

### Query engine

Spark

### Please describe the bug 🐞

I tried to query metadata table on a branch:
```java
  public void test() throws Exception {
    sql("create table foo (x int, p int) using iceberg partitioned by (p)");
    sql("insert into foo values (1, 1)");
    sql("alter table foo create branch br1");
    sql(
        "select status,snapshot_id from spark_catalog.default.foo.entries version as of 'br1' where data_file.partition.p > 0");
  }
```

It fails with exception:
```shell
Cannot find field 'data_file.partition.p' in struct: struct<1: x: optional int, 2: p: optional int>
org.apache.iceberg.exceptions.ValidationException: Cannot find field 'data_file.partition.p' in struct: struct<1: x: optional int, 2: p: optional int>
at org.apache.iceberg.expressions.Binder.bind(Binder.java:60)
		at org.apache.iceberg.BaseEntriesTable$ManifestContentEvaluator.<init>(BaseEntriesTable.java:110)
		at org.apache.iceberg.BaseEntriesTable.planFiles(BaseEntriesTable.java:85)
		at org.apache.iceberg.ManifestEntriesTable$EntriesTableScan.doPlanFiles(ManifestEntriesTable.java:69)
		at org.apache.iceberg.SnapshotScan.planFiles(SnapshotScan.java:161)
		at org.apache.iceberg.BatchScanAdapter.planFiles(BatchScanAdapter.java:124)
```

It seems we incorrectly pass data table schema, rather than entries table schema, to `EntriesTableScan`, and therefore we cannot bind the filter expression. I think we should override `useRef` to properly handle the schema, or throw an exception indicating branch is not supported for metadata tables.

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [x] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by lirui-apache**
Fixes #15273 

In `SnapshotScan`, reuse `useSnapshotSchema` to check whether we should use a different schema for `useRef`

### CODE REVIEW

File: core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java [hunk 1]
```diff
@@ -1752,6 +1752,84 @@ public void testEntriesTableEstimateSize() throws Exception {
...
+    Table deleteFilesTable = new DeleteFilesTable(table);
+    assertThat(rowsCount(deleteFilesTable.newScan().useRef("testBranch")))
+        .as("DeleteFilesTable on branch should have 1 delete file")
+        .isEqualTo(1);
+    assertThat(rowsCount(deleteFilesTable.newScan()))
+        .as("DeleteFilesTable on main should have 2 delete files")
+        .isEqualTo(2);
+  }
+
+  private int rowsCount(TableScan scan) throws IOException {
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java]: Minor: rowsCount -> rowCount

File: core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java [hunk 2]
```diff
@@ -1752,6 +1752,84 @@ public void testEntriesTableEstimateSize() throws Exception {
     assertEstimatedRowCount(new AllEntriesTable(table), 4);
   }
 
+  @TestTemplate
+  public void testMetadataTableScansOnBranch() throws IOException {
+    table.newFastAppend().appendFile(FILE_A).commit();
+    table.manageSnapshots().createBranch("testBranch").commit();
+
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java]: Minor: Needless newline here and same in the below method.

**Comment by lirui-apache** [comment]
@amogh-jahagirdar Thanks for the review. Updated accordingly.

File: core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java [hunk 3]
```diff
@@ -1752,6 +1752,82 @@ public void testEntriesTableEstimateSize() throws Exception {
...
+        .isEqualTo(0);
+    assertThat(rowCount(entriesTable.newScan()))
+        .as("ManifestEntriesTable on main should have 2 entries")
+        .isEqualTo(2);
+
+    Table dataFilesTable = new DataFilesTable(table);
+    assertThat(rowCount(dataFilesTable.newScan().useRef("testBranch")))
+        .as("DataFilesTable on branch should have 1 file")
+        .isEqualTo(1);
+    assertThat(rowCount(dataFilesTable.newScan()))
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java:1779]: instead of using `rowCount` everywhere you should be able to replace this directly with 
```
assertThat(dataFilesTable.newScan().planFiles())
        .as("DataFilesTable on main should have 2 files")
        .hasSize(2);
```

Comment (lirui-apache) [reply core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java:1779]: I believe this will produce the same results for entries/files table. But for ManifestsTable, both main and testBranch will have 1 scan task. Is that OK?

Comment (nastra) [reply core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java:1779]: ah you're right, let's leave the code as it is then. thanks for checking
