### PR TITLE
Core: Don't remove trailing slash from absolute paths

### LINKED ISSUE #12373: Iceberg 1.8.0 Breaking oauth2 authentication
### Apache Iceberg version

1.8.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

Version 1.8.0 removes the trailing slash "/" for every URL.
This has a negative side effect when using Authentik for oauth2 authentication.

the Authentic token url is for example : https://authentik.domain.tld/application/o/token/
and is changed to: https://authentik.domain.tld/application/o/token

without the trailing slash, Authentication will return a http 405 

why is Iceberg removing trailing slash? this may also break rother stuff?
and maybe if not required, then revert this change and keep the url as-is

code is in class  org.apache.iceberg.rest.HTTPRequest and the problem is with the "RESTUtil.stripTrailingSlash(fullPath)" part.

```
  @Value.Lazy
  default URI requestUri() {
    // if full path is provided, use the input path as path
    String fullPath =
        (path().startsWith("https://") || path().startsWith("http://"))
            ? path()
            : String.format("%s/%s", baseUri(), path());
    try {
      URIBuilder builder = new URIBuilder(RESTUtil.stripTrailingSlash(fullPath));
      queryParameters().forEach(builder::addParameter);
      return builder.build();
    } catch (URISyntaxException e) {
      throw new RESTException(
          "Failed to create request URI from base %s, params %s", fullPath, queryParameters());
    }
  }
```

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by adutra**
Fixes #12373

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/rest/HTTPRequest.java [hunk 1]
```diff
@@ -53,13 +53,16 @@ enum HTTPMethod {
...
-            ? path()
-            : String.format("%s/%s", baseUri(), path());
+    // if path is an absolute URI, use it as is
+    String fullPath;
+    if (path().startsWith("https://") || path().startsWith("http://")) {
+      fullPath = path();
+    } else {
+      String baseUri = RESTUtil.stripTrailingSlash(baseUri().toString());
+      fullPath = RESTUtil.stripTrailingSlash(String.format("%s/%s", baseUri, path()));
+    }
```
Comment (ajantha-bhat) [inline core/src/main/java/org/apache/iceberg/rest/HTTPRequest.java:63]: nit: Iceberg uses a newline separator after control block. So, please add a new line here.

File: core/src/main/java/org/apache/iceberg/rest/HTTPRequest.java [hunk 2]
```diff
@@ -53,13 +53,16 @@ enum HTTPMethod {
    */
   @Value.Lazy
   default URI requestUri() {
-    // if full path is provided, use the input path as path
-    String fullPath =
-        (path().startsWith("https://") || path().startsWith("http://"))
-            ? path()
-            : String.format("%s/%s", baseUri(), path());
+    // if path is an absolute URI, use it as is
```
Comment (ajantha-bhat) [inline core/src/main/java/org/apache/iceberg/rest/HTTPRequest.java:56]: nit: Please move the comment inside the if block.

**Review by ajantha-bhat — APPROVED** [review]

**Comment by ajantha-bhat** [comment]
@adutra: Thanks for the quick fix. Once, nit is handled, please raise the same PR against branch 1.8.x
https://github.com/apache/iceberg/tree/1.8.x

**Comment by adutra** [comment]
@ajantha-bhat here is the 1.8.x PR: #12390

**Review by nastra — APPROVED** [review]

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @adutra for fixing this, and thanks @ajantha-bhat and @nastra for the review 🙌
