### PR TITLE
Hive: Fix NPE when reading a struct field with null value

### LINKED ISSUE #4282: Hive : Hive throw a NullPointerException when accessing a null struct inside a map.
If we have a column which is a map of a struct, if the value for the key is null, instead of return null as in spark, hive iceberg will throw a NullPointerException

`[2022-03-07 10:46:07]   Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Error evaluating struct(_col3,_col2['key'].context).col2
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:93)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.baseForward(Operator.java:994)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:940)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:927)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:95)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.baseForward(Operator.java:994)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:940)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:927)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.FilterOperator.process(FilterOperator.java:126)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.baseForward(Operator.java:994)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:940)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.TableScanOperator.process(TableScanOperator.java:125)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.MapOperator$MapOpCtx.forward(MapOperator.java:153)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:555)
[2022-03-07 10:46:07]       ... 20 more
[2022-03-07 10:46:07]   Caused by: java.lang.NullPointerException
[2022-03-07 10:46:07]       at org.apache.iceberg.mr.hive.serde.objectinspector.IcebergRecordObjectInspector.getStructFieldData(IcebergRecordObjectInspector.java:75)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeFieldEvaluator._evaluate(ExprNodeFieldEvaluator.java:94)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:80)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeGenericFuncEvaluator$DeferredExprObject.get(ExprNodeGenericFuncEvaluator.java:88)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.udf.generic.GenericUDFStruct.evaluate(GenericUDFStruct.java:70)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeGenericFuncEvaluator._evaluate(ExprNodeGenericFuncEvaluator.java:197)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:80)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeFieldEvaluator._evaluate(ExprNodeFieldEvaluator.java:79)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:80)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.ExprNodeEvaluator.evaluate(ExprNodeEvaluator.java:68)
[2022-03-07 10:46:07]       at org.apache.hadoop.hive.ql.exec.SelectOperator.process(SelectOperator.java:88)
[2022-03-07 10:46:07]       ... 33 more
`

### PR DESCRIPTION
**Pull request by tprelle**
Fix #4282

### CODE REVIEW

**Comment by kbendick** [comment]
Thanks for this @tprelle. Would you mind copying over information from the issue to the PR description so that people can find it properly (e.g. if they're looking at git history in their IDE etc).

Additionally, I noticed you said the behavior of Spark was to return null if a null was encountered in this situation. I'm not a Hive user... is this the same behavior that's expected in Hive proper?

File: mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java [hunk 1]
```diff
@@ -61,4 +61,17 @@ public void testIcebergRecordObjectInspector() {
...
+  public void testIcebergRecordObjectInspectorWithRowNull() {
+    Schema schema = new Schema(
+            required(1, "integer_field", Types.IntegerType.get()),
+            required(2, "struct_field", Types.StructType.of(
+                    Types.NestedField.required(3, "string_field", Types.StringType.get())))
+    );
+    StructObjectInspector soi = (StructObjectInspector) IcebergObjectInspector.create(schema);
+    Assert.assertNull(soi.getStructFieldsDataAsList(null));
+    StructField integerField = soi.getStructFieldRef("integer_field");
+    Assert.assertNull(soi.getStructFieldData(null, integerField));
```
Comment (kbendick) [inline mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java:74]: Would it be possible to stick a null column into an e2e Hive job, to ensure that reading it doesn't cause issues? This is just testing that the object inspector returns null appropriately. But it doesn't test if other code (which previously wasn't getting null) will hit any NPEs or anything.

If that test is too complicated to add in somehow, probably not the end of the world 🙂

File: mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java [hunk 2]
```diff
@@ -61,4 +61,17 @@ public void testIcebergRecordObjectInspector() {
     Assert.assertEquals(innerRecord.get(0), innerSoi.getStructFieldData(innerData, stringField));
   }
 
+  @Test
+  public void testIcebergRecordObjectInspectorWithRowNull() {
+    Schema schema = new Schema(
+            required(1, "integer_field", Types.IntegerType.get()),
+            required(2, "struct_field", Types.StructType.of(
+                    Types.NestedField.required(3, "string_field", Types.StringType.get())))
+    );
```
Comment (kbendick) [inline mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java:70]: Nit: The indenation is off here.

There should be two spaces when the indentation changes, and 4 spaces when the same code statement / expression continues on the next line. Like so. 
```java
    Schema schema = new Schema(
        required(1, "integer_field", Types.IntegerType.get()),
        required(2, "struct_field", Types.StructType.of(
            Types.NestedField.required(3, "string_field", Types.StringType.get())))
    );
```

File: mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergRecordObjectInspector.java [hunk 3]
```diff
@@ -72,11 +72,17 @@ public StructField getStructFieldRef(String name) {
 
   @Override
   public Object getStructFieldData(Object o, StructField structField) {
+    if (o == null) {
+      return null;
+    }
```
Comment (kbendick) [inline mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergRecordObjectInspector.java:77]: Nit: Please add a newline between control flow blocks (so after this if block).

Same comment for below 👍

**Review by kbendick — COMMENTED** [review]
Thanks @tprelle! This looks good to me outside of a few nits.

I'm not much of a Hive user, so it would be nice to have an end to end test where we read in `null` records that were written (and not just check the result of the Object Inspector).

File: mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java (hunk 1 above)
Comment (pvary) [reply mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java:74]: `TestHiveIcebergStorageHandlerWithEngine` might be a place to test out the issue E2E

File: mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java (hunk 2 above)
Comment (tprelle) [reply mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java]: fix

File: mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java (hunk 1 above)
Comment (tprelle) [reply mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java:74]: @kbendick  @pvary, i have an integration test in TestHiveIcebergStorageHandlerWithEngine and edit the commit message
Thanks for the review

**Review by pvary — APPROVED** [review]

File: mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java [hunk 4]
```diff
@@ -707,6 +708,30 @@ public void testMultiTableInsert() throws IOException {
     HiveIcebergTestUtils.validateData(target2, target2Records, 1);
   }
 
+  @Test
+  public void testStructMapWithNull() throws IOException {
+    Assume.assumeTrue("Failed on vectorized parquet for a bug in parquet vectorization",
+        !("PARQUET".equals(fileFormat.name()) && isVectorized));
```
Comment (kbendick) [inline mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java:714]: Nit:  Instead of negating on `assumeTrue`, why not just use `assumeFalse`? Either that or distributing the `not` operator, but I think the following is much easier to read.

```java
    Assume.assumeFalse("...", "PARQUET".equals(fileFormat.name()) && isVectorized);
```

Comment (kbendick) [reply mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java:714]: Also, can you please update the `Assume` statement to provide more details on what the bug is and why we can't run this test under these conditions?

The assume statement should provide enough details and context to know how to follow up if possible, or at least what the bug is. For example, some of the other `Asssume` statements in this file say `Tez is not implemented yet` which is straightforward. But I don't know what the vectorized parquet bug is when seeing this and I'm left with more questions. Is it something that's not yet implemented, or maybe there's an issue that can be referenced from the parquet project? A short high level summary of what would happen and possibly a link to an existing parquet-ticket or something would be really appreciated.  Maybe this is something that can be fixed?

In general, the assume statements and error messages should be written in a way that we have enough context to understand why we're skipping the test and where to follow up if need be.

**Review by kbendick — APPROVED** [review]
This looks great to me. Thank you @tprelle!

The test gives me a lot more confidence that we won't have a regression. I just have one or two small nits.

Can you please change the name of the PR to be more specific (like the issue is)? Maybe `Hive: Fix NPE when reading a struct field with null value`? Will leave up to you the best explanation of what is being fixed, not just how it's fixed.

Also, adding a summary to the PR (vs just the issue link) would be helpful. Many people review git history in their IDE and don't necessarily see the issues or it's much less convenient to have to move out of their workflow for further context.

Again, really appreciate you reporting and fixing this issue!

File: mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java (hunk 4 above)
Comment (tprelle) [reply mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java]: Hi @kbendick, sorry for the delay,
I create an issue for this https://github.com/apache/iceberg/issues/4403 and add the info inside the test.

**Review by rdblue — APPROVED** [review]

**Comment by rdblue** [comment]
Thanks, @tprelle!
