### PR TITLE
Core: Fix case-insensitive validation of fields in schema evolution

### LINKED ISSUE #13696: Setting UpdateSchema.caseSensitive(false) does not prevent multiple columns with the same case-insensitive name being added
### Apache Iceberg version

1.9.2 (latest release)

### Query engine

None

### Please describe the bug 🐞

When creating an `UpdateSchema` and configuring case-insensitive comparison of column names, as well as adding multiple columns that differ only in the case of their names, the schema update will not fail as expected.
```
        table.updateSchema()
                .caseSensitive(false)
                .addColumn("column", Types.IntegerType.get())
                .addColumn("COLUMN", Types.IntegerType.get())
                .commit();
```
The issue originates from the final validation step when committing the `UpdateSchema`, which ignores the case sensitivity setting.

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by riemenschneider**
Closes #13696 

The case sensitivity settings are ignored during the final validation step when committing the `UpdateSchema`.

### CODE REVIEW

File: core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java [hunk 1]
```diff
@@ -779,6 +779,22 @@ public void testAddRequiredColumnCaseInsensitive() {
         .hasMessage("Cannot add column, name already exists: ID");
   }
 
+  @Test
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java:782]: Could we also add an explicit test where the initial schema has (id int, data string) and then we go and try and add `DATA` with case insensitivity? I know the logic will also catch this case but I think it's good to have that explicit test since it verifies that our update logic is holistically evaluating the schema instead of just in incremental fashion.

Comment (riemenschneider) [reply core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java:782]: The previous test method, `testAddRequiredColumnCaseInsensitive()`, performs a similar test. It starts with a column `id` of type `Integer` and attempts to add another column `ID` of type `String`, using a case-insensitive comparison of the column names.

This test is already in place because conflicts between the existing schema and the added columns have been handled correctly.  I have fixed the case where two added columns conflict with each other, but not with the existing schema.

Comment (amogh-jahagirdar) [reply core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java:782]: I see, we already had an additional incremental validation in `internalAddColumn` which was catching the case where a duplicate field is added to a schema already containing that field in a case-insensitive way. Cool, no need to duplicate the same test then.

File: core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java [hunk 2]
```diff
@@ -779,6 +779,22 @@ public void testAddRequiredColumnCaseInsensitive() {
...
+  public void testAddMultipleRequiredColumnCaseInsensitive() {
+    Schema schema = new Schema(required(1, "id", Types.IntegerType.get()));
+
+    assertThatThrownBy(
+            () ->
+                new SchemaUpdate(schema, 1)
+                    .caseSensitive(false)
+                    .allowIncompatibleChanges()
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java:790]: Minor: `allowIncompatibleChanges` isn't strictly required to repro this issue right? I think in this test case it was just set because we're adding required columns but if we were to remove this and just do `addOptionalColumn` for both "data" and "DATA", it should still just fail the same way.

File: core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java [hunk 3]
```diff
@@ -779,6 +779,22 @@ public void testAddRequiredColumnCaseInsensitive() {
...
+                    .addRequiredColumn("data", Types.StringType.get())
+                    .addRequiredColumn("DATA", Types.StringType.get())
+                    .apply())
+        .isInstanceOf(IllegalArgumentException.class)
+        .hasMessage("Cannot build lower case index: data and DATA collide");
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java:795]: I'm good with this but It'd be nice if we can detect this in a different way and fail with a better error message that dosen't really mention anything about the internal indexing we do.  since it's really no worse then the case-sensitive case (and it's consistent) where if someone does ```add("data"....).add("data"...)``` it fails with the same message, I'm good with it.

**Review by amogh-jahagirdar — APPROVED** [review]

**Comment by amogh-jahagirdar** [comment]
Thanks for the fix @riemenschneider and thank you @nandorKollar  @singhpk234 for reviewing. I'll go ahead and merge.

File: core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java (hunk 2 above)
Comment (riemenschneider) [reply core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java:790]: To be honest, I simply took the existing test `testAddRequiredColumnCaseInsensitive()` and adapted it so that it reproduces the error without paying attention to the minimality of the test.

File: core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java (hunk 3 above)
Comment (riemenschneider) [reply core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java:795]: Naming conflicts with the original schema are detected when the `addColumn()` or `addRequiredColumn()` method is called, at which point an appropriate exception (`Cannot add column, name already exists: ...`) is thrown. Conflicts between added columns are detected when the `apply()` method is called. While the error message provides all the necessary information, the indexing part is not helpful to the end user. It seems as though some of the relevant checks are duplicated.

Ideally, the `addColumn()` method would fail at this point with an appropriate error message, since all the necessary information is already available. In this case, the relevant check in the `apply()` method could be skipped entirely (or kept as a safety net). However, this would definitely require a significant change to the existing code.
