### PR TITLE
Core: Use Awaitility instead of Thread.sleep() for async testing

### LINKED ISSUE #6988: flaky test: TestRESTCatalog > testCatalogTokenRefreshFailsAndUsesCredentialForRefresh()
### Apache Iceberg version

master code 

### Query engine

None

### Please describe the bug 🐞

CI run with dummy PR:
https://github.com/apache/iceberg/actions/runs/4315439240/jobs/7529817581

```
TestRESTCatalog > testCatalogTokenRefreshFailsAndUsesCredentialForRefresh() FAILED
    org.mockito.exceptions.verification.TooFewActualInvocations: 
    rESTCatalogAdapter.execute(
        POST,
        "v1/oauth/tokens",
        <any>,
        <custom argument matcher>,
        class org.apache.iceberg.rest.responses.OAuthTokenResponse,
        {"Authorization" = "***"},
        <any>
    );
    Wanted 2 times:
    -> at org.apache.iceberg.rest.RESTCatalogAdapter.execute(RESTCatalogAdapter.java:374)
    But was 1 time:
    -> at org.apache.iceberg.rest.RESTCatalogAdapter.postForm(RESTCatalogAdapter.java:455)
        at org.apache.iceberg.rest.RESTCatalogAdapter.execute(RESTCatalogAdapter.java:374)
        at org.apache.iceberg.rest.TestRESTCatalog.testCatalogTokenRefreshFailsAndUsesCredentialForRefresh(TestRESTCatalog.java:1497)
```

### PR DESCRIPTION
**Pull request by nastra**
This uses https://github.com/awaitility/awaitility instead of `Thread.sleep()` to fix some flakiness in TestRESTCatalog.

fixes #6988

### CODE REVIEW

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 1]
```diff
@@ -1037,71 +1037,75 @@ public void testCatalogTokenRefresh() throws Exception {
     catalog.initialize(
         "prod", ImmutableMap.of(CatalogProperties.URI, "ignored", "credential", "catalog:secret"));
 
-    Thread.sleep(3_000); // sleep until after 2 refresh calls
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java:1040]: there are no code differences in the test code itself, we're just wrapping it in a 
```
Awaitility.await()
        .atMost(5, TimeUnit.SECONDS)
        .untilAsserted(
            () -> { ... })
```

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 2]
```diff
@@ -1037,71 +1037,75 @@ public void testCatalogTokenRefresh() throws Exception {
...
-    Mockito.verify(adapter)
-        .execute(
-            eq(HTTPMethod.POST),
-            eq("v1/oauth/tokens"),
-            any(),
-            Mockito.argThat(secondRefreshRequest::equals),
-            eq(OAuthTokenResponse.class),
-            eq(secondRefreshHeaders),
-            any());
+    Awaitility.await()
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java:1040]: the default poll interval is to poll every 200 millis with an initial delay of 100 millis. I think this is fine for these tests here but not that this can be modified as outlined in https://github.com/awaitility/awaitility/wiki/Usage#polling

**Review by danielcweeks — APPROVED** [review]
