### PR TITLE
Arrow: Align vectorized reader handling of unsigned Parquet integers with BaseParquetReaders

### LINKED ISSUE #14547: Arrow reader should reject unsigned Parquet integers
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

The current implementation of Arrow reader within Iceberg will read each integer field as a signed integer, without considering the flag on the logical type annotation which mark that the integer should be interpreted as signed or unsigned value. Since Iceberg doesn't have unsigned integer type, I think the code should throw an exception, if the Parquet logical type is an unsigned integer.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [x] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by drexler-sky**
The vectorized Arrow reader was silently reading unsigned Parquet integer columns (uint8, uint16, uint32, uint64) as signed, producing incorrect values for any value exceeding the signed maximum for that bit width.

Since Iceberg has no unsigned integer type, throw UnsupportedOperationException when the Arrow reader encounters an unsigned integer logical type annotation, consistent with how the schema conversion layer already rejects uint64.

Fixes #14547

### CODE REVIEW

**Comment by pvary** [comment]
How do we behave when we use non-vectorized readers in Spark? Are we able to use read them?
How hard would it be to more lenient and implement a conversion? What would be the performance cost?

**Comment by anoopj** [comment]
> How do we behave when we use non-vectorized readers in Spark? Are we able to use read them? How hard would it be to more lenient and implement a conversion? What would be the performance cost?

This is a good point. Looks like the non-vectorized readers are more [lenient](https://github.com/apache/iceberg/blob/ecbe8a84b1897015bdaf0e7c3fdcbb8575aa9971/parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java#L197-L213). It allows the conversion, as long as it's not lossy. e.g. Allow reading a `uint32` as Iceberg `long`, `uint16` as `int` etc. The PR is blanket rejecting them. Let's try to be consistent with the non-vectorized reader.

File: arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java [hunk 1]
```diff
@@ -584,6 +584,15 @@ public Optional<LogicalTypeVisitorResult> visit(
     @Override
     public Optional<LogicalTypeVisitorResult> visit(
         LogicalTypeAnnotation.IntLogicalTypeAnnotation intLogicalType) {
+      if (!intLogicalType.isSigned()) {
+        throw new UnsupportedOperationException(
+            String.format(
+                java.util.Locale.ROOT,
```
Comment (anoopj) [inline arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java]: Minor: Import java.util.locale package and then reference `ROOT`, to be consistent.

File: arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java [hunk 2]
```diff
@@ -383,6 +384,68 @@ public void testTimestampMillisAreReadCorrectly() throws Exception {
     assertThat(totalRowsRead).as("Should read all rows").isEqualTo(millisValues.size());
   }
 
+  @Test
+  public void testUnsignedIntegerColumnThrowsException() throws Exception {
+    tables = new HadoopTables();
+
+    for (int[] spec : new int[][] {{8, 32}, {16, 32}, {32, 32}, {64, 64}}) {
```
Comment (anoopj) [inline arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java]: Use a `@ParameterizedTest` instead of this loop such that we get better error messages if there are test failures.

File: arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java [hunk 3]
```diff
@@ -383,6 +384,68 @@ public void testTimestampMillisAreReadCorrectly() throws Exception {
...
+
+      MessageType parquetSchema =
+          new MessageType(
+              "test",
+              primitive(physicalType, Type.Repetition.OPTIONAL)
+                  .as(LogicalTypeAnnotation.intType(unsignedBitWidth, false))
+                  .id(1)
+                  .named("col"));
+
+      File testFile = new File(tempDir, "unsigned-int" + unsignedBitWidth + ".parquet");
```
Comment (anoopj) [inline arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java]: Minor: Generally a good idea to do append a `System.nanoTime()` to temp file names created in tests to guarantee uniqueness

File: arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java (hunk 1 above)
Comment (drexler-sky) [reply arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java]: `java.util.Locale.ROOT` This code is gone

File: arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java (hunk 2 above)
Comment (drexler-sky) [reply arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java]: Changed to `@ParameterizedTest`

File: arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java (hunk 3 above)
Comment (drexler-sky) [reply arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java]: added `System.nanoTime()`

**Comment by drexler-sky** [comment]
Thanks @pvary @anoopj — agreed, the blanket rejection was too aggressive. I've updated the PR to mirror `BaseParquetReaders` exactly:

- uint8 / uint16 → IntegerType: accepted (lossless, same IntVector path — no perf cost)
- uint32 → IntegerType: rejected with IllegalArgumentException("Cannot read UINT32 as an int value")
- uint64 → LongType: rejected with IllegalArgumentException("Cannot read UINT64 as a long value")

Tests updated accordingly: dropped uint8/uint16 from the rejection matrix,  and added a positive test that round-trips uint8=250 / uint16=50000.

**Comment by drexler-sky** [comment]
CI failed with 
```
TestDynamicIcebergSink > testNoShuffleTopology() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at app//org.apache.iceberg.flink.sink.dynamic.TestDynamicIcebergSink.testNoShuffleTopology(TestDynamicIcebergSink.java:330)
```
The failure is unrelated to the changes in this PR.

I submitted [PR #16026](https://github.com/apache/iceberg/pull/16026) to fix the CI failure.

File: arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java [hunk 4]
```diff
@@ -383,6 +388,133 @@ public void testTimestampMillisAreReadCorrectly() throws Exception {
...
+            })
+        .isInstanceOf(IllegalArgumentException.class)
+        .hasMessageContaining(expectedMessage);
+  }
+
+  @Test
+  public void testUnsignedSmallIntegerColumnRoundtrips() throws Exception {
+    tables = new HadoopTables();
+
+    for (int[] spec : new int[][] {{8, 250}, {16, 50000}}) {
```
Comment (huaxingao) [inline arrow/src/test/java/org/apache/iceberg/arrow/vectorized/TestArrowReader.java]: also change this to @ParameterizedTest?

**Review by huaxingao — APPROVED** [review]
LGTM

**Comment by huaxingao** [comment]
@pvary the PR was updated to mirror BaseParquetReaders's rejection policy: uint8/uint16 are now accepted  and uint32/uint64 are rejected with the same IllegalArgumentException messages as the non-vectorized path. The one remaining gap vs the non-vectorized reader is uint32 → long widening (the expected.typeId() == TypeID.LONG branch in BaseParquetReaders), which would require a new vectorized read path and is worth a separate PR. 
Do you have any further concerns? If not, I'll merge.

**Review by pvary — APPROVED** [review]

**Comment by pvary** [comment]
Please update the PR title and the commit message to reflect the actual change

**Comment by huaxingao** [comment]
Thanks @drexler-sky for the PR! Thanks @pvary @anoopj for the review!
