### PR TITLE
Use particular worker pool for flink jobs

### LINKED ISSUE #3776: Flink connector thrown `Trying to access closed classloader`
Hi, i'm trying to test the unreleased Flink 1.13 connector on a Flink 1.13.1 cluster running on k8s.

The task is simple like `INSERT OVERWRITE a SELECT * FROM b`.

When i submit a task for the first time, it's ok.
But when i submit the task for the second time(run on the same TaskManager with the first time), the following exception is thrown, it's weird.

<details>
<summary>java.lang.IllegalStateException: Trying to access closed classloader</summary>

```
2021-12-20 11:53:11,697 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - IcebergFilesCommitter -> Sink: IcebergSink ice.t1.d (1/1)#0 (e74babbac1ebb51fe72958bd177ae534) switched from INITIALIZING to RUNNING.
2021-12-20 11:53:11,854 INFO  org.apache.iceberg.flink.sink.IcebergFilesCommitter          [] - Committing dynamic partition overwrite with 1 data files and 0 delete files to table ice.t1.d
2021-12-20 11:53:11,946 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - IcebergFilesCommitter -> Sink: IcebergSink ice.t1.d (1/1)#0 (e74babbac1ebb51fe72958bd177ae534) switched from RUNNING to FAILED with failure cause: java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.ensureInner(FlinkUserCodeClassLoaders.java:164)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.loadClass(FlinkUserCodeClassLoaders.java:172)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.apache.iceberg.common.DynClasses$Builder.impl(DynClasses.java:68)
	at org.apache.iceberg.avro.GenericAvroReader$ReadBuilder.record(GenericAvroReader.java:85)
	at org.apache.iceberg.avro.GenericAvroReader$ReadBuilder.record(GenericAvroReader.java:72)
	at org.apache.iceberg.avro.AvroSchemaVisitor.visit(AvroSchemaVisitor.java:50)
	at org.apache.iceberg.avro.GenericAvroReader.initReader(GenericAvroReader.java:47)
	at org.apache.iceberg.avro.GenericAvroReader.setSchema(GenericAvroReader.java:53)
	at org.apache.iceberg.avro.ProjectionDatumReader.newDatumReader(ProjectionDatumReader.java:80)
	at org.apache.iceberg.avro.ProjectionDatumReader.setSchema(ProjectionDatumReader.java:69)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:133)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:130)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:122)
	at org.apache.iceberg.shaded.org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:66)
	at org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:100)
	at org.apache.iceberg.avro.AvroIterable.getMetadata(AvroIterable.java:66)
	at org.apache.iceberg.ManifestReader.<init>(ManifestReader.java:103)
	at org.apache.iceberg.ManifestFiles.read(ManifestFiles.java:87)
	at org.apache.iceberg.SnapshotProducer.newManifestReader(SnapshotProducer.java:378)
	at org.apache.iceberg.MergingSnapshotProducer$DataFileFilterManager.newManifestReader(MergingSnapshotProducer.java:716)
	at org.apache.iceberg.ManifestFilterManager.filterManifest(ManifestFilterManager.java:295)
	at org.apache.iceberg.ManifestFilterManager.lambda$filterManifests$0(ManifestFilterManager.java:186)
	at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:405)
	at org.apache.iceberg.util.Tasks$Builder.access$300(Tasks.java:71)
	at org.apache.iceberg.util.Tasks$Builder$1.run(Tasks.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```
</details>

### PR DESCRIPTION
**Pull request by yittg**
Fixes #3776

### CODE REVIEW

**Comment by yittg** [comment]
@rdblue @openinx Please help review this change.

File: core/src/main/java/org/apache/iceberg/util/ThreadPools.java [hunk 1]
```diff
@@ -61,6 +55,16 @@ public static ExecutorService getWorkerPool() {
     return WORKER_POOL;
   }
 
+  public static ExecutorService newWorkerPool(String nameFormat) {
```
Comment (rdblue) [inline core/src/main/java/org/apache/iceberg/util/ThreadPools.java:58]: In other places, we use a name prefix and add `"-%d"` to that prefix so that we can guarantee it is there.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java [hunk 2]
```diff
@@ -350,11 +354,19 @@ public void endInput() throws IOException {
...
+  public void open() throws Exception {
+    this.workerPool = ThreadPools.newWorkerPool("iceberg-files-committer-worker-pool-%d");
+  }
+
   @Override
   public void close() throws Exception {
     if (tableLoader != null) {
       tableLoader.close();
     }
+    if (workerPool != null) {
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java:367]: Nit: we add a newline after control flow blocks and the following statement.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java [hunk 3]
```diff
@@ -79,6 +83,11 @@ public StreamingMonitorFunction(TableLoader tableLoader, ScanContext scanContext
     this.scanContext = scanContext;
   }
 
+  @Override
+  public void open(Configuration parameters) throws Exception {
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:87]: Should the pool size be configured by parameters?

Comment (rdblue) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:87]: Also, is there a way to share pools if there are multiple Iceberg operators in the same Flink job?

File: core/src/main/java/org/apache/iceberg/util/ThreadPools.java (hunk 1 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java:58]: And I think this should also accept a parallelism argument so that it is easily configurable.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java (hunk 3 above)
Comment (yittg) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:87]: > Should the pool size be configured by parameters?

Configured from scan context;

> Also, is there a way to share pools if there are multiple Iceberg operators in the same Flink job?

I think it's hard to share, and it will easily get meaningless across distributed nodes.
What do you think, @rdblue?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java [hunk 4]
```diff
@@ -129,6 +135,10 @@ public void initializeState(StateInitializationContext context) throws Exception
     Preconditions.checkArgument(maxContinuousEmptyCommits > 0,
         MAX_CONTINUOUS_EMPTY_COMMITS + " must be positive");
 
+    int manifestsScanParallelism = PropertyUtil.propertyAsInt(
+        table.properties(), MANIFESTS_SCAN_PARALLELISM, ThreadPools.WORKER_THREAD_POOL_SIZE);
+    this.workerPool = ThreadPools.newWorkerPool("iceberg-files-committer-worker-pool", manifestsScanParallelism);
```
Comment (yittg) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java:140]: configured from `table#properties` like the `MAX_CONTINUOUS_EMPTY_COMMITS` configuration  to make it simple for now. Add another ways if it's needed in the future.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java (hunk 3 above)
Comment (yittg) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:87]: @rdblue do you think that sharing a pool in one job is a blocking issue? If that, we can provide a pool keyed by job. it's somehow reasonable to replace the original pool equivalently  :)

File: core/src/main/java/org/apache/iceberg/util/ThreadPools.java [hunk 5]
```diff
@@ -61,6 +62,26 @@ public static ExecutorService getWorkerPool() {
     return WORKER_POOL;
   }
 
+  public static ExecutorService newWorkerPool(String namePrefix, Integer parallelism) {
+    return MoreExecutors.getExitingExecutorService(
+        (ThreadPoolExecutor) Executors.newFixedThreadPool(
+            Optional.ofNullable(parallelism).orElse(WORKER_THREAD_POOL_SIZE),
```
Comment (stevenzwu) [inline core/src/main/java/org/apache/iceberg/util/ThreadPools.java:68]: should we make the param a primitive type and provide an overload method without the poolSize param?

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java [hunk 6]
```diff
@@ -79,6 +83,16 @@ public StreamingMonitorFunction(TableLoader tableLoader, ScanContext scanContext
...
+    super.open(parameters);
+
+    final String jobId = getRuntimeContext().getJobId().toString();
+    this.workerPool = ThreadPools.newKeyedWorkerPool(jobId, "flink-worker-pool", scanContext.planParallelism());
```
Comment (stevenzwu) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:91]: I saw this shares the same key as `IcebergFilesCommitter`, but not `FlinkInputFormat`. Trying to understand the reasons.

File: flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java [hunk 7]
```diff
@@ -72,7 +73,8 @@ private SplitHelpers() {
       }
 
       final ScanContext scanContext = ScanContext.builder().build();
-      final List<IcebergSourceSplit> splits = FlinkSplitPlanner.planIcebergSourceSplits(table, scanContext);
+      final List<IcebergSourceSplit> splits = FlinkSplitPlanner.planIcebergSourceSplits(
+          table, scanContext, ThreadPools.getWorkerPool());
```
Comment (stevenzwu) [inline flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java:77]: this uses the default/shared worker pool, while others use a separate pool. what are the reasons?

Comment (stevenzwu) [reply flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java:77]: nm. I guess it is because this is a test class.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java (hunk 6 above)
Comment (rdblue) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:91]: I agree here. Since this is creating a different thread pool per job ID, the thread name prefix should also include the job ID to get unique names.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java [hunk 8]
```diff
@@ -79,6 +83,16 @@ public StreamingMonitorFunction(TableLoader tableLoader, ScanContext scanContext
...
+    getRuntimeContext().registerUserCodeClassLoaderReleaseHookIfAbsent(
+        "release-flink-worker-pool", () -> ThreadPools.shutdownKeyedWorkerPool(jobId));
```
Comment (rdblue) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:93]: Is the key here also going to be a problem? Or is this a description?

**Review by rdblue — CHANGES_REQUESTED** [review]
Thanks, @yittg! I really appreciate how patient you've been with me getting back to this review.

There are two main things to fix now. First, I don't think we need to keep track of open pools in `ThreadPools`. Second, I agree with @stevenzwu's comment about passing the same name prefix for all of the pools created by the monitor and the sink. We should make sure the prefix is also unique by job ID.

Thanks!

File: core/src/main/java/org/apache/iceberg/util/ThreadPools.java (hunk 5 above)
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java:68]: I'm okay either way.

File: core/src/main/java/org/apache/iceberg/util/ThreadPools.java [hunk 9]
```diff
@@ -61,6 +62,26 @@ public static ExecutorService getWorkerPool() {
...
+            new ThreadFactoryBuilder()
+                .setDaemon(true)
+                .setNameFormat(namePrefix + "-%d")
+                .build()));
+  }
+
+  public static ExecutorService newKeyedWorkerPool(String key, String namePrefix, Integer parallelism) {
```
[the remark this answers is not in the document]
Comment (stevenzwu) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java:75]: if the intention is to reuse the job specific thread pool in Flink, then we do need the static cache as the same keyed pool may be requested from multiple code path. 

Is this a Flink only problem regarding classloader issue on thread pool? if so, maybe we can move the keyed cache into Flink module.

[the remark this answers is not in the document]
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java:75]: Oh, so the job can share between the monitor and the sink? I don't really mind having two pools for that.

[the remark this answers is not in the document]
Comment (yittg) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java:75]: @rdblue ,sorry, i don't get your point exactly. let me guess, what you really mean is sharing pools for all sources or all sinks, not for all sources and sinks?
To be clear, for example, if a job consists of:
Source: Iceberg A(parallelism: 3), Source:Iceberg B, Sink:Iceberg C, Sink: Iceberg D.
What's your favor?

1. share btw all parallelism of one operator, like 3 subtask for Iceberg A (it can be run in different slots in one TaskManager or different TaskManagers) ;
2. share btw all sources or all sinks, like sharing one for btw A and B, and another one for C and D; 
3. share btw all operators, like sharing btw A, B, C, and D; all subtasks in same TaskManager can share.

[the remark this answers is not in the document]
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java:75]: What I was thinking was a pool per operator in a job, rather than a pool per job. That avoids the need to track thread pools by some key in static state. I think it is probably fine to have more pools since these are primarily for IO. Does that sound reasonable?

[the remark this answers is not in the document]
Comment (yittg) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java:75]: So no any kind of sharing is needed mentioned [here#comment](https://github.com/apache/iceberg/pull/4177#discussion_r812199983), right? That makes sense to me.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java [hunk 10]
```diff
@@ -76,9 +78,12 @@ public BaseStatistics getStatistics(BaseStatistics cachedStatistics) {
   public FlinkInputSplit[] createInputSplits(int minNumSplits) throws IOException {
     // Called in Job manager, so it is OK to load table from catalog.
     tableLoader.open();
+    final ExecutorService workerPool = ThreadPools.newWorkerPool("iceberg-plan-worker-pool", context.planParallelism());
     try (TableLoader loader = tableLoader) {
       Table table = loader.loadTable();
-      return FlinkSplitPlanner.planInputSplits(table, context);
+      return FlinkSplitPlanner.planInputSplits(table, context, workerPool);
+    } finally {
+      workerPool.shutdown();
```
Comment (yittg) [inline flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java:86]: This function is called in client and job manager. So there is no context here. Given it's a adhoc pool and will be shut down after planning, i think it's ok to naming it in this way.

**Review by yittg — COMMENTED** [review]
Given the `StreamingMonitorFunction` and `IcebergFilesCommitter` are both 1-parallelism. We can new worker pool in subtask open along with guaranteeing one worker pool per operator.

File: core/src/main/java/org/apache/iceberg/util/ThreadPools.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (stevenzwu) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java]: after reviewing the usage of the thread pools, I am also in favor of no sharing of thread pools so that we can avoid the static cache. None of the usage is on parallel tasks.
* source: split planning (running on jobmanager or the single-parallelism StreamingMonitorFunction)
* sink: single-parallelism committer

[the remark this answers is not in the document]
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java]: @stevenzwu, for that use case, maybe we should follow up to this PR with one that allows you to configure a named threadpool? I think that's probably the use case that @yittg had in mind when he set up sharing.

File: flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java (hunk 3 above)
Comment (rdblue) [reply flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java:90]: Hey, sorry about this. I think my comment here is probably what caused the confusion about sharing pools by job ID. I think there are use cases around this (Steven has one at least) but let's focus on fixing the problem here and sharing resources later.

Thanks for your patience, @yittg!

**Review by rdblue — APPROVED** [review]

File: core/src/main/java/org/apache/iceberg/util/ThreadPools.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (stevenzwu) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java]: In addition to documentation change, we should also make sure this behavior change is captured in the release note of the next minor version release of 0.14.0.  @rdblue where do we track future release note?

[the remark this answers is not in the document]
Comment (rdblue) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java]: @stevenzwu, I added the "release notes" tag to this PR and added it to the 0.14.0 release milestone so we add this to release notes. If you want, you can add a comment with the suggested release notes at the end.

[the remark this answers is not in the document]
Comment (yittg) [reply core/src/main/java/org/apache/iceberg/util/ThreadPools.java]: Yeah, although I didn't think about sharing at the beginning. but some kind of sharing or global limit sounds good to me after some consideration. We can provide a reasonable solution next I think. 
Thanks, @rdblue and @stevenzwu .
