### PR TITLE
Core: Ensure current and newly added view versions are retained in ViewMetadata build

### LINKED ISSUE #12113: ViewMetadataBuilder does not always retain changes in current build
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

There is one edge case we missed in https://github.com/apache/iceberg/pull/12067 that might lead to a ViewVersion, added in the current build, not beeing retained:

1. Add view version 1 and set current
2. Set retention of versions to 2
3. Add view versions 2 & 3
4. Build

The builder should keep all versions (1, 2, 3) because 1 is the current version and must always be retained and neither 2 nor 3 may be discarded as they where added in this build.

A second build should retain 1 (current version) and 3 (highest id of the remaining) and discard 2.

As discussed CC @nastra 

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by lliangyu-lin**
### Description
Before this change, ```ViewMetadata.Builder``` did not always retain all view versions added in the current build. This issue was caused by ```int numVersionsToKeep = Math.max(numAddedVersions, historySize)```, which did not account for the case where the current view version was not among the newly added versions, leading to one version from the current build being disregarded (```versionsAddedInCurrentBuildAreRetained``` demonstrated the expected behavior).

The fix ensures that:
* The current view version and all view versions added in the current build are explicitly retained.
* Any remaining versions (up to historySize) are retained in descending order of version ID.

### Testing
```./gradlew spotlessApply```
```./gradlew :iceberg-core:test --tests "org.apache.iceberg.view.TestViewMetadata"```

Fixes #12113

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java [hunk 1]
```diff
@@ -494,22 +499,22 @@ public ViewMetadata build() {
 
     @VisibleForTesting
     static List<ViewVersion> expireVersions(
-        Map<Integer, ViewVersion> versionsById, int numVersionsToKeep, ViewVersion currentVersion) {
+        Map<Integer, ViewVersion> versionsById,
+        int numVersionsToKeep,
+        Set<ViewVersion> keepVersions) {
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:504]: rather than changing this API I think we can also just do this:

```
--- a/core/src/main/java/org/apache/iceberg/view/ViewMetadata.java
+++ b/core/src/main/java/org/apache/iceberg/view/ViewMetadata.java
@@ -35,6 +35,7 @@ import org.apache.iceberg.exceptions.ValidationException;
 import org.apache.iceberg.relocated.com.google.common.annotations.VisibleForTesting;
 import org.apache.iceberg.relocated.com.google.common.base.Preconditions;
 import org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap;
+import org.apache.iceberg.relocated.com.google.common.collect.ImmutableSet;
 import org.apache.iceberg.relocated.com.google.common.collect.Lists;
 import org.apache.iceberg.relocated.com.google.common.collect.Maps;
 import org.apache.iceberg.relocated.com.google.common.collect.Sets;
@@ -463,8 +464,13 @@ public interface ViewMetadata extends Serializable {
           historySize);

       // expire old versions, but keep at least the versions added in this builder
-      int numAddedVersions = (int) changes(MetadataUpdate.AddViewVersion.class).count();
-      int numVersionsToKeep = Math.max(numAddedVersions, historySize);
+      Set<Integer> addedVersions =
+          changes(MetadataUpdate.AddViewVersion.class)
+              .map(v -> v.viewVersion().versionId())
+              .collect(Collectors.toSet());
+      int numVersions =
+          ImmutableSet.builder().addAll(addedVersions).add(currentVersionId).build().size();
+      int numVersionsToKeep = Math.max(numVersions, historySize);
```

File: core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java [hunk 2]
```diff
@@ -396,6 +397,28 @@ public void viewVersionHistoryIsCorrectlyRetained() {
...
+            .addSchema(new Schema(Types.NestedField.required(1, "x", Types.LongType.get())))
+            .addVersion(v1)
+            .setCurrentVersionId(v1.versionId())
+            .setProperties(ImmutableMap.of(ViewProperties.VERSION_HISTORY_SIZE, "2"))
+            .build();
+    assertThat(metadata.versions()).containsOnly(v1);
+
+    ViewMetadata updated = ViewMetadata.buildFrom(metadata).addVersion(v2).addVersion(v3).build();
+    assertThat(updated.versions()).containsExactlyInAnyOrder(v1, v2, v3);
+    updated = ViewMetadata.buildFrom(updated).build();
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java:418]: please add `// rebuild the metadata to expire older versions` right above this line

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java (hunk 1 above)
Comment (lliangyu-lin) [reply core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:504]: Thanks @nastra for the review. 
Yeah, the ```addVersionInternal``` will only add new versions with highest id + 1. 
In that case, it make sense just make sure the ```numVersionsToKeep``` has the correct value and pass to expireVersions and no need to update to API. Let me update this.

**Review by nastra — APPROVED** [review]

**Comment by nastra** [comment]
@amogh-jahagirdar could you also take a look please?

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java [hunk 3]
```diff
@@ -462,9 +463,15 @@ public ViewMetadata build() {
...
-      int numAddedVersions = (int) changes(MetadataUpdate.AddViewVersion.class).count();
-      int numVersionsToKeep = Math.max(numAddedVersions, historySize);
+      // expire old versions, but keep at least the versions added in this builder and the current
+      // version
+      Set<Integer> addedVersions =
+          changes(MetadataUpdate.AddViewVersion.class)
+              .map(v -> v.viewVersion().versionId())
+              .collect(Collectors.toSet());
+      int numVersions =
+          ImmutableSet.builder().addAll(addedVersions).add(currentVersionId).build().size();
```
[the remark this answers is not in the document]
Comment (lliangyu-lin) [reply core/src/main/java/org/apache/iceberg/view/ViewMetadata.java]: Thanks for the review. I made a minor change to combine the set and also since we just need the size, there is no set left around. I'm not sure if a function will be needed in this case.

**Comment by lliangyu-lin** [comment]
cc: @Fokko @amogh-jahagirdar PR pending for final review and merge, could you help?

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java [hunk 4]
```diff
@@ -462,9 +463,18 @@ public ViewMetadata build() {
...
+      // version
+      int numVersions =
+          ImmutableSet.builder()
+              .addAll(
+                  changes(MetadataUpdate.AddViewVersion.class)
+                      .map(v -> v.viewVersion().versionId())
+                      .collect(Collectors.toSet()))
+              .add(currentVersionId)
+              .build()
+              .size();
```
Comment (amogh-jahagirdar) [inline core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:476]: Minor: Isn't this the same as 

```
(int) changes(MetadataUpdate.AddViewVersion.class).count() + 1; 
```

Feels a bit easier to read that way along with the comment since I don't think we actually need the set.

**Review by amogh-jahagirdar — COMMENTED** [review]
Had a minor simplification that would be good to address, thank you for the fix @lliangyu-lin !

File: core/src/main/java/org/apache/iceberg/view/ViewMetadata.java (hunk 4 above)
Comment (gaborkaszab) [reply core/src/main/java/org/apache/iceberg/view/ViewMetadata.java:476]: Yes, I also think we need a set here in here. My original comment was to avoid introducing 2 sets as the code was doing so, one is enough instead.

**Review by gaborkaszab — APPROVED** [review]

**Review by amogh-jahagirdar — APPROVED** [review]

**Comment by amogh-jahagirdar** [comment]
Thanks @lliangyu-lin for the fix, @nastra @gaborkaszab for reviewing. I'll go ahead and merge!
