### PR TITLE
Core: Deflake TestManifestCaching.testWeakFileIOReferenceCleanUp

### LINKED ISSUE #5861: Test flakiness: TestManifestCaching > testWeakFileIOReferenceCleanUp
### Apache Iceberg version

main (development)

### Query engine

_No response_

### Please describe the bug 🐞

The test itself was introduced with #4518 and failed on latest master in https://github.com/apache/iceberg/actions/runs/3129464949/jobs/5078743589:

I've been running `TestManifestCaching` in a loop and this test failed quite often for me locally
```
TestManifestCaching > testWeakFileIOReferenceCleanUp FAILED
    java.lang.AssertionError: expected:<8> but was:<1>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.apache.iceberg.TestManifestCaching.testWeakFileIOReferenceCleanUp(TestManifestCaching.java:182)
```

### PR DESCRIPTION
**Pull request by rizaon**
This attempt to deflake testWeakFileIOReferenceCleanUp by removing the failed assertion and changing the cache executor from `ForkJoinPool#commonPool` to `Runnable#run`.

Close #5861

### CODE REVIEW

File: core/src/test/java/org/apache/iceberg/TestManifestCaching.java [hunk 1]
```diff
@@ -178,27 +182,27 @@ public void testWeakFileIOReferenceCleanUp() {
...
     FileIO lastIO = cacheEnabledHadoopFileIO();
     ContentCache lastCache = contentCache(manifestCache, lastIO);
-    System.gc();
-    manifestCache.cleanUp();
-    awaitQuiescence();
+
+    int numGC = 0;
+    int maxGC = 100;
+    while (manifestCache.estimatedSize() > 2 && numGC < maxGC) {
+      System.gc();
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/TestManifestCaching.java:194]: in general it's not a good practice to depend on repeated (or even single) `System.gc()` calls to make something work.
I would probably suggest to use https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/testing/GcFinalization.java#L297 once here instead of plain `System.gc()` calls in a loop

File: core/src/test/java/org/apache/iceberg/TestManifestCaching.java [hunk 2]
```diff
@@ -250,6 +236,18 @@ private Table createTable(Map<String, String> properties) throws Exception {
         .create();
   }
 
+  protected HadoopCatalog hadoopCatalog(Map<String, String> catalogProperties) throws IOException {
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/TestManifestCaching.java:239]: can probably be made private

File: versions.props [hunk 3]
```diff
@@ -10,6 +10,7 @@ org.apache.pig:pig = 0.14.0
 com.fasterxml.jackson.*:* = 2.11.4
 com.google.errorprone:error_prone_annotations = 2.3.3
 com.google.guava:guava = 31.1-jre
+com.google.guava:guava-testlib = 31.1-jre
```
Comment (nastra) [inline versions.props:13]: nit: you should be able to replace the previous line with `com.google.guava:* = 31.1-jre`

File: core/src/test/java/org/apache/iceberg/TestManifestCaching.java [hunk 4]
```diff
@@ -178,22 +181,15 @@ public void testWeakFileIOReferenceCleanUp() {
       }
     }
 
-    System.gc();
+    GcFinalization.awaitFullGc();
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/TestManifestCaching.java:184]: the comment in L188 says `// Insert one more FileIO to trigger cache eviction.` but aren't we triggering cache eviction already here?
It seems the original version of the test was expecting things to be evicted only when `IO_MANIFEST_CACHE_MAX_FILEIO_DEFAULT` is reached/exceeded

Comment (rizaon) [reply core/src/test/java/org/apache/iceberg/TestManifestCaching.java]: I think that comment I made is inherently flawed since I use `System.gc()`.

The main purpose of the test is to verify that cache entry with garbage collected keys will be removed from the cache, and `GcFinalization.awaitFullGc()` + `manifestCache.cleanUp()` does evict those entries. In [572f0ca](https://github.com/apache/iceberg/pull/5862/commits/572f0ca0322f0974ad0b31ac4c184bce8b91ef84), I simplified testWeakFileIOReferenceCleanUp by not exceeding IO_MANIFEST_CACHE_MAX_FILEIO_DEFAULT.

File: versions.props (hunk 3 above)
Comment (rizaon) [reply versions.props]: Done.

**Comment by rizaon** [comment]
Got the following error:
> Error: eckstyle] [ERROR] /home/runner/work/iceberg/iceberg/core/src/test/java/org/apache/iceberg/TestManifestCaching.java:24:1: Use org.apache.iceberg.relocated.* classes from bundled-guava module instead. [BanUnrelocatedGuavaClasses]

I'm not sure how to include guava-testlib into iceberg-bundled-guava.

File: bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java [hunk 5]
```diff
@@ -98,5 +99,6 @@ public class GuavaClasses {
     CountingOutputStream.class.getName();
     Suppliers.class.getName();
     Stopwatch.class.getName();
+    GcFinalization.class.getName();
```
Comment (nastra) [inline bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java:102]: @rdblue any thoughts on adding a test class to `GuavaClasses` vs relaxing checkstyle so that classes from `com.google.common.testing` are allowed in tests?

Comment (rdblue) [reply bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java:102]: I'd probably allow the direct classes in tests.

**Comment by rdblue** [comment]
@danielcweeks, can you help review this as well since you reviewed the original PR?

File: bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java (hunk 5 above)
Comment (nastra) [reply bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java:102]: @rizaon for this you'd want to add something to our [checktyle rules](https://github.com/apache/iceberg/tree/master/.baseline/checkstyle) so that classes from `com.google.common.testing` are allowed to be used in tests directly rather than having to bundle them via `GuavaClasses`

Comment (rizaon) [reply bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java]: Done in 3063b1a

Comment (nastra) [reply bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java]: Using the suppression like this would allow people to e.g. use `com.google.common.base.Preconditions` directly in tests right? We still want to make sure that classes from `com.google.common` are used via `org.apache.iceberg.relocated.*` in tests as well. 
You might need to play a bit with the correct checkstyle configuration so that
* all java code can't import `com.google.common` directly
* test java code can import `com.google.common.testing` only

**Review by nastra — APPROVED** [review]
this LGTM now, thanks for fixing @rizaon

File: core/src/test/java/org/apache/iceberg/TestManifestCaching.java [hunk 6]
```diff
@@ -178,31 +181,20 @@ public void testWeakFileIOReferenceCleanUp() {
...
-        "No entries should be evicted before IO_MANIFEST_CACHE_MAX_FILEIO_DEFAULT exceeded.",
-        0,
-        manifestCache.stats().evictionCount());
-
-    // Insert one more FileIO to trigger cache eviction.
+    // Insert the last FileIO and trigger GC + cleanup.
     FileIO lastIO = cacheEnabledHadoopFileIO();
     ContentCache lastCache = contentCache(manifestCache, lastIO);
-    System.gc();
+    GcFinalization.awaitFullGc();
```
Comment (danielcweeks) [inline core/src/test/java/org/apache/iceberg/TestManifestCaching.java:187]: So this seems like a better approach, but it looks like the recommendation is to use `awaitClear`/`awaitDone` with some condition and timeout if possible.  `awaitFullGc` appears to only wait for a single reference (probably something they construct as part of the test).  Seems likely that we could still end up in a flaky test condition.

Comment (rizaon) [reply core/src/test/java/org/apache/iceberg/TestManifestCaching.java]: Done in 713679b

**Review by danielcweeks — APPROVED** [review]
