### PR TITLE
Fix concurrency issues in Azure credential refresh.

### LINKED ISSUE #13733: Azure Credential Refresh does not work in most cases
### Apache Iceberg version

1.9.2 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

The main issue is that `VendedAdlsCredentialProvider` tries to call `Mono#block` even if in an async context, causing:
```
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-1
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	at reactor.core.publisher.Mono.block(Mono.java:1742)
	at org.apache.iceberg.azure.adlsv2.VendedAdlsCredentialProvider.credentialForAccount(VendedAdlsCredentialProvider.java:78)
	at org.apache.iceberg.azure.adlsv2.VendedAzureSasCredentialPolicy.maybeUpdateCredential(VendedAzureSasCredentialPolicy.java:58)
	at org.apache.iceberg.azure.adlsv2.VendedAzureSasCredentialPolicy.process(VendedAzureSasCredentialPolicy.java:46)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:81)
	at com.azure.storage.common.policy.MetadataValidationPolicy.process(MetadataValidationPolicy.java:45)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:81)
	at com.azure.core.http.policy.AddDatePolicy.lambda$process$0(AddDatePolicy.java:43)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
	... 12 more
```

But there are also other concurrency issues around that code which often lead to e.g. CMEs, e.g. the use of `HashMap#computeIfAbsent` by multiple threads at once.

### Willingness to contribute

I have already PR'ed a fix, just wanted to document the issue as well.

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by msawyer-palantir**
Fixes #13733

The first commit fixes a crash when trying to use the pipeline async on a parallel Reactor thread:
```
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-1
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	at reactor.core.publisher.Mono.block(Mono.java:1742)
	at org.apache.iceberg.azure.adlsv2.VendedAdlsCredentialProvider.credentialForAccount(VendedAdlsCredentialProvider.java:78)
	at org.apache.iceberg.azure.adlsv2.VendedAzureSasCredentialPolicy.maybeUpdateCredential(VendedAzureSasCredentialPolicy.java:58)
	at org.apache.iceberg.azure.adlsv2.VendedAzureSasCredentialPolicy.process(VendedAzureSasCredentialPolicy.java:46)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:81)
	at com.azure.storage.common.policy.MetadataValidationPolicy.process(MetadataValidationPolicy.java:45)
	at com.azure.core.http.HttpPipelineNextPolicy.process(HttpPipelineNextPolicy.java:81)
	at com.azure.core.http.policy.AddDatePolicy.lambda$process$0(AddDatePolicy.java:43)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
	... 12 more
```

The second commit fixes some other thread-safety issues I noticed in the relevant code, which indeed caused failures in our tests.

cc @nastra

### CODE REVIEW

File: azure/src/main/java/org/apache/iceberg/azure/adlsv2/VendedAdlsCredentialProvider.java [hunk 1]
```diff
@@ -51,7 +52,7 @@ public class VendedAdlsCredentialProvider implements Serializable, AutoCloseable
   private final SerializableMap<String, String> properties;
   private final String credentialsEndpoint;
   private final String catalogEndpoint;
-  private transient volatile Map<String, SimpleTokenCache> sasCredentialByAccount;
+  private transient volatile ConcurrentMap<String, SimpleTokenCache> sasCredentialByAccount;
```
Comment (nastra) [inline azure/src/main/java/org/apache/iceberg/azure/adlsv2/VendedAdlsCredentialProvider.java]:
```suggestion
  private transient volatile Map<String, SimpleTokenCache> sasCredentialByAccount;
```

this can still stay a Map

File: azure/src/main/java/org/apache/iceberg/azure/adlsv2/VendedAzureSasCredentialPolicy.java [hunk 2]
```diff
@@ -30,8 +30,8 @@
 class VendedAzureSasCredentialPolicy implements HttpPipelinePolicy {
   private final String account;
   private final VendedAdlsCredentialProvider vendedAdlsCredentialProvider;
-  private AzureSasCredential azureSasCredential;
-  private AzureSasCredentialPolicy azureSasCredentialPolicy;
+  private volatile AzureSasCredential azureSasCredential;
+  private volatile AzureSasCredentialPolicy azureSasCredentialPolicy;
```
Comment (nastra) [inline azure/src/main/java/org/apache/iceberg/azure/adlsv2/VendedAzureSasCredentialPolicy.java]: the double-checked locking only applies to `azureSasCredential`, so I don't think this one needs to be made volatile

**Review by nastra — APPROVED** [review]
