### PR TITLE
Flink : Fix Repeated Rewrite for RewriteDataFilesAction

### LINKED ISSUE #1661: Repeated  rewrite datafile in RewriteDataFilesAction
The default targetSizeInBytes of RewriteDataFilesAction is 128M, but when there are three 120M files in the partition and execute the rewrite action, three new datafiles of the same size as the original files will be regenerated. I think it is unnecessary and will waste the system resources

### PR DESCRIPTION
**Pull request by zhangjun0x01**
the pr fix #1661 

If DataFile cannot be  combined to CombinedScanTask with other DataFiles, the size of CombinedScanTask list size is 1, so we remove these CombinedScanTasks to avoid compressed repeatedly.

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java [hunk 1]
```diff
@@ -228,9 +228,18 @@ public RewriteDataFilesActionResult execute() {
         .flatMap(Streams::stream)
         .collect(Collectors.toList());
 
+    // add a filter  to the CombinedScanTask list to avoid repeated rewrite datafile
+    List<CombinedScanTask> fileterCombinedScanTasks =
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:232]: Typo in variable name

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java [hunk 2]
```diff
@@ -228,9 +228,18 @@ public RewriteDataFilesActionResult execute() {
...
+        combinedScanTasks.stream().filter(task -> task.files().size() > 1).collect(Collectors.toList());
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:233]: Maybe more clear as !(task.files.nonempty)

Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:233]: Could also push this into the build of Combined scan tasks on line 228, rather than doing a new variable

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java [hunk 3]
```diff
@@ -228,9 +228,18 @@ public RewriteDataFilesActionResult execute() {
...
+
+    if (fileterCombinedScanTasks.isEmpty()) {
+      return RewriteDataFilesActionResult.empty();
+    }
+
     List<DataFile> addedDataFiles = rewriteDataForTasks(combinedScanTasks);
-    List<DataFile> currentDataFiles = filteredGroupedTasks.values().stream()
-        .flatMap(tasks -> tasks.stream().map(FileScanTask::file))
+    List<DataFile> currentDataFiles = fileterCombinedScanTasks.stream()
```
Comment (RussellSpitzer) [inline core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:240]: I think the flatmap here is unecessary since we can flatMap within the map operation instead,

```
    filteredCombinedScanTasks.stream()
        .flatMap(task -> task.files().stream().map(FileScanTask::file))
        .collect(Collectors.toList())
```

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java (hunk 2 above)
Comment (zhangjun0x01) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:233]: > Maybe more clear as !(task.files.nonempty)

we need to remove the combinedScanTasks which size is 1 ，not `nonempty`

Comment (zhangjun0x01) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:233]: > Could also push this into the build of Combined scan tasks on line 228, rather than doing a new variable

I refer to the variable filteredGroupedTasks above，maybe it is more clear

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java (hunk 3 above)
Comment (zhangjun0x01) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:240]: yes thanks for your suggestion，I update it

**Comment by zhangjun0x01** [comment]
@openinx could you help me review the pr ? thanks

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java (hunk 2 above)
Comment (openinx) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:233]: I agree with @RussellSpitzer 's comment about "push this into the build of Combined scan tasks on line 228", because in that way we don't have to construct the `List<CombinedScanTask>` twice,  that is unnecessary. 

BTW,  would you pls add few unit tests to address this case ?  I think it's great to improve this but better to fix it with a UT.

Thanks for the work.

Comment (zhangjun0x01) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java]: I update the pr，add a test  case

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java [hunk 4]
```diff
@@ -226,11 +226,16 @@ public RewriteDataFilesActionResult execute() {
...
         .collect(Collectors.toList());
 
+    if (combinedScanTasks.isEmpty()) {
+      return RewriteDataFilesActionResult.empty();
+    }
+
     List<DataFile> addedDataFiles = rewriteDataForTasks(combinedScanTasks);
-    List<DataFile> currentDataFiles = filteredGroupedTasks.values().stream()
-        .flatMap(tasks -> tasks.stream().map(FileScanTask::file))
+    List<DataFile> currentDataFiles = combinedScanTasks.stream()
```
Comment (openinx) [inline core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:237]: Is this change correct  ?   If we have a single file1 with 200MB, and the target file size is 128MB, then it will be planned into two combined tasks:  128MB, 72MB. Finally the `file1` will occur twice in the currentDataFiles  ?

Comment (zhangjun0x01) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:237]: if there is a datafile which size > targetSizeInBytes ,I think it should not be rewrited , I open a new PR to deal this . 
https://github.com/apache/iceberg/pull/1762

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java [hunk 5]
```diff
@@ -280,4 +280,91 @@ public void testRewriteLargeTableHasResiduals() throws IOException {
...
+   *
+   * @throws IOException IOException
+   */
+  @Test
+  public void testRewriteAvoidRepeateCompress() throws IOException {
+    List<String> records = Lists.newArrayList();
+    List<Record> expected = Lists.newArrayList();
+    for (int i = 0; i < 500; i++) {
+      String data = String.valueOf(i) + "hello iceberg,hello flink";
+      records.add("(" + i + ",'" + data + "')");
```
Comment (openinx) [inline flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:323]: nit:  do we need to concat such a complex string for the `data`  ?  It doesn't look elegant.

Comment (zhangjun0x01) [reply flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:323]: This is to construct a file with a larger file size to distinguish the other two small files, so that we can compress the other two small files without compressing the large file. If the three files are similar in size, we will not be able to do the rewrite

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java (hunk 4 above)
Comment (openinx) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:237]: It's right that we may don't have to rewrite those files whose size greater than target file size.  But in this patch, I don't understand why we need to change it , could you revert this pls ?

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java (hunk 5 above)
Comment (openinx) [reply flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:323]: Yeah, i can understand that it's constructing a large string so that we could have a large file,  then we could pack the larger file into a separate `CombinedScanTask` which should not execute the rewrite action. I mean we could just generate a string like that `Strings.repeat(String.valueOf(I), 10)`, don't have to concat and concat again.  It's a minor issue.

Comment (openinx) [reply flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:323]: About the test case, I think it may be better to generate three data files by using `GenericAppenderFactory` : 
1.  create two small files, each have on record ;
2.  create a larger file by using FileAppender ( write few records until the file length exceed the given target file size). 

Then in theory,  we don't have to  set different threshold for different file format [here](https://github.com/apache/iceberg/pull/1704/files#diff-4a4c7e7c4b4e81c01ecdd9fb53fad72d2b87073ac74ccfeaec0af68ec98816d0R342), The current code is hard to maintain because it seems tricky.

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java (hunk 4 above)
Comment (zhangjun0x01) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:237]: `filteredGroupedTasks` contains all the datafiles that meet the conditions of the query. `combinedScanTasks` removes some datafiles that are smaller than targetSizeInBytes but do not need to be compressed. If when constructing `currentDataFiles`,we use filteredGroupedTasks  instead of combinedScanTasks, those large files that do not need to be compressed will be deleted, resulting in results Incorrect.

When I doing this PR, I forgot to consider the datefile  whose size greater than the target file size. I think it is another issue, so I opened a new PR #1762 to fix it when  I found this issue. I think we should modify #1762 first, then modify this PR, or merge #1762 into  this PR ? what do you think?

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java (hunk 5 above)
Comment (zhangjun0x01) [reply flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:323]: Yes, we should generate a file that meets the target size for different formats. I did not find a suitable method to generate a file and meet my expectations at  that time. I will take a look `GenericAppenderFactory`

Comment (zhangjun0x01) [reply flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:323]: > 2. create a larger file by using FileAppender ( write few records until the file length exceed the given target file size).


I took a look and thought it might not be easy to implement. We need to get the file length through the `length` method until the file reaches the target file size, and then close the appender.

But for orc, we cannot get length from an open appending file, we can only get the file length when the file is closed, which is just the opposite of our needs.

  org.apache.iceberg.orc.OrcFileAppender#length method

```
  @Override
  public long length() {
    Preconditions.checkState(isClosed,
        "Cannot return length while appending to an open file.");
    return file.toInputFile().getLength();
  }
```

Comment (zhangjun0x01) [reply flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java]: I update the pr,use `GenericAppenderFactory` to generate the datafile except `ORC` format

File: core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java (hunk 4 above)
Comment (openinx) [reply core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java:237]: I think we should not rely on specific file-selection strategies here, because different selection strategies  may result in duplicated files for `currentDataFiles`.  The correct way is:  remove the duplicated files so that the `currentDataFiles` has correct files.

I saw the [here](https://github.com/apache/iceberg/pull/1704/files#diff-a330da6f6014d3154bb0979281e53f2b69c9e32117d0223bdf94d514a05cf559R264) has used the `set` to remove duplicated files.  So it's OK now.

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java [hunk 6]
```diff
@@ -280,4 +290,79 @@ public void testRewriteLargeTableHasResiduals() throws IOException {
...
+   * <p>
+   * In this test case,we generated 3 data files and set targetSizeInBytes greater than the largest file size so that it
+   * cannot be  combined a CombinedScanTask with other datafiles. The datafile with the largest file size will not be
+   * compressed.
+   *
+   * @throws IOException IOException
+   */
+  @Test
+  public void testRewriteAvoidRepeateCompress() throws IOException {
+    if (!format.equals(FileFormat.ORC)) {
```
Comment (openinx) [inline flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:308]: Use `Assume.assumeFalse("ORC does not support getting length when file is opening", format.equals(FileFormat.ORC));`

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java [hunk 7]
```diff
@@ -280,4 +290,79 @@ public void testRewriteLargeTableHasResiduals() throws IOException {
...
+        expected.add(record);
+      }
+      fileAppender.close();
+
+      DataFile dataFile = DataFiles.builder(icebergTableUnPartitioned.spec())
+          .withPath(file.getAbsolutePath())
+          .withFileSizeInBytes(file.length())
+          .withFormat(format)
+          .withRecordCount(count)
+          .build();
```
Comment (openinx) [inline flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:330]: Use the `try(...){}` to close the fileAppender like this: 

```java
      File file = temp.newFile();

      int fileSize = 2000;
      try (FileAppender<Record> fileAppender = genericAppenderFactory.newAppender(Files.localOutput(file), format)) {
        for (int idx = 0; fileAppender.length() < fileSize; idx++) {
          Record record = RECORD.copy();
          record.setField("id", idx);
          record.setField("data", "iceberg");
          fileAppender.add(record);
          expected.add(record);
        }
      }

      DataFile dataFile = DataFiles.builder(icebergTableUnPartitioned.spec())
          .withPath(file.getAbsolutePath())
          .withFileSizeInBytes(file.length())
          .withFormat(format)
          .withRecordCount(expected.size())
          .build();
```

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java [hunk 8]
```diff
@@ -280,4 +290,79 @@ public void testRewriteLargeTableHasResiduals() throws IOException {
...
+          .splitOpenFileCost(1)
+          .execute();
+      Assert.assertEquals("Action should rewrite 2 data files", 2, result.deletedDataFiles().size());
+      Assert.assertEquals("Action should add 1 data file", 1, result.addedDataFiles().size());
+
+      icebergTableUnPartitioned.refresh();
+
+      CloseableIterable<FileScanTask> tasks1 = icebergTableUnPartitioned.newScan().planFiles();
+      List<DataFile> dataFiles1 = Lists.newArrayList(CloseableIterable.transform(tasks1, FileScanTask::file));
+      Assert.assertEquals("Should have 2 data files after rewrite", 2, dataFiles1.size());
```
Comment (openinx) [inline flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:360]: I think we'd better to check that the compaction did not compaction the biggest file with one of the two small files ?     That means the `dataFiles1`  should have included the `dataFile` ?

**Comment by aokolnychyi** [comment]
I'll try to take a look at this PR this week as well as I wrote a design [doc](https://docs.google.com/document/d/1aXo1VzuXxSuqcTzMLSQdnivMVgtLExgDWUFMvWeXRxc/edit#heading=h.41vc5dxcib1o) for compaction.

**Comment by rdblue** [comment]
@aokolnychyi, @openinx, this seems like a good one to get into the next release. Can you both take a look?

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java [hunk 9]
```diff
@@ -280,4 +292,82 @@ public void testRewriteLargeTableHasResiduals() throws IOException {
...
+    Schema schema = icebergTableUnPartitioned.schema();
+    GenericAppenderFactory genericAppenderFactory = new GenericAppenderFactory(schema);
+    File file = temp.newFile();
+    int count = 0;
+    try (FileAppender<Record> fileAppender = genericAppenderFactory.newAppender(Files.localOutput(file), format)) {
+      long filesize = 20000;
+      for (; fileAppender.length() < filesize; count++) {
+        Record record = RECORD.copy();
+        record.setField("id", count);
+        record.setField("data", "iceberg");
```
Comment (openinx) [inline flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:321]: nit: we could just use the the: 

```java
Record record = SimpleDataUtil.createRecord(count, "iceberg");
```

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java [hunk 10]
```diff
@@ -280,4 +292,82 @@ public void testRewriteLargeTableHasResiduals() throws IOException {
...
+        .targetSizeInBytes(targetSizeInBytes)
+        .splitOpenFileCost(1)
+        .execute();
+    Assert.assertEquals("Action should rewrite 2 data files", 2, result.deletedDataFiles().size());
+    Assert.assertEquals("Action should add 1 data file", 1, result.addedDataFiles().size());
+
+    icebergTableUnPartitioned.refresh();
+
+    CloseableIterable<FileScanTask> tasks1 = icebergTableUnPartitioned.newScan().planFiles();
+    List<DataFile> dataFilesRewrited = Lists.newArrayList(CloseableIterable.transform(tasks1, FileScanTask::file));
```
Comment (openinx) [inline flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:361]: nit:  `Rewrited` -> `Rewrote`,  or we could just name it `newDataFiles`.

File: flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java [hunk 11]
```diff
@@ -280,4 +292,82 @@ public void testRewriteLargeTableHasResiduals() throws IOException {
...
+    Assert.assertEquals("Should have 2 data files after rewrite", 2, dataFilesRewrited.size());
+
+    // the biggest file do not be rewrited
+    List rewritedDataFileNames = dataFilesRewrited.stream().map(df -> df.path()).collect(Collectors.toList());
```
Comment (openinx) [inline flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java:365]: nit:  could use the method references here.  

```java
        // The biggest file do not be rewrote.
    List<CharSequence> newPaths = newDataFiles.stream().map(ContentFile::path).collect(Collectors.toList());
    Assert.assertTrue(newPaths.contains(file.getAbsolutePath()));
```

**Comment by openinx** [comment]
Patch looks good to me,  left few minor comments.  Thanks.

**Comment by zhangjun0x01** [comment]
> Patch looks good to me, left few minor comments. Thanks.

thanks for your review.I update the pr

**Comment by zhangjun0x01** [comment]
the ci test failed ,I check it ,  `org.apache.iceberg.spark.extensions.TestCopyOnWriteDelete` throw an exception, the PR is unrelated with spark ,is it a bug for CI ?

**Comment by openinx** [comment]
Let's trigger the CI again.

**Comment by openinx** [comment]
Seems the unit test is still broken ?  @zhangjun0x01 would you mind to take a look ?

**Comment by zhangjun0x01** [comment]
in my github acount, the ci passed  ([link](https://github.com/zhangjun0x01/iceberg/actions/runs/451845876/workflow)), and I tested  it in my IDE , it is also passed,I have encountered a similar problem before，I guess it may be related to the CI environment

**Comment by openinx** [comment]
CI is OK now,  just got this merged. Thanks @zhangjun0x01  for contributing.
