### PR TITLE
Core: fix propertiesWithPrefix to strip prefix literally, not as regex

### LINKED ISSUE #15631: PropertyUtil.propertiesWithPrefix treats prefix as regex pattern
### Apache Iceberg version

main (development)

### Query engine

_No response_

### Please describe the bug 🐞

`PropertyUtil.propertiesWithPrefix` uses `String.replaceFirst(prefix, "")` to strip the prefix from matched keys. Since `replaceFirst` treats its first argument as a Java regex pattern, prefixes containing regex-special characters (e.g. `[`, `(`, `+`, `$`) cause incorrect behavior:

1. **Silent mismatch**: A prefix like `prefix[0].` is valid regex where `[0]` matches char `0` and `.` matches any char. After `startsWith` filtering, the key always starts with the literal prefix, but `replaceFirst` fails to match the regex at position 0, silently returning the full key instead of stripping the prefix.

2. **PatternSyntaxException**: A prefix like `prefix[0.` contains an unclosed character class, causing `replaceFirst` to throw `PatternSyntaxException`.

The fix is to replace `replaceFirst(prefix, "")` with `substring(prefix.length())`, which is safe, explicit, and consistent with the `startsWith(prefix)` filter applied immediately before.

Discovered while investigating #15347.

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by moomindani**
## Summary

`PropertyUtil.propertiesWithPrefix` used `String.replaceFirst(prefix, "")` to strip the prefix from matched keys. Since `replaceFirst` treats its first argument as a Java regex pattern, prefixes containing regex-special characters cause incorrect behavior:

1. **Silent mismatch**: e.g. `prefix[0].` — `[0]` is valid regex matching char `0`, so `replaceFirst` fails to match the literal prefix
2. **PatternSyntaxException**: e.g. `prefix[0.` — unclosed character class

The fix replaces `replaceFirst(prefix, "")` with `substring(prefix.length())`, which is safe, explicit, and consistent with the `startsWith(prefix)` filter applied immediately before.

Fixes #15631

## Test plan

- [x] `TestPropertyUtil#propertiesWithPrefixHandlesRegexSpecialChars` — verifies prefix with valid regex-special characters that cause silent mismatch with `replaceFirst`
- [x] `TestPropertyUtil#propertiesWithPrefixHandlesUnclosedRegexChars` — verifies prefix with unclosed regex that throws `PatternSyntaxException` with `replaceFirst`
- [x] Both tests verified to fail with old `replaceFirst` code and pass with `substring` fix
- [x] Existing `TestPropertyUtil` tests still pass

### CODE REVIEW

File: parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java [hunk 1]
```diff
@@ -269,6 +269,54 @@ public void testColumnStatisticsEnabled() throws Exception {
     }
   }
 
+  @Test
+  public void testMultipleColumnsStatisticsDisabled() throws Exception {
```
Comment (ebyhr) [inline parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java]: This test passes even without `PropertyUtil` change. Could you modify it so that it fails without this change?

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java [hunk 2]
```diff
@@ -168,7 +168,9 @@ public static Map<String, String> propertiesWithPrefix(
 
     return properties.entrySet().stream()
         .filter(e -> e.getKey().startsWith(prefix))
-        .collect(Collectors.toMap(e -> e.getKey().replaceFirst(prefix, ""), Map.Entry::getValue));
+        .collect(
+            Collectors.toMap(
+                e -> e.getKey().substring(prefix.length()), Map.Entry::getValue));
```
Comment (ebyhr) [inline core/src/main/java/org/apache/iceberg/util/PropertyUtil.java]: Can we add a new test to TestPropertyUtil?

File: parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java (hunk 1 above)
Comment (moomindani) [reply parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java]: Removed this test. Added two tests to `TestPropertyUtil` instead — one with dot-containing prefixes, and one with regex-special characters (`[`) that would throw `PatternSyntaxException` with the old `replaceFirst` code.

File: core/src/main/java/org/apache/iceberg/util/PropertyUtil.java (hunk 2 above)
Comment (moomindani) [reply core/src/main/java/org/apache/iceberg/util/PropertyUtil.java]: Done, added `propertiesWithPrefixStripsLiterally` and `propertiesWithPrefixHandlesRegexSpecialChars` to `TestPropertyUtil`. The latter fails with the old `replaceFirst` code due to `PatternSyntaxException`.

**Comment by moomindani** [comment]
Dropped the first commit from #15557. The branch now contains only the `PropertyUtil` fix and `TestPropertyUtil` tests.

File: core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java [hunk 3]
```diff
@@ -25,6 +25,37 @@
...
+  }
+
+  @Test
+  void propertiesWithPrefixHandlesRegexSpecialChars() {
+    // Prefix with regex-special characters that would cause PatternSyntaxException
+    // with replaceFirst but work correctly with substring
+    Map<String, String> properties = Map.of("prefix[0].key", "value");
+
+    Map<String, String> result =
+        PropertyUtil.propertiesWithPrefix(properties, "prefix[0].");
```
Comment (mukund-thakur) [inline core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java]: replaceFirst doesn't throw PatternSyntaxException in this case but this **prefix[0.** will 
```
java.util.regex.PatternSyntaxException: Unclosed character class near index 8
prefix[0.
```

**Comment by mukund-thakur** [comment]
I was trying to understand this more. I do think this is a valid issue and the code fix provided here should be added but I am not sure if the root cause of https://github.com/apache/iceberg/issues/15347 is same. 
I tried to write a UT and case explained here seems to work fine even with the old replaceFirst code.

File: core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java (hunk 3 above)
Comment (moomindani) [reply core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java]: Good catch — you're right that `prefix[0].` doesn't throw `PatternSyntaxException`. Fixed the comment to clarify the actual behavior: `replaceFirst` silently fails to strip the prefix since regex `[0]` matches char `0`, not literal `[`. Also added a new test `propertiesWithPrefixHandlesUnclosedRegexChars` with `prefix[0.` which does throw `PatternSyntaxException`. Verified both tests fail with the old `replaceFirst` code and pass with the `substring` fix.

**Comment by moomindani** [comment]
Thanks for investigating. You're right that the actual Iceberg prefix `write.parquet.stats-enabled.column.` works correctly with `replaceFirst`, so this doesn't fix #15347. I've created #15631 to track the `replaceFirst` regex issue separately (discovered while investigating #15347) and updated the PR to fix that instead.

File: core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java [hunk 4]
```diff
@@ -25,6 +25,28 @@
...
 
+  @Test
+  void propertiesWithPrefixHandlesRegexSpecialChars() {
+    // prefix[0]. is a valid regex where [0] matches char '0' and . matches any char,
+    // so replaceFirst would silently fail to strip the literal prefix "prefix[0]."
+    Map<String, String> properties = Map.of("prefix[0].key", "value");
+
+    Map<String, String> result = PropertyUtil.propertiesWithPrefix(properties, "prefix[0].");
+
+    assertThat(result).containsExactlyInAnyOrderEntriesOf(Map.of("key", "value"));
```
Comment (ebyhr) [inline core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java]: nit: We could simplify this assertion with `containsExactly`:
```java
assertThat(result).containsExactly(Map.entry("key", "value"));
```

Same for `propertiesWithPrefixHandlesUnclosedRegexChars`.

File: core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java [hunk 5]
```diff
@@ -25,6 +25,28 @@
 
 public class TestPropertyUtil {
 
+  @Test
+  void propertiesWithPrefixHandlesRegexSpecialChars() {
+    // prefix[0]. is a valid regex where [0] matches char '0' and . matches any char,
+    // so replaceFirst would silently fail to strip the literal prefix "prefix[0]."
```
Comment (ebyhr) [inline core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java]: Future readers might wonder where `replaceFirst` comes from. We could add a brief explanation like: 
```
so replaceFirst (used by the older propertiesWithPrefix) ...
```

File: core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java (hunk 4 above)
Comment (moomindani) [reply core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java]: Done, updated both to use `containsExactly(Map.entry("key", "value"))`.

File: core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java (hunk 5 above)
Comment (moomindani) [reply core/src/test/java/org/apache/iceberg/util/TestPropertyUtil.java]: Done, updated both comments to say "replaceFirst (used by the older propertiesWithPrefix)".

**Comment by RussellSpitzer** [comment]
Looks good to me, any more followups @ebyhr or @mukund-thakur .

**Comment by singhpk234** [comment]
Thank you for the change @moomindani ! Thank your for the review @RussellSpitzer @ebyhr @mukund-thakur

**Comment by moomindani** [comment]
Thank you all!
