### PR TITLE
[core] fix #9997 - Handle s3a file upload interrupt which results in table metadata pointing to files that doesn't exist

### LINKED ISSUE #9997: [core] Table commit successful but metadata json was never created leaving table in a bad state
### Apache Iceberg version

1.3.1

### Query engine

Flink

### Catalog
Hive Metastore

### File IO
Hadoop S3A

### Please describe the bug 🐞

Iceberg table points to a metadata.json that failed to upload to s3. Due to this the table was not loadable as latest metadata json was not found 
`The main method caused an error: Failed to open input stream for file: s3a://bucket/prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json`

### Expected:
when s3 upload to metadata json failed, iceberg's hive commit should have failed as write metadata failed.

### Actual:

Iceberg logs show that commit was successful

`2024-03-06T23:06:36.160+00:00 INFO org.apache.iceberg.hive.HiveTableOperations 
     Committed to table iceberg.default.some_table with the new metadata location s3a://bucket/prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json `

#### However the upload to s3 failed!
`
06/Mar/2024:23:06:01 +0000 REST.PUT.OBJECT	prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json	"PUT /bucket/prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json HTTP/1.1"	**400	IncompleteBody**`

#### Flink pipeline fails around same time as upload 

`2024-03-06T23:06:36.110+00:00  WARN org.apache.flink.runtime.taskmanager.Task 
    message:  Source: table[11] -> PythonCalc[12] -> (Calc[13] -> IcebergStreamWriter, Calc[15] -> IcebergStreamWriter) (2/4)#0 switched from INITIALIZING to FAILED with failure cause:`

### PR DESCRIPTION
**Pull request by abmo-x**
This is fix for https://github.com/apache/iceberg/issues/9997

### Root cause

s3a putObject was interrupted due to flink pipeline failure _while_ the object was being uploaded. As this interrupt is not handled and thrown as an exception, the metadata writer assumes write was successful which results in table pointing to a metadata json file that doesn't exist.

#### Hadoop S3A code
This is the s3a code block which is called from stream close to putObject which is the root cause.

https://github.com/apache/hadoop/blob/0f51d2a4ec17bad754beb17048409811a151be53/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java#L636

``` 
try {
      putObjectResult.get();
      return size;
    } catch (InterruptedException ie) {
      LOG.warn("Interrupted object upload", ie);
      Thread.currentThread().interrupt();
      return 0;
    } catch (ExecutionException ee) {
      throw extractException("regular upload", key, ee);
    }
```

#### Iceberg commit successful on upload interrupt

`
2024-03-06T23:06:36.160+00:00 INFO org.apache.iceberg.hive.HiveTableOperations  Committed to table iceberg.default.some_table with the new metadata location s3a://bucket/prefix/default.db/some_table/metadata/52949-1e28478a-bf5e-4ec0-8d2c-......metadata.json `

But request interrupted 
`2024-03-06T23:06:36.024+00:00 WARN  org.apache.hadoop.fs.s3a.S3ABlockOutputStream  Interrupted object upload`

### CODE REVIEW

**Comment by abmo-x** [comment]
@rdblue 
I reproduced and verified this locally with an Integration test. 

I am wondering whats the best way to include a test for this. I didn't see any tests using hadoop-aws module or s3a. 

cc @nastra @ajantha-bhat  appreciate any inputs to test this with hadoop fs with s3a

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java [hunk 1]
```diff
@@ -185,8 +185,20 @@ public void flush() throws IOException {
...
-      stream.close();
-      this.closed = true;
+      try {
+        stream.close();
+        // {@link org.apache.hadoop.fs.s3a.S3ABlockOutputStream#close()} calls {@link
+        // org.apache.hadoop.fs.s3a.S3ABlockOutputStream#putObject()}
+        // which doesn't throw an exception when interrupted. Need to handle interrupts here to make
+        // sure file is uploaded on close.
+        if (Thread.interrupted()
+            && "S3ABlockOutputStream"
```
Comment (abmo-x) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:195]: I can remove this explicit class name check and just check for an interrupt.

This will make it easier to test this with just unit test

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java [hunk 2]
```diff
@@ -185,8 +185,20 @@ public void flush() throws IOException {
...
+                .equals(stream.getWrappedStream().getClass().getSimpleName())) {
+          throw new IOException("object upload failed as it was interrupted during close");
```
Comment (mas-chen) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:197]: nit: technically, the upload was interrupted (not during close).
```suggestion
          throw new IOException("Failed to close stream since object upload failed.");
```
or something similar? Or maybe this exception should really be thrown by the write APIs?

Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:197]: technically it was interrupted during close as:

`stream.close -> ... internally calls putObject() .. which uploads to s3`

Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:197]: How about just "object upload interrupted"

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 1 above)
Comment (pvary) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:195]: Could we create a class with a same name in a different package?

Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:195]: @pvary
you mean we should include the full class name with package in the if check to cover for other classes with same name?

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java [hunk 3]
```diff
@@ -185,8 +185,20 @@ public void flush() throws IOException {
 
     @Override
     public void close() throws IOException {
-      stream.close();
-      this.closed = true;
+      try {
+        stream.close();
+        // {@link org.apache.hadoop.fs.s3a.S3ABlockOutputStream#close()} calls {@link
+        // org.apache.hadoop.fs.s3a.S3ABlockOutputStream#putObject()}
+        // which doesn't throw an exception when interrupted. Need to handle interrupts here to make
```
Comment (stevenzwu) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:192]: nit: `make sure` is not accurate here. It is more like `Need to check the interrupted flag to detect failed object upload and propagate the error up`.

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 1 above)
Comment (stevenzwu) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:195]: +1 on the fully qualified name. or maybe just use `instanceOf`.

Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:195]: I didn't want to add hadoop-aws module to use `instanceOf`. Let me update this to fully qualified name.

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 3 above)
Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java]: Done.

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 1 above)
Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java]: updated to fully qualified name instead. cannot use `instanceOf` as `org.apache.hadoop.fs.s3a.S3ABlockOutputStream` is package protected.

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java [hunk 4]
```diff
@@ -185,8 +185,21 @@ public void flush() throws IOException {
...
     @Override
     public void close() throws IOException {
-      stream.close();
-      this.closed = true;
+      try {
+        stream.close();
+        // {@link org.apache.hadoop.fs.s3a.S3ABlockOutputStream#close()} calls {@link
+        // org.apache.hadoop.fs.s3a.S3ABlockOutputStream#putObject()}
+        // which doesn't throw an exception when interrupted. Need to check the interrupted flag to
+        // detect failed object upload
```
Comment (stevenzwu) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:193]: nit: comment formatting. merge the next line here

**Review by stevenzwu — APPROVED** [review]
LGTM. let's wait for feedbacks from others @rdblue @RussellSpitzer etc.

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java [hunk 5]
```diff
@@ -185,8 +185,21 @@ public void flush() throws IOException {
...
+        // and propagate the error up.
+        if (Thread.interrupted()
+            && "org.apache.hadoop.fs.s3a.S3ABlockOutputStream"
+                .equals(stream.getWrappedStream().getClass().getName())) {
+          throw new IOException("object upload failed as it was interrupted during close");
+        }
+      } finally {
+        this.closed = true;
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:201]: why not just set this right after `stream.close()`? Then there wouldn't be a need to have the `finally` block

Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:201]: `stream.close` can throw an exception. we want to mark this closed no matter what that's why we need the finally block here.

Comment (nastra) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:201]: if we want to set `this.closed = true` no matter the outcome, then we could also set it right before calling close

Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:201]: sure I can do that. but that's what `finally` block does as well by marking it to true _no matter what_.

Trying to understand better if its not recommended to use finally or it has any drawbacks.

**Comment by abmo-x** [comment]
Added a unit test 

@stevenzwu if you can take a look again. Thanks

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 2 above)
Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java]: Done. Thanks

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java [hunk 6]
```diff
@@ -185,8 +185,21 @@ public void flush() throws IOException {
...
-      this.closed = true;
+      try {
+        stream.close();
+        // {@link org.apache.hadoop.fs.s3a.S3ABlockOutputStream#close()} calls {@link
+        // org.apache.hadoop.fs.s3a.S3ABlockOutputStream#putObject()}
+        // which doesn't throw an exception when interrupted.
+        // Need to check the interrupted flag to detect failed object upload
+        // and propagate the error up.
+        if (Thread.interrupted()
+            && "org.apache.hadoop.fs.s3a.S3ABlockOutputStream"
```
[the remark this answers is not in the document]
Comment (RussellSpitzer) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:196]: Ah package private

**Review by RussellSpitzer — COMMENTED** [review]
I don't know enough about this but it feels like a bug in the Hadoop utility methods here. Do we have a Hadoop issue tracking this as well? I don't have a problem with us patching Iceberg to work around the issue if it is this kind of otherwise silent failure.

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:196]: yeah couldn't use it bcoz of that

**Comment by abmo-x** [comment]
@RussellSpitzer 
Thanks for the review.

waiting for access to create a issue in the hadoop project. 

Looks like the hadoop projects uses this pattern widely and they check for interrupts everywhere https://github.com/search?q=repo%3Aapache%2Fhadoop%20Thread.interrupted&type=code. Not sure why interrupt is preferred vs throwing an exception.

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 5 above)
Comment (stevenzwu) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:201]: Personally I am slightly favoring changing `closed` after the stream is actually closed. I checked the current style in Iceberg. I saw two styles: (1) setting `closed` before the action (2) just set it after the action without finally. It is not be necessary to set it In error/failure case, because close didn't complete successfully.

File: core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+package org.apache.iceberg.hadoop;
+
+import java.io.IOException;
+import org.apache.hadoop.fs.FSDataOutputStream;
+import org.apache.hadoop.fs.s3a.S3ABlockOutputStream;
+import org.apache.iceberg.io.PositionOutputStream;
+import org.junit.jupiter.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+class HadoopStreamsTest {
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java:28]: style is `TestClassFoo`

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+package org.apache.hadoop.fs.s3a;
+
+import java.io.IOException;
+import java.io.OutputStream;
+
+/** mock class for testing hadoop s3a writer */
+public class S3ABlockOutputStream extends OutputStream {
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:25]: move this inside the test class

File: core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+  void closeShouldThrowIOExceptionOnInterrupted() throws IOException {
+
+    FSDataOutputStream fsDataOutputStream =
+        new FSDataOutputStream(new S3ABlockOutputStream(), null);
+    PositionOutputStream wrap = HadoopStreams.wrap(fsDataOutputStream);
+
+    // mock interrupt in S3ABlockOutputStream#putObject
+    Thread.currentThread().interrupt();
+
+    Assertions.assertThrowsExactly(IOException.class, wrap::close);
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java:40]: the codebase typically uses `assertThatThrownBy(...).isInstanceOf(...)`

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 5 above)
Comment (nastra) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:201]: > Personally I am slightly favoring changing `closed` after the stream is actually closed. I checked the existing Iceberg code on handling close. I saw two styles: (1) setting `closed` before the action (2) just set it after the action without finally. It is not be necessary to set it In error/failure case, because close didn't complete successfully.

yes that was my observation as well when looking through the codebase, meaning we can probably have 
```
public void close() throws IOException {
    stream.close();
    this.closed = true;
    if (interrupted && ...) {
        throw IOException(..);
    }
}
```
without needed the try-finally block

Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:201]: ok, removed the finally block.

File: core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java (hunk 7 above)
Comment (abmo-x) [reply core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java:28]: Done

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java (hunk 8 above)
Comment (abmo-x) [reply core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:25]: we cannot as we need the package to be hadoop for fully qualified name check

File: core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+
+  @Test
+  void closeShouldThrowIOExceptionOnInterrupted() throws IOException {
+
+    FSDataOutputStream fsDataOutputStream =
+        new FSDataOutputStream(new S3ABlockOutputStream(), null);
+    PositionOutputStream wrap = HadoopStreams.wrap(fsDataOutputStream);
+
+    // mock interrupt in S3ABlockOutputStream#putObject
+    Thread.currentThread().interrupt();
```
[the remark this answers is not in the document]
Comment (abmo-x) [reply core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java:38]: It does check the scenario, if I remove the fix this test fails. This works as the interrupt is set in the same thread in https://github.com/apache/hadoop/blob/0f51d2a4ec17bad754beb17048409811a151be53/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java#L635 as well

File: core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java (hunk 9 above)
Comment (abmo-x) [reply core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java:40]: Updated

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java (hunk 8 above)
Comment (stevenzwu) [reply core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:25]: oh. I see.

File: core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (stevenzwu) [reply core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java]: I understood that test fails if fix is removed. but the scenario is not exactly the same, interrupt typically wasn't interrupted from the same thread. usually another thread is trying to interrupt a thread.

[the remark this answers is not in the document]
Comment (abmo-x) [reply core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java]: yes but do we have to mock another thread interrupting current thread here if we are able to set the interrupt and mimic the behavior. 

I can start another thread in the test [S3ABlockOutputStream.java]'s close method and then interrupt it to set the interrupted flag but I feel that is not needed but nice to have as eventually all this will do is do what line #38 here is doing

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+
+  @Override
+  public void write(int b) throws IOException {
+    throw new IOException("mocked clas, do not use");
```
Comment (nastra) [inline core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:29]:
```suggestion
    throw new IOException("mocked class, do not use");
```

File: core/src/test/java/org/apache/iceberg/hadoop/TestHadoopStreams.java [hunk 12]
```diff
@@ -0,0 +1,44 @@
...
+import org.apache.hadoop.fs.FSDataOutputStream;
+import org.apache.hadoop.fs.s3a.S3ABlockOutputStream;
+import org.apache.iceberg.io.PositionOutputStream;
+import org.assertj.core.api.Assertions;
+import org.junit.jupiter.api.Test;
+
+class TestHadoopStreams {
+
+  @Test
+  void closeShouldThrowIOExceptionOnInterrupted() throws IOException {
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/hadoop/TestHadoopStreams.java:31]:
```suggestion
  void closeShouldThrowIOExceptionWhenInterrupted() throws IOException {
```

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java [hunk 13]
```diff
@@ -187,6 +187,16 @@ public void flush() throws IOException {
...
       this.closed = true;
+      // {@link org.apache.hadoop.fs.s3a.S3ABlockOutputStream#close()} calls {@link
+      // org.apache.hadoop.fs.s3a.S3ABlockOutputStream#putObject()}
+      // which doesn't throw an exception when interrupted.
+      // Need to check the interrupted flag to detect failed object upload
+      // and propagate the error up.
+      if (Thread.interrupted()
+          && "org.apache.hadoop.fs.s3a.S3ABlockOutputStream"
+              .equals(stream.getWrappedStream().getClass().getName())) {
+        throw new IOException("Failed to close stream as object failed to upload.");
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:198]: is the error msg accurate? technically the stream was closed (L118) but we just failed to upload the object. So maybe this should be updated to `Failed to upload object after stream was closed` or to `S3ABlockOutputStream failed to upload object after stream was closed`?

**Review by nastra — COMMENTED** [review]
overall LGTM, but I think the error msg could be improved

File: core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java (hunk 13 above)
Comment (abmo-x) [reply core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java:198]: latter sounds better, updated to that. Thanks!

**Review by nastra — APPROVED** [review]

File: core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (stevenzwu) [reply core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java]: I would prefer that we change the test to interrupt the close from another thread. the close can sleep/block for 10 mins. interrupt should cancel the the close action and the assertion is that close takes less than 10 mins

[the remark this answers is not in the document]
Comment (abmo-x) [reply core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java]: done

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java [hunk 14]
```diff
@@ -0,0 +1,67 @@
...
+  @Override
+  public void write(int b) throws IOException {
+    throw new IOException("mocked class, do not use");
+  }
+
+  @Override
+  public void close() throws IOException {
+    try {
+      mockUploadOnClose =
+          mockCloseService.submit(
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:46]: wondering if we need to sleep in a separate thread. just sleep directly?

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java [hunk 15]
```diff
@@ -0,0 +1,67 @@
...
+              () -> {
+                try {
+                  Thread.sleep(30 * 1000);
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:49]: nit: can we increase it the sleep timeout to 2 mins. CI machines tend to be very overloaded. wondering if 30s may give higher false alarm.

File: core/src/test/java/org/apache/iceberg/hadoop/TestHadoopStreams.java [hunk 16]
```diff
@@ -0,0 +1,60 @@
...
+              s3ABlockOutputStream.interruptClose();
+            });
+
+    Assertions.assertThatThrownBy(wrap::close)
+        .isInstanceOf(IOException.class)
+        .hasMessage("S3ABlockOutputStream failed to upload object after stream was closed");
+
+    long endTime = System.currentTimeMillis();
+    long closeDuration = endTime - startTime;
+    Assert.assertTrue(closeDuration < 30 * 1000 && closeDuration > 1000);
```
Comment (stevenzwu) [inline core/src/test/java/org/apache/iceberg/hadoop/TestHadoopStreams.java:58]: I know I suggested this earlier. seems like the error msg check might be enough to verify the interrupt behavior. I am ok to remove the time check, which might cause flakiness.

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java (hunk 14 above)
Comment (abmo-x) [reply core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:46]: we need separate thread as we cannot call interrupt before close it called.

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java (hunk 15 above)
Comment (abmo-x) [reply core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:49]: this is sleep after the test starts, I don't think CI machine will affect this after test starts running as CI machine will not affect this sleep. I think 30 seconds is enough here

File: core/src/test/java/org/apache/iceberg/hadoop/TestHadoopStreams.java (hunk 16 above)
Comment (abmo-x) [reply core/src/test/java/org/apache/iceberg/hadoop/TestHadoopStreams.java:58]: ok, removed

File: core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java (hunk 15 above)
Comment (nastra) [reply core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:49]: I would suggest to look at https://github.com/awaitility/awaitility/wiki/Usage in order to avoid adding sleeps to  tests and achieve what we want without sleeps and without adding potential flakiness to tests

Comment (abmo-x) [reply core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java:49]: removed assert for duration. 

Looked into awaitlity, I don't think we need it here as awaitility provides utils to make test wait for results and assert with a timeout. We are not doing that here anymore.

**Review by stevenzwu — APPROVED** [review]
