### PR TITLE
ICEBERG-13343: fix race condition in JdbcCatalog

### LINKED ISSUE #13343: Creating 2 or more Iceberg Kafka Sink Connectors using slow JDBC catalog causes a startup failure on first run.
### Apache Iceberg version

1.9.0

### Query engine

Kafka Connect

### Please describe the bug 🐞

If Kafka Connect is started with 2 or more Iceberg sink connectors that are using JDBC catalog and the JDBC is slow the some of the connectors will throw:

```
org.apache.iceberg.jdbc.UncheckedSQLException: Cannot initialize JDBC catalog
	at org.apache.iceberg.jdbc.JdbcCatalog.initializeCatalogTables(JdbcCatalog.java:206)
	at org.apache.iceberg.jdbc.JdbcCatalog.initialize(JdbcCatalog.java:147)
	at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:277)
	at org.apache.iceberg.CatalogUtil.buildIcebergCatalog(CatalogUtil.java:331)
	at org.apache.iceberg.connect.CatalogUtils.loadCatalog(CatalogUtils.java:44)
	at org.apache.iceberg.connect.IcebergSinkTask.start(IcebergSinkTask.java:48)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
	at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
  Detail: Key (typname, typnamespace)=(iceberg_tables, 2200) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180)
		at org.apache.iceberg.jdbc.JdbcCatalog.lambda$initializeCatalogTables$0(JdbcCatalog.java:178)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:72)
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:65)
	at org.apache.iceberg.jdbc.JdbcCatalog.initializeCatalogTables(JdbcCatalog.java:162)
	... 15 more
```

This is caused because the `JdbcCatalog` checks to see if the table exists and if not creates it.  However this leaves a window where a race condition can arise when another thread creates the table before the create is called.  

This only occurs the first time the connector is started as the error is that the table exists and the table existence check will detect that case.  

I have a test and fix for this bug and will submit same.

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by Claudenw**
Fix for ICEBERG-13343

Closes #13343

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java [hunk 1]
```diff
@@ -123,7 +123,7 @@ enum SchemaVersion {
           + JdbcTableOperations.METADATA_LOCATION_PROP
           + " = ?";
   static final String V0_CREATE_CATALOG_SQL =
-      "CREATE TABLE "
+      "CREATE TABLE IF NOT EXISTS "
```
Comment (jbonofre) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java]: Afair, it has been discussed while ago.

As this syntax is not supported by all SQL backends, we control that via `JdbcUtil.INIT_CATALOG_TABLES_PROPERTY`.

You can see the login in the `initializeCatalogTables()` method.

**Review by jbonofre — COMMENTED** [review]
Imho, this PR is not relevant related to previous discussions and logic used in the init method.

**Comment by Claudenw** [comment]
Based on @jbonofre comments I have reworked the code to not use "IF NOT EXISTS" and instead to check if the table was created after the creation fails.  This case will occur during the race condition.

Added Apache Derby as a test DB as SqlLite does not handle multiple connections well.

Refactored some code to make it cleaner and easier to read.

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java [hunk 2]
```diff
@@ -149,4 +190,1015 @@ public synchronized void testConcurrentConnections() throws InterruptedException
...
+      List<Future<JdbcCatalog>> futures = Lists.newArrayList();
+      for (int i = 0; i < parallelism; i++) {
+        futures.add(executorService.submit(makeCatalog));
+      }
+      for (Future<JdbcCatalog> future : futures) {
+        future.get();
+      }
+    } finally {
+      DriverManager.deregisterDriver(slowDriver);
+    }
```
Comment (kevinjqliu) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java:231]: nit: add a catalog operation here to verify that both catalog clients are initialized and ready

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java [hunk 3]
```diff
@@ -149,4 +190,1015 @@ public synchronized void testConcurrentConnections() throws InterruptedException
...
+    // number of threads and requests to attempt.
+    int parallelism = 2;
+    // verifies that multiple calls to initialize with slow responses will not fail.
+    Map<String, String> properties = Maps.newHashMap();
+
+    properties.put(CatalogProperties.WAREHOUSE_LOCATION, tableDir.getAbsolutePath());
+    String testingDB = "jdbc:slow:derby:memory:testDb;create=true";
+    new org.apache.derby.jdbc.EmbeddedDriver();
+    properties.put(CatalogProperties.URI, testingDB);
+    SlowDriver slowDriver = new SlowDriver(testingDB);
```
Comment (kevinjqliu) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java:206]: Curious if we can test this without `SlowDriver`.

Can we simulate the same behavior by raising the parallelism? 
For example, `testConcurrentConnections` uses 7 threads

**Review by kevinjqliu — COMMENTED** [review]
Thanks for adding this change to address the race condition during JDBC catalog initialization.


I think JB made a good point in the [other thread](https://github.com/apache/iceberg/issues/13343#issuecomment-2985448183),
```
We are suppose to create table at JDBC Catalog init, before the sink is "running".
```
This is a good workaround, and this PR eliminates the need for it.

I added a few nit comments. Please take a look

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java [hunk 4]
```diff
@@ -149,4 +190,1015 @@ public synchronized void testConcurrentConnections() throws InterruptedException
     assertThat(executorService.awaitTermination(3, TimeUnit.MINUTES)).as("Timeout").isTrue();
     assertThat(Iterables.size(icebergTable.snapshots())).isEqualTo(7);
   }
+
+  @Test
+  public synchronized void testInitializeWithSlowConcurrentConnections()
```
Comment (Fokko) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java:195]: Appreciate the tests here 👍

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java (hunk 1 above)
Comment (Fokko) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java]: It might also fail because of permissions. It can be that a user has read privileges, but does not have create table privileges.

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 5]
```diff
@@ -156,48 +157,62 @@ public void initialize(String name, Map<String, String> properties) {
...
+          if (tableExists.test(tableName)) {
+            return true;
+          }
+
+          LOG.debug("Creating table {} {}", tableName, reason);
+          try {
+            conn.prepareStatement(sqlCommand).execute();
+            return true;
+          } catch (SQLException e) {
+            // see if table was created by another thread.
```
Comment (Fokko) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java]:
```suggestion
            // see if table was created by another thread or process.
```

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java (hunk 3 above)
Comment (Claudenw) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java:206]: You can try but then the pass/fail of the test is dependent upon the system on which it runs.  I feel that if you want to test a condition where a thread gets paused between two steps, make it pause.

I would be willing to make the entire wrapper classes a library so that here it would simply be creating an instance and overriding the two methods.

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java (hunk 2 above)
Comment (Claudenw) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java:231]: I am not sure what you are asking for here.  the future executes creates and initializes the JdbcCatalog which does not return from initialize until the initialization is complete.  So the `future.get` at line 227 ensures that the creation and initialization has completed for both.

I don't see a Catalog method to call to verify that it is valid/working.  Do you have a suggestion?

Comment (kevinjqliu) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java:231]: So the test here is testing that the `JdbcCatalog` be can initialize with multiple concurrent connections. 

My ask is to add a catalog operation (i.e. listNamespaces) on L232, after testing the initialization logic, to test that the catalog is indeed initialized correctly

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java (hunk 3 above)
Comment (kevinjqliu) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java:206]: make sense, ty

**Review by kevinjqliu — APPROVED** [review]
LGTM!

**Comment by Claudenw** [comment]
@jbonofre @Fokko @bryanck 
Do we have consensus here or are there specific changes that some reviewers would like to see?

**Review by jbonofre — APPROVED** [review]

**Comment by Claudenw** [comment]
I do not have authority to merge as I do not have write access.

**Comment by jbonofre** [comment]
Lgtm
I would just have split in 2 PRs:
One to show the issue (using derby) one to fix 

But only for me

**Review by jbonofre — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @Claudenw for fixing this 🙌 and thanks @jbonofre and @kevinjqliu for the review 🚀
