### PR TITLE
Hive: Use base table metadata to create HiveLock

### LINKED ISSUE #10006: HiveLock is chosen according to new table metadata
### Apache Iceberg version

main (development)

### Query engine

None

### Please describe the bug 🐞

When `HiveTableOperations` commits, which kind of `HiveLock` to use is decided using the new table metadata: https://github.com/apache/iceberg/blob/main/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L180

Suppose a table was initially created with lock enabled. At some time, we decide to disable the lock by running an ALTER TABLE to change the property. I wonder if this ALTER TABLE can cause problem with other concurrent writes, because they will use different lock mechanism.

### PR DESCRIPTION
**Pull request by lirui-apache**
Use base (instead of new) table metadata to create the lock object, so that concurrent commits use the same lock mechanism.

Fixes #10006

### CODE REVIEW

**Comment by pvary** [comment]
@lirui-apache: please add a new test too, to make sure that this behavior does not change in the future.
Thx, Peter

**Comment by lirui-apache** [comment]
@pvary I added a new test to verify changing lock mechanism should use the current lock type rather than the new one.

File: hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java [hunk 1]
```diff
@@ -64,7 +66,7 @@ public void testSuppressUnlockExceptions() {
 
     AtomicReference<HiveLock> lockRef = new AtomicReference<>();
 
-    when(spyOps.lockObject(metadataV1))
+    when(spyOps.lockObject(any()))
```
Comment (pvary) [inline hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java:69]: Why `any`? Why not `metadataV2`?

File: hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java [hunk 2]
```diff
@@ -273,11 +275,11 @@ public void testThriftExceptionConcurrentCommit() throws TException, Interrupted
     AtomicReference<HiveLock> lock = new AtomicReference<>();
     doAnswer(
             l -> {
-              lock.set(ops.lockObject(metadataV1));
+              lock.set(ops.lockObject(l.getArgument(0)));
               return lock.get();
             })
         .when(spyOps)
-        .lockObject(metadataV1);
+        .lockObject(any());
```
Comment (pvary) [inline hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java:282]: Why `any`? Why not `metadataV2`?

File: hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java [hunk 3]
```diff
@@ -397,6 +399,36 @@ public void testLockExceptionUnknownSuccessCommit() throws TException, Interrupt
...
+
+    AtomicReference<HiveLock> lockRef = new AtomicReference<>();
+    HiveTableOperations spyOps = spy(ops);
+    doAnswer(
+            i -> {
+              lockRef.set(ops.lockObject(i.getArgument(0)));
+              return lockRef.get();
+            })
+        .when(spyOps)
+        .lockObject(any());
```
Comment (pvary) [inline hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java:417]: Can we avoid `any` if possible?

Comment (lirui-apache) [reply hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java:417]: Yeah, but would you mind elaborate why `any` is bad? The stub here is meant to capture the lock returned by `lockObject`. I don't understand why we care about the argument.

Comment (pvary) [reply hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java:417]: If we check the argument, then we also check, that our assumptions about the tests are correct. I recently faced an issue when an unrelated change made the test irrelevant (the methods called with different parameter values), but the tests were green, because `any` were used to match the arguments

Comment (lirui-apache) [reply hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java]: Thanks for explaining. PR updated accordingly.

**Review by pvary — APPROVED** [review]
Thanks for the fix.
Let's give some time to @RussellSpitzer and/or @szehon-ho to chime in, if they want before merging

**Review by szehon-ho — APPROVED** [review]

**Comment by pvary** [comment]
Merged to main. 
Thanks @lirui-apache for the PR and @szehon-ho for the review!

**Comment by lirui-apache** [comment]
Thanks @pvary @szehon-ho for reviewing and merging!
