### PR TITLE
Core: Don't reset snapshotLog in `TableMetadata.removeRef` method

### LINKED ISSUE #11777: REST catalog doesn't return old history if we execute `CREATE OR REPLACE TABLE` statement
### Apache Iceberg version

1.7.1 (latest release)

### Query engine

Trino

### Please describe the bug 🐞

https://github.com/trinodb/trino/pull/24312 is trying to use `org.apache.iceberg.MetadataTableUtils#createMetadataTableInstance` method for history metadata table. Only REST catalog doesn't return the past history if we execute `CREATE OR REPLACE TABLE` statement. 

```sql
trino:tpch> TABLE "region$history";
          made_current_at           |     snapshot_id     | parent_id | is_current_ancestor
------------------------------------+---------------------+-----------+---------------------
 2024-12-13 16:26:02.387 Asia/Tokyo | 4753270524621689028 |      NULL | true
(1 row)

trino:tpch> CREATE OR REPLACE TABLE region AS SELECT * FROM orders;
CREATE TABLE: 15000 rows

trino:tpch> TABLE "region$history";
          made_current_at           |     snapshot_id     | parent_id | is_current_ancestor
------------------------------------+---------------------+-----------+---------------------
 2024-12-13 16:27:51.756 Asia/Tokyo | 7793069171159305791 |      NULL | true
(1 row)

trino:tpch> SHOW CREATE TABLE region;
                                                                          Create Table
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE TABLE iceberg.tpch.region (
    orderkey bigint,
    custkey bigint,
    orderstatus varchar,
    totalprice double,
    orderdate date,
    orderpriority varchar,
    clerk varchar,
    shippriority integer,
    comment varchar
 )
 WITH (
    format = 'PARQUET',
    format_version = 2,
    location = '/var/folders/9s/_zwn4r_n2_9bp0krllp1pl3c0000gp/T/a6a26fac-b6be-4c9c-b05b-cbe7ec894b2f/iceberg_data/tpch/region-4f41a42ee7f84d3093d85649bc557e46'
 )
(1 row)
```

[region-4f41a42ee7f84d3093d85649bc557e46.zip](https://github.com/user-attachments/files/18122848/region-4f41a42ee7f84d3093d85649bc557e46.zip)

The following request contains `RemoveSnapshotRef` that clears existing snapshot logs.  
https://github.com/apache/iceberg/blob/540d6a6251e31b232fe6ed2413680621454d107a/core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java#L434-L437

https://apache-iceberg.slack.com/archives/C03LG1D563F/p1733195549342209

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [X] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #11777

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java [hunk 1]
```diff
@@ -548,7 +552,8 @@ private static MetadataUpdate readSetSnapshotRef(JsonNode node) {
 
   private static MetadataUpdate readRemoveSnapshotRef(JsonNode node) {
     String refName = JsonUtil.getString(REF_NAME, node);
-    return new MetadataUpdate.RemoveSnapshotRef(refName);
+    boolean purge = JsonUtil.getBool(PURGE, node);
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java:555]: older clients won't send this flag, so we shouldn't be failing here

File: core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java [hunk 2]
```diff
@@ -417,6 +420,7 @@ private static void writeSetSnapshotRef(MetadataUpdate.SetSnapshotRef update, Js
   private static void writeRemoveSnapshotRef(
       MetadataUpdate.RemoveSnapshotRef update, JsonGenerator gen) throws IOException {
     gen.writeStringField(REF_NAME, update.name());
+    gen.writeBooleanField(PURGE, update.purge());
```
[the remark this answers is not in the document]
Comment (ebyhr) [reply core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java:423]: Thanks for your suggestion. Posted https://lists.apache.org/thread/7q4rplst9tf9fpm7b9cco82j5n9q1hl7

File: core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java (hunk 1 above)
Comment (ebyhr) [reply core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java]: Updated. The new logic sets `true` by default for backward compatibility.

**Review by amogh-jahagirdar — COMMENTED** [review]
@ebyhr I think we may want to take a different approach. 

Currently, we clear the snapshot log when TableMetadata#removeRef is called [here](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/TableMetadata.java#L1289) . If you see, the non-REST case goes through `resetMain` which won't clear the snapshot log but for the REST changes that are produced, we produce a RemoveSnapshotRef update type which when applied server side clears the log. 

Quite simply, I think we probably just want to remove the `snapshotLog.clear()` call in the removeRef API. In the past, I think there was concern that a user using that API may somehow rely on that behavior but really the only action on an Iceberg table that should remove history is snapshot expiration. `removeRef(MAIN)` should not really change history in anyway, this was probably just an oversight in the implementation done a long time ago. 

I also discussed this issue with a few others @Fokko @nastra @rdblue @danielcweeks and I think we're on the same page there. 

What are your thoughts? If you agree, would be happy to review the PR with the change to stop clearing the snapshot log, and some tests to verify that history is preserved during a REPLACE, and we can get a fix for this issue in!

**Comment by ebyhr** [comment]
@amogh-jahagirdar There is no reason to disagree from my perspective. I was simply trying to keep the existing behavior because I didn't know the historical reason. Reverted most changes and removed `snapshotLog.clear()` call with some tests.

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 3]
```diff
@@ -2418,6 +2421,34 @@ public void testPaginationForListTables(int numberOfItems) {
             eq(ListTablesResponse.class));
   }
 
+  @Test
+  public void testReplaceTableKeepsSnapshotLog() {
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java:2425]: Could we put this test in `CatalogTests`? That'll cover both REST + non-REST cases (TestRESTCatalog extends `CatalogTests`).

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 4]
```diff
@@ -2418,6 +2421,34 @@ public void testPaginationForListTables(int numberOfItems) {
...
+    assertThat(snapshotLogBeforeReplace).hasSize(1);
+
+    Transaction replaceTableTransaction = catalog.newReplaceTableTransaction(TABLE, SCHEMA, false);
+    replaceTableTransaction.newAppend().appendFile(FILE_A).commit();
+    replaceTableTransaction.commitTransaction();
+
+    table.refresh();
+    assertThat(((BaseTable) table).operations().current().snapshotLog())
+        .hasSize(2)
+        .containsAll(snapshotLogBeforeReplace);
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java:2449]: Could we assert the exact snapshot log contents instead of just doing a containsAll check? We should have both the log before the replace and the new snapshot produced as part of the replace.

**Comment by ebyhr** [comment]
@amogh-jahagirdar Thanks for your review. Addressed comments.

**Review by Fokko — APPROVED** [review]
Thanks for looking into this @ebyhr and @amogh-jahagirdar, I agree that this is the right approach.
