### PR TITLE
Core: Improve pagination logic to handle null pageToken

### LINKED ISSUE #13119: REST Catalog fixture is particular about query params
### Apache Iceberg version

1.9.0 (latest release)

### Query engine

None

### Please describe the bug 🐞

I was testing the Iceberg CLI built using https://github.com/apache/iceberg-go while working on the new release along with @kevinjqliu and we discovered an issue in the iceberg-rest-fixture. It turns out that if you set a `pageSize` then you *have* to also pass `pageToken` even for the initial request, otherwise you get an exception that it failed to parse an integer.

The exception stack looks like the following:

Image

With a bit of digging, the issue appears to be here: https://github.com/apache/iceberg/blob/apache-iceberg-1.9.0/core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java#L114

On that line, we do `INITIAL_PAGE_TOKEN.equals(pageToken)` where `INITIAL_PAGE_TOKEN` is an empty string. But if you don't pass a `pageToken` query parameter (which you wouldn't do on the first request, you'd only use it on subsequent requests) then the check fails because `pageToken` is `null`. Leading to `Integer.parseInt(pageToken)` throwing an exception because of the null string. The fix is likely just to add a null check there.

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by elphastori**
Allow listing tables, views and namespaces in rest catalog without `pageToken` query parameter when `pageSize` query parameter is included. Closes #13119

Examples:
- http://localhost:8181/v1/namespaces?pageSize=1
- http://localhost:8181/v1/namespaces/default/tables?pageSize=1
- http://localhost:8181/v1/namespaces/default/views?pageSize=1

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java [hunk 1]
```diff
@@ -111,7 +111,8 @@ public CommitFailedException wrapped() {
   }
 
   private static <T> Pair<List<T>, String> paginate(List<T> list, String pageToken, int pageSize) {
-    int pageStart = INITIAL_PAGE_TOKEN.equals(pageToken) ? 0 : Integer.parseInt(pageToken);
+    int pageStart =
+        pageToken == null || INITIAL_PAGE_TOKEN.equals(pageToken) ? 0 : Integer.parseInt(pageToken);
```
[the remark this answers is not in the document]
Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java]: It looks better, I'll take it!

File: core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java [hunk 2]
```diff
@@ -565,13 +568,16 @@ public List<Namespace> listNamespaces(SessionContext context, Namespace namespac
...
     if (pageSize != null) {
       queryParams.put("pageSize", String.valueOf(pageSize));
     }
 
     do {
-      queryParams.put("pageToken", pageToken);
+      if (pageToken != null) {
+        queryParams.put("pageToken", pageToken);
+      }
+
```
[the remark this answers is not in the document]
Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java:580]: It's a nice thought experiment, but if we remove the condition here, a null check will throw a NullPointerException while attempting to construct the HTTP request.

Instead of having the null check in the HTTP client, we could filter out keys with null values, but I prefer the null check.

Omitting the parameter altogether is currently the only way to relay that the value is exactly `null` to the server.

[the remark this answers is not in the document]
Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java:580]: `pageToken` needs to be set inside the loop because it must be updated with each request, unlike `pageSize`, which remains constant.

Here’s an example sequence of requests from the unit tests:
1. http://localhost:8181/v1/namespaces/default/tables?pageSize=10
2. http://localhost:8181/v1/namespaces/default/tables?pageSize=10&pageToken=10
3. http://localhost:8181/v1/namespaces/default/tables?pageSize=10&pageToken=20

[the remark this answers is not in the document]
Comment (kevinjqliu) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java:580]: oh good one, i missed the `queryParams`

[the remark this answers is not in the document]
Comment (kevinjqliu) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java:580]: once `pageToken` is almost `null` at the start, how about something like this? update the `queryParams` only when `pageToken` is updated. 

```
    String pageToken = null;
    if (pageSize != null) {
      queryParams.put("pageSize", String.valueOf(pageSize));
    }

    do {
      AuthSession contextualSession = authManager.contextualSession(context, catalogAuth);
      ListTablesResponse response =
          client
              .withAuthSession(contextualSession)
              .get(
                  paths.tables(ns),
                  queryParams,
                  ListTablesResponse.class,
                  Map.of(),
                  ErrorHandlers.namespaceErrorHandler());
      pageToken = response.nextPageToken();
      if (pageToken != null) {
        queryParams.put("pageToken", pageToken);
      }
      tables.addAll(response.identifiers());
    } while (pageToken != null);
```

File: core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java [hunk 3]
```diff
@@ -111,6 +111,10 @@ public CommitFailedException wrapped() {
   }
 
   private static <T> Pair<List<T>, String> paginate(List<T> list, String pageToken, int pageSize) {
+    if (pageToken == null) {
+      pageToken = INITIAL_PAGE_TOKEN;
```
Comment (kevinjqliu) [inline core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java:115]: Looks like java checkstyle doesn't like parameter reassignement,
```
> Task :iceberg-core:showDeprecationRulesOnRevApiFailure SKIPPED
Error: eckstyle] [ERROR] /home/runner/work/iceberg/iceberg/core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java:115:17: Assignment of parameter 'pageToken' is not allowed. [ParameterAssignment]
```

Let's go back to the previous implementation 
```
int start = (pageToken == null || INITIAL_PAGE_TOKEN.equals(pageToken)) ? 0 : Integer.parseInt(pageToken);
```

File: core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (geruh) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java:580]: I'm fine with either approach here! I usually see where the request details are set after the first iteration but it is a header

[the remark this answers is not in the document]
Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java:580]: @kevinjqliu I agree, your suggestion seems to be the more natural use of a `do...while` loop.

At this point, we could even remove the null check because no further iteration will been run if pageToken is `null`.

Let me run some tests and push the change.

**Review by kevinjqliu — APPROVED** [review]
LGTM!

**Comment by kevinjqliu** [comment]
`apache/iceberg-rest-fixture` rebuilds automatically and should pick up the change on the next run

https://github.com/apache/iceberg/blob/a5a0b8af84362edd876ab88d377c6a608d634098/.github/workflows/publish-iceberg-rest-fixture-docker.yml#L27

**Comment by kevinjqliu** [comment]
tagging a few folks to take a look. Otherwise, I can merge this :)

File: core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java [hunk 4]
```diff
@@ -268,13 +268,12 @@ public List<TableIdentifier> listTables(SessionContext context, Namespace ns) {
     checkNamespaceIsValid(ns);
     Map<String, String> queryParams = Maps.newHashMap();
     ImmutableList.Builder<TableIdentifier> tables = ImmutableList.builder();
-    String pageToken = "";
+    String pageToken = null;
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java]: changing this here will break when the client talks to an older server that expects the `pageToken` to be an empty string on the first pagination attempt

File: core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java [hunk 5]
```diff
@@ -111,7 +111,8 @@ public CommitFailedException wrapped() {
   }
 
   private static <T> Pair<List<T>, String> paginate(List<T> list, String pageToken, int pageSize) {
-    int pageStart = INITIAL_PAGE_TOKEN.equals(pageToken) ? 0 : Integer.parseInt(pageToken);
+    int pageStart =
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java]: maybe update this to 
```
   private static <T> Pair<List<T>, String> paginate(List<T> list, String pageToken, int pageSize) {
-    int pageStart = INITIAL_PAGE_TOKEN.equals(pageToken) ? 0 : Integer.parseInt(pageToken);
+    String token = null == pageToken ? INITIAL_PAGE_TOKEN : pageToken;
+    int pageStart = INITIAL_PAGE_TOKEN.equals(token) ? 0 : Integer.parseInt(token);
```

to make it slightly more readable

File: core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java (hunk 4 above)
Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java]: This specific change is only cosmetic, whether we have an empty string or a null, the logic doesn't include the parameter on the first request.

File: core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java (hunk 5 above)
Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java]: Thanks! I definitely underestimated how hard that line was to read. Your suggestion was great, I’ve taken it a step further, and I think this version is even more readable now:

```
  private static <T> Pair<List<T>, String> paginate(List<T> list, String pageToken, int pageSize) {
    boolean isFirstPage = pageToken == null || pageToken.equals(INITIAL_PAGE_TOKEN);
    int pageStart = isFirstPage ? 0 : Integer.parseInt(pageToken);
    ...
```

File: core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java (hunk 4 above)
Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java]: The issue with older servers expecting an empty string for the initial `pageToken` still stands.

I'm thinking of reverting all my changes to `RESTSessionCatalog`, since I only modified it because it's used by the unit tests. That would mean reverting the related test changes as well.

I believe the change in `CatalogHandlers` is straightforward enough and well-covered by tests. What do you think?

Comment (nastra) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java]: > The issue with older servers expecting an empty string for the initial pageToken still stands.

I don't think this is true, because the `queryParams` have been moved further below and are not being sent anymore on the first request. An older server would be expecting `pageToken` and `pageSize` to be sent on the very first request

Comment (nastra) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java]: > I'm thinking of reverting all my changes to RESTSessionCatalog, since I only modified it because it's used by the unit tests. That would mean reverting the related test changes as well.

Yes it's best to revert those changes. We'll have to see whether there's an easy option on how to properly test this in a separate unit test (outside of `TestRESTCatalog` / `TestRESTViewCatalog`) if possible

Comment (elphastori) [reply core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java]: I've reverted the changes. I'll explore other ways to add a separate a unit test like you've suggested.

> > The issue with older servers expecting an empty string for the initial `pageToken` still stands.
>
> I don't think this is true, because the `queryParams` have been moved further below and are not being sent anymore on the first request. An older server would be expecting `pageToken` and `pageSize` to be sent on the very first request

This is no longer relevant after the revert, but just to clarify: the `queryParams` were still being sent on all requests, it was only the `pageToken` parameter that was excluded on the first request. That omission would indeed have broken compatibility with older servers expecting it

This was the example sequence of requests from the unit tests:

- http://localhost:8181/v1/namespaces/default/tables?pageSize=10
- http://localhost:8181/v1/namespaces/default/tables?pageSize=10&pageToken=10
- http://localhost:8181/v1/namespaces/default/tables?pageSize=10&pageToken=20

**Review by kevinjqliu — APPROVED** [review]
LGTM

In `RESTCatalogAdapter`, `pageToken` is set to `null` when its not found in the request parameters
https://github.com/apache/iceberg/blob/9fa50f3b82b321a98698c07977096d1638a9b185/core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java#L318

So `paginate` needs to support `null` value for `pageToken`

**Review by nastra — APPROVED** [review]

**Comment by kevinjqliu** [comment]
im going to manually triggering CI

**Comment by kevinjqliu** [comment]
Edited the title for clarity. 

Thanks @elphastori for the fix and @nastra for the review!

**Comment by elphastori** [comment]
Thank you for all the help 🙌
