### PR TITLE
Core: do not cleanup 503s for CREATE transaction

### LINKED ISSUE #15050: REST Catalog 503 errors should not be cleanable failures
### Apache Iceberg version

1.10.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Currently, HTTP 503 responses are not retried, yet they are still classified as cleanable failures for CreateTable transactions (stage create + updateTable request). This can lead to table corruption in scenarios where the commit is successfully persisted by the catalog, but an intermediate component returns a 503 to the client.

https://github.com/apache/iceberg/blob/7bac8650f65279c470d7d2c005c40a858933134a/core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java#L172

In our setup, Spark communicates with the catalog through Envoy (acting as a reverse proxy). When Envoy returns a 503 due to a transient downstream issue, the client assumes the commit failed and proceeds with cleanup. However, the catalog may have already committed the transaction successfully. As a result, valid manifest files can be incorrectly cleaned up, leaving the table in an corrupted state.

This behavior makes 503 responses unsafe to treat as cleanable failures, especially in deployments with proxies between the client and the catalog.

Should we use a `tableCommitErrorHandler` instead of a `tableErrorHandler` also in case of CREATE updateType and not only for REPLACE and SIMPLE?

Previous related work:
https://github.com/apache/iceberg/pull/13619 and [thread](https://lists.apache.org/thread/oqonscy1b4qlmovnjtbcohz38kgprgmq)

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by alessandro-nori**
Fixes #15050

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java [hunk 1]
```diff
@@ -169,7 +169,7 @@ public void commit(TableMetadata base, TableMetadata metadata) {
                 .addAll(metadata.changes())
                 .build();
         requirements = UpdateRequirements.forCreateTable(updates);
-        errorHandler = ErrorHandlers.tableErrorHandler(); // throws NoSuchTableException
+        errorHandler = ErrorHandlers.tableCommitHandler(); // throws NoSuchTableException
```
Comment (singhpk234) [inline core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java]: can you please add some tests?

Comment (nastra) [reply core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java]: on a first glance this seems correct to me but you'll most likely also need to update
```
diff --git a/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java b/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
index c2fd24856f..057a889bec 100644
--- a/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
+++ b/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
@@ -2182,8 +2182,10 @@ public abstract class CatalogTests<C extends Catalog & SupportsNamespaces> {
         supportsServerSideRetry()
             ? "Requirement failed: table already exists"
             : "Table already exists";
+    Class<? extends RuntimeException> expectedException =
+        supportsServerSideRetry() ? AlreadyExistsException.class : CommitFailedException.class;
     assertThatThrownBy(create::commitTransaction)
-        .isInstanceOf(AlreadyExistsException.class)
+        .isInstanceOf(expectedException)
         .hasMessageStartingWith(expectedMessage);

     // validate the concurrently created table is unmodified
@@ -2434,8 +2436,10 @@ public abstract class CatalogTests<C extends Catalog & SupportsNamespaces> {
         supportsServerSideRetry()
             ? "Requirement failed: table already exists"
             : "Table already exists";
+    Class<? extends RuntimeException> expectedException =
+        supportsServerSideRetry() ? AlreadyExistsException.class : CommitFailedException.class;
     assertThatThrownBy(createOrReplace::commitTransaction)
-        .isInstanceOf(AlreadyExistsException.class)
+        .isInstanceOf(expectedException)
         .hasMessageStartingWith(expectedMessage);
```

Comment (alessandro-nori) [reply core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java]: what do you think about 409?
I was not sure if in this case it was ok to return a CommitFailedException instead of a TableAlreadyExists exception

Comment (amogh-jahagirdar) [reply core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java]: Yeah I think we may just want to add a createTableErrorHandler() which extends the commit error handler, but we override the 409 behavior to be a TableAlreadyExists exception, and then in any other case fallback to super.accept(error).

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 2]
```diff
@@ -2543,6 +2543,74 @@ public void testNoCleanupForNonCleanableCreateTransaction() {
...
+                  ErrorResponse error =
+                      ErrorResponse.builder()
+                          .responseCode(503)
+                          .withMessage("Service unavailable")
+                          .build();
+
+                  errorHandler.accept(error);
+                  throw new IllegalStateException("Error handler should have thrown");
+                }
+                return super.execute(request, responseType, errorHandler, responseHeaders);
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java]: I feel like we should be able to slim this setup down a bit by just doing something like:

```
    RESTCatalogAdapter adapter = Mockito.spy(new RESTCatalogAdapter(backendCatalog));
    Mockito.doThrow(new ServiceFailureException("some service failure"))
        .when(adapter)
        .execute(reqMatcher(HTTPMethod.POST), any(), any(), any());

```

Think it's OK to mock the commit state unknown here, since all we're trying to test is the client's reaction to it on create? I see the other tests in this class do that as well.

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 3]
```diff
@@ -2543,6 +2543,74 @@ public void testNoCleanupForNonCleanableCreateTransaction() {
...
+                      .filter(update -> update instanceof MetadataUpdate.AddSnapshot)
+                      .findFirst();
+              assertThat(appendSnapshot).isPresent();
+
+              MetadataUpdate.AddSnapshot addSnapshot =
+                  (MetadataUpdate.AddSnapshot) appendSnapshot.get();
+              String manifestListLocation = addSnapshot.snapshot().manifestListLocation();
+              // Files should still exist because we don't know if commit succeeded
+              assertThat(catalog.loadTable(TABLE).io().newInputFile(manifestListLocation).exists())
+                  .isTrue();
```
Comment (amogh-jahagirdar) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java]: Maybe a more assertJ "fluent" way:

```
assertThat(body.updates().stream()
        .filter(MetadataUpdate.AddSnapshot.class::isInstance)
        .map(MetadataUpdate.AddSnapshot.class::cast)
        .findFirst())
    .hasValueSatisfying(addSnapshot -> {
      String manifestListLocation = addSnapshot.snapshot().manifestListLocation();
      assertThat(catalog.loadTable(TABLE).io().newInputFile(manifestListLocation).exists())
          .isTrue();
    });

```

File: core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java [hunk 4]
```diff
@@ -138,6 +142,26 @@ public void accept(ErrorResponse error) {
     }
   }
 
+  /** Table create error handler */
+  private static class CreateTableErrorHandler extends TableErrorHandler {
```
Comment (amogh-jahagirdar) [inline core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java]: This is also fine, just wondering it may be a smaller diff if we just extended CommitErrorHandler, and overrode the 409 case? Unless I'm missing a case in handling.

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java (hunk 2 above)
Comment (alessandro-nori) [reply core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java]: Thank you very much for your review.

My goal was to test that the new ErrorHandler is correctly mapping `503` errors to `CommitStateUnknownException`.

I tried debugging what you suggested but the ErrorHandler code is not called in that case. There is already a test to check that **not** `CleanableFailure`s like `ServiceFailureException` do not delete files https://github.com/apache/iceberg/blob/0b83a6359d6af1bf7fbacb62ec819c5c47dee404/core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java#L2505-L2544

My new test instead fails without the new error handler.

I don't have enough expertise in Java so it's very possible I'm doing something wrong.

File: core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java (hunk 4 above)
Comment (alessandro-nori) [reply core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java]: we also need to override 404 because it should be `NoSuchNamespaceException` for create-table instead of `NoSuchTableException`.

I like your approach better because CreateTableErrorHandler should be used in case of a _commit_.
I'm also fine with reverting https://github.com/apache/iceberg/pull/15051/commits/26d4dda5f44b3910c42e53d3af2375a3fc8d37ad in case we change our mind

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java (hunk 2 above)
Comment (amogh-jahagirdar) [reply core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java]: Ah this is my bad, I had to look at the code further. You're right, given how the http client is invoked, to trigger a failure and go through the error handler, we can't just mock execute. The error handler invocation is handled below the execution API. I think this is fine, maybe we want a separate helper method for better simulation of errors that go through the error handlers.

On a separate note, I'm starting to think a bit more about how we look at CleanableFailure. The original intent of the CleanableFailure marker interface was to prevent issues in case arbitrary exceptions happened to be thrown on the commit path. We generally expect Error handlers to map to the commit state unknown, and any other exception we fail to handle goes through as a runtime exception, which we validate is cleanable or not. Anyways this is separate.

Minor point, I'd just shorten the test name a bit: `testNoCleanupOnCreate503` or something. The commit state unknown is more of an internal handling detail for this case.

File: core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java [hunk 5]
```diff
@@ -169,7 +169,7 @@ public void commit(TableMetadata base, TableMetadata metadata) {
                 .addAll(metadata.changes())
                 .build();
         requirements = UpdateRequirements.forCreateTable(updates);
-        errorHandler = ErrorHandlers.tableErrorHandler(); // throws NoSuchTableException
+        errorHandler = ErrorHandlers.createTableErrorHandler(); // throws NoSuchTableException
```
Comment (nastra) [inline core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java]: I don't think the comment is accurate anymore, since the error handler doesn't throw that exception

File: core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java [hunk 6]
```diff
@@ -2543,6 +2543,79 @@ public void testNoCleanupForNonCleanableCreateTransaction() {
...
+              }
+            });
+
+    RESTCatalog catalog = catalog(adapter);
+
+    if (requiresNamespaceCreate()) {
+      catalog.createNamespace(TABLE.namespace());
+    }
+
+    catalog.createTable(TABLE, SCHEMA);
```
Comment (nastra) [inline core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java]: this doesn't seem to be required

Comment (alessandro-nori) [reply core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java]: Thanks! There was a bug in the unit test.

**Comment by amogh-jahagirdar** [comment]
I'm going to go ahead and merge. Thank you @alessandro-nori for the fix, thank you @singhpk234 @nastra for reviewing
