### PR TITLE
Core: Exclude unexpected namespaces JdbcCatalog.listNamespaces

### LINKED ISSUE #10213: Iceberg rest catalog with postgres - List namespaces with parent returns wrong children namespaces
### Apache Iceberg version

1.4.2

### Query engine

None

### Please describe the bug 🐞

We are using version 1.4.2 but we are planning to upgrade to 1.5.0 and I confirmed that the problem is still there.

Problem: When you have 2 namespaces with similar names
E.g.: 
namespaces:
- test.auto_rag
- test_auto_rag

API CALL: http://<iceberg-rest-catalog>/v1/namespaces?parent=test_auto_rag

Response:
```
{
    "namespaces": [
        [
            "test",
            "auto_rag"
        ]
    ]
}
```
That is incorrect. `test_auto_rag` namespace doesn't have children namespaces.

In a quick look the issue seems to be with the behavior of this query with postgres:
- https://github.com/apache/iceberg/blob/866021d7d34f274349ce7de1f29d113395e7f28c/core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java#L428
- https://github.com/apache/iceberg/blob/866021d7d34f274349ce7de1f29d113395e7f28c/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java#L340

image

Notice:
In case is useful, this is the version we are using:  `PostgreSQL 14.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), 64-bit`

### PR DESCRIPTION
**Pull request by ebyhr**
JdbcCatalog.listNamespaces returned unexpected namespaces because of `LIKE` with `%`. 

The updated `testListNamespace` test fails without this change:
```java
    List<Namespace> nsp1 = catalog.listNamespaces(Namespace.of("db"));
    assertThat(nsp1).hasSize(3);

Expected size: 3 but was: 4 in:
[db.ns1, db.ns2, db.ns3, db2.ns4]
java.lang.AssertionError: 
Expected size: 3 but was: 4 in:
[db.ns1, db.ns2, db.ns3, db2.ns4]
```

Fixes #10213

### CODE REVIEW

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 1]
```diff
@@ -466,6 +466,16 @@ public List<Namespace> listNamespaces(Namespace namespace) throws NoSuchNamespac
                         Arrays.stream(n.levels())
                             .limit(subNamespaceLevelLength)
                             .toArray(String[]::new)))
+            // exclude fuzzy matches
```
Comment (findepi) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:469]:
```suggestion
            // exclude fuzzy matches when `namespace` contains `%` or `_`
```

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 2]
```diff
@@ -466,6 +466,16 @@ public List<Namespace> listNamespaces(Namespace namespace) throws NoSuchNamespac
...
+            .filter(
+                n -> {
+                  for (int i = 0; i < namespace.levels().length; i++) {
+                    if (!n.levels()[i].equals(namespace.levels()[i])) {
```
Comment (findepi) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:473]: this may be more expensive that deduplication, so let's put this filter after the distinct.

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java [hunk 3]
```diff
@@ -753,8 +753,9 @@ public void testListNamespace() {
     TableIdentifier tbl4 = TableIdentifier.of("db", "metadata");
     TableIdentifier tbl5 = TableIdentifier.of("db2", "metadata");
     TableIdentifier tbl6 = TableIdentifier.of("tbl6");
+    TableIdentifier tbl7 = TableIdentifier.of("db2", "ns4", "tbl5");
```
Comment (findepi) [inline core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:756]: How does this test change exercise the problem?
this new additional doesn't include `_` nor `%`

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 2 above)
Comment (jbonofre) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:473]: I would put after `distinct()`. Your PR is a good point.

**Review by jbonofre — CHANGES_REQUESTED** [review]

**Comment by nastra** [comment]
@ebyhr thanks for working on this and it would be great to get this into 1.6.0.

File: core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java (hunk 3 above)
Comment (ebyhr) [reply core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java:756]: This namespace was returned for `listNamespaces(Namespace.of("db"))` because of the following condition:
https://github.com/apache/iceberg/blob/24d26b6a35a1287531e72357691d9dbd3d7f79bd/core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java#L447

Anyway, I added two namespaces having `_` or `%`.

**Comment by ebyhr** [comment]
Addressed comments. Sorry for my late response. Iceberg IntelliJ project somehow broke after sending this PR.

**Review by jbonofre — APPROVED** [review]

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 4]
```diff
@@ -468,6 +468,16 @@ public List<Namespace> listNamespaces(Namespace namespace) throws NoSuchNamespac
...
+            // exclude fuzzy matches when `namespace` contains `%` or `_`
+            .filter(
+                n -> {
+                  for (int i = 0; i < namespace.levels().length; i++) {
+                    if (!n.levels()[i].equals(namespace.levels()[i])) {
+                      return false;
+                    }
+                  }
+                  return true;
+                })
```
Comment (Fokko) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:480]:
```suggestion
            // exclude fuzzy matches when `namespace` contains `%` or `_`
            .filter(
                n -> {
                  for (int i = 0; i < namespace.levels().length; i++) {
                    if (!n.levels()[i].equals(namespace.levels()[i])) {
                      return false;
                    }
                  }
                  return true;
                })
            // remove duplicates
            .distinct()
```

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java (hunk 2 above)
Comment (ebyhr) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:473]: @Fokko Why did you swap the order in a new commit?

Comment (Fokko) [reply core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:473]: This was still open, and I skimmed over it. From intuition, I assume that deduplicating is more expensive than filtering, so I pushed that down to get this in for 1.6.0. I'll revert the change and merge this. Sorry about this

File: core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java [hunk 5]
```diff
@@ -466,6 +466,16 @@ public List<Namespace> listNamespaces(Namespace namespace) throws NoSuchNamespac
...
             // remove duplicates
             .distinct()
```
Comment (Fokko) [inline core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java:480]: Swap it back:
```suggestion
            // remove duplicates
            .distinct()
            // exclude fuzzy matches when `namespace` contains `%` or `_`
            .filter(
                n -> {
                  for (int i = 0; i < namespace.levels().length; i++) {
                    if (!n.levels()[i].equals(namespace.levels()[i])) {
                      return false;
                    }
                  }
                  return true;
                })
```

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @ebyhr for working on this 👍
