### PR TITLE
Core: Fix child AuthSession inheriting parent's expiresAtMillis

### LINKED ISSUE #16002: Child AuthSession inherits parent's expiresAtMillis, causing incorrect token refresh scheduling
### Apache Iceberg version

1.10.1 (latest release)

### Query engine

Trino

### Please describe the bug 🐞

When creating a child AuthSession via fromTokenResponse() or fromAccessToken(), the AuthConfig builder uses .from(parent.config()) to inherit configuration. Immutables' from() copies all explicitly set values from the parent config — including expiresAtMillis. This overrides the @Value.Default on expiresAtMillis() that would otherwise recompute from the child's own JWT exp claim.

As a result, the child session's first token refresh is scheduled based on the parent's token expiry, not its own.

Impact
In token exchange flows where a catalog session holds a long-lived token (e.g., 1-hour IdP token) and the exchanged per-user token is short-lived (e.g., 5 minutes), the refresh is scheduled ~54 minutes out instead of ~4.5 minutes. The short-lived token expires without being refreshed, causing 401 Unauthorized errors on subsequent requests.

Root Cause
```
AuthConfig.builder()
    .from(parent.config())   // copies parent's expiresAtMillis
    .token(response.token()) // sets new token, but expiresAtMillis already set
    .tokenType(issuedTokenType)
    .credential(credential)
    .build()
```
The @Value.Default on expiresAtMillis() calls OAuth2Util.expiresAtMillis(token()) to parse the JWT exp claim. But because from() has already copied the parent's explicit expiresAtMillis value, Immutables treats it as explicitly set and skips the default computation.

### Willingness to contribute

- [x] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [ ] I cannot contribute a fix for this bug at this time

### PR DESCRIPTION
**Pull request by bharos**
### What

Fix child `AuthSession` inheriting the parent session's `expiresAtMillis` instead of computing it from its own token.

### Why

When creating a child `AuthSession` via `fromTokenResponse()` or `fromAccessToken()`, the `AuthConfig` builder calls `.from(parent.config())` to inherit configuration (scope, credential, oauth2ServerUri, etc.). However, Immutables' `from()` copies **all** values from the parent, including `expiresAtMillis`. This overrides the `@Value.Default` method that would otherwise recompute the expiry from the child's own JWT `exp` claim.

**Impact**: The child session schedules its first token refresh based on the **parent's** token expiry, not its own. In token exchange flows where:
- Catalog session holds a long-lived token (e.g., 1-hour Azure AD token)
- Exchanged per-user token is short-lived (e.g., 5-minute token)

...the refresh is scheduled ~54 minutes out instead of ~4.5 minutes, causing the short-lived token to expire without being refreshed.

### How

Explicitly set `expiresAtMillis` from the child token in both `fromTokenResponse()` and `fromAccessToken()` builders:

```java
.expiresAtMillis(OAuth2Util.expiresAtMillis(response.token()))
```

This ensures the child session's expiry is always derived from its own token's JWT `exp` claim (or `null` for opaque tokens, falling back to `response.expiresInSeconds()` for scheduling).

Fixes #16002 

### Testing

Added 3 tests to `TestOAuth2Util`:
- `fromTokenResponseUsesChildTokenExpiry` — verifies child JWT token's exp is used, not parent's
- `fromTokenResponseOpaqueTokenDoesNotInheritParentExpiry` — verifies opaque child tokens don't inherit parent's exp
- `fromAccessTokenUsesChildTokenExpiry` — verifies the same fix for `fromAccessToken()`

### CODE REVIEW

**Comment by bharos** [comment]
@adutra can you please review this change (or kindly let know who can do a review). Thanks!

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java [hunk 1]
```diff
@@ -529,6 +529,7 @@ public Pair<Integer, TimeUnit> refresh(RESTClient client) {
                 .from(config())
                 .token(response.token())
                 .tokenType(response.issuedTokenType())
+                .expiresAtMillis(OAuth2Util.expiresAtMillis(response.token()))
```
Comment (adutra) [inline core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java:532]: This change is good imho, but untested – it would be good to have it tested, although I agree it's not easy to test.

File: core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java [hunk 2]
```diff
@@ -135,4 +138,113 @@ public void testCredentialFlowForSessionRefresh() throws IOException {
...
+  private static String tokenWithExp(long expSeconds) {
+    String header = "{\"alg\":\"none\",\"typ\":\"JWT\"}";
+    String payload = "{\"sub\":\"test\",\"exp\":" + expSeconds + "}";
+    Base64.Encoder encoder = Base64.getUrlEncoder().withoutPadding();
+    return encoder.encodeToString(header.getBytes(StandardCharsets.UTF_8))
+        + "."
+        + encoder.encodeToString(payload.getBytes(StandardCharsets.UTF_8))
+        + "."
+        + encoder.encodeToString("fakesig".getBytes(StandardCharsets.UTF_8));
+  }
```
Comment (adutra) [inline core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java:234]: Can be replaced with Nimbus Jose (which comes transitively through MockServer and other deps):

```suggestion
  private static String tokenWithExp(long expSeconds) {
    JWTClaimsSet claimsSet =
        new JWTClaimsSet.Builder().subject("test").claim("exp", expSeconds).build();
    return new PlainJWT(claimsSet).serialize();
  }
```

**Review by adutra — COMMENTED** [review]
Thanks @bharos the changes make perfect sense to me. I only had a few minor remarks.

File: core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java [hunk 3]
```diff
@@ -135,4 +138,113 @@ public void testCredentialFlowForSessionRefresh() throws IOException {
...
+    OAuth2Util.AuthSession parent = new OAuth2Util.AuthSession(Map.of(), parentConfig);
+    assertThat(parent.expiresAtMillis()).isEqualTo(TimeUnit.SECONDS.toMillis(7200));
+
+    OAuthTokenResponse response =
+        OAuthTokenResponse.builder()
+            .withToken(childToken)
+            .withTokenType(BEARER)
+            .withIssuedTokenType(OAuth2Properties.ACCESS_TOKEN_TYPE)
+            .setExpirationInSeconds(600)
+            .build();
```
Comment (singhpk234) [inline core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java]: i wonder if we can extract these common block in a helper private function below as creating partent token and creating a OAuthTokenResponse from the child token etc .....

**Review by singhpk234 — COMMENTED** [review]
+1 to the change

File: core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java (hunk 1 above)
Comment (bharos) [reply core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java:532]: Added refreshUsesRefreshedTokenExpiry() test

File: core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java (hunk 3 above)
Comment (bharos) [reply core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java]: Done — extracted parentSession(), childTokenResponse(), and tokenWithExp() helpers.

File: core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java (hunk 2 above)
Comment (bharos) [reply core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java:234]: Good point — replaced manual Base64 JWT construction with Nimbus PlainJWT

**Comment by bharos** [comment]
Thanks for the review @adutra and @singhpk234 , addressed your comments. PTAL

**Review by adutra — APPROVED** [review]

**Review by singhpk234 — APPROVED** [review]
LGTM, thanks @bharos, can you please rebase, so that we can proceed with merge

**Comment by bharos** [comment]
@singhpk234 Thanks, rebased. Kindly merge this PR

**Comment by singhpk234** [comment]
Thanks for change @bharos, thanks for the review @adutra
