### PR TITLE
Nessie: Provide better commit message on table registation #8331

### LINKED ISSUE #8331: Improper commit message post table migration at the Nessie commit
### Apache Iceberg version

1.3.1 (latest release)

### Query engine

Spark

### Please describe the bug 🐞

Steps to repro:

* Migrate a table with existing snapshots on to the NessieCatalog using `registerTable(..)`

* The commit message is configured against the commit type of the current snapshot
```
Iceberg append against db.migration_table
Authored by: xx 2 minutes ago

Properties:
application-type: iceberg
iceberg.operation: append
```
https://github.com/apache/iceberg/blob/c1fc55022557653cfeb6125c1d51bf8ab12c8f96/nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java#L475C15-L475C28

The ask of this ticket is for a better commit message and `iceberg.operation`, which clearly identifies that it's a table registration activity.

### PR DESCRIPTION
**Pull request by harshm-dev**
Small change covering the registration time commit message when the catalog is Nessie.

Fixes #8331

### CODE REVIEW

File: nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java [hunk 1]
```diff
@@ -513,6 +513,8 @@ private String buildCommitMsg(TableMetadata base, TableMetadata metadata, String
           "Iceberg %s against %s", metadata.currentSnapshot().operation(), tableName);
     } else if (base != null && metadata.currentSchemaId() != base.currentSchemaId()) {
       return String.format("Iceberg schema change against %s", tableName);
+    } else if (base == null) {
+      return String.format("Iceberg table registered with name %s", tableName);
```
Comment (ajantha-bhat) [inline nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java:517]: Does create table also enter this flow? 🤔

**Comment by harshm-dev** [comment]
Yes it does, sharing an example effect of this change: 

Screenshot 2023-08-25 at 9 38 28 AM

File: nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java (hunk 1 above)
Comment (harshm-dev) [reply nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java:517]: Yes it does, sharing an example effect of this change: 

Screenshot 2023-08-25 at 9 38 28 AM

**Comment by harshm-dev** [comment]
This PR has been in review for a while now. Is there anything I can do to make things move on this track?

**Comment by harshm-dev** [comment]
Resolves #8331

File: nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java (hunk 1 above)
Comment (ajantha-bhat) [reply nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java:517]: So, we can't differentiate create table and register flow? 

If there is no way, I am ok with having this commit message (which was better than previous)

**Review by ajantha-bhat — APPROVED** [review]

**Comment by ajantha-bhat** [comment]
cc: @nastra. @snazy, @dimas-b

**Comment by ajantha-bhat** [comment]
PR title we don't mention issue number. 
And PR description can have a last line as Fixes #8331 

Just a style that Iceberg follows.

File: nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java (hunk 1 above)
Comment (snazy) [reply nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java:517]: IMO `registered` has a special meaning, I'd favor `created/registered` instead of just `registered`

Comment (dimas-b) [reply nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java:517]: +1 to @snazy 's suggesion

Comment (harshm-dev) [reply nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java]: Thanks, changed the message likewise `created/registered instead of just registered`.

> So, we can't differentiate create table and register flow?
The nearest possibility is to consider the case as `create` if there are no snapshots in the new metadata. Since it may not always be true, not pursuing that path.

**Review by nastra — APPROVED** [review]

**Review by ajantha-bhat — APPROVED** [review]

**Comment by harshm-dev** [comment]
@nastra will need your help with the merge.
